In [1]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 41 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 1s (7,624 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 121703 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

# 데이터 불러오기

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rc('font', family='NanumBarunGothic')

!pip install tspoon

import tspoon as tsp

Collecting tspoon
  Downloading tspoon-0.2.10-py3-none-any.whl.metadata (4.2 kB)
Downloading tspoon-0.2.10-py3-none-any.whl (9.2 kB)
Installing collected packages: tspoon
Successfully installed tspoon-0.2.10

In [3]:
!pip install xmltodict
import pandas as pd

import requests
import xml.etree.ElementTree as ET
import xml.dom.minidom
import xmltodict

import json
from urllib.request import urlopen

def getECOS(topic,period,beg,end,item1='?',item2='?',item3='?',item4='?', df=None):
    key = ''
    url = 'https://ecos.bok.or.kr/api/StatisticSearch/'+'OIT9OYFOZDZWLHSBQJWU'+'/xml/kr/'+str(1)+'/'+str(50000)+'/'+topic+'/'+period+'/'+beg+'/'+end \
            +'/'+item1+'/'+item2+'/'+item3+'/'+item4
    # print(url)
    ## call OpenAPI URL
    response = requests.get(url)

    ## get API return value upon the http request
    if response.status_code == 200:
        try:
            contents = response.text
            ecosRoot = ET.fromstring(contents)

            # error check
            if ecosRoot[0].text[:4] in ("INFO","ERRO"):
                print(ecosRoot[0].text + " : " + ecosRoot[1].text)

            else:
                #print(contents)
                #dom = xml.dom.minidom.parse(xml_fname)
                dom = xml.dom.minidom.parseString(contents)
                pretty_xml_as_string = dom.toprettyxml(indent=" ")
                # print(pretty_xml_as_string)
                dic = xmltodict.parse(pretty_xml_as_string)

                n = int(dic['StatisticSearch']['list_total_count']['#text'])
                df_ecos = pd.DataFrame(index = [dic['StatisticSearch']['row'][i]['TIME'] for i in range(n)])
                df_ecos[dic['StatisticSearch']['row'][0]['ITEM_NAME1']] = [float(dic['StatisticSearch']['row'][i]['DATA_VALUE']) for i in range(n)]

                if type(df)==type(pd.DataFrame()):
                    df_ecos = df.merge(df_ecos, left_index=True, right_index=True, how='left')

                return df_ecos

        except Exception as e:
            print(str(e))


def getKOSIS(table,period,beg,end,item, orgId='101', obj1='',obj2='',obj3='',obj4='',obj5='',obj6='',obj7='',obj8='', title=None, title_no='0', debug=False):
     # Korean Statistics
    key = 'MzhiMmQwZTYyMWZiNGM1ZGFkZDJmZTI2OTE1OGU2NzQ='
    url = 'https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey='+key \
            +'&orgId='+orgId\
            +'&tblId='+table \
            +'&prdSe='+period \
            +'&startPrdDe='+beg \
            +'&endPrdDe='+end \
            +'&itmId='+item \
            +'&objL1='+obj1 \
            +'&objL2='+obj2 \
            +'&objL3='+obj3 \
            +'&objL4='+obj4 \
            +'&objL5='+obj5 \
            +'&objL6='+obj6 \
            +'&objL7='+obj7 \
            +'&objL8='+obj8 \
            +'&format=json&jsonVD=Y&outputFields=ITM_NM+PRD_DE+DT'
    res = requests.get(url)
    py_json = res.json()

    data = []
    for v in py_json:
        value = []
        value.append(v['PRD_DE'])

        # ✅ DT 값이 '-' 또는 ''일 때 NaN으로 처리
        try:
            value.append(float(v['DT']))
        except (ValueError, KeyError):
            value.append(np.nan)

        data.append(value)

    df = pd.DataFrame(data, columns=['PRD_DE', 'DT'])

    if debug:
        print(df.head())

    return df


    #get json data from url
    with urlopen(url) as url_:
        json_file = url_.read()

    py_json = json.loads(json_file.decode('utf-8'))


    #data transformation
    data = []

    for i, v in enumerate(py_json):
        value = []
        value.append(v['PRD_DE'])
        value.append(float(v['DT']))

        data.append(value)

    if title is not None:
        title = str(title)
    elif title_no=='0':
        title = v['ITM_NM_ENG']
    else:
        title = v['C'+title_no+'_NM_ENG']

    df_kosis = pd.DataFrame({v['PRD_SE']:[x[0] for x in data], title:[x[1] for x in data]}).set_index(v['PRD_SE'])

    if debug:
        return v

    return df_kosis

Collecting xmltodict
  Downloading xmltodict-1.0.2-py3-none-any.whl.metadata (15 kB)
Downloading xmltodict-1.0.2-py3-none-any.whl (13 kB)
Installing collected packages: xmltodict
Successfully installed xmltodict-1.0.2

In [4]:
import pandas as pd
import numpy as np
import os
import seaborn as sns

In [5]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

In [6]:
# change directory to where you have your data file!!
%cd gdrive/MyDrive/GDP/데이터

/content/gdrive/MyDrive/GDP/데이터

## GDP

In [7]:
gdp = getECOS('200Y104', 'Q', '2015Q1', '2025Q2','110310').reset_index()
gdp

     index  전기장비 제조업
0   2015Q1    7301.1
1   2015Q2    7317.3
2   2015Q3    7135.0
3   2015Q4    6629.3
4   2016Q1    6644.5
5   2016Q2    6572.8
6   2016Q3    6739.4
7   2016Q4    6765.3
8   2017Q1    7320.1
9   2017Q2    7310.8
10  2017Q3    7690.1
11  2017Q4    7460.4
12  2018Q1    7742.8
13  2018Q2    7743.4
14  2018Q3    7845.2
15  2018Q4    8239.1
16  2019Q1    7852.0
17  2019Q2    8150.7
18  2019Q3    7909.0
19  2019Q4    8058.7
20  2020Q1    7777.7
21  2020Q2    7555.8
22  2020Q3    7970.5
23  2020Q4    8570.5
24  2021Q1    8819.7
25  2021Q2    8808.2
26  2021Q3    8557.5
27  2021Q4    8934.8
28  2022Q1    9456.8
29  2022Q2    9482.1
30  2022Q3    9167.8
31  2022Q4    8857.0
32  2023Q1    8842.2
33  2023Q2    8948.2
34  2023Q3    9348.9
35  2023Q4    8913.5
36  2024Q1    8686.4
37  2024Q2    8622.5
38  2024Q3    8858.9
39  2024Q4    8455.4
40  2025Q1    8297.6
41  2025Q2    8522.7

## PPI

In [8]:
ppi = getECOS('404Y014','Q','2015Q1','2025Q2','310AA').reset_index()
ppi

     index    전기장비
0   2015Q1   98.29
1   2015Q2   97.68
2   2015Q3   97.68
3   2015Q4   97.13
4   2016Q1   97.07
5   2016Q2   96.80
6   2016Q3   96.29
7   2016Q4   97.01
8   2017Q1   98.04
9   2017Q2   97.72
10  2017Q3   98.43
11  2017Q4   99.21
12  2018Q1   99.73
13  2018Q2   99.98
14  2018Q3   99.33
15  2018Q4   99.40
16  2019Q1   99.70
17  2019Q2  100.11
18  2019Q3  100.11
19  2019Q4   99.99
20  2020Q1   99.78
21  2020Q2   99.24
22  2020Q3  100.32
23  2020Q4  100.66
24  2021Q1  102.33
25  2021Q2  105.31
26  2021Q3  105.94
27  2021Q4  107.46
28  2022Q1  110.23
29  2022Q2  112.21
30  2022Q3  112.92
31  2022Q4  115.12
32  2023Q1  117.65
33  2023Q2  118.14
34  2023Q3  119.55
35  2023Q4  121.44
36  2024Q1  122.38
37  2024Q2  125.61
38  2024Q3  124.47
39  2024Q4  124.99
40  2025Q1  126.24
41  2025Q2  125.59

In [9]:
ppi = ppi.rename(columns={'전기장비':'전기장비ppi'})

##BSI

In [10]:
업황실적BSI = getECOS('512Y007','M','201501','202506','AA','C2800').reset_index()
매출실적BSI = getECOS('512Y007','M','201501','202506','AB','C2800').reset_index()
채산성실적BSI = getECOS('512Y007','M','201501','202506','AE','C2800').reset_index()
수출실적BSI= getECOS('512Y007','M','201501','202506','AM','C2800').reset_index()
내수판매실적BSI= getECOS('512Y007','M','201501','202506','AL','C2800').reset_index()
생산실적BSI= getECOS('512Y007','M','201501','202506','AC','C2800').reset_index()
신규수주실적BSI= getECOS('512Y007','M','201501','202506','AD','C2800').reset_index()
제품재고실적BSI= getECOS('512Y007','M','201501','202506','AG','C2800').reset_index()
가동률실적BSI= getECOS('512Y007','M','201501','202506','AK','C2800').reset_index()
생산설비실적BSI= getECOS('512Y007','M','201501','202506','AH','C2800').reset_index()
설비투자실적BSI= getECOS('512Y007','M','201501','202506','AI','C2800').reset_index()
자금사정실적BSI = getECOS('512Y007','M','201501','202506','AO','C2800').reset_index()
인력사정실적BSI = getECOS('512Y007','M','201501','202506','AJ','C2800').reset_index()

업황실적BSI = 업황실적BSI.rename(columns={'업황실적BSI 1)':'업황실적BSI'})
매출실적BSI = 매출실적BSI.rename(columns={'매출실적BSI 2)':'매출실적BSI'})
채산성실적BSI = 채산성실적BSI.rename(columns={'채산성실적BSI 6)':'채산성실적BSI'})
수출실적BSI = 수출실적BSI.rename(columns={'수출실적BSI 2)':'수출실적BSI'})
내수판매실적BSI = 내수판매실적BSI.rename(columns={'내수판매실적BSI 2)':'내수판매실적BSI'})
생산실적BSI = 생산실적BSI.rename(columns={'생산실적BSI 2)':'생산실적BSI'})
신규수주실적BSI = 신규수주실적BSI.rename(columns={'신규수주실적BSI 2)':'신규수주실적BSI'})
제품재고실적BSI = 제품재고실적BSI.rename(columns={'제품재고실적BSI 3)':'제품재고실적BSI'})
가동률실적BSI = 가동률실적BSI.rename(columns={'가동률실적BSI 4)':'가동률실적BSI'})
생산설비실적BSI = 생산설비실적BSI.rename(columns={'생산설비실적BSI 3)':'생산설비실적BSI'})
설비투자실적BSI = 설비투자실적BSI.rename(columns={'설비투자실적BSI 5)':'설비투자실적BSI '})
자금사정실적BSI = 자금사정실적BSI.rename(columns={'자금사정실적BSI 6)':'자금사정실적BSI'})
인력사정실적BSI = 인력사정실적BSI.rename(columns={'인력사정실적BSI 3)':'인력사정실적BSI'})

In [11]:
from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [업황실적BSI, 매출실적BSI,수출실적BSI, 내수판매실적BSI, 생산실적BSI, 신규수주실적BSI, 제품재고실적BSI, 가동률실적BSI,설비투자실적BSI, 채산성실적BSI, 자금사정실적BSI, 인력사정실적BSI]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
df_merged = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
df_merged

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI
0,201501,61.0,85.0,92.0,79.0,86.0,85.0,103.0,92.0,91.0,86.0,86.0,88.0
1,201502,76.0,95.0,96.0,91.0,92.0,93.0,105.0,86.0,97.0,86.0,85.0,97.0
2,201503,66.0,79.0,72.0,81.0,85.0,79.0,104.0,78.0,95.0,86.0,85.0,99.0
3,201504,78.0,88.0,81.0,89.0,86.0,88.0,104.0,89.0,90.0,93.0,85.0,97.0
4,201505,71.0,91.0,86.0,87.0,90.0,90.0,110.0,90.0,91.0,91.0,91.0,96.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,202502,78.0,84.0,105.0,76.0,92.0,87.0,103.0,92.0,90.0,92.0,98.0,87.0
122,202503,73.0,81.0,84.0,76.0,87.0,81.0,108.0,89.0,92.0,84.0,85.0,95.0
123,202504,64.0,69.0,72.0,69.0,80.0,66.0,107.0,85.0,92.0,80.0,82.0,97.0
124,202505,65.0,71.0,78.0,70.0,83.0,71.0,102.0,84.0,89.0,84.0,84.0,98.0
125,202506,68.0,80.0,100.0,72.0,88.0,87.0,107.0,93.0,93.0,82.0,90.0,97.0

In [12]:
df_merged.isnull().sum()

index         0
업황실적BSI       0
매출실적BSI       0
수출실적BSI       0
내수판매실적BSI     0
생산실적BSI       0
신규수주실적BSI     0
제품재고실적BSI     0
가동률실적BSI      0
설비투자실적BSI     0
채산성실적BSI      0
자금사정실적BSI     0
인력사정실적BSI     0
dtype: int64

In [13]:
import pandas as pd

# index가 숫자라면 문자열로 변환
df_merged['index'] = df_merged['index'].astype(str)

# 연도와 월 분리
df_merged['연도'] = df_merged['index'].str[:4].astype(int)
df_merged['월'] = df_merged['index'].str[4:6].astype(int)

# 월 → 분기 변환 함수
def month_to_quarter(month):
    if month in [1, 2, 3]:
        return 'Q1'
    elif month in [4, 5, 6]:
        return 'Q2'
    elif month in [7, 8, 9]:
        return 'Q3'
    else:
        return 'Q4'

# 분기 계산
df_merged['분기'] = df_merged['월'].apply(month_to_quarter)

# 분기 인덱스 생성 (예: 2015Q1)
df_merged['index'] = df_merged['연도'].astype(str) + df_merged['분기']

# 분기별 평균 집계
df_quarter = df_merged.groupby('index').mean(numeric_only=True).reset_index()

# 결과 확인
print(df_quarter.head())

    index    업황실적BSI    매출실적BSI    수출실적BSI  내수판매실적BSI    생산실적BSI  신규수주실적BSI  \
0  2015Q1  67.666667  86.333333  86.666667  83.666667  87.666667  85.666667
1  2015Q2  70.333333  85.666667  81.666667  82.333333  84.666667  84.666667
2  2015Q3  60.000000  72.666667  81.000000  68.333333  78.666667  75.000000
3  2015Q4  60.000000  70.000000  76.000000  64.333333  80.000000  74.333333
4  2016Q1  59.333333  69.666667  74.000000  66.000000  74.333333  69.000000

    제품재고실적BSI   가동률실적BSI  설비투자실적BSI    채산성실적BSI  자금사정실적BSI  인력사정실적BSI      연도  \
0  104.000000  85.333333   94.333333  86.000000  85.333333  94.666667  2015.0
1  106.666667  84.666667   89.000000  88.000000  85.333333  97.333333  2015.0
2  109.000000  78.333333   91.666667  82.000000  83.666667  97.333333  2015.0
3  107.000000  76.333333   89.333333  79.333333  82.333333  99.000000  2015.0
4  107.666667  73.666667   91.333333  84.666667  82.000000  95.333333  2016.0

      월
0   2.0
1   5.0
2   8.0
3  11.0
4   2.0

In [14]:
df_quarter.head()

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,연도,월
0,2015Q1,67.666667,86.333333,86.666667,83.666667,87.666667,85.666667,104.000000,85.333333,94.333333,86.000000,85.333333,94.666667,2015.0,2.0
1,2015Q2,70.333333,85.666667,81.666667,82.333333,84.666667,84.666667,106.666667,84.666667,89.000000,88.000000,85.333333,97.333333,2015.0,5.0
2,2015Q3,60.000000,72.666667,81.000000,68.333333,78.666667,75.000000,109.000000,78.333333,91.666667,82.000000,83.666667,97.333333,2015.0,8.0
3,2015Q4,60.000000,70.000000,76.000000,64.333333,80.000000,74.333333,107.000000,76.333333,89.333333,79.333333,82.333333,99.000000,2015.0,11.0
4,2016Q1,59.333333,69.666667,74.000000,66.000000,74.333333,69.000000,107.666667,73.666667,91.333333,84.666667,82.000000,95.333333,2016.0,2.0

In [15]:
df_quarter = df_quarter.drop(columns=['연도', '월'], errors='ignore')

In [16]:
dfs = [ppi, gdp]
df_final = df_quarter.copy()
key_col = 'index'
for df in dfs:
    df_final = df_final.merge(df, on=key_col, how='left')

df_final

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,전기장비ppi,전기장비 제조업
0,2015Q1,67.666667,86.333333,86.666667,83.666667,87.666667,85.666667,104.000000,85.333333,94.333333,86.000000,85.333333,94.666667,98.29,7301.1
1,2015Q2,70.333333,85.666667,81.666667,82.333333,84.666667,84.666667,106.666667,84.666667,89.000000,88.000000,85.333333,97.333333,97.68,7317.3
2,2015Q3,60.000000,72.666667,81.000000,68.333333,78.666667,75.000000,109.000000,78.333333,91.666667,82.000000,83.666667,97.333333,97.68,7135.0
3,2015Q4,60.000000,70.000000,76.000000,64.333333,80.000000,74.333333,107.000000,76.333333,89.333333,79.333333,82.333333,99.000000,97.13,6629.3
4,2016Q1,59.333333,69.666667,74.000000,66.000000,74.333333,69.000000,107.666667,73.666667,91.333333,84.666667,82.000000,95.333333,97.07,6644.5
5,2016Q2,62.666667,72.333333,81.000000,70.333333,77.000000,72.000000,110.000000,78.333333,86.666667,84.666667,86.333333,102.000000,96.80,6572.8
6,2016Q3,62.666667,69.333333,77.666667,69.666667,74.666667,68.666667,107.666667,74.333333,90.000000,84.333333,88.333333,100.666667,96.29,6739.4
7,2016Q4,68.333333,74.333333,85.000000,72.000000,81.000000,76.000000,103.666667,83.666667,91.666667,85.333333,88.000000,97.333333,97.01,6765.3
8,2017Q1,69.333333,79.333333,88.333333,78.000000,87.000000,81.333333,107.666667,85.000000,93.666667,77.333333,81.000000,96.666667,98.04,7320.1
9,2017Q2,80.333333,84.666667,91.000000,81.000000,93.333333,89.000000,108.333333,87.666667,95.333333,88.000000,87.666667,103.333333,97.72,7310.8
10,2017Q3,82.666667,95.000000,86.666667,91.333333,94.000000,85.666667,109.666667,93.000000,97.333333,85.666667,87.333333,98.333333,98.43,7690.1
11,2017Q4,73.666667,83.000000,79.333333,82.333333,85.000000,80.666667,107.333333,85.000000,91.666667,83.333333,82.000000,95.333333,99.21,7460.4
12,2018Q1,74.666667,84.000000,84.666667,81.000000,84.333333,81.333333,105.666667,82.333333,98.000000,83.333333,83.333333,97.333333,99.73,7742.8
13,2018Q2,86.666667,97.333333,89.333333,94.333333,94.666667,92.000000,103.666667,95.000000,100.000000,86.000000,88.666667,104.000000,99.98,7743.4
14,2018Q3,76.666667,88.666667,84.333333,88.666667,88.000000,79.333333,107.333333,86.000000,94.000000,87.000000,83.000000,104.333333,99.33,7845.2
15,2018Q4,76.333333,84.333333,90.000000,81.666667,82.666667,77.000000,102.666667,81.666667,93.333333,88.333333,82.666667,99.333333,99.40,8239.1
16,2019Q1,71.666667,87.666667,94.000000,86.000000,87.000000,80.666667,103.666667,87.000000,97.333333,89.666667,84.000000,101.000000,99.70,7852.0
17,2019Q2,74.666667,79.666667,87.000000,76.000000,88.000000,79.000000,107.000000,85.333333,94.666667,83.333333,78.000000,105.000000,100.11,8150.7
18,2019Q3,60.666667,72.666667,84.000000,70.333333,79.333333,75.000000,111.000000,79.333333,87.333333,78.000000,74.000000,104.000000,100.11,7909.0
19,2019Q4,74.666667,79.333333,86.000000,75.333333,82.666667,82.000000,109.000000,82.666667,87.333333,85.000000,79.666667,101.333333,99.99,8058.7
20,2020Q1,66.000000,71.333333,83.333333,69.000000,79.333333,76.000000,108.333333,78.000000,87.000000,83.333333,77.666667,105.666667,99.78,7777.7
21,2020Q2,45.666667,45.333333,46.000000,47.666667,55.000000,52.333333,105.666667,50.666667,78.333333,71.666667,61.666667,112.666667,99.24,7555.8
22,2020Q3,68.000000,66.333333,68.333333,65.333333,71.000000,66.000000,107.333333,77.000000,80.000000,84.000000,83.666667,105.000000,100.32,7970.5
23,2020Q4,83.333333,78.333333,85.000000,76.000000,86.333333,75.666667,102.333333,87.333333,87.000000,87.000000,83.333333,103.666667,100.66,8570.5
24,2021Q1,81.666667,81.333333,86.666667,79.000000,87.666667,85.333333,102.666667,87.666667,91.666667,86.000000,86.666667,96.666667,102.33,8819.7
25,2021Q2,87.333333,104.666667,108.333333,97.000000,102.000000,97.333333,98.333333,102.333333,100.000000,82.666667,86.333333,93.666667,105.31,8808.2
26,2021Q3,90.000000,97.666667,107.000000,87.666667,98.666667,89.333333,104.666667,100.000000,100.000000,83.000000,88.000000,94.666667,105.94,8557.5
27,2021Q4,94.333333,98.000000,106.000000,91.333333,101.000000,90.333333,99.333333,103.000000,95.666667,88.000000,86.000000,88.666667,107.46,8934.8
28,2022Q1,83.000000,100.000000,106.666667,98.000000,97.666667,95.000000,100.333333,97.333333,98.333333,79.333333,86.000000,91.333333,110.23,9456.8
29,2022Q2,85.333333,98.000000,108.333333,96.666667,91.666667,92.000000,95.000000,94.333333,94.666667,73.333333,79.000000,87.000000,112.21,9482.1
30,2022Q3,80.333333,97.666667,109.333333,97.000000,89.333333,88.666667,104.666667,90.666667,94.000000,80.333333,82.666667,87.666667,112.92,9167.8
31,2022Q4,84.000000,95.333333,109.666667,95.000000,91.000000,92.333333,112.000000,91.333333,94.000000,79.666667,84.000000,85.000000,115.12,8857.0
32,2023Q1,77.000000,91.000000,103.666667,85.000000,87.333333,90.000000,103.333333,86.333333,87.000000,82.000000,85.000000,86.666667,117.65,8842.2
33,2023Q2,78.333333,90.333333,106.000000,84.666667,93.000000,87.000000,99.333333,91.666667,91.000000,79.333333,84.000000,90.000000,118.14,8948.2
34,2023Q3,79.666667,92.333333,106.333333,86.333333,93.000000,86.000000,101.666667,93.333333,92.666667,81.000000,90.666667,92.000000,119.55,9348.9
35,2023Q4,82.000000,81.333333,84.333333,81.333333,85.666667,77.000000,108.666667,82.666667,95.333333,86.666667,83.666667,86.333333,121.44,8913.5
36,2024Q1,78.666667,90.666667,84.000000,86.666667,89.666667,92.333333,109.666667,86.666667,96.666667,81.666667,86.666667,88.000000,122.38,8686.4
37,2024Q2,82.666667,87.666667,89.333333,83.333333,91.333333,86.666667,108.666667,92.333333,95.666667,87.666667,86.333333,93.333333,125.61,8622.5
38,2024Q3,73.000000,80.333333,81.666667,74.000000,79.666667,76.333333,113.000000,82.000000,94.666667,78.666667,83.333333,93.000000,124.47,8858.9
39,2024Q4,71.666667,79.000000,88.000000,75.333333,85.000000,81.000000,110.666667,83.000000,90.000000,81.000000,86.666667,92.333333,124.99,8455.4
40,2025Q1,76.666667,82.333333,91.666667,77.333333,89.333333,84.000000,106.000000,88.666667,90.666667,86.666667,89.333333,90.666667,126.24,8297.6
41,2025Q2,65.666667,73.333333,83.333333,70.333333,83.666667,74.666667,105.333333,87.333333,91.333333,82.000000,85.333333,97.333333,125.59,8522.7

In [17]:
df_final.to_csv("전기장비1차.csv")

## 생산지수

In [18]:
생산지수 = getKOSIS('DT_1F02001','Q','201501','202502','T20','101','00','C28')

def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

생산지수['index']=생산지수['PRD_DE'].apply(to_quarter)
생산지수 = 생산지수.drop(columns=["PRD_DE"])
생산지수 = 생산지수.rename(columns={'DT': '생산지수'})
생산지수

       생산지수   index
0    90.577  2015Q1
1    90.360  2015Q2
2    93.073  2015Q3
3    94.494  2015Q4
4    95.813  2016Q1
5    92.740  2016Q2
6    94.348  2016Q3
7    97.281  2016Q4
8    96.966  2017Q1
9    98.666  2017Q2
10   98.381  2017Q3
11  100.384  2017Q4
12   96.856  2018Q1
13   98.682  2018Q2
14   98.309  2018Q3
15  100.190  2018Q4
16   97.446  2019Q1
17  100.310  2019Q2
18  101.271  2019Q3
19  103.959  2019Q4
20   97.400  2020Q1
21   94.900  2020Q2
22  101.800  2020Q3
23  105.800  2020Q4
24  106.300  2021Q1
25  106.600  2021Q2
26  108.400  2021Q3
27  111.200  2021Q4
28  111.300  2022Q1
29  112.100  2022Q2
30  114.400  2022Q3
31  109.200  2022Q4
32  117.300  2023Q1
33  116.400  2023Q2
34  108.600  2023Q3
35  105.100  2023Q4
36  105.500  2024Q1
37  105.600  2024Q2
38  100.800  2024Q3
39  102.900  2024Q4
40  103.300  2025Q1
41  104.200  2025Q2

## 내수/수출출하지수

https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MGNkMzY3MTdhNjZlMTNiZDMxYjU4NDA4NTdjZWU0YmQ=&itmId=T21+&objL1=C28+&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Q&startPrdDe=201501&endPrdDe=202502&outputFields=OBJ_NM+NM+ITM_NM+PRD_DE+&orgId=101&tblId=DT_1F02016

In [19]:
수출출하지수 = getKOSIS('DT_1F02016','Q','201501','202502','T21','101','C28')

def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

수출출하지수['index']=수출출하지수['PRD_DE'].apply(to_quarter)
수출출하지수 = 수출출하지수.drop(columns=["PRD_DE"])
수출출하지수 = 수출출하지수.rename(columns={'DT': '수출출하지수'})
수출출하지수

     수출출하지수   index
0    90.071  2015Q1
1    91.428  2015Q2
2    93.093  2015Q3
3    94.480  2015Q4
4    99.969  2016Q1
5    95.899  2016Q2
6    97.564  2016Q3
7    97.718  2016Q4
8    95.961  2017Q1
9    96.731  2017Q2
10   98.982  2017Q3
11  102.713  2017Q4
12   98.489  2018Q1
13   95.868  2018Q2
14   98.735  2018Q3
15   93.710  2018Q4
16  103.207  2019Q1
17  106.599  2019Q2
18  105.119  2019Q3
19  107.216  2019Q4
20  100.600  2020Q1
21   86.900  2020Q2
22  100.700  2020Q3
23  112.200  2020Q4
24  105.700  2021Q1
25  110.300  2021Q2
26  112.300  2021Q3
27  122.100  2021Q4
28  132.200  2022Q1
29  137.500  2022Q2
30  143.800  2022Q3
31  134.300  2022Q4
32  134.800  2023Q1
33  132.000  2023Q2
34  114.100  2023Q3
35  102.500  2023Q4
36  100.300  2024Q1
37   97.600  2024Q2
38   89.600  2024Q3
39   89.000  2024Q4
40   85.600  2025Q1
41   94.800  2025Q2

In [20]:
내수출하지수 = getKOSIS('DT_1F02016','Q','201501','202502','T20','101','C28')
def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

내수출하지수['index']=내수출하지수['PRD_DE'].apply(to_quarter)
내수출하지수 = 내수출하지수.drop(columns=["PRD_DE"])
내수출하지수 = 내수출하지수.rename(columns={'DT': '내수출하지수'})
내수출하지수

     내수출하지수   index
0    90.381  2015Q1
1    90.138  2015Q2
2    92.510  2015Q3
3    91.658  2015Q4
4    90.381  2016Q1
5    89.712  2016Q2
6    90.442  2016Q3
7    94.152  2016Q4
8    94.669  2017Q1
9    94.244  2017Q2
10   96.433  2017Q3
11   93.727  2017Q4
12   97.862  2018Q1
13  101.329  2018Q2
14  100.904  2018Q3
15  100.721  2018Q4
16  101.117  2019Q1
17  101.056  2019Q2
18  100.204  2019Q3
19  101.117  2019Q4
20   97.300  2020Q1
21   99.600  2020Q2
22  100.000  2020Q3
23  102.600  2020Q4
24  102.600  2021Q1
25  101.100  2021Q2
26  101.400  2021Q3
27  103.200  2021Q4
28  103.300  2022Q1
29  104.000  2022Q2
30  104.100  2022Q3
31  102.600  2022Q4
32  108.200  2023Q1
33  105.900  2023Q2
34  104.800  2023Q3
35  104.800  2023Q4
36  101.700  2024Q1
37   95.400  2024Q2
38   90.900  2024Q3
39   91.400  2024Q4
40   96.600  2025Q1
41   97.400  2025Q2

https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MGNkMzY3MTdhNjZlMTNiZDMxYjU4NDA4NTdjZWU0YmQ=&itmId=T10+T30+&objL1=C28+&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Q&startPrdDe=201501&endPrdDe=202502&outputFields=OBJ_NM+NM+ITM_NM+PRD_DE+&orgId=101&tblId=DT_1F32001

## 생산능력지수 & 가동률지수

In [21]:
생산능력지수 = getKOSIS('DT_1F32001','Q','201501','202502','T10','101','C28')
def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

생산능력지수['index']=생산능력지수['PRD_DE'].apply(to_quarter)
생산능력지수 = 생산능력지수.drop(columns=["PRD_DE"])
생산능력지수 = 생산능력지수.rename(columns={'DT': '생산능력지수'})
생산능력지수

     생산능력지수   index
0    93.177  2015Q1
1    93.333  2015Q2
2    94.178  2015Q3
3    94.929  2015Q4
4    94.210  2016Q1
5    93.865  2016Q2
6    94.773  2016Q3
7    94.053  2016Q4
8    95.211  2017Q1
9    96.369  2017Q2
10   95.994  2017Q3
11   96.714  2017Q4
12   96.870  2018Q1
13   97.340  2018Q2
14   97.653  2018Q3
15   98.185  2018Q4
16   98.028  2019Q1
17   97.871  2019Q2
18   97.715  2019Q3
19   98.122  2019Q4
20  100.100  2020Q1
21   99.400  2020Q2
22   99.900  2020Q3
23  100.600  2020Q4
24  100.300  2021Q1
25   98.800  2021Q2
26   98.500  2021Q3
27   98.200  2021Q4
28  102.700  2022Q1
29  103.400  2022Q2
30  101.400  2022Q3
31   98.100  2022Q4
32  103.200  2023Q1
33  104.300  2023Q2
34  100.800  2023Q3
35   98.800  2023Q4
36  100.400  2024Q1
37  101.100  2024Q2
38  102.000  2024Q3
39  102.100  2024Q4
40  100.800  2025Q1
41  101.600  2025Q2

In [22]:
가동률지수 = getKOSIS('DT_1F32001','Q','201501','202502','T30','101','C28')
def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

가동률지수['index']=가동률지수['PRD_DE'].apply(to_quarter)
가동률지수 = 가동률지수.drop(columns=["PRD_DE"])
가동률지수 = 가동률지수.rename(columns={'DT': '가동률지수'})
가동률지수

      가동률지수   index
0    97.858  2015Q1
1    97.522  2015Q2
2   100.217  2015Q3
3    99.958  2015Q4
4   101.547  2016Q1
5    99.093  2016Q2
6   100.701  2016Q3
7   103.622  2016Q4
8   102.813  2017Q1
9   102.724  2017Q2
10  102.886  2017Q3
11  104.056  2017Q4
12  101.008  2018Q1
13  101.864  2018Q2
14  100.483  2018Q3
15  102.260  2018Q4
16   99.709  2019Q1
17  102.098  2019Q2
18  102.939  2019Q3
19  105.009  2019Q4
20   97.500  2020Q1
21   96.000  2020Q2
22  101.900  2020Q3
23  104.600  2020Q4
24  106.500  2021Q1
25  107.200  2021Q2
26  108.200  2021Q3
27  110.100  2021Q4
28  106.600  2022Q1
29  106.700  2022Q2
30  109.800  2022Q3
31  109.200  2022Q4
32  112.300  2023Q1
33  108.300  2023Q2
34  103.700  2023Q3
35  101.500  2023Q4
36  103.600  2024Q1
37  103.900  2024Q2
38   98.500  2024Q3
39   98.600  2024Q4
40  100.300  2025Q1
41   99.700  2025Q2

## 기업데이터 (인건비 + 에빗다)

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
기업 = pd.read_excel("Data_통합.xlsx")

In [25]:
import pandas as pd

file_path = "Data_통합.xlsx"

# 엑셀 파일 객체 생성
xls = pd.ExcelFile(file_path)

# 빈 딕셔너리 (시트별 데이터 저장용)
dfs = {}

# 모든 시트를 순회
for sheet in xls.sheet_names:
    print(f"Loading {sheet} ...")

    if sheet == "Sheet":
        # 첫 번째 시트는 첫 번째 줄이 컬럼명
        dfs[sheet] = pd.read_excel(file_path, sheet_name=sheet)
    else:
        # 다른 시트는 두 번째 줄부터 컬럼명
        dfs[sheet] = pd.read_excel(file_path, sheet_name=sheet, header=1)

    print(f"{sheet} shape: {dfs[sheet].shape}")

Loading Sheet ...
Sheet shape: (374340, 14)
Loading EBITDA ...
EBITDA shape: (7342, 112)
Loading 인건비 ...
인건비 shape: (7342, 112)
Loading 유무형리스자산의증가 ...
유무형리스자산의증가 shape: (7342, 112)
Loading 매출원가 ...
매출원가 shape: (7342, 112)
Loading 수익 ...
수익 shape: (7342, 112)

In [26]:
dfs["Sheet"]

,업체코드,종목코드,종목명,691005.업체명,691020.사업자번호,691050.상장일,691060.결산월,691450.KSIC-세세분류(11차),DATE,EBITDA,인건비,"유,무형,리스자산의증가",매출원가,수익(매출액)
0,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2000-01-01,0.000000e+00,3829199.0,0.000000e+00,1.698668e+10,2.874157e+10
1,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2000-04-01,0.000000e+00,4129827.0,0.000000e+00,2.042499e+10,3.281942e+10
2,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2000-07-01,0.000000e+00,3811223.0,0.000000e+00,2.191622e+10,3.407650e+10
3,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2000-10-01,4.886518e+09,7843796.0,4.438878e+09,2.584407e+10,4.259254e+10
4,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2001-01-01,0.000000e+00,4329948.0,0.000000e+00,1.674465e+10,3.004641e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374335,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2024-04-01,-9.589924e+09,-2940319.0,9.632000e+06,0.000000e+00,0.000000e+00
374336,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2024-07-01,-1.188333e+10,7760477.0,5.462700e+07,0.000000e+00,1.090765e+09
374337,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2024-10-01,3.202594e+10,-7760477.0,-1.113170e+08,0.000000e+00,-1.090765e+09
374338,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2025-01-01,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00
374339,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2025-04-01,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00

In [27]:
arr = dfs["Sheet"]['691450.KSIC-세세분류(11차)'].unique()
arr2 = pd.DataFrame(arr, columns=['산업분류'])
arr2

                             산업분류
0    C21212.합성의약품 및 기타 완제 의약품 제조업
1                C31921.모터사이클 제조업
2             G47119.기타 대형 종합 소매업
3                     K64992.지주회사
4                             NaN
..                            ...
473        C29222.디지털 적층 성형기계 제조업
474              C15219.기타 신발 제조업
475             C29163.컨베이어장치 제조업
476      G45212.자동차용 전용 신품 부품 판매업
477     M70130.자연과학 및 공학 융합 연구개발업

[478 rows x 1 columns]

In [28]:
arr2.to_csv('기업데이터 산업.csv', encoding='utf-8-sig')

In [29]:
df1 = pd.read_csv('산업코드.csv')

In [30]:
df1

                        산업 구분 산업코드
0                        농림어업    A
1                          광업    B
2                음식료품 제조업_식료품  C10
3                 음식료품 제조업_음료  C11
4                 음식료품 제조업_담배  C12
5            섬유 및 가죽제품 제조업_섬유  C13
6          섬유 및 가죽제품 제조업_의복모피  C14
7        섬유 및 가죽제품 제조업_가죽가방신발  C15
8       목재, 종이, 인쇄 및 복제업_목재나무  C16
9       목재, 종이, 인쇄 및 복제업_펄프종이  C17
10  목재, 종이, 인쇄 및 복제업_인쇄기록매체복제  C18
11            코크스 및 석유정제품 제조업  C19
12     화학물질 및 화학제품 제조업_화학물질제품  C20
13    화학물질 및 화학제품 제조업_의료물질의약품  C21
14     화학물질 및 화학제품 제조업_고무플라스틱  C22
15                비금속광물제품 제조업  C23
16                   1차금속 제조업  C24
17                 금속가공제품 제조업  C25
18  컴퓨터, 전자 및 광학기기 제조업_전자영상통신  C26
19  컴퓨터, 전자 및 광학기기 제조업_의료정밀기기  C27
20                   전기장비 제조업  C28
21                기계 및 장비 제조업  C29
22               운송장비 제조업_자동차  C30
23            운송장비 제조업_조선기타운수  C31
24     기타 제조업 및 산업용 장비 수리업_가구  C32
25   기타 제조업 및 산업용 장비 수리업_기타제품  C33
26    전기업 + 가스, 증기 및 공기조절 공급업  D35
27    수도, 하수 및 폐기물 처리, 원료 재생업  E38
28               건물건설 및 건축보수업  F41
29                      토목건설업  F42
30                       도소매업    G
31                  숙박 및 음식점업    I
32                        운수업    H
33                   금융 및 보험업    K
34                       부동산업    L
35     출판, 방송, 영상, 정보서비스업&통신업    J
36         전문, 과학 및 기술관련 서비스업    M
37                  사업지원 서비스업    N
38            공공행정, 국방 및 사회보장   1E
39                     교육서비스업    P
40         의료, 보건업 및 사회복지서비스업    Q
41       문화 및 기타 서비스업_예술스포츠여가    R
42        문화 및 기타 서비스업_기타서비스업    S

In [31]:
def match_industry(row, code_dict):
    if pd.isna(row):
        return np.nan
    for code, industry in code_dict.items():
        if str(row).startswith(code):
            return industry
    return ''

code_dict = dict(zip(df1['산업코드'], df1['산업 구분']))

In [32]:
# df2['산업분류']에서 코드 부분만 추출해서 매핑
arr2['매핑한 산업'] = arr2['산업분류'].apply(lambda x: match_industry(x, code_dict))
arr2

                             산업분류                   매핑한 산업
0    C21212.합성의약품 및 기타 완제 의약품 제조업  화학물질 및 화학제품 제조업_의료물질의약품
1                C31921.모터사이클 제조업          운송장비 제조업_조선기타운수
2             G47119.기타 대형 종합 소매업                     도소매업
3                     K64992.지주회사                 금융 및 보험업
4                             NaN                      NaN
..                            ...                      ...
473        C29222.디지털 적층 성형기계 제조업              기계 및 장비 제조업
474              C15219.기타 신발 제조업     섬유 및 가죽제품 제조업_가죽가방신발
475             C29163.컨베이어장치 제조업              기계 및 장비 제조업
476      G45212.자동차용 전용 신품 부품 판매업                     도소매업
477     M70130.자연과학 및 공학 융합 연구개발업       전문, 과학 및 기술관련 서비스업

[478 rows x 2 columns]

In [33]:
dfs["Sheet"]['매핑한 산업'] = dfs["Sheet"]['691450.KSIC-세세분류(11차)'].apply(lambda x: match_industry(x, code_dict))
dfs["Sheet"]

,업체코드,종목코드,종목명,691005.업체명,691020.사업자번호,691050.상장일,691060.결산월,691450.KSIC-세세분류(11차),DATE,EBITDA,인건비,"유,무형,리스자산의증가",매출원가,수익(매출액),매핑한 산업
0,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2000-01-01,0.000000e+00,3829199.0,0.000000e+00,1.698668e+10,2.874157e+10,화학물질 및 화학제품 제조업_의료물질의약품
1,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2000-04-01,0.000000e+00,4129827.0,0.000000e+00,2.042499e+10,3.281942e+10,화학물질 및 화학제품 제조업_의료물질의약품
2,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2000-07-01,0.000000e+00,3811223.0,0.000000e+00,2.191622e+10,3.407650e+10,화학물질 및 화학제품 제조업_의료물질의약품
3,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2000-10-01,4.886518e+09,7843796.0,4.438878e+09,2.584407e+10,4.259254e+10,화학물질 및 화학제품 제조업_의료물질의약품
4,N350605,A000020,동화약품,동화약품(주),110-81-00102,1976-03-24,12.0,C21212.합성의약품 및 기타 완제 의약품 제조업,2001-01-01,0.000000e+00,4329948.0,0.000000e+00,1.674465e+10,3.004641e+10,화학물질 및 화학제품 제조업_의료물질의약품
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374335,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2024-04-01,-9.589924e+09,-2940319.0,9.632000e+06,0.000000e+00,0.000000e+00,"전문, 과학 및 기술관련 서비스업"
374336,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2024-07-01,-1.188333e+10,7760477.0,5.462700e+07,0.000000e+00,1.090765e+09,"전문, 과학 및 기술관련 서비스업"
374337,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2024-10-01,3.202594e+10,-7760477.0,-1.113170e+08,0.000000e+00,-1.090765e+09,"전문, 과학 및 기술관련 서비스업"
374338,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2025-01-01,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,"전문, 과학 및 기술관련 서비스업"
374339,NMC8807,A950220,네오이뮨텍,(주)네오이뮨텍,NaN,2021-03-16,12.0,M70130.자연과학 및 공학 융합 연구개발업,2025-04-01,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,"전문, 과학 및 기술관련 서비스업"

In [34]:
industry_list = [
   "전기장비 제조업","기계 및 장비 제조업","운송장비 제조업_자동차", "운송장비 제조업_조선기타운수", "기타 제조업 및 산업용 장비 수리업_가구","기타 제조업 및 산업용 장비 수리업_기타제품","전기업 + 가스, 증기 및 공기조절 공급업",
   "수도, 하수 및 폐기물 처리, 원료 재생업","건물건설 및 건축보수업","토목건설업","도소매업","숙박 및 음식점업","운수업"
]

filtered_df = dfs["Sheet"][dfs["Sheet"]['매핑한 산업'].isin(industry_list)]
filtered_df

,업체코드,종목코드,종목명,691005.업체명,691020.사업자번호,691050.상장일,691060.결산월,691450.KSIC-세세분류(11차),DATE,EBITDA,인건비,"유,무형,리스자산의증가",매출원가,수익(매출액),매핑한 산업
102,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2000-01-01,0.000000e+00,544152.0,0.000000e+00,2.799049e+10,3.131630e+10,운송장비 제조업_조선기타운수
103,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2000-04-01,0.000000e+00,529446.0,0.000000e+00,3.218369e+10,3.792470e+10,운송장비 제조업_조선기타운수
104,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2000-07-01,0.000000e+00,530405.0,0.000000e+00,3.185522e+10,3.875848e+10,운송장비 제조업_조선기타운수
105,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2000-10-01,-7.798581e+09,10143695.0,3.741770e+09,2.611673e+10,2.787019e+10,운송장비 제조업_조선기타운수
106,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2001-01-01,0.000000e+00,537856.0,0.000000e+00,2.133264e+10,2.561618e+10,운송장비 제조업_조선기타운수
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373927,NJB0688,A950170,JTC,(주)제이티씨,NaN,2018-04-06,2.0,G47130.면세점,2024-04-01,1.109332e+10,5284616.0,3.226334e+09,1.960907e+10,7.749555e+10,도소매업
373928,NJB0688,A950170,JTC,(주)제이티씨,NaN,2018-04-06,2.0,G47130.면세점,2024-07-01,1.145466e+10,5532262.0,1.890192e+09,1.798675e+10,7.447296e+10,도소매업
373929,NJB0688,A950170,JTC,(주)제이티씨,NaN,2018-04-06,2.0,G47130.면세점,2024-10-01,-6.333496e+09,-3883023.0,-4.152853e+09,-2.321521e+10,-8.668787e+10,도소매업
373930,NJB0688,A950170,JTC,(주)제이티씨,NaN,2018-04-06,2.0,G47130.면세점,2025-01-01,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,도소매업
373931,NJB0688,A950170,JTC,(주)제이티씨,NaN,2018-04-06,2.0,G47130.면세점,2025-04-01,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,도소매업

In [35]:
filtered_df = filtered_df.rename(columns={'691005.업체명':'업체명', '691020.사업자번호':'사업자번호',
                                    '691050.상장일':'상장번호', '691050.상장일':'상장일',
                                    '691060.결산월':'결산월', '691450.KSIC-세세분류(11차)':'산업세세분류',
                                    'DATE':'조사일'})
filtered_df.head()

,업체코드,종목코드,종목명,업체명,사업자번호,상장일,결산월,산업세세분류,조사일,EBITDA,인건비,"유,무형,리스자산의증가",매출원가,수익(매출액),매핑한 산업
102,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2000-01-01,0.000000e+00,544152.0,0.000000e+00,2.799049e+10,3.131630e+10,운송장비 제조업_조선기타운수
103,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2000-04-01,0.000000e+00,529446.0,0.000000e+00,3.218369e+10,3.792470e+10,운송장비 제조업_조선기타운수
104,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2000-07-01,0.000000e+00,530405.0,0.000000e+00,3.185522e+10,3.875848e+10,운송장비 제조업_조선기타운수
105,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2000-10-01,-7.798581e+09,10143695.0,3.741770e+09,2.611673e+10,2.787019e+10,운송장비 제조업_조선기타운수
106,N320498,A000040,KR모터스,KR모터스(주),305-81-00020,1976-05-25,12.0,C31921.모터사이클 제조업,2001-01-01,0.000000e+00,537856.0,0.000000e+00,2.133264e+10,2.561618e+10,운송장비 제조업_조선기타운수

In [36]:
filtered_df.to_csv('임지오기업.csv', encoding='utf-8-sig')

In [37]:
df = pd.read_csv('임지오기업.csv')

In [38]:
전기장비기업 = df[df['매핑한 산업'] == "전기장비 제조업"]

In [39]:
columns = ['EBITDA', '인건비']
grouped = 전기장비기업.groupby('조사일')[columns].sum()
grouped

                  EBITDA          인건비
조사일
2000-01-01  0.000000e+00   11873990.0
2000-04-01  0.000000e+00   63903976.0
2000-07-01  0.000000e+00   -7221776.0
2000-10-01  1.422085e+12  743075745.0
2001-01-01  0.000000e+00   15667442.0
...                  ...          ...
2024-04-01  5.880269e+11  550383950.0
2024-07-01  7.237220e+10  492519748.0
2024-10-01  1.550230e+11  585506854.0
2025-01-01  1.248370e+11  235882356.0
2025-04-01 -2.341485e+10 -235882356.0

[102 rows x 2 columns]

In [40]:
grouped = grouped.reset_index()

In [41]:
grouped

            조사일        EBITDA          인건비
0    2000-01-01  0.000000e+00   11873990.0
1    2000-04-01  0.000000e+00   63903976.0
2    2000-07-01  0.000000e+00   -7221776.0
3    2000-10-01  1.422085e+12  743075745.0
4    2001-01-01  0.000000e+00   15667442.0
..          ...           ...          ...
97   2024-04-01  5.880269e+11  550383950.0
98   2024-07-01  7.237220e+10  492519748.0
99   2024-10-01  1.550230e+11  585506854.0
100  2025-01-01  1.248370e+11  235882356.0
101  2025-04-01 -2.341485e+10 -235882356.0

[102 rows x 3 columns]

In [42]:
grouped['조사일']=pd.to_datetime(grouped['조사일'])

# 분기(Quarter) 단위로 변환
grouped["index"] = grouped["조사일"].dt.to_period("Q")
grouped = grouped.drop(columns=["조사일"])
print(grouped)

# # 조사일이 Period 타입(예: 2010Q1)이라고 가정
# mask = (grouped["index"] >= pd.Period("2010Q1")) & (grouped["index"] <= pd.Period("2025Q1"))
# 기업= grouped.loc[mask]

           EBITDA          인건비   index
0    0.000000e+00   11873990.0  2000Q1
1    0.000000e+00   63903976.0  2000Q2
2    0.000000e+00   -7221776.0  2000Q3
3    1.422085e+12  743075745.0  2000Q4
4    0.000000e+00   15667442.0  2001Q1
..            ...          ...     ...
97   5.880269e+11  550383950.0  2024Q2
98   7.237220e+10  492519748.0  2024Q3
99   1.550230e+11  585506854.0  2024Q4
100  1.248370e+11  235882356.0  2025Q1
101 -2.341485e+10 -235882356.0  2025Q2

[102 rows x 3 columns]

In [43]:
mask = (grouped["index"] >= pd.Period("2015Q1")) & (grouped["index"] <= pd.Period("2025Q2"))
기업= grouped.loc[mask]
기업
기업['합산'] = 기업['EBITDA']+기업['인건비']
기업

/tmp/ipython-input-2516843845.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기업['합산'] = 기업['EBITDA']+기업['인건비']

           EBITDA           인건비   index            합산
60   2.596062e+11  1.686700e+08  2015Q1  2.597749e+11
61   2.846790e+11  1.546657e+08  2015Q2  2.848337e+11
62   3.663875e+11  1.607252e+08  2015Q3  3.665482e+11
63   1.716946e+11  4.209451e+08  2015Q4  1.721156e+11
64  -4.316049e+11  6.914076e+08  2016Q1 -4.309135e+11
65   2.069940e+11  1.461942e+08  2016Q2  2.071402e+11
66   1.598279e+11  1.370653e+08  2016Q3  1.599650e+11
67   4.143464e+11  7.003417e+08  2016Q4  4.150468e+11
68   2.254426e+11  1.457721e+08  2017Q1  2.255884e+11
69   3.773892e+11  1.413807e+08  2017Q2  3.775305e+11
70   4.272031e+11  1.398476e+08  2017Q3  4.273429e+11
71   4.748173e+11  7.139244e+08  2017Q4  4.755312e+11
72   3.034750e+11  1.611954e+08  2018Q1  3.036362e+11
73   4.703969e+11  1.912284e+08  2018Q2  4.705882e+11
74   5.344569e+11  2.021853e+08  2018Q3  5.346591e+11
75   6.585925e+11  1.062600e+09  2018Q4  6.596551e+11
76   4.741316e+11  2.012634e+08  2019Q1  4.743329e+11
77   4.960235e+11  1.929453e+08  2019Q2  4.962164e+11
78   5.637235e+11  2.002745e+08  2019Q3  5.639238e+11
79   5.759796e+11  1.356616e+09  2019Q4  5.773363e+11
80   3.119670e+11  2.431611e+08  2020Q1  3.122102e+11
81   6.267943e+11  2.087825e+08  2020Q2  6.270031e+11
82   6.537075e+11  2.179198e+08  2020Q3  6.539254e+11
83   4.321661e+11  1.171149e+09  2020Q4  4.333372e+11
84   7.196173e+11  3.632690e+08  2021Q1  7.199806e+11
85   1.467562e+12  4.027726e+08  2021Q2  1.467964e+12
86   1.750081e+11  4.068541e+08  2021Q3  1.754150e+11
87   5.409614e+11  1.750690e+09  2021Q4  5.427121e+11
88   7.425286e+11  4.601909e+08  2022Q1  7.429888e+11
89   7.540633e+11  4.631064e+08  2022Q2  7.545264e+11
90   1.316167e+12  5.397201e+08  2022Q3  1.316707e+12
91   7.727310e+11  1.772289e+09  2022Q4  7.745033e+11
92   7.842936e+11  5.215198e+08  2023Q1  7.848151e+11
93   9.015983e+11  5.430673e+08  2023Q2  9.021413e+11
94   1.005060e+12  5.231579e+08  2023Q3  1.005583e+12
95   4.923215e+11  1.744635e+09  2023Q4  4.940661e+11
96   3.908666e+11  5.647366e+08  2024Q1  3.914313e+11
97   5.880269e+11  5.503840e+08  2024Q2  5.885773e+11
98   7.237220e+10  4.925197e+08  2024Q3  7.286472e+10
99   1.550230e+11  5.855069e+08  2024Q4  1.556085e+11
100  1.248370e+11  2.358824e+08  2025Q1  1.250729e+11
101 -2.341485e+10 -2.358824e+08  2025Q2 -2.365073e+10

In [44]:
기업 = 기업[['index'] + [col for col in 기업.columns if col != 'index']]
기업 = 기업.reset_index()

In [45]:
기업
기업 = 기업.drop(columns=['level_0'])

In [46]:
기업

     index        EBITDA           인건비            합산
0   2015Q1  2.596062e+11  1.686700e+08  2.597749e+11
1   2015Q2  2.846790e+11  1.546657e+08  2.848337e+11
2   2015Q3  3.663875e+11  1.607252e+08  3.665482e+11
3   2015Q4  1.716946e+11  4.209451e+08  1.721156e+11
4   2016Q1 -4.316049e+11  6.914076e+08 -4.309135e+11
5   2016Q2  2.069940e+11  1.461942e+08  2.071402e+11
6   2016Q3  1.598279e+11  1.370653e+08  1.599650e+11
7   2016Q4  4.143464e+11  7.003417e+08  4.150468e+11
8   2017Q1  2.254426e+11  1.457721e+08  2.255884e+11
9   2017Q2  3.773892e+11  1.413807e+08  3.775305e+11
10  2017Q3  4.272031e+11  1.398476e+08  4.273429e+11
11  2017Q4  4.748173e+11  7.139244e+08  4.755312e+11
12  2018Q1  3.034750e+11  1.611954e+08  3.036362e+11
13  2018Q2  4.703969e+11  1.912284e+08  4.705882e+11
14  2018Q3  5.344569e+11  2.021853e+08  5.346591e+11
15  2018Q4  6.585925e+11  1.062600e+09  6.596551e+11
16  2019Q1  4.741316e+11  2.012634e+08  4.743329e+11
17  2019Q2  4.960235e+11  1.929453e+08  4.962164e+11
18  2019Q3  5.637235e+11  2.002745e+08  5.639238e+11
19  2019Q4  5.759796e+11  1.356616e+09  5.773363e+11
20  2020Q1  3.119670e+11  2.431611e+08  3.122102e+11
21  2020Q2  6.267943e+11  2.087825e+08  6.270031e+11
22  2020Q3  6.537075e+11  2.179198e+08  6.539254e+11
23  2020Q4  4.321661e+11  1.171149e+09  4.333372e+11
24  2021Q1  7.196173e+11  3.632690e+08  7.199806e+11
25  2021Q2  1.467562e+12  4.027726e+08  1.467964e+12
26  2021Q3  1.750081e+11  4.068541e+08  1.754150e+11
27  2021Q4  5.409614e+11  1.750690e+09  5.427121e+11
28  2022Q1  7.425286e+11  4.601909e+08  7.429888e+11
29  2022Q2  7.540633e+11  4.631064e+08  7.545264e+11
30  2022Q3  1.316167e+12  5.397201e+08  1.316707e+12
31  2022Q4  7.727310e+11  1.772289e+09  7.745033e+11
32  2023Q1  7.842936e+11  5.215198e+08  7.848151e+11
33  2023Q2  9.015983e+11  5.430673e+08  9.021413e+11
34  2023Q3  1.005060e+12  5.231579e+08  1.005583e+12
35  2023Q4  4.923215e+11  1.744635e+09  4.940661e+11
36  2024Q1  3.908666e+11  5.647366e+08  3.914313e+11
37  2024Q2  5.880269e+11  5.503840e+08  5.885773e+11
38  2024Q3  7.237220e+10  4.925197e+08  7.286472e+10
39  2024Q4  1.550230e+11  5.855069e+08  1.556085e+11
40  2025Q1  1.248370e+11  2.358824e+08  1.250729e+11
41  2025Q2 -2.341485e+10 -2.358824e+08 -2.365073e+10

In [47]:
가동률지수
생산능력지수
생산지수

생산지수['index']=생산지수['PRD_DE'].apply(to_quarter)
생산지수 = 생산지수.drop(columns=["PRD_DE"])
생산지수 = 생산지수.rename(columns={'DT': '생산지수'})
생산지수

KeyError: 'PRD_DE'

In [48]:
내수출하지수

     내수출하지수   index
0    90.381  2015Q1
1    90.138  2015Q2
2    92.510  2015Q3
3    91.658  2015Q4
4    90.381  2016Q1
5    89.712  2016Q2
6    90.442  2016Q3
7    94.152  2016Q4
8    94.669  2017Q1
9    94.244  2017Q2
10   96.433  2017Q3
11   93.727  2017Q4
12   97.862  2018Q1
13  101.329  2018Q2
14  100.904  2018Q3
15  100.721  2018Q4
16  101.117  2019Q1
17  101.056  2019Q2
18  100.204  2019Q3
19  101.117  2019Q4
20   97.300  2020Q1
21   99.600  2020Q2
22  100.000  2020Q3
23  102.600  2020Q4
24  102.600  2021Q1
25  101.100  2021Q2
26  101.400  2021Q3
27  103.200  2021Q4
28  103.300  2022Q1
29  104.000  2022Q2
30  104.100  2022Q3
31  102.600  2022Q4
32  108.200  2023Q1
33  105.900  2023Q2
34  104.800  2023Q3
35  104.800  2023Q4
36  101.700  2024Q1
37   95.400  2024Q2
38   90.900  2024Q3
39   91.400  2024Q4
40   96.600  2025Q1
41   97.400  2025Q2

In [ ]:
수출출하지수
수출출하지수['index']=수출출하지수['PRD_DE'].apply(to_quarter)
수출출하지수 = 수출출하지수.drop(columns=["PRD_DE"])
수출출하지수 = 수출출하지수.rename(columns={'DT': '수출출하지수'})
수출출하지수

## 전체 데이터 합산

In [49]:
from functools import reduce
import pandas as pd

# 모든 데이터프레임의 index 컬럼을 문자열로 변환
for df in [생산지수, 내수출하지수, 수출출하지수, 생산능력지수, 가동률지수, 기업]:
    df['index'] = df['index'].astype(str)

# 리스트에 넣고 합치기
dfs = [생산지수, 내수출하지수, 수출출하지수, 생산능력지수, 가동률지수, 기업]
df_merged = reduce(lambda left, right: pd.merge(left, right, on='index', how='outer'), dfs)

In [50]:
df_merged
df_merged = df_merged[['index'] + [col for col in df_merged.columns if col != 'index']]

In [51]:
df_merged

,index,생산지수,내수출하지수,수출출하지수,생산능력지수,가동률지수,EBITDA,인건비,합산
0,2015Q1,90.577,90.381,90.071,93.177,97.858,2.596062e+11,1.686700e+08,2.597749e+11
1,2015Q2,90.360,90.138,91.428,93.333,97.522,2.846790e+11,1.546657e+08,2.848337e+11
2,2015Q3,93.073,92.510,93.093,94.178,100.217,3.663875e+11,1.607252e+08,3.665482e+11
3,2015Q4,94.494,91.658,94.480,94.929,99.958,1.716946e+11,4.209451e+08,1.721156e+11
4,2016Q1,95.813,90.381,99.969,94.210,101.547,-4.316049e+11,6.914076e+08,-4.309135e+11
5,2016Q2,92.740,89.712,95.899,93.865,99.093,2.069940e+11,1.461942e+08,2.071402e+11
6,2016Q3,94.348,90.442,97.564,94.773,100.701,1.598279e+11,1.370653e+08,1.599650e+11
7,2016Q4,97.281,94.152,97.718,94.053,103.622,4.143464e+11,7.003417e+08,4.150468e+11
8,2017Q1,96.966,94.669,95.961,95.211,102.813,2.254426e+11,1.457721e+08,2.255884e+11
9,2017Q2,98.666,94.244,96.731,96.369,102.724,3.773892e+11,1.413807e+08,3.775305e+11
10,2017Q3,98.381,96.433,98.982,95.994,102.886,4.272031e+11,1.398476e+08,4.273429e+11
11,2017Q4,100.384,93.727,102.713,96.714,104.056,4.748173e+11,7.139244e+08,4.755312e+11
12,2018Q1,96.856,97.862,98.489,96.870,101.008,3.034750e+11,1.611954e+08,3.036362e+11
13,2018Q2,98.682,101.329,95.868,97.340,101.864,4.703969e+11,1.912284e+08,4.705882e+11
14,2018Q3,98.309,100.904,98.735,97.653,100.483,5.344569e+11,2.021853e+08,5.346591e+11
15,2018Q4,100.190,100.721,93.710,98.185,102.260,6.585925e+11,1.062600e+09,6.596551e+11
16,2019Q1,97.446,101.117,103.207,98.028,99.709,4.741316e+11,2.012634e+08,4.743329e+11
17,2019Q2,100.310,101.056,106.599,97.871,102.098,4.960235e+11,1.929453e+08,4.962164e+11
18,2019Q3,101.271,100.204,105.119,97.715,102.939,5.637235e+11,2.002745e+08,5.639238e+11
19,2019Q4,103.959,101.117,107.216,98.122,105.009,5.759796e+11,1.356616e+09,5.773363e+11
20,2020Q1,97.400,97.300,100.600,100.100,97.500,3.119670e+11,2.431611e+08,3.122102e+11
21,2020Q2,94.900,99.600,86.900,99.400,96.000,6.267943e+11,2.087825e+08,6.270031e+11
22,2020Q3,101.800,100.000,100.700,99.900,101.900,6.537075e+11,2.179198e+08,6.539254e+11
23,2020Q4,105.800,102.600,112.200,100.600,104.600,4.321661e+11,1.171149e+09,4.333372e+11
24,2021Q1,106.300,102.600,105.700,100.300,106.500,7.196173e+11,3.632690e+08,7.199806e+11
25,2021Q2,106.600,101.100,110.300,98.800,107.200,1.467562e+12,4.027726e+08,1.467964e+12
26,2021Q3,108.400,101.400,112.300,98.500,108.200,1.750081e+11,4.068541e+08,1.754150e+11
27,2021Q4,111.200,103.200,122.100,98.200,110.100,5.409614e+11,1.750690e+09,5.427121e+11
28,2022Q1,111.300,103.300,132.200,102.700,106.600,7.425286e+11,4.601909e+08,7.429888e+11
29,2022Q2,112.100,104.000,137.500,103.400,106.700,7.540633e+11,4.631064e+08,7.545264e+11
30,2022Q3,114.400,104.100,143.800,101.400,109.800,1.316167e+12,5.397201e+08,1.316707e+12
31,2022Q4,109.200,102.600,134.300,98.100,109.200,7.727310e+11,1.772289e+09,7.745033e+11
32,2023Q1,117.300,108.200,134.800,103.200,112.300,7.842936e+11,5.215198e+08,7.848151e+11
33,2023Q2,116.400,105.900,132.000,104.300,108.300,9.015983e+11,5.430673e+08,9.021413e+11
34,2023Q3,108.600,104.800,114.100,100.800,103.700,1.005060e+12,5.231579e+08,1.005583e+12
35,2023Q4,105.100,104.800,102.500,98.800,101.500,4.923215e+11,1.744635e+09,4.940661e+11
36,2024Q1,105.500,101.700,100.300,100.400,103.600,3.908666e+11,5.647366e+08,3.914313e+11
37,2024Q2,105.600,95.400,97.600,101.100,103.900,5.880269e+11,5.503840e+08,5.885773e+11
38,2024Q3,100.800,90.900,89.600,102.000,98.500,7.237220e+10,4.925197e+08,7.286472e+10
39,2024Q4,102.900,91.400,89.000,102.100,98.600,1.550230e+11,5.855069e+08,1.556085e+11
40,2025Q1,103.300,96.600,85.600,100.800,100.300,1.248370e+11,2.358824e+08,1.250729e+11
41,2025Q2,104.200,97.400,94.800,101.600,99.700,-2.341485e+10,-2.358824e+08,-2.365073e+10

In [52]:
d = pd.read_csv("전기장비1차.csv")

In [53]:
from functools import reduce
import pandas as pd



# 리스트에 넣고 합치기
dfs = [df_merged,d]
merged = reduce(lambda left, right: pd.merge(left, right, on='index', how='outer'), dfs)

In [54]:
merged
merged = merged.drop(columns=["Unnamed: 0"])

In [55]:
merged.to_csv('전기장비.csv')

#데이터QoQ 변환

In [56]:
import pandas as pd

# df는 위의 데이터프레임
df_qoq = merged.copy()

# 분기 순서대로 정렬 (혹시 index가 문자열일 경우를 대비)
df_qoq = df_qoq.sort_values('index')

# 수치형 컬럼만 선택 (index 제외)
num_cols = df_qoq.select_dtypes(include=['number']).columns

# 전분기 대비 증감률 (%) 계산
df_qoq[num_cols] = df_qoq[num_cols].pct_change() * 100

# 결과 확인
print(df_qoq.head())

    index      생산지수    내수출하지수    수출출하지수    생산능력지수     가동률지수      EBITDA  \
0  2015Q1       NaN       NaN       NaN       NaN       NaN         NaN
1  2015Q2 -0.239575 -0.268862  1.506589  0.167423 -0.343355    9.658010
2  2015Q3  3.002435  2.631521  1.821105  0.905360  2.763479   28.701981
3  2015Q4  1.526759 -0.920982  1.489908  0.797426 -0.258439  -53.138517
4  2016Q1  1.395856 -1.393223  5.809695 -0.757408  1.589668 -351.379418

          인건비          합산    업황실적BSI  ...   생산실적BSI  신규수주실적BSI  제품재고실적BSI  \
0         NaN         NaN        NaN  ...       NaN        NaN        NaN
1   -8.302819    9.646348   3.940887  ... -3.422053  -1.167315   2.564103
2    3.917862   28.688523 -14.691943  ... -7.086614 -11.417323   2.187500
3  161.903548  -53.044225   0.000000  ...  1.694915  -0.888889  -1.834862
4   64.251252 -350.362905  -1.111111  ... -7.083333  -7.174888   0.623053

   가동률실적BSI  설비투자실적BSI   채산성실적BSI  자금사정실적BSI  인력사정실적BSI   전기장비ppi  전기장비 제조업
0       NaN         NaN       NaN        NaN        NaN       NaN       NaN
1 -0.781250   -5.653710  2.325581   0.000000   2.816901 -0.620612  0.221884
2 -7.480315    2.996255 -6.818182  -1.953125   0.000000  0.000000 -2.491356
3 -2.553191   -2.545455 -3.252033  -1.593625   1.712329 -0.563063 -7.087596
4 -3.493450    2.238806  6.722689  -0.404858  -3.703704 -0.061773  0.229285

[5 rows x 23 columns]

In [57]:
df_qoq
df_qoq = df_qoq.drop(index=[0, 1, 2,3])

In [58]:
df_qoq.isnull().sum()

index         0
생산지수          0
내수출하지수        0
수출출하지수        0
생산능력지수        0
가동률지수         0
EBITDA        0
인건비           0
합산            0
업황실적BSI       0
매출실적BSI       0
수출실적BSI       0
내수판매실적BSI     0
생산실적BSI       0
신규수주실적BSI     0
제품재고실적BSI     0
가동률실적BSI      0
설비투자실적BSI     0
채산성실적BSI      0
자금사정실적BSI     0
인력사정실적BSI     0
전기장비ppi       0
전기장비 제조업      0
dtype: int64

In [59]:
df_qoq.to_csv('전기장비qoq.csv')

#데이터YoY변환

In [60]:
import pandas as pd

# df_merged는 원본 데이터프레임
df_yoy = merged.copy()

# 분기 순서대로 정렬
df_yoy = df_yoy.sort_values('index')

# 수치형 컬럼만 선택 (index 제외)
num_cols = df_yoy.select_dtypes(include=['number']).columns

# 전년 동분기 대비 증감률 (%) 계산 (4분기 차이)
df_yoy[num_cols] = df_yoy[num_cols].pct_change(periods=4) * 100

# 결과 확인
print(df_yoy.head(10))

    index      생산지수    내수출하지수     수출출하지수    생산능력지수     가동률지수      EBITDA  \
0  2015Q1       NaN       NaN        NaN       NaN       NaN         NaN
1  2015Q2       NaN       NaN        NaN       NaN       NaN         NaN
2  2015Q3       NaN       NaN        NaN       NaN       NaN         NaN
3  2015Q4       NaN       NaN        NaN       NaN       NaN         NaN
4  2016Q1  5.780717  0.000000  10.989109  1.108643  3.769748 -266.253707
5  2016Q2  2.633909 -0.472609   4.890187  0.570002  1.610919  -27.288628
6  2016Q3  1.369892 -2.235434   4.802724  0.631782  0.482952  -56.377356
7  2016Q4  2.949394  2.720985   3.427180 -0.922795  3.665540  141.327551
8  2017Q1  1.203386  4.744360  -4.009243  1.062520  1.246713 -152.233548
9  2017Q2  6.389907  5.051721   0.867579  2.667661  3.664235   82.318879

          인건비          합산    업황실적BSI  ...    생산실적BSI  신규수주실적BSI  제품재고실적BSI  \
0         NaN         NaN        NaN  ...        NaN        NaN        NaN
1         NaN         NaN        NaN  ...        NaN        NaN        NaN
2         NaN         NaN        NaN  ...        NaN        NaN        NaN
3         NaN         NaN        NaN  ...        NaN        NaN        NaN
4  309.917311 -265.879603 -12.315271  ... -15.209125 -19.455253   3.525641
5   -5.477298  -27.276785 -10.900474  ...  -9.055118 -14.960630   3.125000
6  -14.720764  -56.359090   4.444444  ...  -5.084746  -8.444444  -1.223242
7   66.373633  141.144235  13.888889  ...   1.250000   2.242152  -3.115265
8  -78.916618 -152.351186  16.853933  ...  17.040359  17.874396   0.000000
9   -3.292482   82.258456  28.191489  ...  21.212121  23.611111  -1.515152

    가동률실적BSI  설비투자실적BSI   채산성실적BSI  자금사정실적BSI  인력사정실적BSI   전기장비ppi   전기장비 제조업
0        NaN         NaN       NaN        NaN        NaN       NaN        NaN
1        NaN         NaN       NaN        NaN        NaN       NaN        NaN
2        NaN         NaN       NaN        NaN        NaN       NaN        NaN
3        NaN         NaN       NaN        NaN        NaN       NaN        NaN
4 -13.671875   -3.180212 -1.550388  -3.906250   0.704225 -1.241225  -8.993165
5  -7.480315   -2.621723 -3.787879   1.171875   4.794521 -0.900901 -10.174518
6  -5.106383   -1.818182  2.845528   5.577689   3.424658 -1.423014  -5.544499
7   9.606987    2.611940  7.563025   6.882591  -1.683502 -0.123546   2.051499
8  15.384615    2.554745 -8.661417  -1.219512   1.398601  0.999279  10.167808
9  11.914894   10.000000  3.937008   1.544402   1.307190  0.950413  11.228092

[10 rows x 23 columns]

In [61]:
df_yoy=df_yoy.dropna()

In [62]:
df_yoy

,index,생산지수,내수출하지수,수출출하지수,생산능력지수,가동률지수,EBITDA,인건비,합산,업황실적BSI,...,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,전기장비ppi,전기장비 제조업
4,2016Q1,5.780717,0.000000,10.989109,1.108643,3.769748,-266.253707,309.917311,-265.879603,-12.315271,...,-15.209125,-19.455253,3.525641,-13.671875,-3.180212,-1.550388,-3.906250,0.704225,-1.241225,-8.993165
5,2016Q2,2.633909,-0.472609,4.890187,0.570002,1.610919,-27.288628,-5.477298,-27.276785,-10.900474,...,-9.055118,-14.960630,3.125000,-7.480315,-2.621723,-3.787879,1.171875,4.794521,-0.900901,-10.174518
6,2016Q3,1.369892,-2.235434,4.802724,0.631782,0.482952,-56.377356,-14.720764,-56.359090,4.444444,...,-5.084746,-8.444444,-1.223242,-5.106383,-1.818182,2.845528,5.577689,3.424658,-1.423014,-5.544499
7,2016Q4,2.949394,2.720985,3.427180,-0.922795,3.665540,141.327551,66.373633,141.144235,13.888889,...,1.250000,2.242152,-3.115265,9.606987,2.611940,7.563025,6.882591,-1.683502,-0.123546,2.051499
8,2017Q1,1.203386,4.744360,-4.009243,1.062520,1.246713,-152.233548,-78.916618,-152.351186,16.853933,...,17.040359,17.874396,0.000000,15.384615,2.554745,-8.661417,-1.219512,1.398601,0.999279,10.167808
9,2017Q2,6.389907,5.051721,0.867579,2.667661,3.664235,82.318879,-3.292482,82.258456,28.191489,...,21.212121,23.611111,-1.515152,11.914894,10.000000,3.937008,1.544402,1.307190,0.950413,11.228092
10,2017Q3,4.274600,6.624135,1.453405,1.288342,2.169790,167.289393,2.029938,167.147791,31.914894,...,25.892857,24.757282,1.857585,25.112108,8.148148,1.581028,-1.132075,-2.317881,2.222453,14.106597
11,2017Q4,3.189729,-0.451398,5.111648,2.829256,0.418830,14.594280,1.939445,14.572926,7.804878,...,4.938272,6.140351,3.536977,1.593625,0.000000,-2.343750,-6.818182,-2.054795,2.267807,10.274489
12,2018Q1,-0.113442,3.372804,2.634404,1.742446,-1.755615,34.613005,10.580392,34.597476,7.692308,...,-3.065134,0.000000,-1.857585,-3.137255,4.626335,7.758621,2.880658,0.689655,1.723786,5.774511
13,2018Q2,0.016216,7.517720,-0.892165,1.007585,-0.837195,24.645062,35.257714,24.649036,7.883817,...,1.428571,3.370787,-4.307692,8.365019,4.895105,-2.272727,1.140684,0.645161,2.312730,5.917273
14,2018Q3,-0.073185,4.636380,-0.249540,1.728233,-2.335595,25.106058,44.575474,25.112430,-7.258065,...,-6.382979,-7.392996,-2.127660,-7.526882,-3.424658,1.556420,-4.961832,6.101695,0.914355,2.016879
15,2018Q4,-0.193258,7.462097,-8.765200,1.520979,-1.725994,38.704405,48.839333,38.719621,3.619910,...,-2.745098,-4.545455,-4.347826,-3.921569,1.818182,6.000000,0.813008,4.195804,0.191513,10.437778
16,2019Q1,0.609152,3.326112,4.790383,1.195417,-1.286037,56.234156,24.856803,56.217498,-4.017857,...,3.162055,-0.819672,-1.892744,5.668016,-0.680272,7.600000,0.800000,3.767123,-0.030081,1.410343
17,2019Q2,1.649744,-0.269419,11.193516,0.545511,0.229718,5.447852,0.897829,5.446003,-13.846154,...,-7.042254,-14.130435,3.215434,-10.175439,-5.333333,-3.100775,-12.030075,0.961538,0.130026,5.259963
18,2019Q3,3.012949,-0.693729,6.465792,0.063490,2.444195,5.475950,-0.945071,5.473522,-20.869565,...,-9.848485,-5.462185,3.416149,-7.751938,-7.092199,-10.344828,-10.843373,-0.319489,0.785261,0.813236
19,2019Q4,3.761852,0.393165,14.412549,-0.064165,2.688246,-12.543853,27.669429,-12.479076,-2.183406,...,0.000000,6.493506,6.168831,1.224490,-6.428571,-3.773585,-3.629032,2.013423,0.593561,-2.189560
20,2020Q1,-0.047206,-3.774835,-2.525991,2.113682,-2.215447,-34.202448,20.817348,-34.179103,-7.906977,...,-8.812261,-5.785124,4.501608,-10.344828,-10.616438,-7.063197,-7.539683,4.620462,0.080241,-0.946256
21,2020Q2,-5.393281,-1.440785,-18.479535,1.562261,-5.972693,26.363844,8.208156,26.356785,-38.839286,...,-37.500000,-33.755274,-1.246106,-40.625000,-17.253521,-14.000000,-20.940171,7.301587,-0.869044,-7.298760
22,2020Q3,0.522361,-0.203585,-4.203807,2.236095,-1.009336,15.962425,8.810525,15.959885,12.087912,...,-10.504202,-12.000000,-3.303303,-2.941176,-8.396947,7.692308,13.063063,0.961538,0.209769,0.777595
23,2020Q4,1.770890,1.466618,4.648560,2.525428,-0.389490,-24.968518,-13.671297,-24.941972,11.607143,...,4.435484,-7.723577,-6.116208,5.645161,-0.381679,2.352941,4.602510,2.302632,0.670067,6.350900
24,2021Q1,9.137577,5.447071,5.069583,0.199800,9.230769,130.670951,49.394355,130.607650,23.737374,...,10.504202,12.280702,-5.230769,12.393162,5.363985,3.200000,11.587983,-8.517350,2.555622,13.397277
25,2021Q2,12.328767,1.506024,26.927503,-0.603622,11.666667,134.137648,92.914893,134.123922,91.240876,...,85.454545,85.987261,-6.940063,101.973684,27.659574,15.348837,40.000000,-16.863905,6.116485,16.575346
26,2021Q3,6.483301,1.400000,11.519364,-1.401401,6.182532,-73.228373,86.699023,-73.175078,32.352941,...,38.967136,35.353535,-2.484472,29.870130,25.000000,-1.190476,5.179283,-9.841270,5.602073,7.364657
27,2021Q4,5.103970,0.584795,8.823529,-2.385686,5.258126,25.174435,49.484872,25.240137,13.200000,...,16.988417,19.383260,-2.931596,17.938931,9.961686,1.149425,3.200000,-14.469453,6.755414,4.250627
28,2022Q1,4.703669,0.682261,25.070956,2.392822,0.093897,3.183824,26.680499,3.195680,1.632653,...,11.406844,11.328125,-2.272727,11.026616,7.272727,-7.751938,-0.769231,-5.517241,7.720121,7.223602
29,2022Q2,5.159475,2.868447,24.660018,4.655870,-0.466418,-48.617942,14.979629,-48.600492,-2.290076,...,-10.130719,-5.479452,-3.389831,-7.817590,-5.333333,-11.290323,-8.494208,-7.117438,6.552084,7.650825
30,2022Q3,5.535055,2.662722,28.049866,2.944162,1.478743,652.060475,32.656925,650.623842,-10.740741,...,-9.459459,-0.746269,0.000000,-9.333333,-6.000000,-3.212851,-6.060606,-7.394366,6.588635,7.131756
31,2022Q4,-1.798561,-0.581395,9.991810,-0.101833,-0.817439,42.844021,1.233739,42.709794,-10.954064,...,-9.900990,2.214022,12.751678,-11.326861,-1.742160,-9.469697,-2.325581,-4.135338,7.128234,-0.870753
32,2023Q1,5.390836,4.743466,1.966717,0.486855,5.347092,5.624689,13.326839,5.629460,-7.228916,...,-10.580205,-5.263158,2.990033,-11.301370,-11.525424,3.361345,-1.162791,-5.109489,6.731380,-6.499027
33,2023Q2,3.835861,1.826923,-4.000000,0.870406,1.499531,19.565329,17.266198,19.563918,-8.203125,...,1.454545,-5.434783,4.561404,-2.826855,-3.873239,8.181818,6.329114,3.448276,5.284734,-5.630609
34,2023Q3,-5.069930,0.672430,-20.653686,-0.591716,-5.555556,-23.637350,-3.068663,-23.628918,-0.829876,...,4.104478,-3.007519,-2.866242,2.941176,-1.418440,0.829876,9.677419,4.942966,5.871413,1.975392
35,2023Q4,-3.754579,2.144250,-23.678332,0.713558,-7.051282,-36.288124,-1.560361,-36.208656,-2.380952,...,-5.860806,-16.606498,-2.976190,-9.489051,1.418440,8.786611,-0.396825,1.568627,5.489924,0.637914
36,2024Q1,-10.059676,-6.007394,-25.593472,-2.713178,-7.747106,-50.163227,8.286704,-50.124386,2.164502,...,2.671756,2.592593,6.129032,0.386100,11.111111,-0.406504,1.960784,1.538462,4.020399,-1.762005
37,2024Q2,-9.278351,-9.915014,-26.060606,-3.068073,-4.062789,-34.779498,1.347286,-34.757750,5.531915,...,-1.792115,-0.383142,9.395973,0.727273,5.128205,10.504202,2.777778,3.703704,6.323007,-3.639838
38,2024Q3,-7.182320,-13.263359,-21.472393,1.190476,-5.014465,-92.799216,-5.856396,-92.753983,-8.368201,...,-14.336918,-11.240310,11.147541,-12.142857,2.158273,-2.880658,-8.088235,1.086957,4.115433,-5.241258
39,2024Q4,-2.093245,-12.786260,-13.170732,3.340081,-2.857143,-68.511832,-66.439583,-68.504514,-12.601626,...,-0.778210,5.194805,1.840491,0.403226,-5.594406,-6.538462,3.585657,6.949807,2.923254,-5.139395
40,2025Q1,-2.085308,-5.014749,-14.656032,0.398406,-3.185328,-68.061476,-58.231440,-68.047293,-2.542373,...,-0.371747,-9.025271,-3.343465,2.307692,-6.206897,6.122449,3.076923,3.030303,3.154110,-4.475962
41,2025Q2,-1.325758,2.096436,-2.868852,0.494560,-4.042348,-103.981935,-142.857782,-104.018288,-20.564516,...,-8.394161,-13.846154,-3.067485,-5.415162,-4.529617,-6.463878,-1.158301,4.285714,-0.015922,-1.157437

In [63]:
df_yoy.to_csv("전기장비yoy.csv")

# 상관계수 보기(qoq)

In [64]:
qoq = pd.read_csv('전기장비qoq.csv')
qoq = qoq.drop(columns=["Unnamed: 0"])

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# GDP_QoQ 기준
target = '전기장비 제조업'

In [66]:
# 수치형 컬럼만 선택
num_cols = qoq.select_dtypes(include=['number']).columns

# GDP 기준 상관계수 계산
corr = qoq[num_cols].corr()[target].sort_values(ascending=False)

print("📊 GDP 대비 단순 상관계수")
print(corr)

📊 GDP 대비 단순 상관계수
전기장비 제조업      1.000000
매출실적BSI       0.369143
내수판매실적BSI     0.362965
설비투자실적BSI     0.351571
업황실적BSI       0.336849
수출실적BSI       0.332228
생산실적BSI       0.306155
가동률실적BSI      0.284930
수출출하지수        0.273059
신규수주실적BSI     0.251198
생산능력지수        0.235569
생산지수          0.219165
내수출하지수        0.185221
자금사정실적BSI     0.167014
가동률지수         0.129159
인건비           0.092648
전기장비ppi       0.041012
합산            0.017956
EBITDA        0.017661
채산성실적BSI     -0.073892
인력사정실적BSI    -0.169678
제품재고실적BSI    -0.202048
Name: 전기장비 제조업, dtype: float64

In [67]:
# 시차상관 계산 함수
def lag_corr(x, y, max_lag=4):
    result = {}
    for lag in range(-max_lag, max_lag+1):
        corr = x.corr(y.shift(lag))
        result[lag] = corr
    return pd.Series(result)

# 모든 변수와 GDP 간 시차상관 계산
lags = {}
max_lag = 4  # ±4분기 범위에서 시차 비교

for col in num_cols:
    if col != target:
        lags[col] = lag_corr(qoq[target], qoq[col], max_lag=max_lag)

# 시차상관 결과를 DataFrame으로 정리
df_lagcorr = pd.DataFrame(lags)

print("📈 GDP 기준 시차상관계수")
print(df_lagcorr)
df_lagcorr

📈 GDP 기준 시차상관계수
        생산지수    내수출하지수    수출출하지수    생산능력지수     가동률지수    EBITDA       인건비  \
-4  0.024668  0.237938  0.131986  0.211000 -0.056014 -0.067395  0.134957
-3  0.149694 -0.193620  0.176139 -0.085445  0.234369  0.031174  0.032341
-2 -0.100972  0.168579 -0.069058 -0.369179  0.139724  0.100795 -0.033381
-1 -0.042437 -0.099928  0.088371  0.034957 -0.146438  0.140810  0.105336
 0  0.219165  0.185221  0.273059  0.235569  0.129159  0.017661  0.092648
 1  0.333987  0.238888  0.322612  0.118224  0.260471  0.238348  0.048096
 2  0.137404  0.306401 -0.087113  0.049928  0.190171 -0.092729 -0.109056
 3 -0.451634 -0.119108 -0.240829 -0.363663 -0.332738 -0.097250  0.046067
 4  0.105178 -0.219852 -0.000933  0.033944  0.124331 -0.216133  0.151422

          합산   업황실적BSI   매출실적BSI  ...  내수판매실적BSI   생산실적BSI  신규수주실적BSI  \
-4 -0.066532 -0.149412 -0.205658  ...  -0.229259 -0.244657  -0.242770
-3  0.031629 -0.003462  0.034612  ...   0.010064  0.044584   0.037610
-2  0.100785  0.003464  0.088106  ...   0.080579 -0.037319   0.053496
-1  0.140552 -0.004896  0.091041  ...   0.175636  0.096989   0.167319
 0  0.017956  0.336849  0.369143  ...   0.362965  0.306155   0.251198
 1  0.238731  0.171768  0.088294  ...   0.088503  0.201029   0.100123
 2 -0.092774 -0.023972 -0.004095  ...  -0.033230 -0.035830  -0.057393
 3 -0.097329 -0.010921 -0.060848  ...  -0.051784 -0.088628  -0.088480
 4 -0.215800 -0.044361  0.011675  ...   0.072884 -0.074485  -0.001387

    제품재고실적BSI  가동률실적BSI  설비투자실적BSI   채산성실적BSI  자금사정실적BSI  인력사정실적BSI   전기장비ppi
-4  -0.060032 -0.247780   -0.193711 -0.176150  -0.230192   0.084020 -0.077633
-3   0.192598  0.125930   -0.080653  0.141544   0.090600   0.066877  0.210852
-2   0.187403 -0.109943    0.177991 -0.089914  -0.130564  -0.312681  0.105326
-1  -0.011855  0.000397    0.236524  0.025657  -0.048440  -0.133048  0.060217
 0  -0.202048  0.284930    0.351571 -0.073892   0.167014  -0.169678  0.041012
 1  -0.188955  0.251859   -0.131975  0.226243   0.139357   0.133133 -0.071356
 2  -0.114842 -0.039747   -0.017036 -0.143146  -0.031370   0.012148 -0.127892
 3   0.173225 -0.080147    0.078739  0.097525   0.018015  -0.026602 -0.208387
 4  -0.093895 -0.083637    0.043781  0.018135  -0.016733  -0.060671 -0.216299

[9 rows x 21 columns]

,생산지수,내수출하지수,수출출하지수,생산능력지수,가동률지수,EBITDA,인건비,합산,업황실적BSI,매출실적BSI,...,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,전기장비ppi
-4,0.024668,0.237938,0.131986,0.211000,-0.056014,-0.067395,0.134957,-0.066532,-0.149412,-0.205658,...,-0.229259,-0.244657,-0.242770,-0.060032,-0.247780,-0.193711,-0.176150,-0.230192,0.084020,-0.077633
-3,0.149694,-0.193620,0.176139,-0.085445,0.234369,0.031174,0.032341,0.031629,-0.003462,0.034612,...,0.010064,0.044584,0.037610,0.192598,0.125930,-0.080653,0.141544,0.090600,0.066877,0.210852
-2,-0.100972,0.168579,-0.069058,-0.369179,0.139724,0.100795,-0.033381,0.100785,0.003464,0.088106,...,0.080579,-0.037319,0.053496,0.187403,-0.109943,0.177991,-0.089914,-0.130564,-0.312681,0.105326
-1,-0.042437,-0.099928,0.088371,0.034957,-0.146438,0.140810,0.105336,0.140552,-0.004896,0.091041,...,0.175636,0.096989,0.167319,-0.011855,0.000397,0.236524,0.025657,-0.048440,-0.133048,0.060217
0,0.219165,0.185221,0.273059,0.235569,0.129159,0.017661,0.092648,0.017956,0.336849,0.369143,...,0.362965,0.306155,0.251198,-0.202048,0.284930,0.351571,-0.073892,0.167014,-0.169678,0.041012
1,0.333987,0.238888,0.322612,0.118224,0.260471,0.238348,0.048096,0.238731,0.171768,0.088294,...,0.088503,0.201029,0.100123,-0.188955,0.251859,-0.131975,0.226243,0.139357,0.133133,-0.071356
2,0.137404,0.306401,-0.087113,0.049928,0.190171,-0.092729,-0.109056,-0.092774,-0.023972,-0.004095,...,-0.033230,-0.035830,-0.057393,-0.114842,-0.039747,-0.017036,-0.143146,-0.031370,0.012148,-0.127892
3,-0.451634,-0.119108,-0.240829,-0.363663,-0.332738,-0.097250,0.046067,-0.097329,-0.010921,-0.060848,...,-0.051784,-0.088628,-0.088480,0.173225,-0.080147,0.078739,0.097525,0.018015,-0.026602,-0.208387
4,0.105178,-0.219852,-0.000933,0.033944,0.124331,-0.216133,0.151422,-0.215800,-0.044361,0.011675,...,0.072884,-0.074485,-0.001387,-0.093895,-0.083637,0.043781,0.018135,-0.016733,-0.060671,-0.216299

In [68]:
# 동행(0) + 후행(+1~+4) 구간만 추출
df_lagcorr_follow = df_lagcorr.loc[0:4]

# 각 변수별로 절댓값 기준 최대 상관계수와 그때의 lag 찾기
max_corr_lag = df_lagcorr_follow.apply(lambda x: x.abs().idxmax())
max_corr_value = df_lagcorr_follow.apply(lambda x: x.loc[x.abs().idxmax()])

# 결과 DataFrame으로 정리
result_follow = pd.DataFrame({
    '최대상관계수': max_corr_value,
    '시차(lag)': max_corr_lag
}).sort_values(by='최대상관계수', ascending=False)

# 상위 10개 출력
print("📊 GDP 기준 동행·후행 변수 TOP 10")
print(result_follow.head(10))

📊 GDP 기준 동행·후행 변수 TOP 10
              최대상관계수  시차(lag)
매출실적BSI     0.369143        0
내수판매실적BSI   0.362965        0
설비투자실적BSI   0.351571        0
업황실적BSI     0.336849        0
수출실적BSI     0.332228        0
수출출하지수      0.322612        1
내수출하지수      0.306401        2
생산실적BSI     0.306155        0
가동률실적BSI    0.284930        0
신규수주실적BSI   0.251198        0

In [69]:
# df2 사본
df2 = qoq.copy()

# target 및 feature 지정
target_col = '전기장비 제조업'
feature_cols = [col for col in df2.columns if col not in ['index', target_col]]

# 결과 저장용 데이터프레임
corr_df = pd.DataFrame(columns=['Feature', 'Lag', 'Correlation'])

# lag 1~4 생성 및 상관계수 계산
for col in feature_cols:
    for lag in range(1, 5):  # lag 1~4
        lag_col_name = f"{col}_lag{lag}"
        df2[lag_col_name] = df2[col].shift(lag)  # 실제 데이터에 lag 컬럼 추가
        corr = df2[target_col].corr(df2[lag_col_name])  # 상관계수 계산
        corr_df = pd.concat(
            [corr_df, pd.DataFrame({'Feature': [col], 'Lag': [lag], 'Correlation': [corr]})],
            ignore_index=True
        )

# 상관계수 높은 순으로 정렬
corr_df.sort_values(by='Correlation', ascending=False, inplace=True)
corr_df.reset_index(drop=True, inplace=True)

corr_df

/tmp/ipython-input-1274427553.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  corr_df = pd.concat(

     Feature Lag  Correlation
0       생산지수   1     0.333987
1     수출출하지수   1     0.322612
2     내수출하지수   2     0.306401
3      가동률지수   1     0.260471
4   가동률실적BSI   1     0.251859
..       ...  ..          ...
79    내수출하지수   4    -0.219852
80    수출출하지수   3    -0.240829
81     가동률지수   3    -0.332738
82    생산능력지수   3    -0.363663
83      생산지수   3    -0.451634

[84 rows x 3 columns]

In [70]:
# 숫자형 컬럼만 선택 (연도분기 제외)
numeric_df = df2.select_dtypes(include=["number"])

# 전체 상관계수
corr = numeric_df.corr()

# 광업전기대비증감률과 다른 컬럼들 상관계수만 보기
target_corr = corr["전기장비 제조업"].drop("전기장비 제조업")
target_corr = target_corr.sort_values(ascending=False)
target_corr

매출실적BSI        0.369143
내수판매실적BSI      0.362965
설비투자실적BSI      0.351571
업황실적BSI        0.336849
생산지수_lag1      0.333987
                 ...
내수출하지수_lag4   -0.219852
수출출하지수_lag3   -0.240829
가동률지수_lag3    -0.332738
생산능력지수_lag3   -0.363663
생산지수_lag3     -0.451634
Name: 전기장비 제조업, Length: 105, dtype: float64

In [71]:
target_corr.to_csv('전기장비순서.csv')

In [72]:
df2.dropna(inplace=True)

In [73]:
df2

,index,생산지수,내수출하지수,수출출하지수,생산능력지수,가동률지수,EBITDA,인건비,합산,업황실적BSI,...,자금사정실적BSI_lag3,자금사정실적BSI_lag4,인력사정실적BSI_lag1,인력사정실적BSI_lag2,인력사정실적BSI_lag3,인력사정실적BSI_lag4,전기장비ppi_lag1,전기장비ppi_lag2,전기장비ppi_lag3,전기장비ppi_lag4
4,2017Q1,-0.323804,0.549112,-1.798031,1.231221,-0.780722,-45.590800,-79.185573,-45.647488,1.463415,...,5.284553,-0.404858,-3.311258,-1.307190,6.993007,-3.703704,0.747741,-0.526860,-0.278150,-0.061773
5,2017Q2,1.753192,-0.448933,0.802409,1.216246,-0.086565,67.399237,-3.012489,67.353738,15.865385,...,2.316602,5.284553,-0.684932,-3.311258,-1.307190,6.993007,1.061746,0.747741,-0.526860,-0.278150
6,2017Q3,-0.288853,2.322694,2.327072,-0.389129,0.157704,13.199618,-1.084406,13.194269,2.904564,...,-0.377358,2.316602,6.896552,-0.684932,-3.311258,-1.307190,-0.326397,1.061746,0.747741,-0.526860
7,2017Q4,2.035962,-2.806093,3.769372,0.750047,1.137181,11.145572,410.501734,11.276261,-10.887097,...,-7.954545,-0.377358,-4.838710,6.896552,-0.684932,-3.311258,0.726566,-0.326397,1.061746,0.747741
8,2018Q1,-3.514504,4.411749,-4.112430,0.161300,-2.929192,-36.085938,-77.421227,-36.147996,1.357466,...,8.230453,-7.954545,-3.050847,-4.838710,6.896552,-0.684932,0.792441,0.726566,-0.326397,1.061746
9,2018Q2,1.885273,3.542744,-2.661211,0.485186,0.847458,55.003510,18.631421,54.984201,16.071429,...,-0.380228,8.230453,2.097902,-3.050847,-4.838710,6.896552,0.524141,0.792441,0.726566,-0.326397
10,2018Q3,-0.377982,-0.419426,2.990570,0.321553,-1.355729,13.618283,5.729783,13.615078,-11.538462,...,-6.106870,-0.380228,6.849315,2.097902,-3.050847,-4.838710,0.250677,0.524141,0.792441,0.726566
11,2018Q4,1.913355,-0.181361,-5.089381,0.544786,1.768458,23.226490,425.557588,23.378635,-0.434783,...,1.626016,-6.106870,0.320513,6.849315,2.097902,-3.050847,-0.650130,0.250677,0.524141,0.792441
12,2019Q1,-2.738796,0.393165,10.134457,-0.159902,-2.494622,-28.008346,-81.059352,-28.093803,-6.113537,...,6.400000,1.626016,-4.792332,0.320513,6.849315,2.097902,0.070472,-0.650130,0.250677,0.524141
13,2019Q2,2.939064,-0.060326,3.286599,-0.160158,2.395972,4.617247,-4.132954,4.613534,4.186047,...,-6.390977,6.400000,1.677852,-4.792332,0.320513,6.849315,0.301811,0.070472,-0.650130,0.250677
14,2019Q3,0.958030,-0.843097,-1.388381,-0.159393,0.823718,13.648559,3.798627,13.644729,-18.750000,...,-0.401606,-6.390977,3.960396,1.677852,-4.792332,0.320513,0.411234,0.301811,0.070472,-0.650130
15,2019Q4,2.654264,0.911141,1.994882,0.416517,2.010900,2.174135,577.378079,2.378416,23.076923,...,1.612903,-0.401606,-0.952381,3.960396,1.677852,-4.792332,0.000000,0.411234,0.301811,0.070472
16,2020Q1,-6.309218,-3.774835,-6.170721,2.015858,-7.150816,-45.837146,-82.075906,-45.922299,-11.607143,...,-7.142857,1.612903,-2.564103,-0.952381,3.960396,1.677852,-0.119868,0.000000,0.411234,0.301811
17,2020Q2,-2.566735,2.363823,-13.618290,-0.699301,-1.538462,100.916860,-14.138190,100.827251,-30.808081,...,-5.128205,-7.142857,4.276316,-2.564103,-0.952381,3.960396,-0.210021,-0.119868,0.000000,0.411234
18,2020Q3,7.270811,0.401606,15.880322,0.503018,6.145833,4.293776,4.376450,4.293804,48.905109,...,7.657658,-5.128205,6.624606,4.276316,-2.564103,-0.952381,-0.541191,-0.210021,-0.119868,0.000000
19,2020Q4,3.929273,2.600000,11.420060,0.700701,2.649657,-33.889993,437.422007,-33.732929,22.549020,...,-2.510460,7.657658,-6.804734,6.624606,4.276316,-2.564103,1.088271,-0.541191,-0.210021,-0.119868
20,2021Q1,0.472590,0.000000,-5.793226,-0.298211,1.816444,66.514067,-68.981829,66.147872,-2.000000,...,-20.600858,-2.510460,-1.269841,-6.804734,6.624606,4.276316,0.338915,1.088271,-0.541191,-0.210021
21,2021Q2,0.282220,-1.461988,4.351939,-1.495513,0.657277,103.936390,10.874483,103.889436,6.938776,...,35.675676,-20.600858,-6.752412,-1.269841,-6.804734,6.624606,1.659050,0.338915,1.088271,-0.541191
22,2021Q3,1.688555,0.296736,1.813237,-0.303644,0.932836,-88.074904,1.013358,-88.050460,3.053435,...,-0.398406,35.675676,-3.103448,-6.752412,-1.269841,-6.804734,2.912147,1.659050,0.338915,1.088271
23,2021Q4,2.583026,1.775148,8.726625,-0.304569,1.756007,209.106461,330.299304,209.387553,4.814815,...,4.000000,-0.398406,1.067616,-3.103448,-6.752412,-1.269841,0.598234,2.912147,1.659050,0.338915
24,2022Q1,0.089928,0.096899,8.271908,4.582485,-3.178928,37.260921,-73.713746,36.902937,-12.014134,...,-0.384615,4.000000,-6.338028,1.067616,-3.103448,-6.752412,1.434774,0.598234,2.912147,1.659050
25,2022Q2,0.718778,0.677638,4.009077,0.681597,0.093809,1.553432,0.633539,1.552862,2.811245,...,1.930502,-0.384615,3.007519,-6.338028,1.067616,-3.103448,2.577703,1.434774,0.598234,2.912147
26,2022Q3,2.051740,0.096154,4.581818,-1.934236,2.905342,74.543294,16.543440,74.507696,-5.859375,...,-2.272727,1.930502,-4.744526,3.007519,-6.338028,1.067616,1.796244,2.577703,1.434774,0.598234
27,2022Q4,-4.545455,-1.440922,-6.606398,-3.254438,-0.546448,-41.289283,228.371907,-41.178748,4.564315,...,0.000000,-2.272727,0.766284,-4.744526,3.007519,-6.338028,0.632742,1.796244,2.577703,1.434774
28,2023Q1,7.417582,5.458090,0.372301,5.198777,2.838828,1.496318,-70.573663,1.331401,-8.333333,...,-8.139535,0.000000,-3.041825,0.766284,-4.744526,3.007519,1.948282,0.632742,1.796244,2.577703
29,2023Q2,-0.767263,-2.125693,-2.077151,1.065891,-3.561888,14.956736,4.131666,14.949542,1.731602,...,4.641350,-8.139535,1.960784,-3.041825,0.766284,-4.744526,2.197707,1.948282,0.632742,1.796244
30,2023Q3,-6.701031,-1.038716,-13.560606,-3.355705,-4.247461,11.475364,-3.666089,11.466249,1.702128,...,1.612903,4.641350,3.846154,1.960784,-3.041825,0.766284,0.416490,2.197707,1.948282,0.632742
31,2023Q4,-3.222836,0.000000,-10.166521,-1.984127,-2.121504,-51.015713,233.481545,-50.867703,2.928870,...,1.190476,1.612903,2.222222,3.846154,1.960784,-3.041825,1.193499,0.416490,2.197707,1.948282
32,2024Q1,0.380590,-2.958015,-2.146341,1.619433,2.068966,-20.607440,-67.630103,-20.773485,-4.065041,...,-1.176471,1.190476,-6.159420,2.222222,3.846154,1.960784,1.580928,1.193499,0.416490,2.197707
33,2024Q2,0.094787,-6.194690,-2.691924,0.697211,0.289575,50.441843,-2.541481,50.365402,5.084746,...,7.936508,-1.176471,1.930502,-6.159420,2.222222,3.846154,0.774045,1.580928,1.193499,0.416490
34,2024Q3,-4.545455,-4.716981,-8.196721,0.890208,-5.197305,-87.692366,-10.513425,-87.620195,-11.693548,...,-7.720588,7.936508,6.060606,1.930502,-6.159420,2.222222,2.639320,0.774045,1.580928,1.193499
35,2024Q4,2.083333,0.550055,-0.669643,0.098039,0.101523,114.202420,18.879874,113.558100,-1.826484,...,3.585657,-7.720588,-0.357143,6.060606,1.930502,-6.159420,-0.907571,2.639320,0.774045,1.580928
36,2025Q1,0.388727,5.689278,-3.820225,-1.273262,1.724138,-19.471936,-59.713135,-19.623351,6.976744,...,-0.384615,3.585657,-0.716846,-0.357143,6.060606,1.930502,0.417771,-0.907571,2.639320,0.774045
37,2025Q2,0.871249,0.828157,10.747664,0.793651,-0.598205,-118.756333,-200.000000,-118.909555,-14.347826,...,-3.474903,-0.384615,-1.805054,-0.716846,-0.357143,6.060606,1.000080,0.417771,-0.907571,2.639320

In [74]:
df2 = df2.reset_index()
df2 = df2.drop(columns=["level_0"])

In [75]:
df2.to_csv('전기장비lag.csv', encoding='utf-8-sig')

In [76]:
print(df2.columns)

Index(['index', '생산지수', '내수출하지수', '수출출하지수', '생산능력지수', '가동률지수', 'EBITDA', '인건비',
       '합산', '업황실적BSI',
       ...
       '자금사정실적BSI_lag3', '자금사정실적BSI_lag4', '인력사정실적BSI_lag1', '인력사정실적BSI_lag2',
       '인력사정실적BSI_lag3', '인력사정실적BSI_lag4', '전기장비ppi_lag1', '전기장비ppi_lag2',
       '전기장비ppi_lag3', '전기장비ppi_lag4'],
      dtype='object', length=107)

#ARIMA

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('전기장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = '전기장비 제조업'   # GDP 예측 대상 칼럼
exog_vars = [
    '매출실적BSI', '내수판매실적BSI', '설비투자실적BSI '
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (3.0, 1.0, 2.0)
📉 평균 Train MAE: 2.2601
📈 평균 Test MAE: 2.5059

## ARIMA 예측값

In [77]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('전기장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = '전기장비 제조업'
exog_vars = ['매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ']

y = df[target].dropna()
X = df[exog_vars].dropna()

df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    pred = fit.forecast(steps=1, exog=X_test)

                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 최적 (p,d,q) 선택
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

best_p, best_d, best_q = int(best['p']), int(best['d']), int(best['q'])

print("✅ 최적 ARIMAX(p,d,q):", (best_p, best_d, best_q))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

# ---------------------------------------------------
# 8️⃣ 최적 (p,d,q)로 전체 구간 롤링 예측값 저장
# ---------------------------------------------------
rolling_preds = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    train_data = y.loc[train_start:train_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(train_data) < train_window or len(X_test) == 0:
        continue

    try:
        model = SARIMAX(train_data, exog=X_train, order=(best_p, best_d, best_q),
                        enforce_stationarity=False, enforce_invertibility=False)
        fit = model.fit(disp=False)
        pred = fit.forecast(steps=1, exog=X_test)

        rolling_preds.append({
            'date': test_end,
            'pred': float(pred),
            'actual': float(y.loc[test_end])
        })
    except:
        continue

pred_df = pd.DataFrame(rolling_preds).set_index('date')

print("\n📌 최적 모델 예측값(pred) 시계열:")
print(pred_df)

✅ 최적 ARIMAX(p,d,q): (3, 1, 2)
📉 평균 Train MAE: 2.2601
📈 평균 Test MAE: 2.5059

📌 최적 모델 예측값(pred) 시계열:
            pred    actual
date
2022Q1  7.723651  5.842324
2022Q2 -0.449448  0.267532
2022Q3 -3.890779 -3.314667
2022Q4 -1.061917 -3.390126
2023Q1  0.561319 -0.167099
2023Q2  2.521847  1.198797
2023Q3  0.524786  4.477996
2023Q4  2.370049 -4.657232
2024Q1 -2.231566 -2.547821
2024Q2 -2.220798 -0.735633
2024Q3  1.909485  2.741664
2024Q4  0.837295 -4.554742
2025Q1 -2.510679 -1.866263
2025Q2 -5.165492  2.712833

In [80]:
level_2025Q1 = 8297.6

qoq_2025Q2_pred = pred_df.loc['2025Q2', 'pred']
level_2025Q2_pred = level_2025Q1 * (1 + qoq_2025Q2_pred / 100)

print("2025Q2 수준값(예측):", level_2025Q2_pred)

2025Q2 수준값(예측): 7868.988153757635

# 랜덤포레스트

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2017Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '전기장비 제조업'
exog_vars = ['매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.3496
📈 평균 Test MAE: 3.7894

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2017Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '전기장비 제조업'
exog_vars = ['매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ', '업황실적BSI']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.3278
📈 평균 Test MAE: 3.7153

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2017Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '전기장비 제조업'
exog_vars = ['매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ', '업황실적BSI', '생산지수_lag3','생산능력지수_lag3','가동률지수_lag3'
    ]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.2311
📈 평균 Test MAE: 3.3029

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2017Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '전기장비 제조업'
exog_vars = ['매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ',  '생산지수_lag3','생산능력지수_lag3','가동률지수_lag3'
    ]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.2357
📈 평균 Test MAE: 3.0444

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '전기장비 제조업'
exog_vars = ['매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ',  '생산지수_lag3','생산능력지수_lag3','가동률지수_lag3'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'n_estimators': [200, 400],
    'max_depth': [8, 10, 12],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# 첫 번째 윈도우 구간 설정
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

# 하이퍼파라미터 탐색 (단 1회)
rf = RandomForestRegressor(random_state=42)
rand_search = RandomizedSearchCV(
    rf,
    param_distributions=param_grid,
    n_iter=10,            # 108조합 중 10개만 탐색
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 고정된 최적 파라미터로 학습
        model = RandomForestRegressor(**best_params, random_state=42)
        model.fit(X_train, y_train)

        # 예측
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # MAE 계산
        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 랜덤포레스트 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'n_estimators': 400, 'min_samples_split': 5, 'max_features': 'sqrt', 'max_depth': 12}

📊 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.6646
📈 평균 Test MAE: 3.0959

## 랜포 예측값

In [81]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ y, X 설정
# -----------------------------
target = '전기장비 제조업'
exog_vars = [
    '매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ',
    '생산지수_lag3','생산능력지수_lag3','가동률지수_lag3'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ RandomizedSearchCV (초기 구간 1회)
# -----------------------------
param_grid = {
    'n_estimators': [200, 400],
    'max_depth': [8, 10, 12],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

rf = RandomForestRegressor(random_state=42)
rand_search = RandomizedSearchCV(
    rf,
    param_distributions=param_grid,
    n_iter=10,
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 + pred 저장
# -----------------------------
train_mae_list = []
test_mae_list = []
rolling_preds = []   # ⭐ 예측값 저장 리스트

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = RandomForestRegressor(**best_params, random_state=42)
        model.fit(X_train, y_train)

        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

        # ⭐ 예측값 저장
        rolling_preds.append({
            'date': test_end,
            'pred': float(test_pred),
            'actual': float(y_test.values[0])
        })

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 정리
# -----------------------------
print("\n📊 랜덤포레스트 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

pred_df = pd.DataFrame(rolling_preds).set_index('date')

print("\n📌 랜덤포레스트 예측값(pred) 시계열:")
print(pred_df)

✅ 최적 하이퍼파라미터: {'n_estimators': 400, 'min_samples_split': 5, 'max_features': 'sqrt', 'max_depth': 12}

📊 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.6646
📈 평균 Test MAE: 3.0959

📌 랜덤포레스트 예측값(pred) 시계열:
            pred    actual
date
2022Q1  2.663988  5.842324
2022Q2  1.896033  0.267532
2022Q3  1.194283 -3.314667
2022Q4  2.469412 -3.390126
2023Q1  0.024151 -0.167099
2023Q2 -0.619416  1.198797
2023Q3  3.018392  4.477996
2023Q4 -1.516479 -4.657232
2024Q1  2.589457 -2.547821
2024Q2  1.194735 -0.735633
2024Q3 -0.772726  2.741664
2024Q4  0.122523 -4.554742
2025Q1  0.632939 -1.866263
2025Q2 -1.086328  2.712833

In [82]:
level_2025Q1 = 8297.6

qoq_2025Q2_pred = pred_df.loc['2025Q2', 'pred']
level_2025Q2_pred = level_2025Q1 * (1 + qoq_2025Q2_pred / 100)

print("2025Q2 수준값(예측):", level_2025Q2_pred)

2025Q2 수준값(예측): 8207.460874902903

# AR

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비qoq.csv')

# GDP 단일 시계열만 사용 (AR(1))
y = df['전기장비 제조업'].dropna()
y.index = pd.PeriodIndex(df.loc[y.index, 'index'], freq='Q')

# -----------------------------
# 2️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

train_mae_list = []
test_mae_list = []

# -----------------------------
# 3️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    train_data = y.loc[train_start:train_end]
    test_data = y.loc[test_end:test_end]

    if len(train_data) < train_window:
        continue

    try:
        # AR(1) 학습
        model = AutoReg(train_data, lags=1, old_names=False)
        fit = model.fit()

        # --- Train 예측 ---
        # fittedvalues는 길이가 n-1이므로 첫 번째 값 제외하고 MAE 계산
        train_mae = mean_absolute_error(train_data[1:], fit.fittedvalues)
        train_mae_list.append(train_mae)

        # --- Test 예측 (1분기 앞 예측) ---
        pred = fit.predict(start=len(train_data), end=len(train_data))
        test_mae = mean_absolute_error(test_data, pred)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 4️⃣ 결과 출력
# -----------------------------
print("✅ AR(1) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ AR(1) 롤링 예측 결과
📉 평균 Train MAE: 3.0799
📈 평균 Test MAE: 2.9676

## AR 예측값

In [83]:
import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비qoq.csv')

# GDP 단일 시계열
y = df['전기장비 제조업'].dropna()
y.index = pd.PeriodIndex(df.loc[y.index, 'index'], freq='Q')

# -----------------------------
# 2️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

train_mae_list = []
test_mae_list = []

# ⭐ 예측값 저장할 리스트
rolling_preds = []

# -----------------------------
# 3️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    train_data = y.loc[train_start:train_end]
    test_data = y.loc[test_end:test_end]

    if len(train_data) < train_window:
        continue

    try:
        # AR(1) 학습
        model = AutoReg(train_data, lags=1, old_names=False)
        fit = model.fit()

        # --- Train MAE ---
        train_mae = mean_absolute_error(train_data[1:], fit.fittedvalues)
        train_mae_list.append(train_mae)

        # --- Test 예측 ---
        pred = fit.predict(start=len(train_data), end=len(train_data))
        test_mae = mean_absolute_error(test_data, pred)
        test_mae_list.append(test_mae)

        # ⭐ 예측값 저장
        rolling_preds.append({
            'date': test_end,
            'pred': float(pred),
            'actual': float(test_data.values[0])
        })

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 4️⃣ 결과 출력
# -----------------------------
print("✅ AR(1) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

# -----------------------------
# 5️⃣ pred 시계열 데이터프레임 출력
# -----------------------------
pred_df = pd.DataFrame(rolling_preds).set_index('date')

print("\n📌 AR(1) 예측값(pred) 시계열:")
print(pred_df)

✅ AR(1) 롤링 예측 결과
📉 평균 Train MAE: 3.0799
📈 평균 Test MAE: 2.9676

📌 AR(1) 예측값(pred) 시계열:
            pred    actual
date
2021Q1 -0.771004  2.907648
2021Q2  1.232106 -0.130390
2021Q3  1.963444 -2.846211
2021Q4  2.348448  4.408998
2022Q1  0.357684  5.842324
2022Q2  0.556166  0.267532
2022Q3  1.371332 -3.314667
2022Q4  1.587722 -3.390126
2023Q1  0.649860 -0.167099
2023Q2  0.721498  1.198797
2023Q3  0.785374  4.477996
2023Q4  0.913790 -4.657232
2024Q1  0.408815 -2.547821
2024Q2 -0.232855 -0.735633
2024Q3  0.234061  2.741664
2024Q4  1.164140 -4.554742
2025Q1 -0.738577 -1.866263
2025Q2  0.016359  2.712833

In [84]:
level_2025Q1 = 8297.6

qoq_2025Q2_pred = pred_df.loc['2025Q2', 'pred']
level_2025Q2_pred = level_2025Q1 * (1 + qoq_2025Q2_pred / 100)

print("2025Q2 수준값(예측):", level_2025Q2_pred)

2025Q2 수준값(예측): 8298.95739670467

#XGB

In [ ]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '전기장비 제조업'
exog_vars = [
    '매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ',
    '생산지수_lag3', '생산능력지수_lag3', '가동률지수_lag3'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 하이퍼파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'n_estimators': [200, 400, 600],
    'learning_rate': [0.03, 0.05, 0.1],
    'max_depth': [3, 5, 7, 9],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.3]
}

# 첫 번째 윈도우로 탐색
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

# RandomizedSearchCV 실행
xgb = XGBRegressor(random_state=42, objective='reg:squarederror')
rand_search = RandomizedSearchCV(
    xgb,
    param_distributions=param_grid,
    n_iter=15,          # 전체 중 15조합 탐색
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 고정된 최적 파라미터로 학습
        model = XGBRegressor(**best_params, random_state=42, objective='reg:squarederror')
        model.fit(X_train, y_train)

        # 예측
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # MAE 계산
        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 XGBoost 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'subsample': 0.8, 'n_estimators': 200, 'min_child_weight': 5, 'max_depth': 5, 'learning_rate': 0.03, 'gamma': 0.3, 'colsample_bytree': 0.8}

📊 XGBoost 롤링 예측 결과
📉 평균 Train MAE: 1.4020
📈 평균 Test MAE: 3.1500

##XGB 예측값

In [85]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ y, X 설정
# -----------------------------
target = '전기장비 제조업'
exog_vars = [
    '매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ',
    '생산지수_lag3', '생산능력지수_lag3', '가동률지수_lag3'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ RandomizedSearchCV (초기 구간)
# -----------------------------
param_grid = {
    'n_estimators': [200, 400, 600],
    'learning_rate': [0.03, 0.05, 0.1],
    'max_depth': [3, 5, 7, 9],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.3]
}

first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

xgb = XGBRegressor(random_state=42, objective='reg:squarederror')
rand_search = RandomizedSearchCV(
    xgb,
    param_distributions=param_grid,
    n_iter=15,
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 + pred 저장
# -----------------------------
train_mae_list = []
test_mae_list = []
rolling_preds = []   # ⭐ 예측값 저장

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = XGBRegressor(**best_params, random_state=42, objective='reg:squarederror')
        model.fit(X_train, y_train)

        # 예측
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # MAE
        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

        # ⭐ 예측값 저장
        rolling_preds.append({
            'date': test_end,
            'pred': float(test_pred),
            'actual': float(y_test.values[0])
        })

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 XGBoost 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

pred_df = pd.DataFrame(rolling_preds).set_index('date')

print("\n📌 XGBoost 예측값(pred) 시계열:")
print(pred_df)

✅ 최적 하이퍼파라미터: {'subsample': 0.8, 'n_estimators': 200, 'min_child_weight': 5, 'max_depth': 5, 'learning_rate': 0.03, 'gamma': 0.3, 'colsample_bytree': 0.8}

📊 XGBoost 롤링 예측 결과
📉 평균 Train MAE: 1.4020
📈 평균 Test MAE: 3.1500

📌 XGBoost 예측값(pred) 시계열:
            pred    actual
date
2022Q1  1.525646  5.842324
2022Q2  1.315158  0.267532
2022Q3  1.148519 -3.314667
2022Q4  1.520859 -3.390126
2023Q1  1.559204 -0.167099
2023Q2 -1.240709  1.198797
2023Q3  1.805433  4.477996
2023Q4 -1.948887 -4.657232
2024Q1  1.764948 -2.547821
2024Q2  1.092644 -0.735633
2024Q3 -0.786187  2.741664
2024Q4 -0.927528 -4.554742
2025Q1  0.146662 -1.866263
2025Q2 -1.792564  2.712833

In [86]:
level_2025Q1 = 8297.6

qoq_2025Q2_pred = pred_df.loc['2025Q2', 'pred']
level_2025Q2_pred = level_2025Q1 * (1 + qoq_2025Q2_pred / 100)

print("2025Q2 수준값(예측):", level_2025Q2_pred)

2025Q2 수준값(예측): 8148.860196784974

# MLP

In [ ]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '전기장비 제조업'
exog_vars = [
    '매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ',
    '생산지수_lag3', '생산능력지수_lag3', '가동률지수_lag3'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# 스케일링 (NN에서는 매우 중요)
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(), index=y.index)

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 하이퍼파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'hidden_layer_sizes': [(32,), (64,), (32,16), (64,32), (128,64)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'lbfgs'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate_init': [0.001, 0.01]
}

# 첫 번째 윈도우로 하이퍼파라미터 탐색
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X_scaled.loc[start_period:first_train_end]
first_y_train = y_scaled.loc[start_period:first_train_end]

mlp = MLPRegressor(random_state=42, max_iter=1000)
rand_search = RandomizedSearchCV(
    mlp,
    param_distributions=param_grid,
    n_iter=10,
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y_scaled.loc[train_start:train_end]
    y_test = y_scaled.loc[test_end:test_end]
    X_train = X_scaled.loc[train_start:train_end]
    X_test = X_scaled.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = MLPRegressor(**best_params, random_state=42, max_iter=1000)
        model.fit(X_train, y_train)

        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # 스케일링 복원
        train_pred_inv = scaler_y.inverse_transform(train_pred.reshape(-1, 1)).flatten()
        test_pred_inv = scaler_y.inverse_transform(test_pred.reshape(-1, 1)).flatten()
        y_train_inv = scaler_y.inverse_transform(y_train.values.reshape(-1, 1)).flatten()
        y_test_inv = scaler_y.inverse_transform(y_test.values.reshape(-1, 1)).flatten()

        # MAE 계산
        train_mae = mean_absolute_error(y_train_inv, train_pred_inv)
        test_mae = mean_absolute_error(y_test_inv, test_pred_inv)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 Neural Network (MLP) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'solver': 'adam', 'learning_rate_init': 0.001, 'hidden_layer_sizes': (64,), 'alpha': 0.01, 'activation': 'relu'}

📊 Neural Network (MLP) 롤링 예측 결과
📉 평균 Train MAE: 0.4536
📈 평균 Test MAE: 4.4022

## MLP 예측값

In [91]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ y, X 설정
# -----------------------------
target = '전기장비 제조업'
exog_vars = [
    '매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ',
    '생산지수_lag3', '생산능력지수_lag3', '가동률지수_lag3'
]

df_model = df[[target] + exog_vars].dropna()

y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 스케일링 (정상 코드)
# -----------------------------
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(
    scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(),
    index=y.index
)

# -----------------------------
# 4️⃣ 롤링 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 5️⃣ 하이퍼파라미터 축소 (안정성)
# -----------------------------
param_grid = {
    'hidden_layer_sizes': [(32,), (64,), (32,16)],
    'activation': ['relu'],
    'solver': ['adam'],
    'alpha': [0.0001, 0.001],
    'learning_rate_init': [0.001, 0.005]
}

first_train_end = start_period + (train_window - 1)
first_X_train = X_scaled.loc[start_period:first_train_end]
first_y_train = y_scaled.loc[start_period:first_train_end]

mlp = MLPRegressor(random_state=42, max_iter=2000)
rand_search = RandomizedSearchCV(
    mlp, param_grid, n_iter=5, cv=3,
    scoring='neg_mean_absolute_error', n_jobs=-1, random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 파라미터:", best_params)

# -----------------------------
# 6️⃣ 롤링 예측
# -----------------------------
train_mae_list = []
test_mae_list = []
rolling_preds = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    train_start = train_end - (train_window - 1)
    test_end = test_start

    X_train = X_scaled.loc[train_start:train_end]
    y_train = y_scaled.loc[train_start:train_end]
    X_test = X_scaled.loc[test_end:test_end]
    y_test = y_scaled.loc[test_end:test_end]

    if len(X_train) < train_window:
        continue

    try:
        model = MLPRegressor(
            **best_params,
            random_state=42,
            max_iter=2000
        )
        model.fit(X_train, y_train)

        # ---- Train 예측 ----
        train_pred_scaled = model.predict(X_train)
        train_pred = scaler_y.inverse_transform(train_pred_scaled.reshape(-1,1)).flatten()
        train_real = scaler_y.inverse_transform(y_train.values.reshape(-1,1)).flatten()
        train_mae = mean_absolute_error(train_real, train_pred)
        train_mae_list.append(train_mae)

        # ---- Test 예측 ----
        test_pred_scaled = model.predict(X_test)
        test_pred = scaler_y.inverse_transform(test_pred_scaled.reshape(-1,1)).flatten()
        test_real = scaler_y.inverse_transform(y_test.values.reshape(-1,1)).flatten()
        test_mae = mean_absolute_error(test_real, test_pred)
        test_mae_list.append(test_mae)

        # ---- pred 저장 ----
        rolling_preds.append({
            'date': test_end,
            'pred': float(test_pred[0]),
            'actual': float(test_real[0])
        })

    except Exception as e:
        print("❌ 오류 발생:", e)
        continue

# -----------------------------
# 7️⃣ 결과 출력
# -----------------------------
print("\n📊 Neural Network (MLP) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

if len(rolling_preds) > 0:
    pred_df = pd.DataFrame(rolling_preds).set_index('date')
    print(pred_df)
else:
    print("⚠ rolling_preds가 텅 빔 → 모델 학습 실패")

✅ 최적 파라미터: {'solver': 'adam', 'learning_rate_init': 0.001, 'hidden_layer_sizes': (64,), 'alpha': 0.001, 'activation': 'relu'}

📊 Neural Network (MLP) 롤링 예측 결과
📉 평균 Train MAE: 0.4241
📈 평균 Test MAE: 4.4846
             pred    actual
date
2022Q1   1.065699  5.842324
2022Q2   3.072443  0.267532
2022Q3   0.528665 -3.314667
2022Q4   6.197137 -3.390126
2023Q1   0.371793 -0.167099
2023Q2   2.139057  1.198797
2023Q3  11.410291  4.477996
2023Q4 -13.759665 -4.657232
2024Q1   0.493672 -2.547821
2024Q2   6.188217 -0.735633
2024Q3  -1.440296  2.741664
2024Q4   2.737262 -4.554742
2025Q1  -0.879373 -1.866263
2025Q2   0.880723  2.712833

In [92]:
level_2025Q1 = 8297.6

qoq_2025Q2_pred = pred_df.loc['2025Q2', 'pred']
level_2025Q2_pred = level_2025Q1 * (1 + qoq_2025Q2_pred / 100)

print("2025Q2 수준값(예측):", level_2025Q2_pred)

2025Q2 수준값(예측): 8370.678909590544

#LSTM

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '전기장비 제조업'
exog_vars = [
    '매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ',
    '생산지수_lag3', '생산능력지수_lag3', '가동률지수_lag3'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 스케일링
# -----------------------------
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(), index=y.index)

# -----------------------------
# 4️⃣ LSTM 입력 형태 변환 함수
# -----------------------------
def create_lstm_input(X, y, lookback=4):
    """
    lookback: 과거 몇 분기 데이터를 사용할지 (ex. 4 = 1년)
    """
    Xs, ys, idxs = [], [], []
    for i in range(lookback, len(X)):
        Xs.append(X.iloc[i-lookback:i].values)
        ys.append(y.iloc[i])
        idxs.append(y.index[i])
    return np.array(Xs), np.array(ys), idxs

lookback = 4
X_seq, y_seq, idxs = create_lstm_input(X_scaled, y_scaled, lookback)
y_seq = pd.Series(y_seq, index=idxs)

# -----------------------------
# 5️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 6️⃣ LSTM 모델 정의 함수
# -----------------------------
def build_lstm(input_shape):
    model = Sequential()
    model.add(LSTM(64, activation='tanh', input_shape=input_shape, return_sequences=False))
    model.add(Dropout(0.2))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mae')
    return model

# -----------------------------
# 7️⃣ 롤링 예측
# -----------------------------
train_mae_list, test_mae_list = [], []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    # 윈도우 범위 맞추기
    train_mask = (np.array(idxs) >= train_start) & (np.array(idxs) <= train_end)
    test_mask = (np.array(idxs) == test_end)

    X_train, y_train = X_seq[train_mask], y_seq[train_mask]
    X_test, y_test = X_seq[test_mask], y_seq[test_mask]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = build_lstm((X_train.shape[1], X_train.shape[2]))
        early_stop = EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)
        model.fit(X_train, y_train, epochs=200, batch_size=8, verbose=0, callbacks=[early_stop])

        # 예측
        train_pred = model.predict(X_train, verbose=0)
        test_pred = model.predict(X_test, verbose=0)

        # 스케일링 복원
        train_pred_inv = scaler_y.inverse_transform(train_pred)
        test_pred_inv = scaler_y.inverse_transform(test_pred)
        y_train_inv = scaler_y.inverse_transform(y_train.values.reshape(-1, 1))
        y_test_inv = scaler_y.inverse_transform(y_test.values.reshape(-1, 1))

        # MAE 계산
        train_mae = mean_absolute_error(y_train_inv, train_pred_inv)
        test_mae = mean_absolute_error(y_test_inv, test_pred_inv)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 8️⃣ 결과 요약
# -----------------------------
print("\n📊 LSTM 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7e52509c6d40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7e52509c6d40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

📊 LSTM 롤링 예측 결과
📉 평균 Train MAE: 0.7800
📈 평균 Test MAE: 2.7868

## lstm 예측값

In [93]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ y, X 설정
# -----------------------------
target = '전기장비 제조업'
exog_vars = [
    '매출실적BSI', '내수판매실적BSI', '설비투자실적BSI ',
    '생산지수_lag3', '생산능력지수_lag3', '가동률지수_lag3'
]

df_model = pd.concat([df[target], df[exog_vars]], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 스케일링
# -----------------------------
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(
    scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(),
    index=y.index
)

# -----------------------------
# 4️⃣ LSTM 입력 생성
# -----------------------------
def create_lstm_input(X, y, lookback=4):
    Xs, ys, idxs = [], [], []
    for i in range(lookback, len(X)):
        Xs.append(X.iloc[i-lookback:i].values)
        ys.append(y.iloc[i])
        idxs.append(y.index[i])
    return np.array(Xs), np.array(ys), idxs

lookback = 4
X_seq, y_seq, idxs = create_lstm_input(X_scaled, y_scaled, lookback)
y_seq = pd.Series(y_seq, index=idxs)

# -----------------------------
# 5️⃣ 롤링 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2017Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 6️⃣ 모델 생성 함수
# -----------------------------
def build_lstm(input_shape):
    model = Sequential()
    model.add(LSTM(64, activation='tanh', input_shape=input_shape))
    model.add(Dropout(0.2))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mae')
    return model

# -----------------------------
# 7️⃣ 롤링 예측 + pred 저장
# -----------------------------
train_mae_list, test_mae_list = [], []
rolling_preds = []  # ⭐ 예측값 저장 리스트

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    train_start = train_end - (train_window - 1)
    test_end = test_start

    # LSTM용 슬라이싱
    idx_arr = np.array(idxs)

    train_mask = (idx_arr >= train_start) & (idx_arr <= train_end)
    test_mask  = (idx_arr == test_end)

    X_train, y_train = X_seq[train_mask], y_seq[train_mask]
    X_test,  y_test  = X_seq[test_mask], y_seq[test_mask]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = build_lstm((X_train.shape[1], X_train.shape[2]))
        early = EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)

        model.fit(X_train, y_train, epochs=200, batch_size=8,
                  verbose=0, callbacks=[early])

        # ---- Train 예측 ----
        train_pred = model.predict(X_train, verbose=0)
        test_pred  = model.predict(X_test, verbose=0)

        # ---- 스케일 복원 ----
        train_pred_inv = scaler_y.inverse_transform(train_pred)
        y_train_inv = scaler_y.inverse_transform(y_train.values.reshape(-1,1))

        test_pred_inv = scaler_y.inverse_transform(test_pred)
        y_test_inv  = scaler_y.inverse_transform(y_test.values.reshape(-1,1))

        # ---- MAE ----
        train_mae = mean_absolute_error(y_train_inv, train_pred_inv)
        test_mae = mean_absolute_error(y_test_inv, test_pred_inv)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

        # ⭐ 예측값 저장
        rolling_preds.append({
            'date': test_end,
            'pred': float(test_pred_inv[0]),
            'actual': float(y_test_inv[0])
        })

    except Exception as e:
        print(f"❌ Error: {e}")
        continue

# -----------------------------
# 8️⃣ 결과 요약 + pred_df 출력
# -----------------------------
print("\n📊 LSTM 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE:  {np.mean(test_mae_list):.4f}")

# ⭐ 예측값 시계열 출력
pred_df = pd.DataFrame(rolling_preds).set_index('date')
print("\n📌 LSTM 예측값(pred) 시계열:")
print(pred_df)

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7c2e3c974360> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7c2e3c974360> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

📊 LSTM 롤링 예측 결과
📉 평균 Train MAE: 0.8140
📈 평균 Test MAE:  2.8509

📌 LSTM 예측값(pred) 시계열:
            pred    actual
date
2023Q1 -0.107376 -0.167099
2023Q2 -0.120912  1.198797
2023Q3  0.688824  4.477996
2023Q4 -1.464730 -4.657232
2024Q1 -0.835468 -2.547821
2024Q2  0.192028 -0.735633
2024Q3 -4.149986  2.741664
2024Q4  2.011340 -4.554742
2025Q1 -1.879964 -1.866263
2025Q2 -1.323711  2.712833

In [94]:
level_2025Q1 = 8297.6

qoq_2025Q2_pred = pred_df.loc['2025Q2', 'pred']
level_2025Q2_pred = level_2025Q1 * (1 + qoq_2025Q2_pred / 100)

print("2025Q2 수준값(예측):", level_2025Q2_pred)

2025Q2 수준값(예측): 8187.763792507172

# 단변량 아리마(예측도 포함)

In [96]:
import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기장비lag.csv')

df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상
# -----------------------------
y = df['전기장비 제조업'].dropna()

# -----------------------------
# 3️⃣ 롤링 윈도우
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2021Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ (p,d,q) 범위
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                y_train = y.loc[train_start:train_end]
                y_test = y.loc[test_end:test_end]

                if len(y_train) < train_window:
                    continue

                try:
                    model = ARIMA(y_train, order=(p, d, q))
                    fit = model.fit()

                    pred = fit.forecast(steps=1)

                    train_mae = mean_absolute_error(y_train, fit.fittedvalues)
                    test_mae = mean_absolute_error(y_test, pred)

                    train_mae_list.append(train_mae)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 최적 모델 선택
# -----------------------------
results_df = pd.DataFrame(results)

if results_df.empty:
    print("⚠️ 모든 조합 실패")
else:
    best = results_df.loc[results_df['test_MAE'].idxmin()]
    best_p, best_d, best_q = int(best['p']), int(best['d']), int(best['q'])

    print("✅ 최적 ARIMA(p,d,q):", (best_p, best_d, best_q))
    print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
    print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

# -----------------------------
# 8️⃣ ⭐ 최적 모델로 pred 저장 (재예측)
# -----------------------------
rolling_preds = []
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]

    if len(y_train) < train_window:
        continue

    try:
        model = ARIMA(y_train, order=(best_p, best_d, best_q))
        fit = model.fit()

        pred = fit.forecast(steps=1)

        # MAE
        train_mae_list.append(mean_absolute_error(y_train, fit.fittedvalues))
        test_mae_list.append(mean_absolute_error(y_test, pred))

        # ⭐ 예측값 저장
        rolling_preds.append({
            'date': test_end,
            'pred': float(pred),
            'actual': float(y_test.values[0])
        })

    except Exception as e:
        print("❌ 재예측 오류:", e)
        continue

# -----------------------------
# 9️⃣ pred_df 출력
# -----------------------------
pred_df = pd.DataFrame(rolling_preds).set_index('date')

print("\n📌 ARIMA 최적모델 예측(pred) 시계열:")
print(pred_df)

print("\n📉 최종 Train MAE:", np.mean(train_mae_list))
print("📈 최종 Test MAE:", np.mean(test_mae_list))

✅ 최적 ARIMA(p,d,q): (0, 1, 2)
📉 평균 Train MAE: 3.3782
📈 평균 Test MAE: 2.9442

📌 ARIMA 최적모델 예측(pred) 시계열:
            pred    actual
date
2022Q1  0.954324  5.842324
2022Q2  0.541721  0.267532
2022Q3  1.404535 -3.314667
2022Q4  1.261751 -3.390126
2023Q1  0.546317 -0.167099
2023Q2  0.670947  1.198797
2023Q3  0.844867  4.477996
2023Q4  1.421961 -4.657232
2024Q1 -0.693421 -2.547821
2024Q2  0.443201 -0.735633
2024Q3 -0.428712  2.741664
2024Q4  2.132440 -4.554742
2025Q1 -2.349218 -1.866263
2025Q2  0.354959  2.712833

📉 최종 Train MAE: 3.378175475725655
📈 최종 Test MAE: 2.9441769734160004

In [97]:
level_2025Q1 = 8297.6

qoq_2025Q2_pred = pred_df.loc['2025Q2', 'pred']
level_2025Q2_pred = level_2025Q1 * (1 + qoq_2025Q2_pred / 100)

print("2025Q2 수준값(예측):", level_2025Q2_pred)

2025Q2 수준값(예측): 8327.053062990253