In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 41 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 2s (4,153 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 125079 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

# 데이터 불러오기

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rc('font', family='NanumBarunGothic')

!pip install tspoon
import tspoon as tsp

Collecting tspoon
  Downloading tspoon-0.2.10-py3-none-any.whl.metadata (4.2 kB)
Downloading tspoon-0.2.10-py3-none-any.whl (9.2 kB)
Installing collected packages: tspoon
Successfully installed tspoon-0.2.10

In [ ]:
!pip install xmltodict
import pandas as pd

import requests
import xml.etree.ElementTree as ET
import xml.dom.minidom
import xmltodict

import json
from urllib.request import urlopen

def getECOS(topic,period,beg,end,item1='?',item2='?',item3='?',item4='?', df=None):
    key = ''
    url = 'https://ecos.bok.or.kr/api/StatisticSearch/'+'OIT9OYFOZDZWLHSBQJWU'+'/xml/kr/'+str(1)+'/'+str(50000)+'/'+topic+'/'+period+'/'+beg+'/'+end \
            +'/'+item1+'/'+item2+'/'+item3+'/'+item4
    # print(url)
    ## call OpenAPI URL
    response = requests.get(url)

    ## get API return value upon the http request
    if response.status_code == 200:
        try:
            contents = response.text
            ecosRoot = ET.fromstring(contents)

            # error check
            if ecosRoot[0].text[:4] in ("INFO","ERRO"):
                print(ecosRoot[0].text + " : " + ecosRoot[1].text)

            else:
                #print(contents)
                #dom = xml.dom.minidom.parse(xml_fname)
                dom = xml.dom.minidom.parseString(contents)
                pretty_xml_as_string = dom.toprettyxml(indent=" ")
                # print(pretty_xml_as_string)
                dic = xmltodict.parse(pretty_xml_as_string)

                n = int(dic['StatisticSearch']['list_total_count']['#text'])
                df_ecos = pd.DataFrame(index = [dic['StatisticSearch']['row'][i]['TIME'] for i in range(n)])
                df_ecos[dic['StatisticSearch']['row'][0]['ITEM_NAME1']] = [float(dic['StatisticSearch']['row'][i]['DATA_VALUE']) for i in range(n)]

                if type(df)==type(pd.DataFrame()):
                    df_ecos = df.merge(df_ecos, left_index=True, right_index=True, how='left')

                return df_ecos

        except Exception as e:
            print(str(e))


def getKOSIS(table,period,beg,end,item, orgId='101', obj1='',obj2='',obj3='',obj4='',obj5='',obj6='',obj7='',obj8='', title=None, title_no='0', debug=False):
     # Korean Statistics
    key = 'MzhiMmQwZTYyMWZiNGM1ZGFkZDJmZTI2OTE1OGU2NzQ='
    url = 'https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey='+key \
            +'&orgId='+orgId\
            +'&tblId='+table \
            +'&prdSe='+period \
            +'&startPrdDe='+beg \
            +'&endPrdDe='+end \
            +'&itmId='+item \
            +'&objL1='+obj1 \
            +'&objL2='+obj2 \
            +'&objL3='+obj3 \
            +'&objL4='+obj4 \
            +'&objL5='+obj5 \
            +'&objL6='+obj6 \
            +'&objL7='+obj7 \
            +'&objL8='+obj8 \
            +'&format=json&jsonVD=Y&outputFields=ITM_NM+PRD_DE+DT'
    res = requests.get(url)
    py_json = res.json()

    data = []
    for v in py_json:
        value = []
        value.append(v['PRD_DE'])

        # ✅ DT 값이 '-' 또는 ''일 때 NaN으로 처리
        try:
            value.append(float(v['DT']))
        except (ValueError, KeyError):
            value.append(np.nan)

        data.append(value)

    df = pd.DataFrame(data, columns=['PRD_DE', 'DT'])

    if debug:
        print(df.head())

    return df


    #get json data from url
    with urlopen(url) as url_:
        json_file = url_.read()

    py_json = json.loads(json_file.decode('utf-8'))


    #data transformation
    data = []

    for i, v in enumerate(py_json):
        value = []
        value.append(v['PRD_DE'])
        value.append(float(v['DT']))

        data.append(value)

    if title is not None:
        title = str(title)
    elif title_no=='0':
        title = v['ITM_NM_ENG']
    else:
        title = v['C'+title_no+'_NM_ENG']

    df_kosis = pd.DataFrame({v['PRD_SE']:[x[0] for x in data], title:[x[1] for x in data]}).set_index(v['PRD_SE'])

    if debug:
        return v

    return df_kosis

Collecting xmltodict
  Downloading xmltodict-1.0.2-py3-none-any.whl.metadata (15 kB)
Downloading xmltodict-1.0.2-py3-none-any.whl (13 kB)
Installing collected packages: xmltodict
Successfully installed xmltodict-1.0.2

In [ ]:
import pandas as pd
import numpy as np
import os
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

In [ ]:
# change directory to where you have your data file!!
%cd gdrive/MyDrive/GDP/데이터

/content/gdrive/MyDrive/GDP/데이터

## GDP

In [ ]:
gdp = getECOS('200Y104', 'Q', '2014Q1', '2025Q2','110311').reset_index()
gdp
gdp = gdp.rename(columns={'기계 및 장비 제조업':'gdp'})
gdp

     index      gdp
0   2014Q1  10373.2
1   2014Q2  10670.1
2   2014Q3  10884.5
3   2014Q4  11070.5
4   2015Q1  10882.6
5   2015Q2  10826.7
6   2015Q3  10806.8
7   2015Q4  10658.1
8   2016Q1   9955.5
9   2016Q2  10140.4
10  2016Q3  10467.9
11  2016Q4  11153.8
12  2017Q1  12129.1
13  2017Q2  12887.7
14  2017Q3  12637.7
15  2017Q4  12328.5
16  2018Q1  12701.9
17  2018Q2  12525.2
18  2018Q3  12534.6
19  2018Q4  12265.2
20  2019Q1  12544.7
21  2019Q2  12251.2
22  2019Q3  12075.0
23  2019Q4  12631.6
24  2020Q1  12637.4
25  2020Q2  11782.6
26  2020Q3  12175.1
27  2020Q4  12699.9
28  2021Q1  13328.1
29  2021Q2  13952.7
30  2021Q3  13953.5
31  2021Q4  13975.0
32  2022Q1  14421.8
33  2022Q2  14444.4
34  2022Q3  14976.9
35  2022Q4  14882.2
36  2023Q1  13893.3
37  2023Q2  13364.4
38  2023Q3  13538.1
39  2023Q4  13902.1
40  2024Q1  13830.0
41  2024Q2  13825.1
42  2024Q3  14021.4
43  2024Q4  13779.2
44  2025Q1  13215.4
45  2025Q2  13576.3

##PPI

In [ ]:
ppi = getECOS('404Y014','Q','2014Q1','2025Q2','311AA').reset_index()
ppi

     index   기계및장비
0   2014Q1   97.79
1   2014Q2   98.08
2   2014Q3   98.02
3   2014Q4   98.09
4   2015Q1   98.53
5   2015Q2   98.48
6   2015Q3   98.51
7   2015Q4   98.48
8   2016Q1   98.61
9   2016Q2   98.61
10  2016Q3   98.93
11  2016Q4   98.91
12  2017Q1   98.99
13  2017Q2   99.08
14  2017Q3   99.22
15  2017Q4   99.24
16  2018Q1   99.30
17  2018Q2   99.25
18  2018Q3   99.36
19  2018Q4   99.40
20  2019Q1   99.81
21  2019Q2   99.99
22  2019Q3  100.04
23  2019Q4  100.05
24  2020Q1  100.08
25  2020Q2   99.95
26  2020Q3   99.99
27  2020Q4   99.98
28  2021Q1   99.84
29  2021Q2  100.17
30  2021Q3  101.49
31  2021Q4  103.18
32  2022Q1  104.42
33  2022Q2  105.78
34  2022Q3  107.48
35  2022Q4  107.54
36  2023Q1  108.17
37  2023Q2  108.70
38  2023Q3  109.01
39  2023Q4  109.15
40  2024Q1  110.02
41  2024Q2  110.35
42  2024Q3  110.85
43  2024Q4  110.93
44  2025Q1  111.32
45  2025Q2  111.78

In [ ]:
ppi = ppi.rename(columns={'기계및장비':'ppi'})

##BSI

In [ ]:
업황실적BSI = getECOS('512Y007','M','201401','202506','AA','C2900').reset_index()
매출실적BSI = getECOS('512Y007','M','201401','202506','AB','C2900').reset_index()
채산성실적BSI = getECOS('512Y007','M','201401','202506','AE','C2900').reset_index()
수출실적BSI= getECOS('512Y007','M','201401','202506','AM','C2900').reset_index()
내수판매실적BSI= getECOS('512Y007','M','201401','202506','AL','C2900').reset_index()
생산실적BSI= getECOS('512Y007','M','201401','202506','AC','C2900').reset_index()
신규수주실적BSI= getECOS('512Y007','M','201401','202506','AD','C2900').reset_index()
제품재고실적BSI= getECOS('512Y007','M','201401','202506','AG','C2900').reset_index()
가동률실적BSI= getECOS('512Y007','M','201401','202506','AK','C2900').reset_index()
생산설비실적BSI= getECOS('512Y007','M','201401','202506','AH','C2900').reset_index()
설비투자실적BSI= getECOS('512Y007','M','201401','202506','AI','C2900').reset_index()
자금사정실적BSI = getECOS('512Y007','M','201401','202506','AO','C2900').reset_index()
인력사정실적BSI = getECOS('512Y007','M','201401','202506','AJ','C2900').reset_index()
원자재구입가격BSI = getECOS('512Y007','M','201401','202506','AN','C2900').reset_index()

업황실적BSI = 업황실적BSI.rename(columns={'업황실적BSI 1)':'업황실적BSI'})
매출실적BSI = 매출실적BSI.rename(columns={'매출실적BSI 2)':'매출실적BSI'})
채산성실적BSI = 채산성실적BSI.rename(columns={'채산성실적BSI 6)':'채산성실적BSI'})
수출실적BSI = 수출실적BSI.rename(columns={'수출실적BSI 2)':'수출실적BSI'})
내수판매실적BSI = 내수판매실적BSI.rename(columns={'내수판매실적BSI 2)':'내수판매실적BSI'})
생산실적BSI = 생산실적BSI.rename(columns={'생산실적BSI 2)':'생산실적BSI'})
신규수주실적BSI = 신규수주실적BSI.rename(columns={'신규수주실적BSI 2)':'신규수주실적BSI'})
제품재고실적BSI = 제품재고실적BSI.rename(columns={'제품재고실적BSI 3)':'제품재고실적BSI'})
가동률실적BSI = 가동률실적BSI.rename(columns={'가동률실적BSI 4)':'가동률실적BSI'})
생산설비실적BSI = 생산설비실적BSI.rename(columns={'생산설비실적BSI 3)':'생산설비실적BSI'})
설비투자실적BSI = 설비투자실적BSI.rename(columns={'설비투자실적BSI 5)':'설비투자실적BSI '})
자금사정실적BSI = 자금사정실적BSI.rename(columns={'자금사정실적BSI 6)':'자금사정실적BSI'})
인력사정실적BSI = 인력사정실적BSI.rename(columns={'인력사정실적BSI 3)':'인력사정실적BSI'})
원자재구입가격BSI = 원자재구입가격BSI.rename(columns={'원자재구입가격BSI 4)':'원자재구입가격BSI'})

In [ ]:
from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [업황실적BSI, 매출실적BSI,수출실적BSI, 내수판매실적BSI, 생산실적BSI, 신규수주실적BSI, 제품재고실적BSI, 가동률실적BSI,설비투자실적BSI, 채산성실적BSI, 자금사정실적BSI, 인력사정실적BSI,원자재구입가격BSI]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
df_merged = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
df_merged

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,원자재구입가격실적BSI 4)
0,201401,81.0,81.0,85.0,80.0,85.0,84.0,102.0,87.0,97.0,97.0,86.0,94.0,108.0
1,201402,79.0,85.0,84.0,84.0,86.0,86.0,98.0,85.0,95.0,90.0,89.0,98.0,105.0
2,201403,89.0,87.0,86.0,82.0,92.0,90.0,101.0,89.0,98.0,94.0,89.0,94.0,111.0
3,201404,86.0,90.0,89.0,86.0,86.0,85.0,97.0,85.0,95.0,95.0,85.0,93.0,97.0
4,201405,76.0,88.0,80.0,89.0,90.0,92.0,93.0,90.0,99.0,94.0,92.0,94.0,101.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,202502,62.0,70.0,71.0,76.0,73.0,63.0,99.0,71.0,86.0,73.0,74.0,97.0,123.0
134,202503,65.0,72.0,75.0,76.0,75.0,70.0,101.0,77.0,89.0,75.0,79.0,100.0,126.0
135,202504,65.0,74.0,83.0,66.0,79.0,74.0,97.0,78.0,88.0,73.0,74.0,99.0,128.0
136,202505,70.0,76.0,81.0,75.0,81.0,78.0,106.0,85.0,91.0,71.0,81.0,96.0,118.0
137,202506,70.0,84.0,83.0,81.0,84.0,77.0,99.0,88.0,90.0,78.0,78.0,96.0,117.0

In [ ]:
df_merged = df_merged.rename(columns={'원자재구입가격실적BSI 4)':'원자재구입가격BSI'})

In [ ]:
df_merged.isnull().sum()

index         0
업황실적BSI       0
매출실적BSI       0
수출실적BSI       0
내수판매실적BSI     0
생산실적BSI       0
신규수주실적BSI     0
제품재고실적BSI     0
가동률실적BSI      0
설비투자실적BSI     0
채산성실적BSI      0
자금사정실적BSI     0
인력사정실적BSI     0
원자재구입가격BSI    0
dtype: int64

In [ ]:
import pandas as pd

# index가 숫자라면 문자열로 변환
df_merged['index'] = df_merged['index'].astype(str)

# 연도와 월 분리
df_merged['연도'] = df_merged['index'].str[:4].astype(int)
df_merged['월'] = df_merged['index'].str[4:6].astype(int)

# 월 → 분기 변환 함수
def month_to_quarter(month):
    if month in [1, 2, 3]:
        return 'Q1'
    elif month in [4, 5, 6]:
        return 'Q2'
    elif month in [7, 8, 9]:
        return 'Q3'
    else:
        return 'Q4'

# 분기 계산
df_merged['분기'] = df_merged['월'].apply(month_to_quarter)

# 분기 인덱스 생성 (예: 2015Q1)
df_merged['index'] = df_merged['연도'].astype(str) + df_merged['분기']

# 분기별 평균 집계
df_quarter = df_merged.groupby('index').mean(numeric_only=True).reset_index()

# 결과 확인
print(df_quarter.head())

    index    업황실적BSI    매출실적BSI    수출실적BSI  내수판매실적BSI    생산실적BSI  신규수주실적BSI  \
0  2014Q1  83.000000  84.333333  85.000000  82.000000  87.666667  86.666667
1  2014Q2  78.666667  87.000000  84.333333  86.000000  88.000000  87.000000
2  2014Q3  72.000000  78.333333  85.333333  76.666667  86.333333  83.000000
3  2014Q4  71.666667  89.333333  93.000000  85.666667  90.000000  85.666667
4  2015Q1  75.666667  97.000000  98.333333  97.000000  98.000000  96.333333

    제품재고실적BSI    가동률실적BSI  설비투자실적BSI    채산성실적BSI  자금사정실적BSI  인력사정실적BSI  \
0  100.333333   87.000000   96.666667  93.666667  88.000000  95.333333
1   95.333333   88.666667   97.000000  93.333333  88.000000  95.000000
2   99.333333   87.000000   93.000000  90.000000  84.666667  97.333333
3  103.666667   89.000000   93.666667  88.666667  82.000000  94.333333
4  104.000000  101.000000   95.333333  90.000000  85.000000  96.000000

   원자재구입가격BSI      연도     월
0  108.000000  2014.0   2.0
1   99.666667  2014.0   5.0
2  106.000000  2014.0   8.0
3  107.666667  2014.0  11.0
4   99.333333  2015.0   2.0

In [ ]:
df_quarter = df_quarter.drop(columns=['연도', '월'], errors='ignore')

In [ ]:
dfs = [ppi, gdp]
df_final = df_quarter.copy()
key_col = 'index'
for df in dfs:
    df_final = df_final.merge(df, on=key_col, how='left')

df_final

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,원자재구입가격BSI,ppi,gdp
0,2014Q1,83.000000,84.333333,85.000000,82.000000,87.666667,86.666667,100.333333,87.000000,96.666667,93.666667,88.000000,95.333333,108.000000,97.79,10373.2
1,2014Q2,78.666667,87.000000,84.333333,86.000000,88.000000,87.000000,95.333333,88.666667,97.000000,93.333333,88.000000,95.000000,99.666667,98.08,10670.1
2,2014Q3,72.000000,78.333333,85.333333,76.666667,86.333333,83.000000,99.333333,87.000000,93.000000,90.000000,84.666667,97.333333,106.000000,98.02,10884.5
3,2014Q4,71.666667,89.333333,93.000000,85.666667,90.000000,85.666667,103.666667,89.000000,93.666667,88.666667,82.000000,94.333333,107.666667,98.09,11070.5
4,2015Q1,75.666667,97.000000,98.333333,97.000000,98.000000,96.333333,104.000000,101.000000,95.333333,90.000000,85.000000,96.000000,99.333333,98.53,10882.6
5,2015Q2,72.000000,90.333333,97.000000,85.333333,93.000000,88.000000,110.666667,93.333333,94.333333,87.333333,80.000000,96.333333,102.333333,98.48,10826.7
6,2015Q3,62.666667,77.333333,85.333333,71.666667,79.666667,72.666667,105.666667,80.000000,90.333333,87.000000,77.000000,97.000000,106.666667,98.51,10806.8
7,2015Q4,61.666667,77.000000,82.333333,72.000000,80.000000,74.000000,105.666667,77.666667,91.666667,85.000000,75.333333,98.333333,100.000000,98.48,10658.1
8,2016Q1,56.333333,70.666667,77.666667,68.333333,76.333333,70.666667,106.333333,77.333333,89.333333,79.000000,74.000000,102.000000,102.333333,98.61,9955.5
9,2016Q2,62.000000,76.333333,80.000000,73.000000,84.666667,78.333333,104.333333,86.666667,89.666667,84.666667,75.666667,95.333333,112.666667,98.61,10140.4
10,2016Q3,65.000000,75.000000,71.000000,73.333333,80.666667,72.666667,105.000000,80.333333,91.333333,85.000000,76.666667,93.666667,110.666667,98.93,10467.9
11,2016Q4,64.333333,79.000000,81.333333,77.666667,82.666667,79.333333,105.000000,83.000000,92.666667,80.333333,75.333333,94.666667,114.000000,98.91,11153.8
12,2017Q1,78.666667,89.333333,87.333333,87.000000,91.666667,88.000000,104.333333,93.666667,95.000000,81.000000,81.666667,90.333333,124.333333,98.99,12129.1
13,2017Q2,85.000000,92.666667,95.666667,86.333333,94.666667,89.000000,101.333333,97.000000,94.666667,86.666667,80.000000,93.666667,112.000000,99.08,12887.7
14,2017Q3,79.000000,87.000000,86.666667,83.666667,88.000000,83.333333,102.333333,89.333333,93.333333,82.333333,79.666667,93.333333,113.000000,99.22,12637.7
15,2017Q4,74.666667,84.333333,88.666667,77.000000,86.666667,83.000000,102.333333,85.666667,94.666667,80.666667,78.333333,91.666667,117.333333,99.24,12328.5
16,2018Q1,75.666667,84.666667,88.000000,78.333333,87.000000,82.333333,103.333333,85.666667,93.333333,79.000000,76.666667,93.333333,125.333333,99.30,12701.9
17,2018Q2,73.000000,82.333333,80.000000,82.000000,86.666667,85.000000,101.000000,88.333333,91.333333,78.666667,78.666667,87.000000,127.666667,99.25,12525.2
18,2018Q3,67.333333,80.000000,81.333333,79.000000,84.333333,83.666667,100.666667,82.333333,89.333333,78.333333,75.333333,85.000000,127.333333,99.36,12534.6
19,2018Q4,65.666667,77.666667,81.333333,75.000000,85.333333,79.333333,106.333333,84.666667,89.000000,78.333333,73.000000,88.666667,124.000000,99.40,12265.2
20,2019Q1,66.666667,79.333333,79.333333,77.333333,82.666667,78.333333,105.333333,82.666667,92.333333,78.666667,75.333333,88.666667,127.666667,99.81,12544.7
21,2019Q2,71.333333,79.666667,83.333333,79.333333,82.000000,81.333333,105.333333,83.333333,91.666667,82.333333,78.333333,90.333333,126.000000,99.99,12251.2
22,2019Q3,66.333333,72.666667,77.666667,71.333333,76.000000,69.666667,104.666667,75.000000,89.333333,80.000000,77.000000,90.666667,122.333333,100.04,12075.0
23,2019Q4,67.333333,75.333333,78.666667,74.666667,79.666667,75.333333,106.666667,77.333333,89.000000,81.666667,76.333333,90.333333,120.333333,100.05,12631.6
24,2020Q1,64.666667,72.666667,76.333333,70.333333,78.000000,74.000000,104.000000,77.000000,91.666667,81.666667,73.666667,90.666667,116.333333,100.08,12637.4
25,2020Q2,46.666667,53.666667,55.333333,57.000000,58.333333,50.000000,108.666667,57.000000,81.666667,77.000000,67.333333,103.000000,113.000000,99.95,11782.6
26,2020Q3,60.000000,67.000000,64.000000,67.666667,62.666667,60.000000,106.666667,64.333333,82.000000,81.333333,74.333333,96.666667,109.666667,99.99,12175.1
27,2020Q4,70.000000,73.666667,73.666667,73.000000,74.666667,71.666667,103.666667,79.666667,86.333333,85.333333,80.333333,96.000000,110.333333,99.98,12699.9
28,2021Q1,82.000000,90.666667,90.666667,90.666667,91.666667,89.666667,99.666667,92.666667,96.000000,87.000000,83.666667,89.666667,123.666667,99.84,13328.1
29,2021Q2,93.000000,107.666667,109.000000,103.333333,104.333333,107.000000,96.333333,108.000000,94.666667,80.666667,84.000000,81.666667,139.000000,100.17,13952.7
30,2021Q3,89.666667,99.000000,101.666667,96.000000,100.000000,101.666667,96.333333,104.333333,95.666667,74.000000,80.333333,84.000000,149.000000,101.49,13953.5
31,2021Q4,91.333333,105.000000,101.666667,103.666667,104.000000,106.333333,101.666667,105.666667,98.000000,75.333333,81.666667,85.333333,142.333333,103.18,13975.0
32,2022Q1,92.000000,102.666667,104.000000,100.666667,101.666667,101.000000,97.333333,102.333333,95.333333,72.666667,81.000000,83.000000,144.000000,104.42,14421.8
33,2022Q2,87.000000,97.000000,92.666667,97.333333,96.666667,96.000000,97.000000,97.333333,94.666667,69.333333,79.000000,83.666667,152.666667,105.78,14444.4
34,2022Q3,86.000000,101.333333,97.666667,98.000000,95.000000,93.666667,100.666667,96.000000,94.333333,75.000000,79.333333,79.000000,134.000000,107.48,14976.9
35,2022Q4,78.000000,93.000000,96.000000,90.333333,91.000000,86.666667,107.000000,91.666667,91.333333,75.333333,79.666667,87.333333,128.666667,107.54,14882.2
36,2023Q1,63.666667,77.333333,79.333333,78.333333,80.333333,76.333333,104.666667,79.333333,88.666667,74.666667,77.333333,90.333333,120.666667,108.17,13893.3
37,2023Q2,73.666667,84.000000,85.333333,80.333333,81.666667,80.666667,105.000000,82.000000,93.666667,80.666667,77.333333,91.333333,112.333333,108.70,13364.4
38,2023Q3,68.666667,74.333333,73.000000,75.000000,77.666667,72.666667,105.333333,78.000000,90.000000,80.666667,80.000000,95.000000,110.000000,109.01,13538.1
39,2023Q4,69.666667,78.000000,78.000000,75.666667,77.333333,74.666667,105.666667,81.000000,88.666667,80.000000,79.333333,89.000000,120.333333,109.15,13902.1
40,2024Q1,73.000000,84.000000,86.333333,78.666667,79.333333,74.333333,100.666667,84.000000,91.000000,76.000000,77.666667,85.666667,121.000000,110.02,13830.0
41,2024Q2,70.666667,80.000000,87.666667,76.666667,84.333333,75.333333,100.000000,86.000000,91.000000,79.000000,82.000000,91.000000,123.666667,110.35,13825.1
42,2024Q3,72.333333,82.333333,83.333333,79.000000,82.666667,78.333333,103.000000,83.666667,90.000000,83.333333,85.000000,91.333333,117.666667,110.85,14021.4
43,2024Q4,68.000000,79.333333,86.000000,73.000000,76.000000,70.666667,99.666667,78.000000,89.000000,80.000000,82.666667,93.000000,116.333333,110.93,13779.2
44,2025Q1,63.666667,71.333333,77.000000,75.000000,74.666667,66.666667,99.333333,74.333333,87.333333,73.333333,78.666667,97.666667,124.333333,111.32,13215.4
45,2025Q2,68.333333,78.000000,82.333333,74.000000,81.333333,76.333333,100.666667,83.666667,89.666667,74.000000,77.666667,97.000000,121.000000,111.78,13576.3

In [ ]:
df_final.to_csv("기계장비1차.csv")

##생산지수

In [ ]:
생산지수 = getKOSIS('DT_1F02001','Q','201401','202502','T20','101','00','C29')

def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

생산지수['index']=생산지수['PRD_DE'].apply(to_quarter)
생산지수 = 생산지수.drop(columns=["PRD_DE"])
생산지수 = 생산지수.rename(columns={'DT': '생산지수'})
생산지수

       생산지수   index
0    94.196  2014Q1
1    94.913  2014Q2
2    95.065  2014Q3
3    98.759  2014Q4
4    94.013  2015Q1
5    92.414  2015Q2
6    93.534  2015Q3
7    90.416  2015Q4
8    88.974  2016Q1
9    90.234  2016Q2
10   93.752  2016Q3
11  101.309  2016Q4
12  104.616  2017Q1
13  109.811  2017Q2
14  108.293  2017Q3
15  105.308  2017Q4
16  108.617  2018Q1
17  105.961  2018Q2
18  101.451  2018Q3
19   98.694  2018Q4
20   95.056  2019Q1
21   94.922  2019Q2
22   96.630  2019Q3
23  100.636  2019Q4
24  100.100  2020Q1
25   93.900  2020Q2
26  100.000  2020Q3
27  106.000  2020Q4
28  110.700  2021Q1
29  114.200  2021Q2
30  110.400  2021Q3
31  113.300  2021Q4
32  108.000  2022Q1
33  108.400  2022Q2
34  118.300  2022Q3
35  118.100  2022Q4
36  108.000  2023Q1
37  104.100  2023Q2
38  102.700  2023Q3
39  106.100  2023Q4
40  101.800  2024Q1
41  101.800  2024Q2
42  103.000  2024Q3
43  107.900  2024Q4
44  101.800  2025Q1
45  101.200  2025Q2

https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MGNkMzY3MTdhNjZlMTNiZDMxYjU4NDA4NTdjZWU0YmQ=&itmId=T20+&objL1=C29+&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Q&startPrdDe=201401&endPrdDe=202502&outputFields=OBJ_NM+NM+ITM_NM+PRD_DE+&orgId=101&tblId=DT_1F02016

##내수/수출출하지수

In [ ]:
수출출하지수 = getKOSIS('DT_1F02016','Q','201401','202502','T21','101','C29')

def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

수출출하지수['index']=수출출하지수['PRD_DE'].apply(to_quarter)
수출출하지수 = 수출출하지수.drop(columns=["PRD_DE"])
수출출하지수 = 수출출하지수.rename(columns={'DT': '수출출하지수'})
수출출하지수

     수출출하지수   index
0    99.080  2014Q1
1   102.612  2014Q2
2   100.695  2014Q3
3   103.981  2014Q4
4    95.406  2015Q1
5    95.217  2015Q2
6    96.857  2015Q3
7    90.927  2015Q4
8    95.091  2016Q1
9    91.842  2016Q2
10   92.725  2016Q3
11   99.254  2016Q4
12  105.246  2017Q1
13  111.049  2017Q2
14  107.706  2017Q3
15  106.287  2017Q4
16  107.012  2018Q1
17  109.536  2018Q2
18  112.847  2018Q3
19  109.441  2018Q4
20  103.070  2019Q1
21  102.282  2019Q2
22  104.489  2019Q3
23  105.751  2019Q4
24  104.700  2020Q1
25   89.400  2020Q2
26  102.400  2020Q3
27  104.000  2020Q4
28  116.500  2021Q1
29  121.700  2021Q2
30  112.200  2021Q3
31  117.000  2021Q4
32  111.000  2022Q1
33  109.900  2022Q2
34  120.800  2022Q3
35  113.000  2022Q4
36  113.000  2023Q1
37  113.100  2023Q2
38  108.200  2023Q3
39  103.200  2023Q4
40   99.800  2024Q1
41  102.700  2024Q2
42  102.500  2024Q3
43  102.200  2024Q4
44  102.400  2025Q1
45  110.600  2025Q2

In [ ]:
내수출하지수 = getKOSIS('DT_1F02016','Q','201401','202502','T20','101','C29')
def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

내수출하지수['index']=내수출하지수['PRD_DE'].apply(to_quarter)
내수출하지수 = 내수출하지수.drop(columns=["PRD_DE"])
내수출하지수 = 내수출하지수.rename(columns={'DT': '내수출하지수'})
내수출하지수

     내수출하지수   index
0    90.668  2014Q1
1    91.032  2014Q2
2    91.561  2014Q3
3    95.727  2014Q4
4    92.881  2015Q1
5    92.169  2015Q2
6    94.707  2015Q3
7    92.263  2015Q4
8    86.196  2016Q1
9    91.643  2016Q2
10   98.205  2016Q3
11  104.828  2016Q4
12  105.293  2017Q1
13  111.452  2017Q2
14  109.533  2017Q3
15  106.438  2017Q4
16  109.254  2018Q1
17  103.405  2018Q2
18   96.781  2018Q3
19   93.841  2018Q4
20   94.769  2019Q1
21   93.779  2019Q2
22   92.696  2019Q3
23  100.402  2019Q4
24   98.700  2020Q1
25   97.300  2020Q2
26   98.500  2020Q3
27  104.900  2020Q4
28  108.000  2021Q1
29  110.600  2021Q2
30  107.500  2021Q3
31  106.400  2021Q4
32  105.800  2022Q1
33  104.700  2022Q2
34  114.300  2022Q3
35  115.500  2022Q4
36  102.600  2023Q1
37  101.500  2023Q2
38  102.200  2023Q3
39  106.600  2023Q4
40  104.700  2024Q1
41  104.700  2024Q2
42  106.800  2024Q3
43  108.400  2024Q4
44  103.600  2025Q1
45   99.100  2025Q2

##생산능력지수&가동률지수

In [ ]:
생산능력지수 = getKOSIS('DT_1F32001','Q','201401','202502','T10','101','C29')
def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

생산능력지수['index']=생산능력지수['PRD_DE'].apply(to_quarter)
생산능력지수 = 생산능력지수.drop(columns=["PRD_DE"])
생산능력지수 = 생산능력지수.rename(columns={'DT': '생산능력지수'})
생산능력지수

     생산능력지수   index
0    98.819  2014Q1
1    99.304  2014Q2
2    99.590  2014Q3
3   100.075  2014Q4
4    97.797  2015Q1
5    98.192  2015Q2
6    99.014  2015Q3
7    99.441  2015Q4
8    99.441  2016Q1
9    99.310  2016Q2
10   99.080  2016Q3
11   99.244  2016Q4
12   98.422  2017Q1
13   98.619  2017Q2
14   98.850  2017Q3
15   99.277  2017Q4
16   99.277  2018Q1
17  100.066  2018Q2
18   99.902  2018Q3
19  100.756  2018Q4
20   98.817  2019Q1
21   98.554  2019Q2
22   98.685  2019Q3
23   99.310  2019Q4
24   98.800  2020Q1
25   99.200  2020Q2
26  100.100  2020Q3
27  101.900  2020Q4
28  101.900  2021Q1
29  101.500  2021Q2
30  100.500  2021Q3
31   99.900  2021Q4
32   98.500  2022Q1
33   97.000  2022Q2
34   95.100  2022Q3
35   95.500  2022Q4
36   94.600  2023Q1
37   95.900  2023Q2
38   96.600  2023Q3
39   97.400  2023Q4
40   94.800  2024Q1
41   94.800  2024Q2
42   94.700  2024Q3
43   94.500  2024Q4
44   91.500  2025Q1
45   90.400  2025Q2

In [ ]:
가동률지수 = getKOSIS('DT_1F32001','Q','201401','202502','T30','101','C29')
def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

가동률지수['index']=가동률지수['PRD_DE'].apply(to_quarter)
가동률지수 = 가동률지수.drop(columns=["PRD_DE"])
가동률지수 = 가동률지수.rename(columns={'DT': '가동률지수'})
가동률지수

      가동률지수   index
0   110.695  2014Q1
1   114.809  2014Q2
2   112.053  2014Q3
3   111.644  2014Q4
4   107.665  2015Q1
5   106.787  2015Q2
6   104.312  2015Q3
7   101.056  2015Q4
8   100.956  2016Q1
9   102.030  2016Q2
10  100.953  2016Q3
11  101.302  2016Q4
12  104.804  2017Q1
13  107.141  2017Q2
14  110.572  2017Q3
15  107.433  2017Q4
16  108.722  2018Q1
17  108.826  2018Q2
18  105.326  2018Q3
19  104.540  2018Q4
20  104.664  2019Q1
21  107.952  2019Q2
22  109.059  2019Q3
23  106.996  2019Q4
24  107.500  2020Q1
25   92.400  2020Q2
26   96.000  2020Q3
27  104.200  2020Q4
28  105.200  2021Q1
29  107.000  2021Q2
30  106.000  2021Q3
31  111.700  2021Q4
32  108.300  2022Q1
33  109.200  2022Q2
34  117.200  2022Q3
35  120.000  2022Q4
36  117.500  2023Q1
37  115.200  2023Q2
38  109.800  2023Q3
39  107.400  2023Q4
40  106.900  2024Q1
41  106.000  2024Q2
42  102.800  2024Q3
43  102.000  2024Q4
44  105.700  2025Q1
45  106.900  2025Q2

## 수출액/수입액

https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MGNkMzY3MTdhNjZlMTNiZDMxYjU4NDA4NTdjZWU0YmQ=&itmId=T001+&objL1=20000+&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=M&startPrdDe=201401&endPrdDe=202506&outputFields=OBJ_NM+NM+ITM_NM+PRD_DE+&orgId=373&tblId=DT_373001_B001

In [ ]:
수출액 = getKOSIS('DT_373001_B001','M','201401','202506','T001','373','20000')
수출액

     PRD_DE            DT
0    201401  3.518386e+09
1    201402  3.491683e+09
2    201403  3.813932e+09
3    201404  4.103635e+09
4    201405  3.834125e+09
..      ...           ...
133  202502  4.172434e+09
134  202503  4.583673e+09
135  202504  4.759810e+09
136  202505  4.480524e+09
137  202506  4.406104e+09

[138 rows x 2 columns]

In [ ]:
수입액 = getKOSIS('DT_373001_B001','M','201401','202506','T002','373','20000')
수입액

     PRD_DE            DT
0    201401  2.621683e+09
1    201402  2.929583e+09
2    201403  2.938747e+09
3    201404  3.370108e+09
4    201405  3.161762e+09
..      ...           ...
133  202502  3.632532e+09
134  202503  3.807077e+09
135  202504  3.924553e+09
136  202505  3.537014e+09
137  202506  3.987397e+09

[138 rows x 2 columns]

In [ ]:
from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
df2 = [수출액,수입액]
df2 = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in df2]

# '시점' 기준으로 병합
df_merged2 = reduce(lambda left, right: pd.merge(left, right, on="PRD_DE", how="outer"), df2)
df_merged2

     PRD_DE          DT_x          DT_y
0    201401  3.518386e+09  2.621683e+09
1    201402  3.491683e+09  2.929583e+09
2    201403  3.813932e+09  2.938747e+09
3    201404  4.103635e+09  3.370108e+09
4    201405  3.834125e+09  3.161762e+09
..      ...           ...           ...
133  202502  4.172434e+09  3.632532e+09
134  202503  4.583673e+09  3.807077e+09
135  202504  4.759810e+09  3.924553e+09
136  202505  4.480524e+09  3.537014e+09
137  202506  4.406104e+09  3.987397e+09

[138 rows x 3 columns]

In [ ]:
import pandas as pd

# index가 숫자라면 문자열로 변환
df_merged2['PRD_DE'] = df_merged2['PRD_DE'].astype(str)

# 연도와 월 분리
df_merged2['연도'] = df_merged2['PRD_DE'].str[:4].astype(int)
df_merged2['월'] = df_merged2['PRD_DE'].str[4:6].astype(int)

# 월 → 분기 변환 함수
def month_to_quarter(month):
    if month in [1, 2, 3]:
        return 'Q1'
    elif month in [4, 5, 6]:
        return 'Q2'
    elif month in [7, 8, 9]:
        return 'Q3'
    else:
        return 'Q4'

# 분기 계산
df_merged2['분기'] = df_merged2['월'].apply(month_to_quarter)

# 분기 인덱스 생성 (예: 2015Q1)
df_merged2['index'] = df_merged2['연도'].astype(str) + df_merged2['분기']

# 분기별 평균 집계
df_quarter2 = df_merged2.groupby('index').mean(numeric_only=True).reset_index()

# 결과 확인
print(df_quarter2.head())

    index          DT_x          DT_y      연도     월
0  2014Q1  3.608000e+09  2.830004e+09  2014.0   2.0
1  2014Q2  3.872889e+09  3.116658e+09  2014.0   5.0
2  2014Q3  3.667544e+09  2.858808e+09  2014.0   8.0
3  2014Q4  3.854089e+09  3.166458e+09  2014.0  11.0
4  2015Q1  3.731872e+09  2.921134e+09  2015.0   2.0

In [ ]:
df_quarter2 = df_quarter2.drop(columns=['연도', '월'], errors='ignore')

In [ ]:
df_quarter2 = df_quarter2.rename(columns={'DT_x':'수출액'})
df_quarter2 = df_quarter2.rename(columns={'DT_y':'수입액'})

In [ ]:
df_quarter2.to_csv("기계장비수출입.csv")

## 기업데이터

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('임지오기업.csv')

In [ ]:
기계장비기업 = df[df['매핑한 산업'] == "기계 및 장비 제조업"]

In [ ]:
columns = ['EBITDA', '인건비']
grouped = 기계장비기업.groupby('조사일')[columns].sum()
grouped

                  EBITDA          인건비
조사일
2000-01-01  0.000000e+00   41070236.0
2000-04-01  0.000000e+00   90555409.0
2000-07-01  0.000000e+00   -7865244.0
2000-10-01  6.921846e+11  837597188.0
2001-01-01  0.000000e+00   59314689.0
...                  ...          ...
2024-04-01  1.207368e+12  461605628.0
2024-07-01  1.155090e+12  441623912.0
2024-10-01  7.714153e+11  782976901.0
2025-01-01  1.021859e+12  256544262.0
2025-04-01  1.111777e+12 -249973842.0

[102 rows x 2 columns]

In [ ]:
grouped = grouped.reset_index()

In [ ]:
grouped

            조사일        EBITDA          인건비
0    2000-01-01  0.000000e+00   41070236.0
1    2000-04-01  0.000000e+00   90555409.0
2    2000-07-01  0.000000e+00   -7865244.0
3    2000-10-01  6.921846e+11  837597188.0
4    2001-01-01  0.000000e+00   59314689.0
..          ...           ...          ...
97   2024-04-01  1.207368e+12  461605628.0
98   2024-07-01  1.155090e+12  441623912.0
99   2024-10-01  7.714153e+11  782976901.0
100  2025-01-01  1.021859e+12  256544262.0
101  2025-04-01  1.111777e+12 -249973842.0

[102 rows x 3 columns]

In [ ]:
grouped['조사일']=pd.to_datetime(grouped['조사일'])

# 분기(Quarter) 단위로 변환
grouped["index"] = grouped["조사일"].dt.to_period("Q")
grouped = grouped.drop(columns=["조사일"])
print(grouped)

           EBITDA          인건비   index
0    0.000000e+00   41070236.0  2000Q1
1    0.000000e+00   90555409.0  2000Q2
2    0.000000e+00   -7865244.0  2000Q3
3    6.921846e+11  837597188.0  2000Q4
4    0.000000e+00   59314689.0  2001Q1
..            ...          ...     ...
97   1.207368e+12  461605628.0  2024Q2
98   1.155090e+12  441623912.0  2024Q3
99   7.714153e+11  782976901.0  2024Q4
100  1.021859e+12  256544262.0  2025Q1
101  1.111777e+12 -249973842.0  2025Q2

[102 rows x 3 columns]

In [ ]:
mask = (grouped["index"] >= pd.Period("2014Q1")) & (grouped["index"] <= pd.Period("2025Q2"))
기업= grouped.loc[mask]
기업
기업['합산'] = 기업['EBITDA']+기업['인건비']
기업

/tmp/ipython-input-1389489221.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기업['합산'] = 기업['EBITDA']+기업['인건비']

           EBITDA           인건비   index            합산
56   5.437342e+11  2.842432e+08  2014Q1  5.440185e+11
57   5.617213e+11  2.922078e+08  2014Q2  5.620135e+11
58   3.814502e+11  2.689605e+08  2014Q3  3.817191e+11
59   5.230960e+11  1.205299e+09  2014Q4  5.243013e+11
60   5.123197e+11  3.019108e+08  2015Q1  5.126216e+11
61   5.705730e+11  2.773232e+08  2015Q2  5.708503e+11
62   4.574159e+11  2.963735e+08  2015Q3  4.577122e+11
63   3.114078e+11  1.355684e+09  2015Q4  3.127634e+11
64   5.492057e+11  2.468207e+08  2016Q1  5.494525e+11
65   5.412574e+11  2.840172e+08  2016Q2  5.415414e+11
66   5.049225e+11  2.482402e+08  2016Q3  5.051708e+11
67   8.038010e+11  1.457730e+09  2016Q4  8.052587e+11
68   8.746092e+11  2.910922e+08  2017Q1  8.749002e+11
69   1.328643e+12  2.959673e+08  2017Q2  1.328939e+12
70   9.628408e+11  3.280118e+08  2017Q3  9.631688e+11
71   9.502225e+11  1.939426e+09  2017Q4  9.521620e+11
72   8.783616e+11  3.147275e+08  2018Q1  8.786763e+11
73   9.061697e+11  2.970989e+08  2018Q2  9.064668e+11
74   7.361397e+11  3.063240e+08  2018Q3  7.364460e+11
75   6.039006e+11  2.473850e+09  2018Q4  6.063744e+11
76   6.664142e+11  3.230076e+08  2019Q1  6.667372e+11
77   8.515774e+11  3.201069e+08  2019Q2  8.518975e+11
78   5.662552e+11  3.245174e+08  2019Q3  5.665797e+11
79   6.762271e+11  2.529068e+09  2019Q4  6.787561e+11
80   6.636823e+11  4.724953e+08  2020Q1  6.641548e+11
81   6.840599e+11  3.724895e+08  2020Q2  6.844324e+11
82   7.902491e+11  3.177418e+08  2020Q3  7.905669e+11
83   5.465905e+11  2.355996e+09  2020Q4  5.489465e+11
84   8.193097e+11  3.536725e+08  2021Q1  8.196634e+11
85   1.073810e+12  3.688898e+08  2021Q2  1.074179e+12
86   7.979106e+11  3.471856e+08  2021Q3  7.982578e+11
87   8.562412e+11  1.867754e+09  2021Q4  8.581089e+11
88   9.289508e+11  4.103001e+08  2022Q1  9.293611e+11
89   1.156476e+12  3.887183e+08  2022Q2  1.156865e+12
90   1.191591e+12  4.187830e+08  2022Q3  1.192010e+12
91   1.211496e+12  1.846281e+09  2022Q4  1.213342e+12
92   9.413128e+11  4.152969e+08  2023Q1  9.417281e+11
93   1.047534e+12  4.192693e+08  2023Q2  1.047953e+12
94   8.357181e+11  3.843113e+08  2023Q3  8.361024e+11
95   1.072947e+12  1.697913e+09  2023Q4  1.074645e+12
96   9.762627e+11  4.295516e+08  2024Q1  9.766922e+11
97   1.207368e+12  4.616056e+08  2024Q2  1.207830e+12
98   1.155090e+12  4.416239e+08  2024Q3  1.155532e+12
99   7.714153e+11  7.829769e+08  2024Q4  7.721983e+11
100  1.021859e+12  2.565443e+08  2025Q1  1.022116e+12
101  1.111777e+12 -2.499738e+08  2025Q2  1.111527e+12

In [ ]:
기업 = 기업[['index'] + [col for col in 기업.columns if col != 'index']]
기업 = 기업.reset_index()

In [ ]:
기업

    level_0   index        EBITDA           인건비            합산
0        56  2014Q1  5.437342e+11  2.842432e+08  5.440185e+11
1        57  2014Q2  5.617213e+11  2.922078e+08  5.620135e+11
2        58  2014Q3  3.814502e+11  2.689605e+08  3.817191e+11
3        59  2014Q4  5.230960e+11  1.205299e+09  5.243013e+11
4        60  2015Q1  5.123197e+11  3.019108e+08  5.126216e+11
5        61  2015Q2  5.705730e+11  2.773232e+08  5.708503e+11
6        62  2015Q3  4.574159e+11  2.963735e+08  4.577122e+11
7        63  2015Q4  3.114078e+11  1.355684e+09  3.127634e+11
8        64  2016Q1  5.492057e+11  2.468207e+08  5.494525e+11
9        65  2016Q2  5.412574e+11  2.840172e+08  5.415414e+11
10       66  2016Q3  5.049225e+11  2.482402e+08  5.051708e+11
11       67  2016Q4  8.038010e+11  1.457730e+09  8.052587e+11
12       68  2017Q1  8.746092e+11  2.910922e+08  8.749002e+11
13       69  2017Q2  1.328643e+12  2.959673e+08  1.328939e+12
14       70  2017Q3  9.628408e+11  3.280118e+08  9.631688e+11
15       71  2017Q4  9.502225e+11  1.939426e+09  9.521620e+11
16       72  2018Q1  8.783616e+11  3.147275e+08  8.786763e+11
17       73  2018Q2  9.061697e+11  2.970989e+08  9.064668e+11
18       74  2018Q3  7.361397e+11  3.063240e+08  7.364460e+11
19       75  2018Q4  6.039006e+11  2.473850e+09  6.063744e+11
20       76  2019Q1  6.664142e+11  3.230076e+08  6.667372e+11
21       77  2019Q2  8.515774e+11  3.201069e+08  8.518975e+11
22       78  2019Q3  5.662552e+11  3.245174e+08  5.665797e+11
23       79  2019Q4  6.762271e+11  2.529068e+09  6.787561e+11
24       80  2020Q1  6.636823e+11  4.724953e+08  6.641548e+11
25       81  2020Q2  6.840599e+11  3.724895e+08  6.844324e+11
26       82  2020Q3  7.902491e+11  3.177418e+08  7.905669e+11
27       83  2020Q4  5.465905e+11  2.355996e+09  5.489465e+11
28       84  2021Q1  8.193097e+11  3.536725e+08  8.196634e+11
29       85  2021Q2  1.073810e+12  3.688898e+08  1.074179e+12
30       86  2021Q3  7.979106e+11  3.471856e+08  7.982578e+11
31       87  2021Q4  8.562412e+11  1.867754e+09  8.581089e+11
32       88  2022Q1  9.289508e+11  4.103001e+08  9.293611e+11
33       89  2022Q2  1.156476e+12  3.887183e+08  1.156865e+12
34       90  2022Q3  1.191591e+12  4.187830e+08  1.192010e+12
35       91  2022Q4  1.211496e+12  1.846281e+09  1.213342e+12
36       92  2023Q1  9.413128e+11  4.152969e+08  9.417281e+11
37       93  2023Q2  1.047534e+12  4.192693e+08  1.047953e+12
38       94  2023Q3  8.357181e+11  3.843113e+08  8.361024e+11
39       95  2023Q4  1.072947e+12  1.697913e+09  1.074645e+12
40       96  2024Q1  9.762627e+11  4.295516e+08  9.766922e+11
41       97  2024Q2  1.207368e+12  4.616056e+08  1.207830e+12
42       98  2024Q3  1.155090e+12  4.416239e+08  1.155532e+12
43       99  2024Q4  7.714153e+11  7.829769e+08  7.721983e+11
44      100  2025Q1  1.021859e+12  2.565443e+08  1.022116e+12
45      101  2025Q2  1.111777e+12 -2.499738e+08  1.111527e+12

In [ ]:
기업
기업 = 기업.drop(columns=['level_0'])

In [ ]:
기업

     index        EBITDA           인건비            합산
0   2014Q1  5.437342e+11  2.842432e+08  5.440185e+11
1   2014Q2  5.617213e+11  2.922078e+08  5.620135e+11
2   2014Q3  3.814502e+11  2.689605e+08  3.817191e+11
3   2014Q4  5.230960e+11  1.205299e+09  5.243013e+11
4   2015Q1  5.123197e+11  3.019108e+08  5.126216e+11
5   2015Q2  5.705730e+11  2.773232e+08  5.708503e+11
6   2015Q3  4.574159e+11  2.963735e+08  4.577122e+11
7   2015Q4  3.114078e+11  1.355684e+09  3.127634e+11
8   2016Q1  5.492057e+11  2.468207e+08  5.494525e+11
9   2016Q2  5.412574e+11  2.840172e+08  5.415414e+11
10  2016Q3  5.049225e+11  2.482402e+08  5.051708e+11
11  2016Q4  8.038010e+11  1.457730e+09  8.052587e+11
12  2017Q1  8.746092e+11  2.910922e+08  8.749002e+11
13  2017Q2  1.328643e+12  2.959673e+08  1.328939e+12
14  2017Q3  9.628408e+11  3.280118e+08  9.631688e+11
15  2017Q4  9.502225e+11  1.939426e+09  9.521620e+11
16  2018Q1  8.783616e+11  3.147275e+08  8.786763e+11
17  2018Q2  9.061697e+11  2.970989e+08  9.064668e+11
18  2018Q3  7.361397e+11  3.063240e+08  7.364460e+11
19  2018Q4  6.039006e+11  2.473850e+09  6.063744e+11
20  2019Q1  6.664142e+11  3.230076e+08  6.667372e+11
21  2019Q2  8.515774e+11  3.201069e+08  8.518975e+11
22  2019Q3  5.662552e+11  3.245174e+08  5.665797e+11
23  2019Q4  6.762271e+11  2.529068e+09  6.787561e+11
24  2020Q1  6.636823e+11  4.724953e+08  6.641548e+11
25  2020Q2  6.840599e+11  3.724895e+08  6.844324e+11
26  2020Q3  7.902491e+11  3.177418e+08  7.905669e+11
27  2020Q4  5.465905e+11  2.355996e+09  5.489465e+11
28  2021Q1  8.193097e+11  3.536725e+08  8.196634e+11
29  2021Q2  1.073810e+12  3.688898e+08  1.074179e+12
30  2021Q3  7.979106e+11  3.471856e+08  7.982578e+11
31  2021Q4  8.562412e+11  1.867754e+09  8.581089e+11
32  2022Q1  9.289508e+11  4.103001e+08  9.293611e+11
33  2022Q2  1.156476e+12  3.887183e+08  1.156865e+12
34  2022Q3  1.191591e+12  4.187830e+08  1.192010e+12
35  2022Q4  1.211496e+12  1.846281e+09  1.213342e+12
36  2023Q1  9.413128e+11  4.152969e+08  9.417281e+11
37  2023Q2  1.047534e+12  4.192693e+08  1.047953e+12
38  2023Q3  8.357181e+11  3.843113e+08  8.361024e+11
39  2023Q4  1.072947e+12  1.697913e+09  1.074645e+12
40  2024Q1  9.762627e+11  4.295516e+08  9.766922e+11
41  2024Q2  1.207368e+12  4.616056e+08  1.207830e+12
42  2024Q3  1.155090e+12  4.416239e+08  1.155532e+12
43  2024Q4  7.714153e+11  7.829769e+08  7.721983e+11
44  2025Q1  1.021859e+12  2.565443e+08  1.022116e+12
45  2025Q2  1.111777e+12 -2.499738e+08  1.111527e+12

## 전체 데이터 합산

In [ ]:
from functools import reduce
import pandas as pd

# 모든 데이터프레임의 index 컬럼을 문자열로 변환
for df in [df_final,생산지수, 수출출하지수, 내수출하지수,생산능력지수, 가동률지수, df_quarter2,기업]:
    df['index'] = df['index'].astype(str)

# 리스트에 넣고 합치기
dfs = [df_final,생산지수, 수출출하지수, 내수출하지수,생산능력지수, 가동률지수, df_quarter2,기업]
df_merged = reduce(lambda left, right: pd.merge(left, right, on='index', how='outer'), dfs)

In [ ]:
df_merged
df_merged = df_merged[['index'] + [col for col in df_merged.columns if col != 'index']]

In [ ]:
df_merged

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,...,생산지수,수출출하지수,내수출하지수,생산능력지수,가동률지수,수출액,수입액,EBITDA,인건비,합산
0,2014Q1,83.000000,84.333333,85.000000,82.000000,87.666667,86.666667,100.333333,87.000000,96.666667,...,94.196,99.080,90.668,98.819,110.695,3.608000e+09,2.830004e+09,5.437342e+11,2.842432e+08,5.440185e+11
1,2014Q2,78.666667,87.000000,84.333333,86.000000,88.000000,87.000000,95.333333,88.666667,97.000000,...,94.913,102.612,91.032,99.304,114.809,3.872889e+09,3.116658e+09,5.617213e+11,2.922078e+08,5.620135e+11
2,2014Q3,72.000000,78.333333,85.333333,76.666667,86.333333,83.000000,99.333333,87.000000,93.000000,...,95.065,100.695,91.561,99.590,112.053,3.667544e+09,2.858808e+09,3.814502e+11,2.689605e+08,3.817191e+11
3,2014Q4,71.666667,89.333333,93.000000,85.666667,90.000000,85.666667,103.666667,89.000000,93.666667,...,98.759,103.981,95.727,100.075,111.644,3.854089e+09,3.166458e+09,5.230960e+11,1.205299e+09,5.243013e+11
4,2015Q1,75.666667,97.000000,98.333333,97.000000,98.000000,96.333333,104.000000,101.000000,95.333333,...,94.013,95.406,92.881,97.797,107.665,3.731872e+09,2.921134e+09,5.123197e+11,3.019108e+08,5.126216e+11
5,2015Q2,72.000000,90.333333,97.000000,85.333333,93.000000,88.000000,110.666667,93.333333,94.333333,...,92.414,95.217,92.169,98.192,106.787,3.934809e+09,2.941282e+09,5.705730e+11,2.773232e+08,5.708503e+11
6,2015Q3,62.666667,77.333333,85.333333,71.666667,79.666667,72.666667,105.666667,80.000000,90.333333,...,93.534,96.857,94.707,99.014,104.312,3.544786e+09,2.685010e+09,4.574159e+11,2.963735e+08,4.577122e+11
7,2015Q4,61.666667,77.000000,82.333333,72.000000,80.000000,74.000000,105.666667,77.666667,91.666667,...,90.416,90.927,92.263,99.441,101.056,3.618473e+09,2.674149e+09,3.114078e+11,1.355684e+09,3.127634e+11
8,2016Q1,56.333333,70.666667,77.666667,68.333333,76.333333,70.666667,106.333333,77.333333,89.333333,...,88.974,95.091,86.196,99.441,100.956,3.380938e+09,2.459957e+09,5.492057e+11,2.468207e+08,5.494525e+11
9,2016Q2,62.000000,76.333333,80.000000,73.000000,84.666667,78.333333,104.333333,86.666667,89.666667,...,90.234,91.842,91.643,99.310,102.030,3.526572e+09,2.625121e+09,5.412574e+11,2.840172e+08,5.415414e+11
10,2016Q3,65.000000,75.000000,71.000000,73.333333,80.666667,72.666667,105.000000,80.333333,91.333333,...,93.752,92.725,98.205,99.080,100.953,3.326284e+09,2.820241e+09,5.049225e+11,2.482402e+08,5.051708e+11
11,2016Q4,64.333333,79.000000,81.333333,77.666667,82.666667,79.333333,105.000000,83.000000,92.666667,...,101.309,99.254,104.828,99.244,101.302,3.763047e+09,2.930868e+09,8.038010e+11,1.457730e+09,8.052587e+11
12,2017Q1,78.666667,89.333333,87.333333,87.000000,91.666667,88.000000,104.333333,93.666667,95.000000,...,104.616,105.246,105.293,98.422,104.804,3.849085e+09,3.364433e+09,8.746092e+11,2.910922e+08,8.749002e+11
13,2017Q2,85.000000,92.666667,95.666667,86.333333,94.666667,89.000000,101.333333,97.000000,94.666667,...,109.811,111.049,111.452,98.619,107.141,4.391872e+09,3.806136e+09,1.328643e+12,2.959673e+08,1.328939e+12
14,2017Q3,79.000000,87.000000,86.666667,83.666667,88.000000,83.333333,102.333333,89.333333,93.333333,...,108.293,107.706,109.533,98.850,110.572,3.849519e+09,3.641462e+09,9.628408e+11,3.280118e+08,9.631688e+11
15,2017Q4,74.666667,84.333333,88.666667,77.000000,86.666667,83.000000,102.333333,85.666667,94.666667,...,105.308,106.287,106.438,99.277,107.433,3.960776e+09,3.390381e+09,9.502225e+11,1.939426e+09,9.521620e+11
16,2018Q1,75.666667,84.666667,88.000000,78.333333,87.000000,82.333333,103.333333,85.666667,93.333333,...,108.617,107.012,109.254,99.277,108.722,4.296321e+09,3.721968e+09,8.783616e+11,3.147275e+08,8.786763e+11
17,2018Q2,73.000000,82.333333,80.000000,82.000000,86.666667,85.000000,101.000000,88.333333,91.333333,...,105.961,109.536,103.405,100.066,108.826,4.540510e+09,3.589369e+09,9.061697e+11,2.970989e+08,9.064668e+11
18,2018Q3,67.333333,80.000000,81.333333,79.000000,84.333333,83.666667,100.666667,82.333333,89.333333,...,101.451,112.847,96.781,99.902,105.326,4.402445e+09,2.898997e+09,7.361397e+11,3.063240e+08,7.364460e+11
19,2018Q4,65.666667,77.666667,81.333333,75.000000,85.333333,79.333333,106.333333,84.666667,89.000000,...,98.694,109.441,93.841,100.756,104.540,4.522286e+09,2.935951e+09,6.039006e+11,2.473850e+09,6.063744e+11
20,2019Q1,66.666667,79.333333,79.333333,77.333333,82.666667,78.333333,105.333333,82.666667,92.333333,...,95.056,103.070,94.769,98.817,104.664,4.281451e+09,2.817324e+09,6.664142e+11,3.230076e+08,6.667372e+11
21,2019Q2,71.333333,79.666667,83.333333,79.333333,82.000000,81.333333,105.333333,83.333333,91.666667,...,94.922,102.282,93.779,98.554,107.952,4.511916e+09,3.072680e+09,8.515774e+11,3.201069e+08,8.518975e+11
22,2019Q3,66.333333,72.666667,77.666667,71.333333,76.000000,69.666667,104.666667,75.000000,89.333333,...,96.630,104.489,92.696,98.685,109.059,4.008520e+09,2.627314e+09,5.662552e+11,3.245174e+08,5.665797e+11
23,2019Q4,67.333333,75.333333,78.666667,74.666667,79.666667,75.333333,106.666667,77.333333,89.000000,...,100.636,105.751,100.402,99.310,106.996,4.631667e+09,2.665100e+09,6.762271e+11,2.529068e+09,6.787561e+11
24,2020Q1,64.666667,72.666667,76.333333,70.333333,78.000000,74.000000,104.000000,77.000000,91.666667,...,100.100,104.700,98.700,98.800,107.500,4.243064e+09,2.802389e+09,6.636823e+11,4.724953e+08,6.641548e+11
25,2020Q2,46.666667,53.666667,55.333333,57.000000,58.333333,50.000000,108.666667,57.000000,81.666667,...,93.900,89.400,97.300,99.200,92.400,3.809508e+09,3.257603e+09,6.840599e+11,3.724895e+08,6.844324e+11
26,2020Q3,60.000000,67.000000,64.000000,67.666667,62.666667,60.000000,106.666667,64.333333,82.000000,...,100.000,102.400,98.500,100.100,96.000,3.683412e+09,3.223906e+09,7.902491e+11,3.177418e+08,7.905669e+11
27,2020Q4,70.000000,73.666667,73.666667,73.000000,74.666667,71.666667,103.666667,79.666667,86.333333,...,106.000,104.000,104.900,101.900,104.200,4.145901e+09,3.135750e+09,5.465905e+11,2.355996e+09,5.489465e+11
28,2021Q1,82.000000,90.666667,90.666667,90.666667,91.666667,89.666667,99.666667,92.666667,96.000000,...,110.700,116.500,108.000,101.900,105.200,4.217805e+09,3.742197e+09,8.193097e+11,3.536725e+08,8.196634e+11
29,2021Q2,93.000000,107.666667,109.000000,103.333333,104.333333,107.000000,96.333333,108.000000,94.666667,...,114.200,121.700,110.600,101.500,107.000,4.552451e+09,4.127053e+09,1.073810e+12,3.688898e+08,1.074179e+12
30,2021Q3,89.666667,99.000000,101.666667,96.000000,100.000000,101.666667,96.333333,104.333333,95.666667,...,110.400,112.200,107.500,100.500,106.000,4.234552e+09,3.389900e+09,7.979106e+11,3.471856e+08,7.982578e+11
31,2021Q4,91.333333,105.000000,101.666667,103.666667,104.000000,106.333333,101.666667,105.666667,98.000000,...,113.300,117.000,106.400,99.900,111.700,4.644591e+09,3.624880e+09,8.562412e+11,1.867754e+09,8.581089e+11
32,2022Q1,92.000000,102.666667,104.000000,100.666667,101.666667,101.000000,97.333333,102.333333,95.333333,...,108.000,111.000,105.800,98.500,108.300,4.524852e+09,3.518983e+09,9.289508e+11,4.103001e+08,9.293611e+11
33,2022Q2,87.000000,97.000000,92.666667,97.333333,96.666667,96.000000,97.000000,97.333333,94.666667,...,108.400,109.900,104.700,97.000,109.200,4.469880e+09,3.758006e+09,1.156476e+12,3.887183e+08,1.156865e+12
34,2022Q3,86.000000,101.333333,97.666667,98.000000,95.000000,93.666667,100.666667,96.000000,94.333333,...,118.300,120.800,114.300,95.100,117.200,4.314190e+09,3.626438e+09,1.191591e+12,4.187830e+08,1.192010e+12
35,2022Q4,78.000000,93.000000,96.000000,90.333333,91.000000,86.666667,107.000000,91.666667,91.333333,...,118.100,113.000,115.500,95.500,120.000,4.377304e+09,3.566650e+09,1.211496e+12,1.846281e+09,1.213342e+12
36,2023Q1,63.666667,77.333333,79.333333,78.333333,80.333333,76.333333,104.666667,79.333333,88.666667,...,108.000,113.000,102.600,94.600,117.500,4.402053e+09,3.535824e+09,9.413128e+11,4.152969e+08,9.417281e+11
37,2023Q2,73.666667,84.000000,85.333333,80.333333,81.666667,80.666667,105.000000,82.000000,93.666667,...,104.100,113.100,101.500,95.900,115.200,4.549311e+09,3.763172e+09,1.047534e+12,4.192693e+08,1.047953e+12
38,2023Q3,68.666667,74.333333,73.000000,75.000000,77.666667,72.666667,105.333333,78.000000,90.000000,...,102.700,108.200,102.200,96.600,109.800,4.402048e+09,3.009380e+09,8.357181e+11,3.843113e+08,8.361024e+11
39,2023Q4,69.666667,78.000000,78.000000,75.666667,77.333333,74.666667,105.666667,81.000000,88.666667,...,106.100,103.200,106.600,97.400,107.400,4.937019e+09,3.126200e+09,1.072947e+12,1.697913e+09,1.074645e+12
40,2024Q1,73.000000,84.000000,86.333333,78.666667,79.333333,74.333333,100.666667,84.000000,91.000000,...,101.800,99.800,104.700,94.800,106.900,4.541785e+09,3.387412e+09,9.762627e+11,4.295516e+08,9.766922e+11
41,2024Q2,70.666667,80.000000,87.666667,76.666667,84.333333,75.333333,100.000000,86.000000,91.000000,...,101.800,102.700,104.700,94.800,106.000,4.680269e+09,3.449380e+09,1.207368e+12,4.616056e+08,1.207830e+12
42,2024Q3,72.333333,82.333333,83.333333,79.000000,82.666667,78.333333,103.000000,83.666667,90.000000,...,103.000,102.500,106.800,94.700,102.800,4.565025e+09,3.346072e+09,1.155090e+12,4.416239e+08,1.155532e+12
43,2024Q4,68.000000,79.333333,86.000000,73.000000,76.000000,70.666667,99.666667,78.000000,89.000000,...,107.900,102.200,108.400,94.500,102.000,4.428418e+09,3.545513e+09,7.714153e+11,7.829769e+08,7.721983e+11
44,2025Q1,63.666667,71.333333,77.000000,75.000000,74.666667,66.666667,99.333333,74.333333,87.333333,...,101.800,102.400,103.600,91.500,105.700,4.152466e+09,3.581347e+09,1.021859e+12,2.565443e+08,1.022116e+12
45,2025Q2,68.333333,78.000000,82.333333,74.000000,81.333333,76.333333,100.666667,83.666667,89.666667,...,101.200,110.600,99.100,90.400,106.900,4.548813e+09,3.816321e+09,1.111777e+12,-2.499738e+08,1.111527e+12

In [ ]:
df_merged.to_csv('기계장비.csv')

# 데이터QoQ반환

In [ ]:
import pandas as pd

# df는 위의 데이터프레임
df_qoq = df_merged.copy()

# 분기 순서대로 정렬 (혹시 index가 문자열일 경우를 대비)
df_qoq = df_qoq.sort_values('index')

# 수치형 컬럼만 선택 (index 제외)
num_cols = df_qoq.select_dtypes(include=['number']).columns

# 전분기 대비 증감률 (%) 계산
df_qoq[num_cols] = df_qoq[num_cols].pct_change() * 100

# 결과 확인
print(df_qoq.head())

    index   업황실적BSI    매출실적BSI   수출실적BSI  내수판매실적BSI   생산실적BSI  신규수주실적BSI  \
0  2014Q1       NaN        NaN       NaN        NaN       NaN        NaN
1  2014Q2 -5.220884   3.162055 -0.784314   4.878049  0.380228   0.384615
2  2014Q3 -8.474576  -9.961686  1.185771 -10.852713 -1.893939  -4.597701
3  2014Q4 -0.462963  14.042553  8.984375  11.739130  4.247104   3.212851
4  2015Q1  5.581395   8.582090  5.734767  13.229572  8.888889  12.451362

   제품재고실적BSI   가동률실적BSI  설비투자실적BSI   ...      생산지수    수출출하지수    내수출하지수  \
0        NaN        NaN         NaN  ...       NaN       NaN       NaN
1  -4.983389   1.915709    0.344828  ...  0.761179  3.564796  0.401465
2   4.195804  -1.879699   -4.123711  ...  0.160147 -1.868203  0.581114
3   4.362416   2.298851    0.716846  ...  3.885762  3.263320  4.549972
4   0.321543  13.483146    1.779359  ... -4.805638 -8.246699 -2.973038

     생산능력지수     가동률지수       수출액        수입액     EBITDA         인건비         합산
0       NaN       NaN       NaN        NaN        NaN         NaN        NaN
1  0.490796  3.716518  7.341702  10.129100   3.308062    2.802059   3.307797
2  0.288005 -2.400509 -5.302108  -8.273272 -32.092628   -7.955746 -32.080079
3  0.486997 -0.365006  5.086373  10.761460  37.133500  348.132312  37.352631
4 -2.276293 -3.564007 -3.171101  -7.747584  -2.060086  -74.951371  -2.227654

[5 rows x 26 columns]

In [ ]:
df_qoq
df_qoq = df_qoq.drop(index=[0, 1, 2,3])

In [ ]:
df_qoq.isnull().sum()

index         0
업황실적BSI       0
매출실적BSI       0
수출실적BSI       0
내수판매실적BSI     0
생산실적BSI       0
신규수주실적BSI     0
제품재고실적BSI     0
가동률실적BSI      0
설비투자실적BSI     0
채산성실적BSI      0
자금사정실적BSI     0
인력사정실적BSI     0
원자재구입가격BSI    0
ppi           0
gdp           0
생산지수          0
수출출하지수        0
내수출하지수        0
생산능력지수        0
가동률지수         0
수출액           0
수입액           0
EBITDA        0
인건비           0
합산            0
dtype: int64

In [ ]:
df_qoq.to_csv('기계장비qoq.csv')

#데이터YoY변환

In [ ]:
import pandas as pd

# df_merged는 원본 데이터프레임
df_yoy = df_merged.copy()

# 분기 순서대로 정렬
df_yoy = df_yoy.sort_values('index')

# 수치형 컬럼만 선택 (index 제외)
num_cols = df_yoy.select_dtypes(include=['number']).columns

# 전년 동분기 대비 증감률 (%) 계산 (4분기 차이)
df_yoy[num_cols] = df_yoy[num_cols].pct_change(periods=4) * 100

# 결과 확인
print(df_yoy.head(10))

    index    업황실적BSI    매출실적BSI    수출실적BSI  내수판매실적BSI    생산실적BSI  신규수주실적BSI  \
0  2014Q1        NaN        NaN        NaN        NaN        NaN        NaN
1  2014Q2        NaN        NaN        NaN        NaN        NaN        NaN
2  2014Q3        NaN        NaN        NaN        NaN        NaN        NaN
3  2014Q4        NaN        NaN        NaN        NaN        NaN        NaN
4  2015Q1  -8.835341  15.019763  15.686275  18.292683  11.787072  11.153846
5  2015Q2  -8.474576   3.831418  15.019763  -0.775194   5.681818   1.149425
6  2015Q3 -12.962963  -1.276596   0.000000  -6.521739  -7.722008 -12.449799
7  2015Q4 -13.953488 -13.805970 -11.469534 -15.953307 -11.111111 -13.618677
8  2016Q1 -25.550661 -27.147766 -21.016949 -29.553265 -22.108844 -26.643599
9  2016Q2 -13.888889 -15.498155 -17.525773 -14.453125  -8.960573 -10.984848

   제품재고실적BSI   가동률실적BSI  설비투자실적BSI   ...      생산지수     수출출하지수    내수출하지수  \
0        NaN        NaN         NaN  ...       NaN        NaN       NaN
1        NaN        NaN         NaN  ...       NaN        NaN       NaN
2        NaN        NaN         NaN  ...       NaN        NaN       NaN
3        NaN        NaN         NaN  ...       NaN        NaN       NaN
4   3.654485  16.091954   -1.379310  ... -0.194276  -3.708115  2.440773
5  16.083916   5.263158   -2.749141  ... -2.632938  -7.206759  1.249011
6   6.375839  -8.045977   -2.867384  ... -1.610477  -3.811510  3.435961
7   1.929260 -12.734082   -2.135231  ... -8.447838 -12.554217 -3.618624
8   2.243590 -23.432343   -6.293706  ... -5.359897  -0.330168 -7.197382
9  -5.722892  -7.142857   -4.946996  ... -2.358950  -3.544535 -0.570691

     생산능력지수     가동률지수        수출액        수입액     EBITDA        인건비         합산
0       NaN       NaN        NaN        NaN        NaN        NaN        NaN
1       NaN       NaN        NaN        NaN        NaN        NaN        NaN
2       NaN       NaN        NaN        NaN        NaN        NaN        NaN
3       NaN       NaN        NaN        NaN        NaN        NaN        NaN
4 -1.034214 -2.737251   3.433255   3.220133  -5.777546   6.215699  -5.771280
5 -1.119794 -6.987257   1.598820  -5.627045   1.575810  -5.093831   1.572343
6 -0.578371 -6.908338  -3.347138  -6.079409  19.914974  10.192200  19.908123
7 -0.633525 -9.483716  -6.113400 -15.547627 -40.468332  12.476974 -40.346618
8  1.681033 -6.231366  -9.403692 -15.787610   7.199788 -18.247159   7.184801
9  1.138586 -4.454662 -10.375029 -10.749090  -5.137922   2.413780  -5.134253

[10 rows x 26 columns]

In [ ]:
df_yoy=df_yoy.dropna()

In [ ]:
df_yoy

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,...,생산지수,수출출하지수,내수출하지수,생산능력지수,가동률지수,수출액,수입액,EBITDA,인건비,합산
4,2015Q1,-8.835341,15.019763,15.686275,18.292683,11.787072,11.153846,3.654485,16.091954,-1.379310,...,-0.194276,-3.708115,2.440773,-1.034214,-2.737251,3.433255,3.220133,-5.777546,6.215699,-5.771280
5,2015Q2,-8.474576,3.831418,15.019763,-0.775194,5.681818,1.149425,16.083916,5.263158,-2.749141,...,-2.632938,-7.206759,1.249011,-1.119794,-6.987257,1.598820,-5.627045,1.575810,-5.093831,1.572343
6,2015Q3,-12.962963,-1.276596,0.000000,-6.521739,-7.722008,-12.449799,6.375839,-8.045977,-2.867384,...,-1.610477,-3.811510,3.435961,-0.578371,-6.908338,-3.347138,-6.079409,19.914974,10.192200,19.908123
7,2015Q4,-13.953488,-13.805970,-11.469534,-15.953307,-11.111111,-13.618677,1.929260,-12.734082,-2.135231,...,-8.447838,-12.554217,-3.618624,-0.633525,-9.483716,-6.113400,-15.547627,-40.468332,12.476974,-40.346618
8,2016Q1,-25.550661,-27.147766,-21.016949,-29.553265,-22.108844,-26.643599,2.243590,-23.432343,-6.293706,...,-5.359897,-0.330168,-7.197382,1.681033,-6.231366,-9.403692,-15.787610,7.199788,-18.247159,7.184801
9,2016Q2,-13.888889,-15.498155,-17.525773,-14.453125,-8.960573,-10.984848,-5.722892,-7.142857,-4.946996,...,-2.358950,-3.544535,-0.570691,1.138586,-4.454662,-10.375029,-10.749090,-5.137922,2.413780,-5.134253
10,2016Q3,3.723404,-3.017241,-16.796875,2.325581,1.255230,0.000000,-0.630915,0.416667,1.107011,...,0.233070,-4.266083,3.693497,0.066657,-3.220147,-6.164043,5.036533,10.385881,-16.240744,10.368640
11,2016Q4,4.324324,2.597403,-1.214575,7.870370,3.333333,7.207207,-0.630915,6.866953,1.090909,...,12.047646,9.157896,13.618677,-0.198107,0.243429,3.995439,9.600032,158.118481,7.527316,157.465738
12,2017Q1,39.644970,26.415094,12.446352,27.317073,20.087336,24.528302,-1.880878,21.120690,6.343284,...,17.580417,10.679244,22.155320,-1.024728,3.811561,13.846652,36.767962,59.249840,17.936700,59.231282
13,2017Q2,37.096774,21.397380,19.583333,18.264840,11.811024,13.617021,-2.875399,11.923077,5.576208,...,21.695813,20.913090,21.615399,-0.695801,5.009311,24.536583,44.988950,145.473398,4.207509,145.399310
14,2017Q3,21.538462,16.000000,22.065728,14.090909,9.090909,14.678899,-2.539683,11.203320,2.189781,...,15.510069,16.156376,11.535054,-0.232136,9.528196,15.730321,29.118810,90.690786,32.134821,90.662012
15,2017Q4,16.062176,6.751055,9.016393,-0.858369,4.838710,4.621849,-2.539683,3.212851,2.158273,...,3.947329,7.085861,1.535849,0.033251,6.052200,5.254499,15.678410,18.216148,33.044223,18.242991
16,2018Q1,-3.813559,-5.223881,0.763359,-9.961686,-5.090909,-6.439394,-0.958466,-8.540925,-1.754386,...,3.824463,1.677974,3.761884,0.868708,3.738407,11.619269,10.626919,0.429042,8.119531,0.431600
17,2018Q2,-14.117647,-11.151079,-16.376307,-5.019305,-8.450704,-4.494382,-0.328947,-8.934708,-3.521127,...,-3.506024,-1.362462,-7.220149,1.467263,1.572694,3.384385,-5.695188,-31.797345,0.382338,-31.790178
18,2018Q3,-14.767932,-8.045977,-6.153846,-5.577689,-4.166667,0.400000,-1.628664,-7.835821,-4.285714,...,-6.318045,4.773179,-11.642154,1.064239,-4.744420,14.363496,-20.389187,-23.545024,-6.611907,-23.539257
19,2018Q4,-12.053571,-7.905138,-8.270677,-2.597403,-1.538462,-4.417671,3.908795,-1.167315,-5.985915,...,-6.280624,2.967437,-11.835059,1.489771,-2.692841,14.176767,-13.403513,-36.446407,27.555780,-36.316044
20,2019Q1,-11.894273,-6.299213,-9.848485,-1.276596,-4.980843,-4.858300,1.935484,-3.501946,-1.071429,...,-12.485154,-3.683699,-13.258096,-0.463350,-3.732455,-0.346114,-24.305519,-24.129854,2.630883,-24.120268
21,2019Q2,-2.283105,-3.238866,4.166667,-3.252033,-5.384615,-4.313725,4.290429,-5.660377,0.364964,...,-10.417984,-6.622480,-9.309028,-1.511003,-0.803117,-0.629741,-14.394985,-6.024508,7.744227,-6.019996
22,2019Q3,-1.485149,-9.166667,-4.508197,-9.704641,-9.881423,-16.733068,3.973510,-8.906883,0.000000,...,-4.752048,-7.406488,-4.220870,-1.218194,3.544234,-8.947862,-9.371628,-23.077751,5.939288,-23.065681
23,2019Q4,2.538071,-3.004292,-3.278689,-0.444444,-6.640625,-5.042017,0.313480,-8.661417,0.000000,...,1.967698,-3.371680,6.991613,-1.435150,2.349340,2.418701,-9.225341,11.976560,2.232076,11.936805
24,2020Q1,-3.000000,-8.403361,-3.781513,-9.051724,-5.645161,-5.531915,-1.265823,-6.854839,-0.722022,...,5.306346,1.581450,4.147981,-0.017204,2.709623,-0.896581,-0.530128,-0.409947,46.279933,-0.387328
25,2020Q2,-34.579439,-32.635983,-33.600000,-28.151261,-28.861789,-38.524590,3.164557,-31.600000,-10.909091,...,-1.076673,-12.594591,3.754572,0.655478,-14.406403,-15.567843,6.018289,-19.671436,16.364107,-19.657895
26,2020Q3,-9.547739,-7.798165,-17.596567,-5.140187,-17.543860,-13.875598,1.910828,-14.222222,-8.208955,...,3.487530,-1.999254,6.261327,1.433855,-11.974252,-8.110442,22.707310,39.557064,-2.087914,39.533211
27,2020Q4,3.960396,-2.212389,-6.355932,-2.232143,-6.276151,-4.867257,-2.812500,3.017241,-2.996255,...,5.330101,-1.655776,4.479990,2.607995,-2.613182,-10.487931,17.659746,-19.170563,-6.843316,-19.124631
28,2021Q1,26.804124,24.770642,18.777293,28.909953,17.521368,21.171171,-4.166667,20.346320,4.727273,...,10.589411,11.270296,9.422492,3.137652,-2.139535,-0.595309,33.535957,23.449085,-25.147934,23.414512
29,2021Q2,99.285714,100.621118,96.987952,81.286550,78.857143,114.000000,-11.349693,89.473684,15.918367,...,21.618743,36.129754,13.669065,2.318548,15.800866,19.502330,26.689899,56.976057,-0.966392,56.944523
30,2021Q3,49.444444,47.761194,58.854167,41.871921,59.574468,69.444444,-9.687500,62.176166,16.666667,...,10.400000,9.570312,9.137056,0.399600,10.416667,14.962758,5.148825,0.969503,9.266585,0.972837
31,2021Q4,30.476190,42.533937,38.009050,42.009132,39.285714,48.372093,-1.929260,32.635983,13.513514,...,6.886792,12.500000,1.429933,-1.962709,7.197697,12.028506,15.598508,56.651300,-20.723368,56.319219
32,2022Q1,12.195122,13.235294,14.705882,11.029412,10.909091,12.639405,-2.341137,10.431655,-0.694444,...,-2.439024,-4.721030,-2.037037,-3.336605,2.946768,7.279787,-5.964793,13.382131,16.011319,13.383265
33,2022Q2,-6.451613,-9.907121,-14.984709,-5.806452,-7.348243,-10.280374,0.692042,-9.876543,0.000000,...,-5.078809,-9.695974,-5.334539,-4.433498,2.056075,-1.813784,-8.942160,7.698391,5.375195,7.697593
34,2022Q3,-4.089219,2.356902,-3.934426,2.083333,-5.000000,-7.868852,4.498270,-7.987220,-1.393728,...,7.155797,7.664884,6.325581,-5.373134,10.566038,1.880694,6.977723,49.338918,20.622232,49.326429
35,2022Q4,-14.598540,-11.428571,-5.573770,-12.861736,-12.500000,-18.495298,5.245902,-13.249211,-6.802721,...,4.236540,-3.418803,8.552632,-4.404404,7.430618,-5.754790,-1.606402,41.490063,-1.149665,41.397254
36,2023Q1,-30.797101,-24.675325,-23.717949,-22.185430,-20.983607,-24.422442,7.534247,-22.475570,-6.993007,...,0.000000,1.801802,-3.024575,-3.959391,8.494922,-2.713869,0.478580,1.330749,1.217839,1.330699
37,2023Q2,-15.325670,-13.402062,-7.913669,-17.465753,-15.517241,-15.972222,8.247423,-15.753425,-1.056338,...,-3.966790,2.911738,-3.056351,-1.134021,5.494505,1.777040,0.137482,-9.420213,7.859415,-9.414407
38,2023Q3,-20.155039,-26.644737,-25.255973,-23.469388,-18.245614,-22.419929,4.635762,-18.750000,-4.593640,...,-13.186813,-10.430464,-10.586177,1.577287,-6.313993,2.036471,-17.015542,-29.865364,-8.231401,-29.857764
39,2023Q4,-10.683761,-16.129032,-18.750000,-16.236162,-15.018315,-13.846154,-1.246106,-11.636364,-2.919708,...,-10.160881,-8.672566,-7.705628,1.989529,-10.500000,12.786729,-12.349126,-11.436232,-8.036072,-11.431058
40,2024Q1,14.659686,8.620690,8.823529,0.425532,-1.244813,-2.620087,-3.821656,5.882353,2.631579,...,-5.740741,-11.681416,2.046784,0.211416,-9.021277,3.174239,-4.197391,3.712885,3.432400,3.712761
41,2024Q2,-4.072398,-4.761905,2.734375,-4.564315,3.265306,-6.611570,-4.761905,4.878049,-2.846975,...,-2.209414,-9.195402,3.152709,-1.147028,-7.986111,2.878634,-8.338498,15.258167,10.097641,15.256102
42,2024Q3,5.339806,10.762332,14.155251,5.333333,6.437768,7.798165,-2.215190,7.264957,0.000000,...,0.292113,-5.268022,4.500978,-1.966874,-6.375228,3.702317,11.188099,38.215262,14.913073,38.204551
43,2024Q4,-2.392344,1.709402,10.256410,-3.524229,-1.724138,-5.357143,-5.678233,-3.703704,0.375940,...,1.696513,-0.968992,1.688555,-2.977413,-5.027933,-10.301769,13.412878,-28.103107,-53.885921,-28.143843
44,2025Q1,-12.785388,-15.079365,-10.810811,-4.661017,-5.882353,-10.313901,-1.324503,-11.507937,-4.029304,...,0.000000,2.605210,-1.050621,-3.481013,-1.122544,-8.571926,5.725194,4.670541,-40.276264,4.650773
45,2025Q2,-3.301887,-2.500000,-6.083650,-3.478261,-3.557312,1.327434,0.666667,-2.713178,-1.465201,...,-0.589391,7.692308,-5.348615,-4.641350,0.849057,-2.808740,10.637881,-7.917318,-154.153118,-7.973206

In [ ]:
df_yoy.to_csv("기계장비yoy.csv")

#상관계수 보기(qoq)

In [ ]:
qoq = pd.read_csv('기계장비qoq.csv')
qoq = qoq.drop(columns=["Unnamed: 0"])

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# GDP_QoQ 기준
target = 'gdp'

In [ ]:
# 수치형 컬럼만 선택
num_cols = qoq.select_dtypes(include=['number']).columns

# GDP 기준 상관계수 계산
corr = qoq[num_cols].corr()[target].sort_values(ascending=False)

print("📊 GDP 대비 단순 상관계수")
print(corr)

📊 GDP 대비 단순 상관계수
gdp           1.000000
생산지수          0.718497
내수출하지수        0.708106
매출실적BSI       0.656270
업황실적BSI       0.646005
수출실적BSI       0.614636
생산실적BSI       0.606203
신규수주실적BSI     0.586834
가동률실적BSI      0.576615
내수판매실적BSI     0.565992
수출액           0.475486
수출출하지수        0.472829
자금사정실적BSI     0.467228
설비투자실적BSI     0.416056
가동률지수         0.409211
채산성실적BSI      0.308999
수입액           0.255117
원자재구입가격BSI    0.242673
합산            0.213504
EBITDA        0.212040
인건비           0.114037
생산능력지수        0.040563
ppi           0.008140
제품재고실적BSI    -0.208703
인력사정실적BSI    -0.526901
Name: gdp, dtype: float64

In [ ]:
# df2 사본
df2 = qoq.copy()

# target 및 feature 지정
target_col = 'gdp'
feature_cols = [col for col in df2.columns if col not in ['index', target_col]]

# 결과 저장용 데이터프레임
corr_df = pd.DataFrame(columns=['Feature', 'Lag', 'Correlation'])

# lag 1~4 생성 및 상관계수 계산
for col in feature_cols:
    for lag in range(1, 5):  # lag 1~4
        lag_col_name = f"{col}_lag{lag}"
        df2[lag_col_name] = df2[col].shift(lag)  # 실제 데이터에 lag 컬럼 추가
        corr = df2[target_col].corr(df2[lag_col_name])  # 상관계수 계산
        corr_df = pd.concat(
            [corr_df, pd.DataFrame({'Feature': [col], 'Lag': [lag], 'Correlation': [corr]})],
            ignore_index=True
        )

# 상관계수 높은 순으로 정렬
corr_df.sort_values(by='Correlation', ascending=False, inplace=True)
corr_df.reset_index(drop=True, inplace=True)

corr_df

/tmp/ipython-input-1052179002.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  corr_df = pd.concat(

       Feature Lag  Correlation
0       생산능력지수   4     0.355392
1       수출출하지수   1     0.345073
2   원자재구입가격BSI   1     0.327196
3    내수판매실적BSI   1     0.325498
4         생산지수   1     0.322110
..         ...  ..          ...
91    채산성실적BSI   2    -0.195530
92   내수판매실적BSI   4    -0.210515
93     수출실적BSI   4    -0.218137
94   제품재고실적BSI   2    -0.234606
95         ppi   4    -0.332035

[96 rows x 3 columns]

In [ ]:
corr_df.to_csv('k.csv')

In [ ]:
df2

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,...,EBITDA_lag3,EBITDA_lag4,인건비_lag1,인건비_lag2,인건비_lag3,인건비_lag4,합산_lag1,합산_lag2,합산_lag3,합산_lag4
0,2015Q1,5.581395,8.582090,5.734767,13.229572,8.888889,12.451362,0.321543,13.483146,1.779359,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015Q2,-4.845815,-6.872852,-1.355932,-12.027491,-5.102041,-8.650519,6.410256,-7.590759,-1.048951,...,NaN,NaN,-74.951371,NaN,NaN,NaN,-2.227654,NaN,NaN,NaN
2,2015Q3,-12.962963,-14.391144,-12.027491,-16.015625,-14.336918,-17.424242,-4.518072,-14.285714,-4.240283,...,NaN,NaN,-8.143997,-74.951371,NaN,NaN,11.358989,-2.227654,NaN,NaN
3,2015Q4,-1.595745,-0.431034,-3.515625,0.465116,0.418410,1.834862,0.000000,-2.916667,1.476015,...,-2.060086,NaN,6.869332,-8.143997,-74.951371,NaN,-19.819214,11.358989,-2.227654,NaN
4,2016Q1,-8.648649,-8.225108,-5.668016,-5.092593,-4.583333,-4.504505,0.630915,-0.429185,-2.545455,...,11.370482,-2.060086,357.424088,6.869332,-8.143997,-74.951371,-31.668108,-19.819214,11.358989,-2.227654
5,2016Q2,10.059172,8.018868,3.004292,6.829268,10.917031,10.849057,-1.880878,12.068966,0.373134,...,-19.832186,11.370482,-81.793637,357.424088,6.869332,-8.143997,75.676703,-31.668108,-19.819214,11.358989
6,2016Q3,4.838710,-1.746725,-11.250000,0.456621,-4.724409,-7.234043,0.638978,-7.307692,1.858736,...,-31.920212,-19.832186,15.070257,-81.793637,357.424088,6.869332,-1.439817,75.676703,-31.668108,-19.819214
7,2016Q4,-1.025641,5.333333,14.553991,5.909091,2.479339,9.174312,0.000000,3.319502,1.459854,...,76.362235,-31.920212,-12.596764,15.070257,-81.793637,357.424088,-6.716128,-1.439817,75.676703,-31.668108
8,2017Q1,22.279793,13.080169,7.377049,12.017167,10.887097,10.924370,-0.634921,12.851406,2.517986,...,-1.447237,76.362235,487.225659,-12.596764,15.070257,-81.793637,59.403261,-6.716128,-1.439817,75.676703
9,2017Q2,8.050847,3.731343,9.541985,-0.766284,3.272727,1.136364,-2.875399,3.558719,-0.350877,...,-6.713042,-1.447237,-80.031136,487.225659,-12.596764,15.070257,8.648346,59.403261,-6.716128,-1.439817
10,2017Q3,-7.058824,-6.115108,-9.407666,-3.088803,-7.042254,-6.367041,0.986842,-7.903780,-1.408451,...,59.192927,-6.713042,1.674753,-80.031136,487.225659,-12.596764,51.896039,8.648346,59.403261,-6.716128
11,2017Q4,-5.485232,-3.065134,2.307692,-7.968127,-1.515152,-0.400000,0.000000,-4.104478,1.428571,...,8.809170,59.192927,10.827052,1.674753,-80.031136,487.225659,-27.523468,51.896039,8.648346,59.403261
12,2018Q1,1.339286,0.395257,-0.751880,1.731602,0.384615,-0.803213,0.977199,0.000000,-1.408451,...,51.912754,8.809170,491.267167,10.827052,1.674753,-80.031136,-1.142770,-27.523468,51.896039,8.648346
13,2018Q2,-3.524229,-2.755906,-9.090909,4.680851,-0.383142,3.238866,-2.258065,3.112840,-2.142857,...,-27.532011,51.912754,-83.772131,491.267167,10.827052,1.674753,-7.717767,-1.142770,-27.523468,51.896039
14,2018Q3,-7.762557,-2.834008,1.666667,-3.658537,-2.692308,-1.568627,-0.330033,-6.792453,-2.189781,...,-1.310520,-27.532011,-5.601242,-83.772131,491.267167,10.827052,3.162766,-7.717767,-1.142770,-27.523468
15,2018Q4,-2.475248,-2.916667,0.000000,-5.063291,1.185771,-5.179283,5.629139,2.834008,-0.373134,...,-7.562538,-1.310520,3.105060,-5.601242,-83.772131,491.267167,-18.756429,3.162766,-7.717767,-1.142770
16,2019Q1,1.522843,2.145923,-2.459016,3.111111,-3.125000,-1.260504,-0.940439,-2.362205,3.745318,...,3.165906,-7.562538,707.592723,3.105060,-5.601242,-83.772131,-17.662067,-18.756429,3.162766,-7.717767
17,2019Q2,7.000000,0.420168,5.042017,2.586207,-0.806452,3.829787,0.000000,0.806452,-0.722022,...,-18.763597,3.165906,-86.943120,707.592723,3.105060,-5.601242,9.954712,-17.662067,-18.756429,3.162766
18,2019Q3,-7.009346,-8.786611,-6.800000,-10.084034,-7.317073,-14.344262,-0.632911,-10.000000,-2.545455,...,-17.963862,-18.763597,-0.898045,-86.943120,707.592723,3.105060,27.771106,9.954712,-17.662067,-18.756429
19,2019Q4,1.507538,3.669725,1.287554,4.672897,4.824561,8.133971,1.910828,3.111111,-0.373134,...,10.351649,-17.963862,1.377837,-0.898045,-86.943120,707.592723,-33.492036,27.771106,9.954712,-17.662067
20,2020Q1,-3.960396,-3.539823,-2.966102,-5.803571,-2.092050,-1.769912,-2.500000,-0.431034,2.996255,...,27.785001,10.351649,679.332034,1.377837,-0.898045,-86.943120,19.798879,-33.492036,27.771106,9.954712
21,2020Q2,-27.835052,-26.146789,-27.510917,-18.957346,-25.213675,-32.432432,4.487179,-25.974026,-10.909091,...,-33.505143,27.785001,-81.317414,679.332034,1.377837,-0.898045,-2.151194,19.798879,-33.492036,27.771106
22,2020Q3,28.571429,24.844720,15.662651,18.713450,7.428571,20.000000,-1.840491,12.865497,0.408163,...,19.420904,-33.505143,-21.165465,-81.317414,679.332034,1.377837,3.053149,-2.151194,19.798879,-33.492036
23,2020Q4,16.666667,9.950249,15.104167,7.881773,19.148936,19.444444,-2.812500,23.834197,5.284553,...,-1.855115,19.420904,-14.697790,-21.165465,-81.317414,679.332034,15.506929,3.053149,-2.151194,19.798879
24,2021Q1,17.142857,23.076923,23.076923,24.200913,22.767857,25.116279,-3.858521,16.317992,11.196911,...,3.070391,-1.855115,641.481370,-14.697790,-21.165465,-81.317414,-30.562922,15.506929,3.053149,-2.151194
25,2021Q2,13.414634,18.750000,20.220588,13.970588,13.818182,19.330855,-3.344482,16.546763,-1.388889,...,15.523377,3.070391,-84.988408,641.481370,-14.697790,-21.165465,49.315703,-30.562922,15.506929,3.053149
26,2021Q3,-3.584229,-8.049536,-6.727829,-7.096774,-4.153355,-4.984424,0.000000,-3.395062,1.056338,...,-30.833136,15.523377,4.302645,-84.988408,641.481370,-14.697790,31.051260,49.315703,-30.562922,15.506929
27,2021Q4,1.858736,6.060606,0.000000,7.986111,4.000000,4.590164,5.536332,1.277955,2.439024,...,49.894601,-30.833136,-5.883655,4.302645,-84.988408,641.481370,-25.686719,31.051260,49.315703,-30.562922
28,2022Q1,0.729927,-2.222222,2.295082,-2.893891,-2.243590,-5.015674,-4.262295,-3.154574,-2.721088,...,31.062807,49.894601,437.970012,-5.883655,4.302645,-84.988408,7.497721,-25.686719,31.051260,49.315703
29,2022Q2,-5.434783,-5.519481,-10.897436,-3.311258,-4.918033,-4.950495,-0.342466,-4.885993,-0.699301,...,-25.693522,31.062807,-78.032435,437.970012,-5.883655,4.302645,8.303394,7.497721,-25.686719,31.051260
30,2022Q3,-1.149425,4.467354,5.395683,0.684932,-1.724138,-2.430556,3.780069,-1.369863,-0.352113,...,7.310414,-25.693522,-5.260007,-78.032435,437.970012,-5.883655,24.479616,8.303394,7.497721,-25.686719
31,2022Q4,-9.302326,-8.223684,-1.706485,-7.823129,-4.210526,-7.473310,6.291391,-4.513889,-3.180212,...,8.491722,7.310414,7.734307,-5.260007,-78.032435,437.970012,3.037927,24.479616,8.303394,7.497721
32,2023Q1,-18.376068,-16.845878,-17.361111,-13.284133,-11.721612,-11.923077,-2.180685,-13.454545,-2.919708,...,24.492752,8.491722,340.868279,7.734307,-5.260007,-78.032435,1.789634,3.037927,24.479616,8.303394
33,2023Q2,15.706806,8.620690,7.563025,2.553191,1.659751,5.676856,0.318471,3.361345,5.639098,...,3.036349,24.492752,-77.506303,340.868279,7.734307,-5.260007,-22.385631,1.789634,3.037927,24.479616
34,2023Q3,-6.787330,-11.507937,-14.453125,-6.639004,-4.897959,-9.917355,0.317460,-4.878049,-3.914591,...,1.670465,3.036349,0.956514,-77.506303,340.868279,7.734307,11.279800,-22.385631,1.789634,3.037927
35,2023Q4,1.456311,4.932735,6.849315,0.888889,-0.429185,2.752294,0.316456,3.846154,-1.481481,...,-22.301629,1.670465,-8.337846,0.956514,-77.506303,340.868279,-20.215673,11.279800,-22.385631,1.789634
36,2024Q1,4.784689,7.692308,10.683761,3.964758,2.586207,-0.446429,-4.731861,3.703704,2.631579,...,11.284355,-22.301629,341.806666,-8.337846,0.956514,-77.506303,28.530264,-20.215673,11.279800,-22.385631
37,2024Q2,-3.196347,-4.761905,1.544402,-2.542373,6.302521,1.345291,-0.662252,2.380952,0.000000,...,-20.220427,11.284355,-74.701199,341.806666,-8.337846,0.956514,-9.114862,28.530264,-20.215673,11.279800
38,2024Q3,2.358491,2.916667,-4.942966,3.043478,-1.976285,3.982301,3.000000,-2.713178,-1.098901,...,28.386202,-20.220427,7.462207,-74.701199,341.806666,-8.337846,23.665361,-9.114862,28.530264,-20.215673
39,2024Q4,-5.990783,-3.643725,3.200000,-7.594937,-8.064516,-9.787234,-3.236246,-6.772908,-1.111111,...,-9.011073,28.386202,-4.328742,7.462207,-74.701199,341.806666,-4.329949,23.665361,-9.114862,28.530264
40,2025Q1,-6.372549,-10.084034,-10.465116,2.739726,-1.754386,-5.660377,-0.334448,-4.700855,-1.872659,...,23.672490,-9.011073,77.294952,-4.328742,7.462207,-74.701199,-33.173758,-4.329949,23.665361,-9.114862
41,2025Q2,7.329843,9.345794,6.926407,-1.333333,8.928571,14.500000,1.342282,12.556054,2.671756,...,-4.329950,23.672490,-67.234760,77.294952,-4.328742,7.462207,32.364440,-33.173758,-4.329949,23.665361

In [ ]:
# 숫자형 컬럼만 선택 (연도분기 제외)
numeric_df = df2.select_dtypes(include=["number"])

# 전체 상관계수
corr = numeric_df.corr()

target_corr = corr["gdp"].drop("gdp")
target_corr = target_corr.sort_values(ascending=False)
target_corr

생산지수              0.718497
내수출하지수            0.708106
매출실적BSI           0.656270
업황실적BSI           0.646005
수출실적BSI           0.614636
                    ...
내수판매실적BSI_lag4   -0.210515
수출실적BSI_lag4     -0.218137
제품재고실적BSI_lag2   -0.234606
ppi_lag4         -0.332035
인력사정실적BSI        -0.526901
Name: gdp, Length: 120, dtype: float64

In [ ]:
target_corr.to_csv('기계장비순서.csv')

In [ ]:
df2.dropna(inplace=True)

In [ ]:
df2

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,...,EBITDA_lag3,EBITDA_lag4,인건비_lag1,인건비_lag2,인건비_lag3,인건비_lag4,합산_lag1,합산_lag2,합산_lag3,합산_lag4
4,2016Q1,-8.648649,-8.225108,-5.668016,-5.092593,-4.583333,-4.504505,0.630915,-0.429185,-2.545455,...,11.370482,-2.060086,357.424088,6.869332,-8.143997,-74.951371,-31.668108,-19.819214,11.358989,-2.227654
5,2016Q2,10.059172,8.018868,3.004292,6.829268,10.917031,10.849057,-1.880878,12.068966,0.373134,...,-19.832186,11.370482,-81.793637,357.424088,6.869332,-8.143997,75.676703,-31.668108,-19.819214,11.358989
6,2016Q3,4.838710,-1.746725,-11.250000,0.456621,-4.724409,-7.234043,0.638978,-7.307692,1.858736,...,-31.920212,-19.832186,15.070257,-81.793637,357.424088,6.869332,-1.439817,75.676703,-31.668108,-19.819214
7,2016Q4,-1.025641,5.333333,14.553991,5.909091,2.479339,9.174312,0.000000,3.319502,1.459854,...,76.362235,-31.920212,-12.596764,15.070257,-81.793637,357.424088,-6.716128,-1.439817,75.676703,-31.668108
8,2017Q1,22.279793,13.080169,7.377049,12.017167,10.887097,10.924370,-0.634921,12.851406,2.517986,...,-1.447237,76.362235,487.225659,-12.596764,15.070257,-81.793637,59.403261,-6.716128,-1.439817,75.676703
9,2017Q2,8.050847,3.731343,9.541985,-0.766284,3.272727,1.136364,-2.875399,3.558719,-0.350877,...,-6.713042,-1.447237,-80.031136,487.225659,-12.596764,15.070257,8.648346,59.403261,-6.716128,-1.439817
10,2017Q3,-7.058824,-6.115108,-9.407666,-3.088803,-7.042254,-6.367041,0.986842,-7.903780,-1.408451,...,59.192927,-6.713042,1.674753,-80.031136,487.225659,-12.596764,51.896039,8.648346,59.403261,-6.716128
11,2017Q4,-5.485232,-3.065134,2.307692,-7.968127,-1.515152,-0.400000,0.000000,-4.104478,1.428571,...,8.809170,59.192927,10.827052,1.674753,-80.031136,487.225659,-27.523468,51.896039,8.648346,59.403261
12,2018Q1,1.339286,0.395257,-0.751880,1.731602,0.384615,-0.803213,0.977199,0.000000,-1.408451,...,51.912754,8.809170,491.267167,10.827052,1.674753,-80.031136,-1.142770,-27.523468,51.896039,8.648346
13,2018Q2,-3.524229,-2.755906,-9.090909,4.680851,-0.383142,3.238866,-2.258065,3.112840,-2.142857,...,-27.532011,51.912754,-83.772131,491.267167,10.827052,1.674753,-7.717767,-1.142770,-27.523468,51.896039
14,2018Q3,-7.762557,-2.834008,1.666667,-3.658537,-2.692308,-1.568627,-0.330033,-6.792453,-2.189781,...,-1.310520,-27.532011,-5.601242,-83.772131,491.267167,10.827052,3.162766,-7.717767,-1.142770,-27.523468
15,2018Q4,-2.475248,-2.916667,0.000000,-5.063291,1.185771,-5.179283,5.629139,2.834008,-0.373134,...,-7.562538,-1.310520,3.105060,-5.601242,-83.772131,491.267167,-18.756429,3.162766,-7.717767,-1.142770
16,2019Q1,1.522843,2.145923,-2.459016,3.111111,-3.125000,-1.260504,-0.940439,-2.362205,3.745318,...,3.165906,-7.562538,707.592723,3.105060,-5.601242,-83.772131,-17.662067,-18.756429,3.162766,-7.717767
17,2019Q2,7.000000,0.420168,5.042017,2.586207,-0.806452,3.829787,0.000000,0.806452,-0.722022,...,-18.763597,3.165906,-86.943120,707.592723,3.105060,-5.601242,9.954712,-17.662067,-18.756429,3.162766
18,2019Q3,-7.009346,-8.786611,-6.800000,-10.084034,-7.317073,-14.344262,-0.632911,-10.000000,-2.545455,...,-17.963862,-18.763597,-0.898045,-86.943120,707.592723,3.105060,27.771106,9.954712,-17.662067,-18.756429
19,2019Q4,1.507538,3.669725,1.287554,4.672897,4.824561,8.133971,1.910828,3.111111,-0.373134,...,10.351649,-17.963862,1.377837,-0.898045,-86.943120,707.592723,-33.492036,27.771106,9.954712,-17.662067
20,2020Q1,-3.960396,-3.539823,-2.966102,-5.803571,-2.092050,-1.769912,-2.500000,-0.431034,2.996255,...,27.785001,10.351649,679.332034,1.377837,-0.898045,-86.943120,19.798879,-33.492036,27.771106,9.954712
21,2020Q2,-27.835052,-26.146789,-27.510917,-18.957346,-25.213675,-32.432432,4.487179,-25.974026,-10.909091,...,-33.505143,27.785001,-81.317414,679.332034,1.377837,-0.898045,-2.151194,19.798879,-33.492036,27.771106
22,2020Q3,28.571429,24.844720,15.662651,18.713450,7.428571,20.000000,-1.840491,12.865497,0.408163,...,19.420904,-33.505143,-21.165465,-81.317414,679.332034,1.377837,3.053149,-2.151194,19.798879,-33.492036
23,2020Q4,16.666667,9.950249,15.104167,7.881773,19.148936,19.444444,-2.812500,23.834197,5.284553,...,-1.855115,19.420904,-14.697790,-21.165465,-81.317414,679.332034,15.506929,3.053149,-2.151194,19.798879
24,2021Q1,17.142857,23.076923,23.076923,24.200913,22.767857,25.116279,-3.858521,16.317992,11.196911,...,3.070391,-1.855115,641.481370,-14.697790,-21.165465,-81.317414,-30.562922,15.506929,3.053149,-2.151194
25,2021Q2,13.414634,18.750000,20.220588,13.970588,13.818182,19.330855,-3.344482,16.546763,-1.388889,...,15.523377,3.070391,-84.988408,641.481370,-14.697790,-21.165465,49.315703,-30.562922,15.506929,3.053149
26,2021Q3,-3.584229,-8.049536,-6.727829,-7.096774,-4.153355,-4.984424,0.000000,-3.395062,1.056338,...,-30.833136,15.523377,4.302645,-84.988408,641.481370,-14.697790,31.051260,49.315703,-30.562922,15.506929
27,2021Q4,1.858736,6.060606,0.000000,7.986111,4.000000,4.590164,5.536332,1.277955,2.439024,...,49.894601,-30.833136,-5.883655,4.302645,-84.988408,641.481370,-25.686719,31.051260,49.315703,-30.562922
28,2022Q1,0.729927,-2.222222,2.295082,-2.893891,-2.243590,-5.015674,-4.262295,-3.154574,-2.721088,...,31.062807,49.894601,437.970012,-5.883655,4.302645,-84.988408,7.497721,-25.686719,31.051260,49.315703
29,2022Q2,-5.434783,-5.519481,-10.897436,-3.311258,-4.918033,-4.950495,-0.342466,-4.885993,-0.699301,...,-25.693522,31.062807,-78.032435,437.970012,-5.883655,4.302645,8.303394,7.497721,-25.686719,31.051260
30,2022Q3,-1.149425,4.467354,5.395683,0.684932,-1.724138,-2.430556,3.780069,-1.369863,-0.352113,...,7.310414,-25.693522,-5.260007,-78.032435,437.970012,-5.883655,24.479616,8.303394,7.497721,-25.686719
31,2022Q4,-9.302326,-8.223684,-1.706485,-7.823129,-4.210526,-7.473310,6.291391,-4.513889,-3.180212,...,8.491722,7.310414,7.734307,-5.260007,-78.032435,437.970012,3.037927,24.479616,8.303394,7.497721
32,2023Q1,-18.376068,-16.845878,-17.361111,-13.284133,-11.721612,-11.923077,-2.180685,-13.454545,-2.919708,...,24.492752,8.491722,340.868279,7.734307,-5.260007,-78.032435,1.789634,3.037927,24.479616,8.303394
33,2023Q2,15.706806,8.620690,7.563025,2.553191,1.659751,5.676856,0.318471,3.361345,5.639098,...,3.036349,24.492752,-77.506303,340.868279,7.734307,-5.260007,-22.385631,1.789634,3.037927,24.479616
34,2023Q3,-6.787330,-11.507937,-14.453125,-6.639004,-4.897959,-9.917355,0.317460,-4.878049,-3.914591,...,1.670465,3.036349,0.956514,-77.506303,340.868279,7.734307,11.279800,-22.385631,1.789634,3.037927
35,2023Q4,1.456311,4.932735,6.849315,0.888889,-0.429185,2.752294,0.316456,3.846154,-1.481481,...,-22.301629,1.670465,-8.337846,0.956514,-77.506303,340.868279,-20.215673,11.279800,-22.385631,1.789634
36,2024Q1,4.784689,7.692308,10.683761,3.964758,2.586207,-0.446429,-4.731861,3.703704,2.631579,...,11.284355,-22.301629,341.806666,-8.337846,0.956514,-77.506303,28.530264,-20.215673,11.279800,-22.385631
37,2024Q2,-3.196347,-4.761905,1.544402,-2.542373,6.302521,1.345291,-0.662252,2.380952,0.000000,...,-20.220427,11.284355,-74.701199,341.806666,-8.337846,0.956514,-9.114862,28.530264,-20.215673,11.279800
38,2024Q3,2.358491,2.916667,-4.942966,3.043478,-1.976285,3.982301,3.000000,-2.713178,-1.098901,...,28.386202,-20.220427,7.462207,-74.701199,341.806666,-8.337846,23.665361,-9.114862,28.530264,-20.215673
39,2024Q4,-5.990783,-3.643725,3.200000,-7.594937,-8.064516,-9.787234,-3.236246,-6.772908,-1.111111,...,-9.011073,28.386202,-4.328742,7.462207,-74.701199,341.806666,-4.329949,23.665361,-9.114862,28.530264
40,2025Q1,-6.372549,-10.084034,-10.465116,2.739726,-1.754386,-5.660377,-0.334448,-4.700855,-1.872659,...,23.672490,-9.011073,77.294952,-4.328742,7.462207,-74.701199,-33.173758,-4.329949,23.665361,-9.114862
41,2025Q2,7.329843,9.345794,6.926407,-1.333333,8.928571,14.500000,1.342282,12.556054,2.671756,...,-4.329950,23.672490,-67.234760,77.294952,-4.328742,7.462207,32.364440,-33.173758,-4.329949,23.665361

In [ ]:
df2 = df2.reset_index()
df2 = df2.drop(columns=["level_0"])

In [ ]:
df2.to_csv('기계장비lag.csv', encoding='utf-8-sig')

#ARIMA

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('기계장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','생산실적BSI','신규수주실적BSI',
             '가동률실적BSI','내수판매실적BSI','ppi_lag4','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (1.0, 1.0, 3.0)
📉 평균 Train MAE: 1.5463
📈 평균 Test MAE: 4.5765

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('기계장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','생산실적BSI','신규수주실적BSI',
             '가동률실적BSI','내수판매실적BSI','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (3.0, 1.0, 1.0)
📉 평균 Train MAE: 1.0045
📈 평균 Test MAE: 3.5891

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('기계장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','생산실적BSI','신규수주실적BSI',
             '가동률실적BSI','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (2.0, 1.0, 2.0)
📉 평균 Train MAE: 1.1123
📈 평균 Test MAE: 2.678

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('기계장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','생산실적BSI','신규수주실적BSI','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (2.0, 1.0, 2.0)
📉 평균 Train MAE: 1.2208
📈 평균 Test MAE: 2.2326

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('기계장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','생산실적BSI','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (1.0, 1.0, 0.0)
📉 평균 Train MAE: 1.3791
📈 평균 Test MAE: 2.488

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('기계장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (2.0, 1.0, 0.0)
📉 평균 Train MAE: 1.3138
📈 평균 Test MAE: 1.934

# 랜덤포레스트

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('기계장비lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2016Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','인력사정실적BSI']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 0.6116
📈 평균 Test MAE: 1.973

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('기계장비lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2016Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','생산실적BSI','인력사정실적BSI']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 0.6018
📈 평균 Test MAE: 1.9458

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('기계장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'n_estimators': [200, 400],
    'max_depth': [8, 10, 12],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# 첫 번째 윈도우 구간 설정
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

# 하이퍼파라미터 탐색 (단 1회)
rf = RandomForestRegressor(random_state=42)
rand_search = RandomizedSearchCV(
    rf,
    param_distributions=param_grid,
    n_iter=10,            # 108조합 중 10개만 탐색
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 고정된 최적 파라미터로 학습
        model = RandomForestRegressor(**best_params, random_state=42)
        model.fit(X_train, y_train)

        # 예측
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # MAE 계산
        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 랜덤포레스트 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'n_estimators': 400, 'min_samples_split': 5, 'max_features': 'sqrt', 'max_depth': 12}

📊 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 0.7902
📈 평균 Test MAE: 1.9087

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('기계장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'n_estimators': [200, 400],
    'max_depth': [8, 10, 12],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# 첫 번째 윈도우 구간 설정
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

# 하이퍼파라미터 탐색 (단 1회)
rf = RandomForestRegressor(random_state=42)
rand_search = RandomizedSearchCV(
    rf,
    param_distributions=param_grid,
    n_iter=10,            # 108조합 중 10개만 탐색
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 고정된 최적 파라미터로 학습
        model = RandomForestRegressor(**best_params, random_state=42)
        model.fit(X_train, y_train)

        # 예측
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # MAE 계산
        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 랜덤포레스트 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'n_estimators': 400, 'min_samples_split': 5, 'max_features': 'sqrt', 'max_depth': 12}

📊 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 0.8196
📈 평균 Test MAE: 2.0145

#AR

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('기계장비qoq.csv')₩

# GDP 단일 시계열만 사용 (AR(1))
y = df['gdp'].dropna()
y.index = pd.PeriodIndex(df.loc[y.index, 'index'], freq='Q')

# -----------------------------
# 2️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

train_mae_list = []
test_mae_list = []

# -----------------------------
# 3️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    train_data = y.loc[train_start:train_end]
    test_data = y.loc[test_end:test_end]

    if len(train_data) < train_window:
        continue

    try:
        # AR(1) 학습
        model = AutoReg(train_data, lags=1, old_names=False)
        fit = model.fit()

        # --- Train 예측 ---
        # fittedvalues는 길이가 n-1이므로 첫 번째 값 제외하고 MAE 계산
        train_mae = mean_absolute_error(train_data[1:], fit.fittedvalues)
        train_mae_list.append(train_mae)

        # --- Test 예측 (1분기 앞 예측) ---
        pred = fit.predict(start=len(train_data), end=len(train_data))
        test_mae = mean_absolute_error(test_data, pred)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 4️⃣ 결과 출력
# -----------------------------
print("✅ AR(1) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ AR(1) 롤링 예측 결과
📉 평균 Train MAE: 2.9329
📈 평균 Test MAE: 2.8062

#XGB

In [ ]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('기계장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 하이퍼파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'n_estimators': [200, 400, 600],
    'learning_rate': [0.03, 0.05, 0.1],
    'max_depth': [3, 5, 7, 9],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.3]
}

# 첫 번째 윈도우로 탐색
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

# RandomizedSearchCV 실행
xgb = XGBRegressor(random_state=42, objective='reg:squarederror')
rand_search = RandomizedSearchCV(
    xgb,
    param_distributions=param_grid,
    n_iter=15,          # 전체 중 15조합 탐색
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 고정된 최적 파라미터로 학습
        model = XGBRegressor(**best_params, random_state=42, objective='reg:squarederror')
        model.fit(X_train, y_train)

        # 예측
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # MAE 계산
        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 XGBoost 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'subsample': 0.8, 'n_estimators': 600, 'min_child_weight': 3, 'max_depth': 5, 'learning_rate': 0.05, 'gamma': 0.1, 'colsample_bytree': 1.0}

📊 XGBoost 롤링 예측 결과
📉 평균 Train MAE: 0.1513
📈 평균 Test MAE: 2.0730

#MLP

In [ ]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('기계장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# 스케일링 (NN에서는 매우 중요)
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(), index=y.index)

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 하이퍼파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'hidden_layer_sizes': [(32,), (64,), (32,16), (64,32), (128,64)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'lbfgs'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate_init': [0.001, 0.01]
}

# 첫 번째 윈도우로 하이퍼파라미터 탐색
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X_scaled.loc[start_period:first_train_end]
first_y_train = y_scaled.loc[start_period:first_train_end]

mlp = MLPRegressor(random_state=42, max_iter=1000)
rand_search = RandomizedSearchCV(
    mlp,
    param_distributions=param_grid,
    n_iter=10,
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y_scaled.loc[train_start:train_end]
    y_test = y_scaled.loc[test_end:test_end]
    X_train = X_scaled.loc[train_start:train_end]
    X_test = X_scaled.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = MLPRegressor(**best_params, random_state=42, max_iter=1000)
        model.fit(X_train, y_train)

        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # 스케일링 복원
        train_pred_inv = scaler_y.inverse_transform(train_pred.reshape(-1, 1)).flatten()
        test_pred_inv = scaler_y.inverse_transform(test_pred.reshape(-1, 1)).flatten()
        y_train_inv = scaler_y.inverse_transform(y_train.values.reshape(-1, 1)).flatten()
        y_test_inv = scaler_y.inverse_transform(y_test.values.reshape(-1, 1)).flatten()

        # MAE 계산
        train_mae = mean_absolute_error(y_train_inv, train_pred_inv)
        test_mae = mean_absolute_error(y_test_inv, test_pred_inv)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 Neural Network (MLP) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'solver': 'adam', 'learning_rate_init': 0.001, 'hidden_layer_sizes': (64,), 'alpha': 0.01, 'activation': 'relu'}

📊 Neural Network (MLP) 롤링 예측 결과
📉 평균 Train MAE: 0.4995
📈 평균 Test MAE: 2.0553

#LSTM

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('기계장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = [
'생산지수','내수출하지수','매출실적BSI','업황실적BSI','수출실적BSI','인력사정실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 스케일링
# -----------------------------
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(), index=y.index)

# -----------------------------
# 4️⃣ LSTM 입력 형태 변환 함수
# -----------------------------
def create_lstm_input(X, y, lookback=4):
    """
    lookback: 과거 몇 분기 데이터를 사용할지 (ex. 4 = 1년)
    """
    Xs, ys, idxs = [], [], []
    for i in range(lookback, len(X)):
        Xs.append(X.iloc[i-lookback:i].values)
        ys.append(y.iloc[i])
        idxs.append(y.index[i])
    return np.array(Xs), np.array(ys), idxs

lookback = 4
X_seq, y_seq, idxs = create_lstm_input(X_scaled, y_scaled, lookback)
y_seq = pd.Series(y_seq, index=idxs)

# -----------------------------
# 5️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 6️⃣ LSTM 모델 정의 함수
# -----------------------------
def build_lstm(input_shape):
    model = Sequential()
    model.add(LSTM(64, activation='tanh', input_shape=input_shape, return_sequences=False))
    model.add(Dropout(0.2))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mae')
    return model

# -----------------------------
# 7️⃣ 롤링 예측
# -----------------------------
train_mae_list, test_mae_list = [], []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    # 윈도우 범위 맞추기
    train_mask = (np.array(idxs) >= train_start) & (np.array(idxs) <= train_end)
    test_mask = (np.array(idxs) == test_end)

    X_train, y_train = X_seq[train_mask], y_seq[train_mask]
    X_test, y_test = X_seq[test_mask], y_seq[test_mask]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = build_lstm((X_train.shape[1], X_train.shape[2]))
        early_stop = EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)
        model.fit(X_train, y_train, epochs=200, batch_size=8, verbose=0, callbacks=[early_stop])

        # 예측
        train_pred = model.predict(X_train, verbose=0)
        test_pred = model.predict(X_test, verbose=0)

        # 스케일링 복원
        train_pred_inv = scaler_y.inverse_transform(train_pred)
        test_pred_inv = scaler_y.inverse_transform(test_pred)
        y_train_inv = scaler_y.inverse_transform(y_train.values.reshape(-1, 1))
        y_test_inv = scaler_y.inverse_transform(y_test.values.reshape(-1, 1))

        # MAE 계산
        train_mae = mean_absolute_error(y_train_inv, train_pred_inv)
        test_mae = mean_absolute_error(y_test_inv, test_pred_inv)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 8️⃣ 결과 요약
# -----------------------------
print("\n📊 LSTM 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7ec90e4e62a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7ec90e4e62a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

📊 LSTM 롤링 예측 결과
📉 평균 Train MAE: 1.1355
📈 평균 Test MAE: 2.7587