In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 41 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 0s (23.9 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 125080 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

#데이터 불러오기

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rc('font', family='NanumBarunGothic')

!pip install tspoon
import tspoon as tsp

Collecting tspoon
  Downloading tspoon-0.2.10-py3-none-any.whl.metadata (4.2 kB)
Downloading tspoon-0.2.10-py3-none-any.whl (9.2 kB)
Installing collected packages: tspoon
Successfully installed tspoon-0.2.10

In [ ]:
!pip install xmltodict
import pandas as pd

import requests
import xml.etree.ElementTree as ET
import xml.dom.minidom
import xmltodict

import json
from urllib.request import urlopen

def getECOS(topic,period,beg,end,item1='?',item2='?',item3='?',item4='?', df=None):
    key = ''
    url = 'https://ecos.bok.or.kr/api/StatisticSearch/'+'OIT9OYFOZDZWLHSBQJWU'+'/xml/kr/'+str(1)+'/'+str(50000)+'/'+topic+'/'+period+'/'+beg+'/'+end \
            +'/'+item1+'/'+item2+'/'+item3+'/'+item4
    # print(url)
    ## call OpenAPI URL
    response = requests.get(url)

    ## get API return value upon the http request
    if response.status_code == 200:
        try:
            contents = response.text
            ecosRoot = ET.fromstring(contents)

            # error check
            if ecosRoot[0].text[:4] in ("INFO","ERRO"):
                print(ecosRoot[0].text + " : " + ecosRoot[1].text)

            else:
                #print(contents)
                #dom = xml.dom.minidom.parse(xml_fname)
                dom = xml.dom.minidom.parseString(contents)
                pretty_xml_as_string = dom.toprettyxml(indent=" ")
                # print(pretty_xml_as_string)
                dic = xmltodict.parse(pretty_xml_as_string)

                n = int(dic['StatisticSearch']['list_total_count']['#text'])
                df_ecos = pd.DataFrame(index = [dic['StatisticSearch']['row'][i]['TIME'] for i in range(n)])
                df_ecos[dic['StatisticSearch']['row'][0]['ITEM_NAME1']] = [float(dic['StatisticSearch']['row'][i]['DATA_VALUE']) for i in range(n)]

                if type(df)==type(pd.DataFrame()):
                    df_ecos = df.merge(df_ecos, left_index=True, right_index=True, how='left')

                return df_ecos

        except Exception as e:
            print(str(e))


def getKOSIS(table,period,beg,end,item, orgId='101', obj1='',obj2='',obj3='',obj4='',obj5='',obj6='',obj7='',obj8='', title=None, title_no='0', debug=False):
     # Korean Statistics
    key = 'MzhiMmQwZTYyMWZiNGM1ZGFkZDJmZTI2OTE1OGU2NzQ='
    url = 'https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey='+key \
            +'&orgId='+orgId\
            +'&tblId='+table \
            +'&prdSe='+period \
            +'&startPrdDe='+beg \
            +'&endPrdDe='+end \
            +'&itmId='+item \
            +'&objL1='+obj1 \
            +'&objL2='+obj2 \
            +'&objL3='+obj3 \
            +'&objL4='+obj4 \
            +'&objL5='+obj5 \
            +'&objL6='+obj6 \
            +'&objL7='+obj7 \
            +'&objL8='+obj8 \
            +'&format=json&jsonVD=Y&outputFields=ITM_NM+PRD_DE+DT'
    res = requests.get(url)
    py_json = res.json()

    data = []
    for v in py_json:
        value = []
        value.append(v['PRD_DE'])

        # ✅ DT 값이 '-' 또는 ''일 때 NaN으로 처리
        try:
            value.append(float(v['DT']))
        except (ValueError, KeyError):
            value.append(np.nan)

        data.append(value)

    df = pd.DataFrame(data, columns=['PRD_DE', 'DT'])

    if debug:
        print(df.head())

    return df


    #get json data from url
    with urlopen(url) as url_:
        json_file = url_.read()

    py_json = json.loads(json_file.decode('utf-8'))


    #data transformation
    data = []

    for i, v in enumerate(py_json):
        value = []
        value.append(v['PRD_DE'])
        value.append(float(v['DT']))

        data.append(value)

    if title is not None:
        title = str(title)
    elif title_no=='0':
        title = v['ITM_NM_ENG']
    else:
        title = v['C'+title_no+'_NM_ENG']

    df_kosis = pd.DataFrame({v['PRD_SE']:[x[0] for x in data], title:[x[1] for x in data]}).set_index(v['PRD_SE'])

    if debug:
        return v

    return df_kosis

Collecting xmltodict
  Downloading xmltodict-1.0.2-py3-none-any.whl.metadata (15 kB)
Downloading xmltodict-1.0.2-py3-none-any.whl (13 kB)
Installing collected packages: xmltodict
Successfully installed xmltodict-1.0.2

In [ ]:
import pandas as pd
import numpy as np
import os
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

In [ ]:
# change directory to where you have your data file!!
%cd gdrive/MyDrive/GDP/데이터

/content/gdrive/MyDrive/GDP/데이터

##GDP

In [ ]:
gdp = getECOS('200Y104', 'Q', '2014Q1', '2025Q2','110312').reset_index()
gdp

     index  운송장비 제조업
0   2014Q1   17740.3
1   2014Q2   17944.4
2   2014Q3   17202.3
3   2014Q4   16510.7
4   2015Q1   16388.1
5   2015Q2   17144.1
6   2015Q3   17627.4
7   2015Q4   17287.4
8   2016Q1   17222.6
9   2016Q2   17901.5
10  2016Q3   16936.2
11  2016Q4   17089.2
12  2017Q1   16784.1
13  2017Q2   16340.2
14  2017Q3   16267.9
15  2017Q4   15105.1
16  2018Q1   15331.1
17  2018Q2   16055.8
18  2018Q3   15690.5
19  2018Q4   16859.1
20  2019Q1   15836.3
21  2019Q2   16392.2
22  2019Q3   15752.5
23  2019Q4   16453.5
24  2020Q1   14998.7
25  2020Q2   12910.3
26  2020Q3   14445.5
27  2020Q4   15424.1
28  2021Q1   15767.7
29  2021Q2   15586.0
30  2021Q3   14768.8
31  2021Q4   15254.0
32  2022Q1   16478.3
33  2022Q2   16097.9
34  2022Q3   18333.3
35  2022Q4   17232.2
36  2023Q1   19402.9
37  2023Q2   19923.6
38  2023Q3   20607.6
39  2023Q4   19729.6
40  2024Q1   19419.5
41  2024Q2   20801.8
42  2024Q3   21740.3
43  2024Q4   20950.9
44  2025Q1   20621.7
45  2025Q2   21412.0

##PPI

In [ ]:
ppi = getECOS('404Y014','Q','2014Q1','2025Q2','312AA').reset_index()
ppi

     index    운송장비
0   2014Q1   93.83
1   2014Q2   95.66
2   2014Q3   97.20
3   2014Q4   97.70
4   2015Q1   97.94
5   2015Q2   97.88
6   2015Q3   97.89
7   2015Q4   97.64
8   2016Q1   97.83
9   2016Q2   97.75
10  2016Q3   97.83
11  2016Q4   97.80
12  2017Q1   98.40
13  2017Q2   98.31
14  2017Q3   98.55
15  2017Q4   98.65
16  2018Q1   99.19
17  2018Q2   99.31
18  2018Q3   99.29
19  2018Q4   99.13
20  2019Q1   99.36
21  2019Q2   99.33
22  2019Q3   99.62
23  2019Q4   99.61
24  2020Q1   99.85
25  2020Q2  100.09
26  2020Q3   99.90
27  2020Q4  100.16
28  2021Q1  100.67
29  2021Q2  101.06
30  2021Q3  101.48
31  2021Q4  101.72
32  2022Q1  102.53
33  2022Q2  102.88
34  2022Q3  103.90
35  2022Q4  104.55
36  2023Q1  104.71
37  2023Q2  104.61
38  2023Q3  105.26
39  2023Q4  106.51
40  2024Q1  106.89
41  2024Q2  107.08
42  2024Q3  107.53
43  2024Q4  107.98
44  2025Q1  108.27
45  2025Q2  108.32

In [ ]:
ppi = ppi.rename(columns={'운송장비':'ppi'})

##BSI(단순평균으로 계산)

In [ ]:
업황실적BSI1 = getECOS('512Y007','M','201401','202506','AA','C3000').reset_index()
업황실적BSI2 = getECOS('512Y007','M','201401','202506','AA','C3100').reset_index()

In [ ]:
from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [업황실적BSI1,업황실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
업황실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
업황실적BSI

업황실적BSI['업황실적BSI']=(업황실적BSI['업황실적BSI 1)_x']+업황실적BSI['업황실적BSI 1)_y'])/2
업황실적BSI = 업황실적BSI.drop(columns=["업황실적BSI 1)_x","업황실적BSI 1)_y"])
업황실적BSI

      index  업황실적BSI
0    201401     81.0
1    201402     87.0
2    201403     83.5
3    201404     87.0
4    201405     83.5
..      ...      ...
133  202502     87.0
134  202503     91.5
135  202504     89.5
136  202505     94.0
137  202506     86.0

[138 rows x 2 columns]

In [ ]:
매출실적BSI1 = getECOS('512Y007','M','201401','202506','AB','C3000').reset_index()
매출실적BSI2 = getECOS('512Y007','M','201401','202506','AB','C3100').reset_index()

from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [매출실적BSI1,매출실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
매출실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
매출실적BSI

매출실적BSI['매출실적BSI']=(매출실적BSI['매출실적BSI 2)_x']+매출실적BSI['매출실적BSI 2)_y'])/2
매출실적BSI = 매출실적BSI.drop(columns=["매출실적BSI 2)_x","매출실적BSI 2)_y"])
매출실적BSI

      index  매출실적BSI
0    201401     97.0
1    201402     89.0
2    201403     92.0
3    201404    101.5
4    201405    102.0
..      ...      ...
133  202502     93.0
134  202503     95.5
135  202504    101.0
136  202505    102.5
137  202506     94.0

[138 rows x 2 columns]

In [ ]:
채산성실적BSI1 = getECOS('512Y007','M','201401','202506','AE','C3000').reset_index()
채산성실적BSI2 = getECOS('512Y007','M','201401','202506','AE','C3100').reset_index()
from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [채산성실적BSI1,채산성실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
채산성실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
채산성실적BSI

채산성실적BSI['채산성실적BSI']=(채산성실적BSI['채산성실적BSI 6)_x']+채산성실적BSI['채산성실적BSI 6)_y'])/2
채산성실적BSI = 채산성실적BSI.drop(columns=["채산성실적BSI 6)_x","채산성실적BSI 6)_y"])
채산성실적BSI

      index  채산성실적BSI
0    201401      97.0
1    201402      93.5
2    201403      94.5
3    201404     100.0
4    201405      97.0
..      ...       ...
133  202502      89.0
134  202503      94.5
135  202504      89.0
136  202505      90.5
137  202506      85.5

[138 rows x 2 columns]

In [ ]:
수출실적BSI1= getECOS('512Y007','M','201401','202506','AM','C3000').reset_index()
수출실적BSI2= getECOS('512Y007','M','201401','202506','AM','C3100').reset_index()

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [수출실적BSI1,수출실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
수출실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
수출실적BSI

수출실적BSI['수출실적BSI']=(수출실적BSI['수출실적BSI 2)_x']+수출실적BSI['수출실적BSI 2)_y'])/2
수출실적BSI = 수출실적BSI.drop(columns=["수출실적BSI 2)_x","수출실적BSI 2)_y"])
수출실적BSI

      index  수출실적BSI
0    201401     92.0
1    201402     88.0
2    201403     94.5
3    201404    102.0
4    201405    104.0
..      ...      ...
133  202502     99.5
134  202503     96.0
135  202504    100.5
136  202505    107.5
137  202506    101.5

[138 rows x 2 columns]

In [ ]:
내수판매실적BSI1= getECOS('512Y007','M','201401','202506','AL','C3000').reset_index()
내수판매실적BSI2= getECOS('512Y007','M','201401','202506','AL','C3100').reset_index()

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [내수판매실적BSI1,내수판매실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
내수판매실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
내수판매실적BSI


내수판매실적BSI['내수판매실적BSI']=(내수판매실적BSI['내수판매실적BSI 2)_x']+내수판매실적BSI['내수판매실적BSI 2)_y'])/2
내수판매실적BSI = 내수판매실적BSI.drop(columns=["내수판매실적BSI 2)_x","내수판매실적BSI 2)_y"])
내수판매실적BSI

      index  내수판매실적BSI
0    201401       87.5
1    201402       87.0
2    201403       89.0
3    201404       94.0
4    201405       95.0
..      ...        ...
133  202502       89.5
134  202503       91.5
135  202504      100.0
136  202505       95.5
137  202506       87.5

[138 rows x 2 columns]

In [ ]:
생산실적BSI1= getECOS('512Y007','M','201401','202506','AC','C3000').reset_index()
생산실적BSI2= getECOS('512Y007','M','201401','202506','AC','C3100').reset_index()
# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [생산실적BSI1,생산실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
생산실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
생산실적BSI
생산실적BSI['생산실적BSI']=(생산실적BSI['생산실적BSI 2)_x']+생산실적BSI['생산실적BSI 2)_y'])/2
생산실적BSI = 생산실적BSI.drop(columns=["생산실적BSI 2)_x","생산실적BSI 2)_y"])
생산실적BSI

      index  생산실적BSI
0    201401     94.5
1    201402     90.5
2    201403     90.0
3    201404    104.0
4    201405    106.0
..      ...      ...
133  202502     92.0
134  202503    101.5
135  202504     97.0
136  202505     98.5
137  202506     91.5

[138 rows x 2 columns]

In [ ]:
신규수주실적BSI1= getECOS('512Y007','M','201401','202506','AD','C3000').reset_index()
신규수주실적BSI2= getECOS('512Y007','M','201401','202506','AD','C3100').reset_index()

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [신규수주실적BSI1,신규수주실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
신규수주실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
신규수주실적BSI

신규수주실적BSI['신규수주실적BSI']=(신규수주실적BSI['신규수주실적BSI 2)_x']+신규수주실적BSI['신규수주실적BSI 2)_y'])/2
신규수주실적BSI = 신규수주실적BSI.drop(columns=["신규수주실적BSI 2)_x","신규수주실적BSI 2)_y"])
신규수주실적BSI

      index  신규수주실적BSI
0    201401       97.5
1    201402       95.5
2    201403       95.0
3    201404       95.5
4    201405       94.0
..      ...        ...
133  202502       83.0
134  202503       86.0
135  202504       84.0
136  202505       88.5
137  202506       88.0

[138 rows x 2 columns]

In [ ]:

제품재고실적BSI1= getECOS('512Y007','M','201401','202506','AG','C3000').reset_index()
제품재고실적BSI2= getECOS('512Y007','M','201401','202506','AG','C3100').reset_index()

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [제품재고실적BSI1,제품재고실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
제품재고실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
제품재고실적BSI


제품재고실적BSI['제품재고실적BSI']=(제품재고실적BSI['제품재고실적BSI 3)_x']+제품재고실적BSI['제품재고실적BSI 3)_y'])/2
제품재고실적BSI = 제품재고실적BSI.drop(columns=["제품재고실적BSI 3)_x","제품재고실적BSI 3)_y"])
제품재고실적BSI

      index  제품재고실적BSI
0    201401      102.5
1    201402      102.5
2    201403      100.5
3    201404      102.5
4    201405      100.0
..      ...        ...
133  202502      103.0
134  202503       98.0
135  202504      101.0
136  202505       99.0
137  202506      101.5

[138 rows x 2 columns]

In [ ]:
가동률실적BSI1= getECOS('512Y007','M','201401','202506','AK','C3000').reset_index()
가동률실적BSI2= getECOS('512Y007','M','201401','202506','AK','C3100').reset_index()

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [가동률실적BSI1,가동률실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
가동률실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
가동률실적BSI

가동률실적BSI['가동률실적BSI']=(가동률실적BSI['가동률실적BSI 4)_x']+가동률실적BSI['가동률실적BSI 4)_y'])/2
가동률실적BSI = 가동률실적BSI.drop(columns=["가동률실적BSI 4)_x","가동률실적BSI 4)_y"])
가동률실적BSI

      index  가동률실적BSI
0    201401      95.0
1    201402      93.0
2    201403      94.0
3    201404     102.0
4    201405      98.5
..      ...       ...
133  202502      89.0
134  202503      99.5
135  202504      94.5
136  202505      96.5
137  202506      91.0

[138 rows x 2 columns]

In [ ]:
생산설비실적BSI1= getECOS('512Y007','M','201401','202506','AH','C3000').reset_index()
생산설비실적BSI2= getECOS('512Y007','M','201401','202506','AH','C3100').reset_index()
# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [생산설비실적BSI1,생산설비실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
생산설비실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
생산설비실적BSI

생산설비실적BSI['생산설비실적BSI']=(생산설비실적BSI['생산설비실적BSI 3)_x']+생산설비실적BSI['생산설비실적BSI 3)_y'])/2
생산설비실적BSI = 생산설비실적BSI.drop(columns=["생산설비실적BSI 3)_x","생산설비실적BSI 3)_y"])
생산설비실적BSI

      index  생산설비실적BSI
0    201401      103.0
1    201402      106.5
2    201403      104.5
3    201404      104.0
4    201405      101.5
..      ...        ...
120  202401       99.5
121  202402      100.5
122  202403       97.0
123  202404       96.5
124  202405       98.5

[125 rows x 2 columns]

In [ ]:
설비투자실적BSI1= getECOS('512Y007','M','201401','202506','AI','C3000').reset_index()
설비투자실적BSI2= getECOS('512Y007','M','201401','202506','AI','C3100').reset_index()

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [설비투자실적BSI1,설비투자실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
설비투자실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
설비투자실적BSI


설비투자실적BSI['설비투자실적BSI']=(설비투자실적BSI['설비투자실적BSI 5)_x']+설비투자실적BSI['설비투자실적BSI 5)_y'])/2
설비투자실적BSI = 설비투자실적BSI.drop(columns=["설비투자실적BSI 5)_x","설비투자실적BSI 5)_y"])
설비투자실적BSI

      index  설비투자실적BSI
0    201401       96.5
1    201402       92.5
2    201403       97.0
3    201404       94.0
4    201405       96.0
..      ...        ...
133  202502       94.5
134  202503       97.0
135  202504       96.0
136  202505      101.0
137  202506       94.5

[138 rows x 2 columns]

In [ ]:
자금사정실적BSI1 = getECOS('512Y007','M','201401','202506','AO','C3000').reset_index()
자금사정실적BSI2 = getECOS('512Y007','M','201401','202506','AO','C3100').reset_index()


# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [자금사정실적BSI1,자금사정실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
자금사정실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
자금사정실적BSI


자금사정실적BSI['자금사정실적BSI']=(자금사정실적BSI['자금사정실적BSI 6)_x']+자금사정실적BSI['자금사정실적BSI 6)_y'])/2
자금사정실적BSI = 자금사정실적BSI.drop(columns=["자금사정실적BSI 6)_x","자금사정실적BSI 6)_y"])
자금사정실적BSI

      index  자금사정실적BSI
0    201401       87.5
1    201402       90.0
2    201403       90.5
3    201404       92.5
4    201405       89.5
..      ...        ...
133  202502       92.5
134  202503       88.5
135  202504       94.5
136  202505       83.5
137  202506       87.5

[138 rows x 2 columns]

In [ ]:
인력사정실적BSI1 = getECOS('512Y007','M','201401','202506','AJ','C3000').reset_index()
인력사정실적BSI2 = getECOS('512Y007','M','201401','202506','AJ','C3100').reset_index()

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [인력사정실적BSI1,인력사정실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
인력사정실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
인력사정실적BSI

인력사정실적BSI['인력사정실적BSI']=(인력사정실적BSI['인력사정실적BSI 3)_x']+인력사정실적BSI['인력사정실적BSI 3)_y'])/2
인력사정실적BSI = 인력사정실적BSI.drop(columns=["인력사정실적BSI 3)_x","인력사정실적BSI 3)_y"])
인력사정실적BSI

      index  인력사정실적BSI
0    201401      101.5
1    201402       96.0
2    201403       91.0
3    201404       90.5
4    201405       91.5
..      ...        ...
133  202502       94.5
134  202503       87.5
135  202504       88.5
136  202505       91.5
137  202506       94.5

[138 rows x 2 columns]

In [ ]:
원자재구입가격BSI1 = getECOS('512Y007','M','201401','202506','AN','C3000').reset_index()
원자재구입가격BSI2 = getECOS('512Y007','M','201401','202506','AN','C3100').reset_index()

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [원자재구입가격BSI1,원자재구입가격BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
원자재구입가격BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
원자재구입가격BSI

원자재구입가격BSI['원자재구입가격BSI']=(원자재구입가격BSI['원자재구입가격실적BSI 4)_x']+원자재구입가격BSI['원자재구입가격실적BSI 4)_y'])/2
원자재구입가격BSI = 원자재구입가격BSI.drop(columns=["원자재구입가격실적BSI 4)_x","원자재구입가격실적BSI 4)_y"])
원자재구입가격BSI

      index  원자재구입가격BSI
0    201401        99.0
1    201402       102.0
2    201403        98.0
3    201404       106.5
4    201405        99.0
..      ...         ...
133  202502       119.5
134  202503       123.0
135  202504       122.5
136  202505       121.0
137  202506       111.0

[138 rows x 2 columns]

In [ ]:
from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [업황실적BSI, 매출실적BSI,수출실적BSI, 내수판매실적BSI, 생산실적BSI, 신규수주실적BSI, 제품재고실적BSI, 가동률실적BSI,설비투자실적BSI, 채산성실적BSI, 자금사정실적BSI, 인력사정실적BSI,원자재구입가격BSI]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
df_merged = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
df_merged

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,원자재구입가격BSI
0,201401,81.0,97.0,92.0,87.5,94.5,97.5,102.5,95.0,96.5,97.0,87.5,101.5,99.0
1,201402,87.0,89.0,88.0,87.0,90.5,95.5,102.5,93.0,92.5,93.5,90.0,96.0,102.0
2,201403,83.5,92.0,94.5,89.0,90.0,95.0,100.5,94.0,97.0,94.5,90.5,91.0,98.0
3,201404,87.0,101.5,102.0,94.0,104.0,95.5,102.5,102.0,94.0,100.0,92.5,90.5,106.5
4,201405,83.5,102.0,104.0,95.0,106.0,94.0,100.0,98.5,96.0,97.0,89.5,91.5,99.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,202502,87.0,93.0,99.5,89.5,92.0,83.0,103.0,89.0,94.5,89.0,92.5,94.5,119.5
134,202503,91.5,95.5,96.0,91.5,101.5,86.0,98.0,99.5,97.0,94.5,88.5,87.5,123.0
135,202504,89.5,101.0,100.5,100.0,97.0,84.0,101.0,94.5,96.0,89.0,94.5,88.5,122.5
136,202505,94.0,102.5,107.5,95.5,98.5,88.5,99.0,96.5,101.0,90.5,83.5,91.5,121.0
137,202506,86.0,94.0,101.5,87.5,91.5,88.0,101.5,91.0,94.5,85.5,87.5,94.5,111.0

In [ ]:
df_merged.isnull().sum()

index         0
업황실적BSI       0
매출실적BSI       0
수출실적BSI       0
내수판매실적BSI     0
생산실적BSI       0
신규수주실적BSI     0
제품재고실적BSI     0
가동률실적BSI      0
설비투자실적BSI     0
채산성실적BSI      0
자금사정실적BSI     0
인력사정실적BSI     0
원자재구입가격BSI    0
dtype: int64

In [ ]:
import pandas as pd

# index가 숫자라면 문자열로 변환
df_merged['index'] = df_merged['index'].astype(str)

# 연도와 월 분리
df_merged['연도'] = df_merged['index'].str[:4].astype(int)
df_merged['월'] = df_merged['index'].str[4:6].astype(int)

# 월 → 분기 변환 함수
def month_to_quarter(month):
    if month in [1, 2, 3]:
        return 'Q1'
    elif month in [4, 5, 6]:
        return 'Q2'
    elif month in [7, 8, 9]:
        return 'Q3'
    else:
        return 'Q4'

# 분기 계산
df_merged['분기'] = df_merged['월'].apply(month_to_quarter)

# 분기 인덱스 생성 (예: 2015Q1)
df_merged['index'] = df_merged['연도'].astype(str) + df_merged['분기']

# 분기별 평균 집계
df_quarter = df_merged.groupby('index').mean(numeric_only=True).reset_index()

# 결과 확인
print(df_quarter.head())

    index    업황실적BSI     매출실적BSI     수출실적BSI  내수판매실적BSI     생산실적BSI  \
0  2014Q1  83.833333   92.666667   91.500000  87.833333   91.666667
1  2014Q2  85.833333  102.000000  100.000000  95.166667  103.500000
2  2014Q3  76.333333   86.500000   88.666667  83.666667   91.500000
3  2014Q4  74.166667   93.833333   91.833333  89.666667   99.166667
4  2015Q1  73.000000   87.666667   88.333333  86.500000   94.500000

   신규수주실적BSI   제품재고실적BSI   가동률실적BSI  설비투자실적BSI   채산성실적BSI  자금사정실적BSI  \
0  96.000000  101.833333  94.000000  95.333333  95.000000  89.333333
1  96.000000  102.833333  99.666667  96.166667  99.000000  91.333333
2  85.500000  101.833333  90.166667  95.666667  93.166667  86.833333
3  93.666667  102.500000  97.500000  95.333333  94.500000  86.500000
4  83.666667  103.666667  91.666667  95.166667  95.000000  85.666667

    인력사정실적BSI  원자재구입가격BSI      연도     월
0   96.166667   99.666667  2014.0   2.0
1   90.333333  101.333333  2014.0   5.0
2   91.166667  101.500000  2014.0   8.0
3   91.166667  100.666667  2014.0  11.0
4  101.166667   96.500000  2015.0   2.0

In [ ]:
df_quarter = df_quarter.drop(columns=['연도', '월'], errors='ignore')

In [ ]:
dfs = [ppi, gdp]
df_final = df_quarter.copy()
key_col = 'index'
for df in dfs:
    df_final = df_final.merge(df, on=key_col, how='left')

df_final

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,원자재구입가격BSI,ppi,운송장비 제조업
0,2014Q1,83.833333,92.666667,91.500000,87.833333,91.666667,96.000000,101.833333,94.000000,95.333333,95.000000,89.333333,96.166667,99.666667,93.83,17740.3
1,2014Q2,85.833333,102.000000,100.000000,95.166667,103.500000,96.000000,102.833333,99.666667,96.166667,99.000000,91.333333,90.333333,101.333333,95.66,17944.4
2,2014Q3,76.333333,86.500000,88.666667,83.666667,91.500000,85.500000,101.833333,90.166667,95.666667,93.166667,86.833333,91.166667,101.500000,97.20,17202.3
3,2014Q4,74.166667,93.833333,91.833333,89.666667,99.166667,93.666667,102.500000,97.500000,95.333333,94.500000,86.500000,91.166667,100.666667,97.70,16510.7
4,2015Q1,73.000000,87.666667,88.333333,86.500000,94.500000,83.666667,103.666667,91.666667,95.166667,95.000000,85.666667,101.166667,96.500000,97.94,16388.1
5,2015Q2,74.833333,92.666667,92.500000,89.500000,96.833333,84.666667,103.833333,95.333333,94.666667,96.833333,87.166667,96.333333,98.000000,97.88,17144.1
6,2015Q3,64.166667,85.833333,87.333333,82.833333,93.000000,80.166667,104.000000,90.333333,91.000000,92.500000,82.333333,95.666667,103.833333,97.89,17627.4
7,2015Q4,73.333333,87.333333,87.000000,86.833333,95.166667,80.833333,98.666667,92.500000,95.833333,92.333333,81.833333,96.666667,99.500000,97.64,17287.4
8,2016Q1,65.166667,82.500000,84.166667,82.666667,88.166667,77.000000,103.833333,86.166667,91.666667,86.166667,79.166667,95.833333,98.666667,97.83,17222.6
9,2016Q2,62.833333,80.500000,89.333333,76.000000,87.166667,68.666667,97.166667,85.833333,88.833333,89.833333,78.000000,97.000000,102.833333,97.75,17901.5
10,2016Q3,55.000000,69.000000,81.166667,64.500000,76.666667,63.166667,96.166667,73.333333,87.833333,83.833333,77.166667,105.000000,104.500000,97.83,16936.2
11,2016Q4,56.333333,69.666667,76.500000,69.833333,77.666667,71.000000,95.500000,77.666667,88.833333,83.000000,73.500000,105.166667,107.000000,97.80,17089.2
12,2017Q1,59.333333,73.000000,74.500000,72.333333,77.833333,75.833333,94.333333,78.333333,87.333333,83.333333,73.500000,104.666667,112.833333,98.40,16784.1
13,2017Q2,57.833333,62.000000,63.333333,63.666667,69.333333,75.166667,93.666667,68.666667,87.833333,78.333333,70.833333,109.500000,109.666667,98.31,16340.2
14,2017Q3,53.500000,55.166667,56.000000,61.500000,65.500000,73.833333,96.500000,65.500000,83.166667,78.666667,71.000000,108.500000,107.833333,98.55,16267.9
15,2017Q4,56.166667,58.500000,61.833333,60.000000,68.833333,76.833333,92.833333,67.166667,83.000000,78.333333,72.666667,109.833333,112.166667,98.65,15105.1
16,2018Q1,58.833333,59.000000,62.500000,60.833333,68.666667,77.666667,100.333333,69.833333,87.500000,78.500000,72.666667,112.666667,113.166667,99.19,15331.1
17,2018Q2,60.333333,66.166667,69.500000,67.000000,72.500000,75.666667,99.500000,75.666667,87.500000,77.333333,73.666667,110.166667,114.833333,99.31,16055.8
18,2018Q3,54.666667,64.833333,71.500000,66.666667,75.000000,76.666667,95.833333,74.500000,84.333333,81.000000,69.666667,101.000000,123.166667,99.29,15690.5
19,2018Q4,60.333333,77.666667,81.000000,77.000000,83.833333,83.000000,98.666667,85.833333,88.000000,80.333333,69.500000,101.666667,113.666667,99.13,16859.1
20,2019Q1,69.333333,90.166667,96.333333,81.666667,90.500000,86.666667,101.666667,88.333333,90.166667,83.166667,72.166667,100.000000,112.000000,99.36,15836.3
21,2019Q2,75.333333,95.166667,96.833333,90.166667,99.666667,93.333333,100.166667,99.833333,90.833333,88.500000,80.833333,101.166667,111.500000,99.33,16392.2
22,2019Q3,75.500000,94.166667,92.333333,90.500000,97.833333,95.333333,100.333333,97.833333,92.833333,89.000000,81.833333,97.833333,107.833333,99.62,15752.5
23,2019Q4,78.333333,99.500000,100.833333,96.333333,103.500000,93.333333,103.000000,102.333333,92.833333,91.333333,82.166667,99.166667,105.833333,99.61,16453.5
24,2020Q1,67.833333,75.000000,76.333333,75.166667,77.666667,77.166667,103.166667,77.000000,88.666667,82.333333,73.166667,104.166667,105.500000,99.85,14998.7
25,2020Q2,38.666667,46.666667,47.500000,53.500000,51.833333,47.833333,117.833333,50.166667,69.333333,78.666667,54.000000,118.666667,103.166667,100.09,12910.3
26,2020Q3,56.833333,57.833333,59.666667,64.666667,66.000000,59.000000,107.333333,62.833333,78.833333,82.666667,65.333333,109.666667,106.500000,99.90,14445.5
27,2020Q4,78.500000,72.166667,70.000000,82.166667,81.166667,74.500000,104.833333,82.000000,88.500000,86.166667,78.666667,98.666667,105.166667,100.16,15424.1
28,2021Q1,76.500000,82.500000,82.666667,87.833333,89.666667,81.500000,96.500000,89.833333,92.833333,85.500000,77.333333,102.333333,122.166667,100.67,15767.7
29,2021Q2,83.666667,105.666667,99.500000,103.666667,104.500000,105.000000,100.166667,104.166667,92.166667,81.500000,86.333333,98.000000,136.833333,101.06,15586.0
30,2021Q3,82.000000,103.666667,109.500000,98.666667,100.000000,98.666667,101.166667,101.166667,92.333333,79.166667,79.666667,98.833333,142.166667,101.48,14768.8
31,2021Q4,79.666667,88.333333,94.833333,84.666667,91.166667,95.333333,101.833333,90.500000,92.500000,76.833333,80.333333,87.833333,145.166667,101.72,15254.0
32,2022Q1,81.000000,101.166667,105.833333,97.000000,99.000000,97.666667,101.666667,99.500000,95.833333,80.500000,82.333333,87.666667,139.500000,102.53,16478.3
33,2022Q2,75.500000,99.833333,98.666667,95.833333,103.500000,98.000000,103.666667,103.000000,93.833333,72.000000,73.500000,83.166667,149.500000,102.88,16097.9
34,2022Q3,81.333333,111.833333,115.333333,104.166667,110.166667,100.500000,101.000000,111.333333,96.500000,83.333333,78.666667,78.666667,133.500000,103.90,18333.3
35,2022Q4,87.000000,121.833333,121.666667,112.333333,117.333333,105.833333,95.500000,117.333333,98.166667,85.833333,86.833333,73.833333,116.500000,104.55,17232.2
36,2023Q1,92.166667,115.166667,113.666667,107.333333,112.000000,98.166667,97.500000,111.166667,100.166667,89.666667,88.666667,76.166667,115.166667,104.71,19402.9
37,2023Q2,97.000000,119.833333,120.833333,110.333333,111.000000,100.500000,95.500000,113.000000,100.333333,91.166667,88.166667,71.500000,114.833333,104.61,19923.6
38,2023Q3,97.833333,118.333333,121.500000,111.500000,111.166667,101.666667,94.666667,111.833333,103.500000,92.833333,89.333333,75.000000,110.500000,105.26,20607.6
39,2023Q4,93.500000,105.666667,107.000000,96.333333,99.500000,92.000000,101.333333,97.666667,101.500000,91.166667,85.166667,74.500000,118.000000,106.51,19729.6
40,2024Q1,85.500000,97.833333,101.500000,91.000000,94.166667,84.000000,102.666667,95.166667,96.500000,88.500000,85.666667,79.500000,120.166667,106.89,19419.5
41,2024Q2,95.500000,105.500000,105.833333,100.500000,99.500000,90.333333,97.833333,98.833333,95.333333,95.666667,89.333333,84.166667,120.666667,107.08,20801.8
42,2024Q3,92.833333,99.666667,102.666667,93.000000,96.166667,89.000000,106.166667,96.500000,95.000000,90.666667,89.666667,90.666667,112.333333,107.53,21740.3
43,2024Q4,92.000000,100.333333,101.166667,95.000000,96.000000,92.833333,104.500000,93.666667,97.166667,90.000000,89.000000,90.666667,115.000000,107.98,20950.9
44,2025Q1,86.666667,91.000000,98.166667,86.666667,92.166667,83.833333,100.833333,90.166667,96.000000,89.500000,89.333333,91.666667,121.166667,108.27,20621.7
45,2025Q2,89.833333,99.166667,103.166667,94.333333,95.666667,86.833333,100.500000,94.000000,97.166667,88.333333,88.500000,91.500000,118.166667,108.32,21412.0

In [ ]:
df_final.to_csv("운송장비1차.csv")

## 생산지수

In [ ]:
생산지수1 = getKOSIS('DT_1F02001','Q','201401','202502','T20','101','00','C30')
생산지수2 = getKOSIS('DT_1F02001','Q','201401','202502','T20','101','00','C31')

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [생산지수1,생산지수2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
생산지수 = reduce(lambda left, right: pd.merge(left, right, on="PRD_DE", how="outer"), dfs)
생산지수
생산지수['생산지수']=(생산지수['DT_x']+생산지수['DT_y'])/2
생산지수 = 생산지수.drop(columns=["DT_x","DT_y"])
생산지수


def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

생산지수['index']=생산지수['PRD_DE'].apply(to_quarter)
생산지수 = 생산지수.drop(columns=["PRD_DE"])
생산지수 = 생산지수.rename(columns={'DT': '생산지수'})
생산지수

        생산지수   index
0   141.9175  2014Q1
1   139.0690  2014Q2
2   134.2330  2014Q3
3   132.9790  2014Q4
4   135.2305  2015Q1
5   131.1905  2015Q2
6   130.0310  2015Q3
7   125.2675  2015Q4
8   126.1460  2016Q1
9   123.4555  2016Q2
10  115.9965  2016Q3
11  115.6245  2016Q4
12  109.4050  2017Q1
13  110.7700  2017Q2
14  101.0260  2017Q3
15   99.4645  2017Q4
16   94.8195  2018Q1
17  100.2770  2018Q2
18  101.0000  2018Q3
19  103.9620  2018Q4
20  103.0150  2019Q1
21  106.1700  2019Q2
22  109.6185  2019Q3
23  106.7585  2019Q4
24  103.4000  2020Q1
25   92.1500  2020Q2
26  101.0500  2020Q3
27  103.3500  2020Q4
28  100.5500  2021Q1
29   97.3500  2021Q2
30   98.4000  2021Q3
31  104.6500  2021Q4
32  107.8000  2022Q1
33  111.4500  2022Q2
34  119.0000  2022Q3
35  119.2500  2022Q4
36  121.3000  2023Q1
37  124.7500  2023Q2
38  125.7500  2023Q3
39  125.7500  2023Q4
40  124.2000  2024Q1
41  128.8000  2024Q2
42  131.5000  2024Q3
43  130.6500  2024Q4
44  141.1500  2025Q1
45  144.3000  2025Q2

https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MGNkMzY3MTdhNjZlMTNiZDMxYjU4NDA4NTdjZWU0YmQ=&itmId=T20+&objL1=C30+C31+&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Q&startPrdDe=201401&endPrdDe=202502&outputFields=OBJ_NM+NM+ITM_NM+PRD_DE+&orgId=101&tblId=DT_1F02016

## 내수/수출출하지수

In [ ]:
수출출하지수1 = getKOSIS('DT_1F02016','Q','201401','202502','T21','101','C30')
수출출하지수2 = getKOSIS('DT_1F02016','Q','201401','202502','T21','101','C31')


# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [수출출하지수1,수출출하지수2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
수출출하지수 = reduce(lambda left, right: pd.merge(left, right, on="PRD_DE", how="outer"), dfs)
수출출하지수
수출출하지수['수출출하지수']=(수출출하지수['DT_x']+수출출하지수['DT_y'])/2
수출출하지수 = 수출출하지수.drop(columns=["DT_x","DT_y"])
수출출하지수

def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

수출출하지수['index']=수출출하지수['PRD_DE'].apply(to_quarter)
수출출하지수 = 수출출하지수.drop(columns=["PRD_DE"])
수출출하지수 = 수출출하지수.rename(columns={'DT': '수출출하지수'})
수출출하지수

      수출출하지수   index
0   155.9725  2014Q1
1   154.0005  2014Q2
2   150.3085  2014Q3
3   151.3075  2014Q4
4   153.2565  2015Q1
5   149.4950  2015Q2
6   144.8730  2015Q3
7   138.8920  2015Q4
8   138.8810  2016Q1
9   135.2145  2016Q2
10  126.9075  2016Q3
11  129.5710  2016Q4
12  119.6170  2017Q1
13  116.5035  2017Q2
14  105.4650  2017Q3
15  101.7905  2017Q4
16   98.2590  2018Q1
17  105.7875  2018Q2
18  105.8970  2018Q3
19  109.6450  2018Q4
20  110.8050  2019Q1
21  111.7300  2019Q2
22  113.3710  2019Q3
23  106.6635  2019Q4
24  105.3000  2020Q1
25   84.5000  2020Q2
26  104.2500  2020Q3
27  107.0000  2020Q4
28  103.7000  2021Q1
29   96.8000  2021Q2
30  100.0500  2021Q3
31  105.0500  2021Q4
32  109.0000  2022Q1
33  109.9500  2022Q2
34  120.8000  2022Q3
35  117.3000  2022Q4
36  119.7500  2023Q1
37  121.4000  2023Q2
38  120.5500  2023Q3
39  119.3000  2023Q4
40  121.7000  2024Q1
41  128.0000  2024Q2
42  129.9000  2024Q3
43  130.3000  2024Q4
44  137.1000  2025Q1
45  142.3500  2025Q2

In [ ]:
내수출하지수1 = getKOSIS('DT_1F02016','Q','201401','202502','T20','101','C30')
내수출하지수2 = getKOSIS('DT_1F02016','Q','201401','202502','T20','101','C31')


# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [내수출하지수1,내수출하지수2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
내수출하지수 = reduce(lambda left, right: pd.merge(left, right, on="PRD_DE", how="outer"), dfs)
내수출하지수
내수출하지수['내수출하지수']=(내수출하지수['DT_x']+내수출하지수['DT_y'])/2
내수출하지수 = 내수출하지수.drop(columns=["DT_x","DT_y"])
내수출하지수

def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

내수출하지수['index']=내수출하지수['PRD_DE'].apply(to_quarter)
내수출하지수 = 내수출하지수.drop(columns=["PRD_DE"])
내수출하지수 = 내수출하지수.rename(columns={'DT': '내수출하지수'})
내수출하지수

     내수출하지수   index
0   86.7405  2014Q1
1   76.6745  2014Q2
2   69.9075  2014Q3
3   66.3610  2014Q4
4   64.2700  2015Q1
5   65.8325  2015Q2
6   73.1780  2015Q3
7   77.0180  2015Q4
8   77.7615  2016Q1
9   86.1450  2016Q2
10  78.2515  2016Q3
11  72.4855  2016Q4
12  77.2820  2017Q1
13  85.7670  2017Q2
14  84.0730  2017Q3
15  86.3795  2017Q4
16  80.1290  2018Q1
17  84.8550  2018Q2
18  83.5255  2018Q3
19  82.2075  2018Q4
20  80.9085  2019Q1
21  91.8195  2019Q2
22  96.1130  2019Q3
23  99.9630  2019Q4
24  90.0500  2020Q1
25  80.4500  2020Q2
26  81.0000  2020Q3
27  89.0500  2020Q4
28  79.4500  2021Q1
29  75.8000  2021Q2
30  74.8000  2021Q3
31  80.6000  2021Q4
32  74.6500  2022Q1
33  73.5000  2022Q2
34  75.3500  2022Q3
35  78.1000  2022Q4
36  75.4000  2023Q1
37  77.9500  2023Q2
38  78.0000  2023Q3
39  77.3500  2023Q4
40  72.0000  2024Q1
41  72.6000  2024Q2
42  70.9000  2024Q3
43  69.3500  2024Q4
44  71.3500  2025Q1
45  66.2500  2025Q2

##생산능력지수 &가동률지수

https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MGNkMzY3MTdhNjZlMTNiZDMxYjU4NDA4NTdjZWU0YmQ=&itmId=T10+T20+&objL1=C30+C31+&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Q&startPrdDe=201401&endPrdDe=202502&outputFields=OBJ_NM+NM+ITM_NM+PRD_DE+&orgId=101&tblId=DT_1F32001

In [ ]:
생산능력지수1 = getKOSIS('DT_1F32001','Q','201401','202502','T10','101','C30')
생산능력지수2 = getKOSIS('DT_1F32001','Q','201401','202502','T10','101','C31')

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [생산능력지수1,생산능력지수2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
생산능력지수 = reduce(lambda left, right: pd.merge(left, right, on="PRD_DE", how="outer"), dfs)
생산능력지수
생산능력지수['생산능력지수']=(생산능력지수['DT_x']+생산능력지수['DT_y'])/2
생산능력지수 = 생산능력지수.drop(columns=["DT_x","DT_y"])
생산능력지수

def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

생산능력지수['index']=생산능력지수['PRD_DE'].apply(to_quarter)
생산능력지수 = 생산능력지수.drop(columns=["PRD_DE"])
생산능력지수 = 생산능력지수.rename(columns={'DT': '생산능력지수'})
생산능력지수

      생산능력지수   index
0   134.7225  2014Q1
1   135.1870  2014Q2
2   136.9580  2014Q3
3   137.5535  2014Q4
4   137.6245  2015Q1
5   136.2795  2015Q2
6   134.6695  2015Q3
7   134.6370  2015Q4
8   133.5430  2016Q1
9   131.5960  2016Q2
10  129.7570  2016Q3
11  128.8490  2016Q4
12  129.1070  2017Q1
13  127.9770  2017Q2
14  125.8965  2017Q3
15  124.5955  2017Q4
16  118.8945  2018Q1
17  114.3905  2018Q2
18  112.4235  2018Q3
19  112.0440  2018Q4
20  107.1235  2019Q1
21  104.9455  2019Q2
22  103.1110  2019Q3
23  101.9745  2019Q4
24  100.5500  2020Q1
25  100.6000  2020Q2
26   99.2500  2020Q3
27   99.5500  2020Q4
28  100.6000  2021Q1
29  100.9500  2021Q2
30  100.5500  2021Q3
31  101.1000  2021Q4
32  100.2000  2022Q1
33  100.5000  2022Q2
34  100.4000  2022Q3
35  102.2000  2022Q4
36  102.7500  2023Q1
37  103.0000  2023Q2
38  102.6000  2023Q3
39  104.1000  2023Q4
40  104.2500  2024Q1
41  104.5000  2024Q2
42  105.6500  2024Q3
43  106.1000  2024Q4
44  105.1000  2025Q1
45  107.3500  2025Q2

In [ ]:
가동률지수1 = getKOSIS('DT_1F32001','Q','201401','202502','T30','101','C30')
가동률지수2 = getKOSIS('DT_1F32001','Q','201401','202502','T30','101','C31')
# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [가동률지수1,가동률지수2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
가동률지수 = reduce(lambda left, right: pd.merge(left, right, on="PRD_DE", how="outer"), dfs)
가동률지수
가동률지수['가동률지수']=(가동률지수['DT_x']+가동률지수['DT_y'])/2
가동률지수 = 가동률지수.drop(columns=["DT_x","DT_y"])
가동률지수

def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

가동률지수['index']=가동률지수['PRD_DE'].apply(to_quarter)
가동률지수 = 가동률지수.drop(columns=["PRD_DE"])
가동률지수 = 가동률지수.rename(columns={'DT': '가동률지수'})
가동률지수

       가동률지수   index
0   109.8195  2014Q1
1   107.8225  2014Q2
2   102.6310  2014Q3
3   103.4900  2014Q4
4   111.5095  2015Q1
5   107.1530  2015Q2
6   107.9690  2015Q3
7   102.5900  2015Q4
8   103.5050  2016Q1
9   100.2165  2016Q2
10   95.3105  2016Q3
11   96.0190  2016Q4
12   91.2505  2017Q1
13   91.2180  2017Q2
14   86.1665  2017Q3
15   84.1205  2017Q4
16   83.4640  2018Q1
17   89.5690  2018Q2
18   92.1480  2018Q3
19   94.8335  2018Q4
20   98.7160  2019Q1
21  101.1080  2019Q2
22  107.6055  2019Q3
23  105.5335  2019Q4
24  104.1500  2020Q1
25   91.2000  2020Q2
26  101.5000  2020Q3
27  103.1000  2020Q4
28  102.3500  2021Q1
29   96.3500  2021Q2
30   99.0500  2021Q3
31  103.4500  2021Q4
32  108.3500  2022Q1
33  110.6500  2022Q2
34  118.9000  2022Q3
35  115.8000  2022Q4
36  116.5000  2023Q1
37  116.2000  2023Q2
38  117.8500  2023Q3
39  115.9000  2023Q4
40  113.0500  2024Q1
41  116.3000  2024Q2
42  118.2000  2024Q3
43  118.2500  2024Q4
44  127.9000  2025Q1
45  130.5000  2025Q2

##자동차

In [ ]:
자동차 = pd.read_csv('자동차.csv')

In [ ]:
자동차
자동차 = 자동차.drop(columns=["Unnamed: 0"])

In [ ]:
자동차

     index      KGM     kia
0   2014Q1  36671.0  432531
1   2014Q2  37564.0  444863
2   2014Q3  32012.0  390752
3   2014Q4  34800.0  438493
4   2015Q1  32915.0  410613
5   2015Q2  36885.0  454259
6   2015Q3  34074.0  386460
7   2015Q4  40890.0  474394
8   2016Q1  33666.0  384979
9   2016Q2  40911.0  404590
10  2016Q3  37106.0  330102
11  2016Q4  44161.0  433096
12  2017Q1  34228.0  378239
13  2017Q2  36117.0  385471
14  2017Q3  36306.0  389582
15  2017Q4  37034.0  351879
16  2018Q1  30664.0  339294
17  2018Q2  36446.0  388292
18  2018Q3  35136.0  336100
19  2018Q4  41063.0  405960
20  2019Q1  34851.0  348695
21  2019Q2  35426.0  388405
22  2019Q3  31086.0  350017
23  2019Q4  33872.0  366588
24  2020Q1  24139.0  301039
25  2020Q2  25280.0  301248
26  2020Q3  25350.0  343224
27  2020Q4  32647.0  355389
28  2021Q1  18619.0  361475
29  2021Q2  21695.0  385009
30  2021Q3  21840.0  319014
31  2021Q4  22342.0  348794
32  2022Q1  23278.0  334060
33  2022Q2  24431.0  355134
34  2022Q3  32749.0  364871
35  2022Q4  33502.0  395451
36  2023Q1  35113.0  437083
37  2023Q2  30032.0  429764
38  2023Q3  31254.0  358577
39  2023Q4  19700.0  390891
40  2024Q1  29326.0  396210
41  2024Q2  27239.0  413869
42  2024Q3  24078.0  357593
43  2024Q4  28781.0  379737
44  2025Q1  26009.0  393881
45  2025Q2  27263.0  417016

In [ ]:
자동차['자동차']=자동차['KGM']+자동차['kia']
자동차 = 자동차.drop(columns=["KGM","kia"])
자동차

     index       자동차
0   2014Q1  469202.0
1   2014Q2  482427.0
2   2014Q3  422764.0
3   2014Q4  473293.0
4   2015Q1  443528.0
5   2015Q2  491144.0
6   2015Q3  420534.0
7   2015Q4  515284.0
8   2016Q1  418645.0
9   2016Q2  445501.0
10  2016Q3  367208.0
11  2016Q4  477257.0
12  2017Q1  412467.0
13  2017Q2  421588.0
14  2017Q3  425888.0
15  2017Q4  388913.0
16  2018Q1  369958.0
17  2018Q2  424738.0
18  2018Q3  371236.0
19  2018Q4  447023.0
20  2019Q1  383546.0
21  2019Q2  423831.0
22  2019Q3  381103.0
23  2019Q4  400460.0
24  2020Q1  325178.0
25  2020Q2  326528.0
26  2020Q3  368574.0
27  2020Q4  388036.0
28  2021Q1  380094.0
29  2021Q2  406704.0
30  2021Q3  340854.0
31  2021Q4  371136.0
32  2022Q1  357338.0
33  2022Q2  379565.0
34  2022Q3  397620.0
35  2022Q4  428953.0
36  2023Q1  472196.0
37  2023Q2  459796.0
38  2023Q3  389831.0
39  2023Q4  410591.0
40  2024Q1  425536.0
41  2024Q2  441108.0
42  2024Q3  381671.0
43  2024Q4  408518.0
44  2025Q1  419890.0
45  2025Q2  444279.0

##기업데이터

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('임지오기업.csv')

In [ ]:
운송장비기업1 = df[df['매핑한 산업'] == "운송장비 제조업_자동차"]
운송장비기업2 = df[df['매핑한 산업'] == "운송장비 제조업_조선기타운수"]

In [ ]:
columns = ['EBITDA', '인건비']
grouped1 = 운송장비기업1.groupby('조사일')[columns].sum()
grouped1

                  EBITDA           인건비
조사일
2000-01-01  0.000000e+00  2.871476e+08
2000-04-01  0.000000e+00  4.273023e+08
2000-07-01  0.000000e+00  2.268228e+08
2000-10-01  3.597134e+12  3.581286e+09
2001-01-01  0.000000e+00  2.983169e+08
...                  ...           ...
2024-04-01  7.586095e+12  1.315979e+09
2024-07-01  5.126818e+12  1.523017e+09
2024-10-01  5.292829e+12  2.798115e+09
2025-01-01  6.110609e+12  1.280934e+09
2025-04-01  6.257252e+12 -1.279113e+09

[102 rows x 2 columns]

In [ ]:
grouped1 = grouped1.reset_index()

In [ ]:
grouped1['조사일']=pd.to_datetime(grouped1['조사일'])

# 분기(Quarter) 단위로 변환
grouped1["index"] = grouped1["조사일"].dt.to_period("Q")
grouped1 = grouped1.drop(columns=["조사일"])
print(grouped1)

grouped1

           EBITDA           인건비   index
0    0.000000e+00  2.871476e+08  2000Q1
1    0.000000e+00  4.273023e+08  2000Q2
2    0.000000e+00  2.268228e+08  2000Q3
3    3.597134e+12  3.581286e+09  2000Q4
4    0.000000e+00  2.983169e+08  2001Q1
..            ...           ...     ...
97   7.586095e+12  1.315979e+09  2024Q2
98   5.126818e+12  1.523017e+09  2024Q3
99   5.292829e+12  2.798115e+09  2024Q4
100  6.110609e+12  1.280934e+09  2025Q1
101  6.257252e+12 -1.279113e+09  2025Q2

[102 rows x 3 columns]

           EBITDA           인건비   index
0    0.000000e+00  2.871476e+08  2000Q1
1    0.000000e+00  4.273023e+08  2000Q2
2    0.000000e+00  2.268228e+08  2000Q3
3    3.597134e+12  3.581286e+09  2000Q4
4    0.000000e+00  2.983169e+08  2001Q1
..            ...           ...     ...
97   7.586095e+12  1.315979e+09  2024Q2
98   5.126818e+12  1.523017e+09  2024Q3
99   5.292829e+12  2.798115e+09  2024Q4
100  6.110609e+12  1.280934e+09  2025Q1
101  6.257252e+12 -1.279113e+09  2025Q2

[102 rows x 3 columns]

In [ ]:
mask = (grouped1["index"] >= pd.Period("2014Q1")) & (grouped1["index"] <= pd.Period("2025Q2"))
기업1= grouped1.loc[mask]
기업1
기업1['합산'] = 기업1['EBITDA']+기업1['인건비']
기업1

기업1 = 기업1.rename(columns={'EBITDA': 'EBITDA1'})
기업1 = 기업1.rename(columns={'인건비': '인건비1'})
기업1 = 기업1.rename(columns={'합산': '합산1'})

/tmp/ipython-input-2907447296.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기업1['합산'] = 기업1['EBITDA']+기업1['인건비']

In [ ]:
columns = ['EBITDA', '인건비']
grouped2 = 운송장비기업2.groupby('조사일')[columns].sum()
grouped2

                  EBITDA          인건비
조사일
2000-01-01  0.000000e+00   16826463.0
2000-04-01  0.000000e+00    5297307.0
2000-07-01  0.000000e+00    3647703.0
2000-10-01  7.867222e+11  723800341.0
2001-01-01  0.000000e+00   11942467.0
...                  ...          ...
2024-04-01  9.298956e+11  232153430.0
2024-07-01  1.118315e+12  202916546.0
2024-10-01  1.926277e+12 -407930775.0
2025-01-01  1.440408e+12  131225257.0
2025-04-01  1.780024e+12 -128677364.0

[102 rows x 2 columns]

In [ ]:
grouped2 = grouped2.reset_index()

In [ ]:
grouped2['조사일']=pd.to_datetime(grouped2['조사일'])

# 분기(Quarter) 단위로 변환
grouped2["index"] = grouped2["조사일"].dt.to_period("Q")
grouped2 = grouped2.drop(columns=["조사일"])
print(grouped2)

grouped2

           EBITDA          인건비   index
0    0.000000e+00   16826463.0  2000Q1
1    0.000000e+00    5297307.0  2000Q2
2    0.000000e+00    3647703.0  2000Q3
3    7.867222e+11  723800341.0  2000Q4
4    0.000000e+00   11942467.0  2001Q1
..            ...          ...     ...
97   9.298956e+11  232153430.0  2024Q2
98   1.118315e+12  202916546.0  2024Q3
99   1.926277e+12 -407930775.0  2024Q4
100  1.440408e+12  131225257.0  2025Q1
101  1.780024e+12 -128677364.0  2025Q2

[102 rows x 3 columns]

           EBITDA          인건비   index
0    0.000000e+00   16826463.0  2000Q1
1    0.000000e+00    5297307.0  2000Q2
2    0.000000e+00    3647703.0  2000Q3
3    7.867222e+11  723800341.0  2000Q4
4    0.000000e+00   11942467.0  2001Q1
..            ...          ...     ...
97   9.298956e+11  232153430.0  2024Q2
98   1.118315e+12  202916546.0  2024Q3
99   1.926277e+12 -407930775.0  2024Q4
100  1.440408e+12  131225257.0  2025Q1
101  1.780024e+12 -128677364.0  2025Q2

[102 rows x 3 columns]

In [ ]:
mask = (grouped2["index"] >= pd.Period("2014Q1")) & (grouped2["index"] <= pd.Period("2025Q2"))
기업2= grouped2.loc[mask]
기업2
기업2['합산'] = 기업2['EBITDA']+기업2['인건비']
기업2

기업2 = 기업2.rename(columns={'EBITDA': 'EBITDA2'})
기업2 = 기업2.rename(columns={'인건비': '인건비2'})
기업2 = 기업2.rename(columns={'합산': '합산2'})

/tmp/ipython-input-1747950282.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기업2['합산'] = 기업2['EBITDA']+기업2['인건비']

In [ ]:
기업1

          EBITDA1          인건비1   index           합산1
56   3.129183e+12  9.043311e+08  2014Q1  3.130087e+12
57   3.244810e+12  9.099992e+08  2014Q2  3.245720e+12
58   1.938718e+12  9.361093e+08  2014Q3  1.939654e+12
59   3.547278e+12  2.473065e+09  2014Q4  3.549751e+12
60   3.098155e+12  9.797514e+08  2015Q1  3.099134e+12
61   3.702805e+12  9.898881e+08  2015Q2  3.703795e+12
62   3.077155e+12  1.002433e+09  2015Q3  3.078158e+12
63   4.167052e+12  2.548467e+09  2015Q4  4.169601e+12
64   3.575275e+12  9.941619e+08  2016Q1  3.576269e+12
65   3.746672e+12  9.862464e+08  2016Q2  3.747659e+12
66   1.966166e+12  9.824683e+08  2016Q3  1.967148e+12
67   3.571522e+12  2.568507e+09  2016Q4  3.574090e+12
68   3.162592e+12  9.820316e+08  2017Q1  3.163574e+12
69   3.171221e+12  9.574555e+08  2017Q2  3.172179e+12
70   1.361176e+12  1.056179e+09  2017Q3  1.362232e+12
71   2.191291e+12  2.621046e+09  2017Q4  2.193912e+12
72   1.834870e+12  9.509770e+08  2018Q1  1.835821e+12
73   2.447416e+12  9.531603e+08  2018Q2  2.448369e+12
74   1.251509e+12  9.813593e+08  2018Q3  1.252490e+12
75   2.403309e+12  2.544548e+09  2018Q4  2.405854e+12
76   2.505499e+12  1.004388e+09  2019Q1  2.506503e+12
77   3.212824e+12  1.008705e+09  2019Q2  3.213833e+12
78   2.257713e+12  1.020837e+09  2019Q3  2.258733e+12
79   3.135677e+12  2.953248e+09  2019Q4  3.138630e+12
80   2.322684e+12  1.006084e+09  2020Q1  2.323690e+12
81   2.355845e+12  9.992368e+08  2020Q2  2.356844e+12
82   2.062073e+12  9.738160e+08  2020Q3  2.063047e+12
83   2.767082e+12  2.858151e+09  2020Q4  2.769940e+12
84   3.161267e+12  1.012395e+09  2021Q1  3.162279e+12
85   3.173057e+12  9.915924e+08  2021Q2  3.174049e+12
86   1.855708e+12  1.061514e+09  2021Q3  1.856769e+12
87   3.719270e+12  2.922068e+09  2021Q4  3.722192e+12
88   2.246345e+12  1.162432e+09  2022Q1  2.247507e+12
89   3.595822e+12  1.151966e+09  2022Q2  3.596974e+12
90   3.121327e+12  1.139940e+09  2022Q3  3.122467e+12
91   6.182827e+12  2.646220e+09  2022Q4  6.185473e+12
92   4.689545e+12  1.224340e+09  2023Q1  4.690769e+12
93   7.511819e+12  1.241833e+09  2023Q2  7.513060e+12
94   4.308740e+12  1.282809e+09  2023Q3  4.310023e+12
95   5.902100e+12  2.873703e+09  2023Q4  5.904974e+12
96   6.214403e+12  1.283610e+09  2024Q1  6.215686e+12
97   7.586095e+12  1.315979e+09  2024Q2  7.587411e+12
98   5.126818e+12  1.523017e+09  2024Q3  5.128341e+12
99   5.292829e+12  2.798115e+09  2024Q4  5.295627e+12
100  6.110609e+12  1.280934e+09  2025Q1  6.111890e+12
101  6.257252e+12 -1.279113e+09  2025Q2  6.255973e+12

In [ ]:
기업2

          EBITDA2          인건비2   index           합산2
56  -1.967986e+11  7.092543e+07  2014Q1 -1.967277e+11
57   2.004036e+11  1.347470e+08  2014Q2  2.005384e+11
58  -3.874877e+11  1.015454e+08  2014Q3 -3.873862e+11
59   1.334126e+11  2.239488e+08  2014Q4  1.336366e+11
60   1.881541e+11  1.116292e+08  2015Q1  1.882657e+11
61  -1.692743e+12  1.281790e+08  2015Q2 -1.692615e+12
62   1.074329e+11  7.789841e+07  2015Q3  1.075108e+11
63  -1.543518e+10  1.734331e+08  2015Q4 -1.526175e+10
64   2.451261e+11  1.007656e+08  2016Q1  2.452268e+11
65  -2.999220e+09  1.340899e+08  2016Q2 -2.865130e+09
66   3.113636e+11  1.037356e+08  2016Q3  3.114674e+11
67   1.667301e+11  1.717016e+08  2016Q4  1.669018e+11
68   2.097977e+11  8.764710e+07  2017Q1  2.098853e+11
69   2.148878e+11  8.570695e+07  2017Q2  2.149735e+11
70   1.828872e+11  7.404251e+07  2017Q3  1.829612e+11
71  -5.746599e+11  5.009976e+08  2017Q4 -5.741589e+11
72   3.078986e+10  6.984296e+07  2018Q1  3.085970e+10
73   1.911599e+09  6.620574e+07  2018Q2  1.977805e+09
74  -2.185832e+10  6.529455e+07  2018Q3 -2.179302e+10
75  -3.028113e+11  1.948041e+08  2018Q4 -3.026165e+11
76   3.610963e+10  6.957763e+07  2019Q1  3.617920e+10
77   2.930669e+10  6.799469e+07  2019Q2  2.937468e+10
78  -2.920798e+11  6.889240e+07  2019Q3 -2.920109e+11
79   3.171894e+09  1.007430e+09  2019Q4  4.179324e+09
80   1.075495e+11  6.350477e+07  2020Q1  1.076130e+11
81  -3.306180e+11  1.598561e+08  2020Q2 -3.304581e+11
82   2.062156e+11  1.093759e+08  2020Q3  2.063250e+11
83  -1.852546e+11  1.429700e+09  2020Q4 -1.838249e+11
84  -3.036860e+11  1.046918e+08  2021Q1 -3.035813e+11
85  -7.853164e+11  1.117643e+08  2021Q2 -7.852046e+11
86   2.270437e+11  1.234912e+08  2021Q3  2.271672e+11
87  -7.328414e+11  1.524023e+09  2021Q4 -7.313174e+11
88  -1.992457e+11  1.207662e+08  2022Q1 -1.991250e+11
89  -1.470218e+11  1.209438e+08  2022Q2 -1.469008e+11
90   5.935830e+10  1.253488e+08  2022Q3  5.948364e+10
91  -1.000110e+11  2.095980e+08  2022Q4 -9.980137e+10
92   3.299788e+11  1.508718e+08  2023Q1  3.301296e+11
93   3.622540e+11  1.732429e+08  2023Q2  3.624273e+11
94   3.693065e+11  1.662730e+08  2023Q3  3.694727e+11
95   7.318450e+11  3.690835e+08  2023Q4  7.322141e+11
96   2.840976e+11  2.148154e+08  2024Q1  2.843125e+11
97   9.298956e+11  2.321534e+08  2024Q2  9.301278e+11
98   1.118315e+12  2.029165e+08  2024Q3  1.118518e+12
99   1.926277e+12 -4.079308e+08  2024Q4  1.925869e+12
100  1.440408e+12  1.312253e+08  2025Q1  1.440539e+12
101  1.780024e+12 -1.286774e+08  2025Q2  1.779896e+12

In [ ]:
# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [기업1,기업2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
기업 = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
기업

기업['EBITDA']=기업['EBITDA1']+기업['EBITDA2']
기업['인건비']=기업['인건비1']+기업['인건비2']
기업['합산']=기업['합산1']+기업['합산2']
기업

,EBITDA1,인건비1,index,합산1,EBITDA2,인건비2,합산2,EBITDA,인건비,합산
0,3.129183e+12,9.043311e+08,2014Q1,3.130087e+12,-1.967986e+11,7.092543e+07,-1.967277e+11,2.932384e+12,9.752566e+08,2.933360e+12
1,3.244810e+12,9.099992e+08,2014Q2,3.245720e+12,2.004036e+11,1.347470e+08,2.005384e+11,3.445213e+12,1.044746e+09,3.446258e+12
2,1.938718e+12,9.361093e+08,2014Q3,1.939654e+12,-3.874877e+11,1.015454e+08,-3.873862e+11,1.551231e+12,1.037655e+09,1.552268e+12
3,3.547278e+12,2.473065e+09,2014Q4,3.549751e+12,1.334126e+11,2.239488e+08,1.336366e+11,3.680691e+12,2.697014e+09,3.683388e+12
4,3.098155e+12,9.797514e+08,2015Q1,3.099134e+12,1.881541e+11,1.116292e+08,1.882657e+11,3.286309e+12,1.091381e+09,3.287400e+12
5,3.702805e+12,9.898881e+08,2015Q2,3.703795e+12,-1.692743e+12,1.281790e+08,-1.692615e+12,2.010062e+12,1.118067e+09,2.011180e+12
6,3.077155e+12,1.002433e+09,2015Q3,3.078158e+12,1.074329e+11,7.789841e+07,1.075108e+11,3.184588e+12,1.080332e+09,3.185668e+12
7,4.167052e+12,2.548467e+09,2015Q4,4.169601e+12,-1.543518e+10,1.734331e+08,-1.526175e+10,4.151617e+12,2.721900e+09,4.154339e+12
8,3.575275e+12,9.941619e+08,2016Q1,3.576269e+12,2.451261e+11,1.007656e+08,2.452268e+11,3.820401e+12,1.094928e+09,3.821496e+12
9,3.746672e+12,9.862464e+08,2016Q2,3.747659e+12,-2.999220e+09,1.340899e+08,-2.865130e+09,3.743673e+12,1.120336e+09,3.744794e+12
10,1.966166e+12,9.824683e+08,2016Q3,1.967148e+12,3.113636e+11,1.037356e+08,3.114674e+11,2.277529e+12,1.086204e+09,2.278615e+12
11,3.571522e+12,2.568507e+09,2016Q4,3.574090e+12,1.667301e+11,1.717016e+08,1.669018e+11,3.738252e+12,2.740209e+09,3.740992e+12
12,3.162592e+12,9.820316e+08,2017Q1,3.163574e+12,2.097977e+11,8.764710e+07,2.098853e+11,3.372390e+12,1.069679e+09,3.373460e+12
13,3.171221e+12,9.574555e+08,2017Q2,3.172179e+12,2.148878e+11,8.570695e+07,2.149735e+11,3.386109e+12,1.043162e+09,3.387152e+12
14,1.361176e+12,1.056179e+09,2017Q3,1.362232e+12,1.828872e+11,7.404251e+07,1.829612e+11,1.544063e+12,1.130221e+09,1.545193e+12
15,2.191291e+12,2.621046e+09,2017Q4,2.193912e+12,-5.746599e+11,5.009976e+08,-5.741589e+11,1.616631e+12,3.122044e+09,1.619754e+12
16,1.834870e+12,9.509770e+08,2018Q1,1.835821e+12,3.078986e+10,6.984296e+07,3.085970e+10,1.865660e+12,1.020820e+09,1.866681e+12
17,2.447416e+12,9.531603e+08,2018Q2,2.448369e+12,1.911599e+09,6.620574e+07,1.977805e+09,2.449327e+12,1.019366e+09,2.450347e+12
18,1.251509e+12,9.813593e+08,2018Q3,1.252490e+12,-2.185832e+10,6.529455e+07,-2.179302e+10,1.229651e+12,1.046654e+09,1.230697e+12
19,2.403309e+12,2.544548e+09,2018Q4,2.405854e+12,-3.028113e+11,1.948041e+08,-3.026165e+11,2.100498e+12,2.739352e+09,2.103238e+12
20,2.505499e+12,1.004388e+09,2019Q1,2.506503e+12,3.610963e+10,6.957763e+07,3.617920e+10,2.541608e+12,1.073966e+09,2.542682e+12
21,3.212824e+12,1.008705e+09,2019Q2,3.213833e+12,2.930669e+10,6.799469e+07,2.937468e+10,3.242131e+12,1.076699e+09,3.243208e+12
22,2.257713e+12,1.020837e+09,2019Q3,2.258733e+12,-2.920798e+11,6.889240e+07,-2.920109e+11,1.965633e+12,1.089729e+09,1.966723e+12
23,3.135677e+12,2.953248e+09,2019Q4,3.138630e+12,3.171894e+09,1.007430e+09,4.179324e+09,3.138849e+12,3.960678e+09,3.142809e+12
24,2.322684e+12,1.006084e+09,2020Q1,2.323690e+12,1.075495e+11,6.350477e+07,1.076130e+11,2.430233e+12,1.069589e+09,2.431303e+12
25,2.355845e+12,9.992368e+08,2020Q2,2.356844e+12,-3.306180e+11,1.598561e+08,-3.304581e+11,2.025227e+12,1.159093e+09,2.026386e+12
26,2.062073e+12,9.738160e+08,2020Q3,2.063047e+12,2.062156e+11,1.093759e+08,2.063250e+11,2.268289e+12,1.083192e+09,2.269372e+12
27,2.767082e+12,2.858151e+09,2020Q4,2.769940e+12,-1.852546e+11,1.429700e+09,-1.838249e+11,2.581828e+12,4.287850e+09,2.586115e+12
28,3.161267e+12,1.012395e+09,2021Q1,3.162279e+12,-3.036860e+11,1.046918e+08,-3.035813e+11,2.857581e+12,1.117086e+09,2.858698e+12
29,3.173057e+12,9.915924e+08,2021Q2,3.174049e+12,-7.853164e+11,1.117643e+08,-7.852046e+11,2.387741e+12,1.103357e+09,2.388844e+12
30,1.855708e+12,1.061514e+09,2021Q3,1.856769e+12,2.270437e+11,1.234912e+08,2.271672e+11,2.082752e+12,1.185005e+09,2.083937e+12
31,3.719270e+12,2.922068e+09,2021Q4,3.722192e+12,-7.328414e+11,1.524023e+09,-7.313174e+11,2.986429e+12,4.446091e+09,2.990875e+12
32,2.246345e+12,1.162432e+09,2022Q1,2.247507e+12,-1.992457e+11,1.207662e+08,-1.991250e+11,2.047099e+12,1.283198e+09,2.048382e+12
33,3.595822e+12,1.151966e+09,2022Q2,3.596974e+12,-1.470218e+11,1.209438e+08,-1.469008e+11,3.448801e+12,1.272910e+09,3.450074e+12
34,3.121327e+12,1.139940e+09,2022Q3,3.122467e+12,5.935830e+10,1.253488e+08,5.948364e+10,3.180686e+12,1.265289e+09,3.181951e+12
35,6.182827e+12,2.646220e+09,2022Q4,6.185473e+12,-1.000110e+11,2.095980e+08,-9.980137e+10,6.082816e+12,2.855818e+09,6.085671e+12
36,4.689545e+12,1.224340e+09,2023Q1,4.690769e+12,3.299788e+11,1.508718e+08,3.301296e+11,5.019523e+12,1.375212e+09,5.020899e+12
37,7.511819e+12,1.241833e+09,2023Q2,7.513060e+12,3.622540e+11,1.732429e+08,3.624273e+11,7.874073e+12,1.415075e+09,7.875488e+12
38,4.308740e+12,1.282809e+09,2023Q3,4.310023e+12,3.693065e+11,1.662730e+08,3.694727e+11,4.678047e+12,1.449082e+09,4.679496e+12
39,5.902100e+12,2.873703e+09,2023Q4,5.904974e+12,7.318450e+11,3.690835e+08,7.322141e+11,6.633945e+12,3.242786e+09,6.637188e+12
40,6.214403e+12,1.283610e+09,2024Q1,6.215686e+12,2.840976e+11,2.148154e+08,2.843125e+11,6.498500e+12,1.498425e+09,6.499999e+12
41,7.586095e+12,1.315979e+09,2024Q2,7.587411e+12,9.298956e+11,2.321534e+08,9.301278e+11,8.515991e+12,1.548133e+09,8.517539e+12
42,5.126818e+12,1.523017e+09,2024Q3,5.128341e+12,1.118315e+12,2.029165e+08,1.118518e+12,6.245133e+12,1.725933e+09,6.246859e+12
43,5.292829e+12,2.798115e+09,2024Q4,5.295627e+12,1.926277e+12,-4.079308e+08,1.925869e+12,7.219106e+12,2.390184e+09,7.221496e+12
44,6.110609e+12,1.280934e+09,2025Q1,6.111890e+12,1.440408e+12,1.312253e+08,1.440539e+12,7.551017e+12,1.412159e+09,7.552429e+12
45,6.257252e+12,-1.279113e+09,2025Q2,6.255973e+12,1.780024e+12,-1.286774e+08,1.779896e+12,8.037276e+12,-1.407790e+09,8.035868e+12

In [ ]:
기업 = 기업.drop(columns=["EBITDA1","EBITDA2","인건비1","인건비2","합산1","합산2"])
기업

     index        EBITDA           인건비            합산
0   2014Q1  2.932384e+12  9.752566e+08  2.933360e+12
1   2014Q2  3.445213e+12  1.044746e+09  3.446258e+12
2   2014Q3  1.551231e+12  1.037655e+09  1.552268e+12
3   2014Q4  3.680691e+12  2.697014e+09  3.683388e+12
4   2015Q1  3.286309e+12  1.091381e+09  3.287400e+12
5   2015Q2  2.010062e+12  1.118067e+09  2.011180e+12
6   2015Q3  3.184588e+12  1.080332e+09  3.185668e+12
7   2015Q4  4.151617e+12  2.721900e+09  4.154339e+12
8   2016Q1  3.820401e+12  1.094928e+09  3.821496e+12
9   2016Q2  3.743673e+12  1.120336e+09  3.744794e+12
10  2016Q3  2.277529e+12  1.086204e+09  2.278615e+12
11  2016Q4  3.738252e+12  2.740209e+09  3.740992e+12
12  2017Q1  3.372390e+12  1.069679e+09  3.373460e+12
13  2017Q2  3.386109e+12  1.043162e+09  3.387152e+12
14  2017Q3  1.544063e+12  1.130221e+09  1.545193e+12
15  2017Q4  1.616631e+12  3.122044e+09  1.619754e+12
16  2018Q1  1.865660e+12  1.020820e+09  1.866681e+12
17  2018Q2  2.449327e+12  1.019366e+09  2.450347e+12
18  2018Q3  1.229651e+12  1.046654e+09  1.230697e+12
19  2018Q4  2.100498e+12  2.739352e+09  2.103238e+12
20  2019Q1  2.541608e+12  1.073966e+09  2.542682e+12
21  2019Q2  3.242131e+12  1.076699e+09  3.243208e+12
22  2019Q3  1.965633e+12  1.089729e+09  1.966723e+12
23  2019Q4  3.138849e+12  3.960678e+09  3.142809e+12
24  2020Q1  2.430233e+12  1.069589e+09  2.431303e+12
25  2020Q2  2.025227e+12  1.159093e+09  2.026386e+12
26  2020Q3  2.268289e+12  1.083192e+09  2.269372e+12
27  2020Q4  2.581828e+12  4.287850e+09  2.586115e+12
28  2021Q1  2.857581e+12  1.117086e+09  2.858698e+12
29  2021Q2  2.387741e+12  1.103357e+09  2.388844e+12
30  2021Q3  2.082752e+12  1.185005e+09  2.083937e+12
31  2021Q4  2.986429e+12  4.446091e+09  2.990875e+12
32  2022Q1  2.047099e+12  1.283198e+09  2.048382e+12
33  2022Q2  3.448801e+12  1.272910e+09  3.450074e+12
34  2022Q3  3.180686e+12  1.265289e+09  3.181951e+12
35  2022Q4  6.082816e+12  2.855818e+09  6.085671e+12
36  2023Q1  5.019523e+12  1.375212e+09  5.020899e+12
37  2023Q2  7.874073e+12  1.415075e+09  7.875488e+12
38  2023Q3  4.678047e+12  1.449082e+09  4.679496e+12
39  2023Q4  6.633945e+12  3.242786e+09  6.637188e+12
40  2024Q1  6.498500e+12  1.498425e+09  6.499999e+12
41  2024Q2  8.515991e+12  1.548133e+09  8.517539e+12
42  2024Q3  6.245133e+12  1.725933e+09  6.246859e+12
43  2024Q4  7.219106e+12  2.390184e+09  7.221496e+12
44  2025Q1  7.551017e+12  1.412159e+09  7.552429e+12
45  2025Q2  8.037276e+12 -1.407790e+09  8.035868e+12

##전체 데이터 합산

In [ ]:
from functools import reduce
import pandas as pd

# 모든 데이터프레임의 index 컬럼을 문자열로 변환
for df in [df_final,생산지수, 내수출하지수, 수출출하지수, 생산능력지수, 가동률지수,자동차,기업]:
    df['index'] = df['index'].astype(str)

# 리스트에 넣고 합치기
dfs = [df_final,생산지수, 내수출하지수, 수출출하지수, 생산능력지수, 가동률지수,자동차,기업]
df_merged = reduce(lambda left, right: pd.merge(left, right, on='index', how='outer'), dfs)

In [ ]:
df_merged
df_merged = df_merged[['index'] + [col for col in df_merged.columns if col != 'index']]

In [ ]:
df_merged

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,...,운송장비 제조업,생산지수,내수출하지수,수출출하지수,생산능력지수,가동률지수,자동차,EBITDA,인건비,합산
0,2014Q1,83.833333,92.666667,91.500000,87.833333,91.666667,96.000000,101.833333,94.000000,95.333333,...,17740.3,141.9175,86.7405,155.9725,134.7225,109.8195,469202.0,2.932384e+12,9.752566e+08,2.933360e+12
1,2014Q2,85.833333,102.000000,100.000000,95.166667,103.500000,96.000000,102.833333,99.666667,96.166667,...,17944.4,139.0690,76.6745,154.0005,135.1870,107.8225,482427.0,3.445213e+12,1.044746e+09,3.446258e+12
2,2014Q3,76.333333,86.500000,88.666667,83.666667,91.500000,85.500000,101.833333,90.166667,95.666667,...,17202.3,134.2330,69.9075,150.3085,136.9580,102.6310,422764.0,1.551231e+12,1.037655e+09,1.552268e+12
3,2014Q4,74.166667,93.833333,91.833333,89.666667,99.166667,93.666667,102.500000,97.500000,95.333333,...,16510.7,132.9790,66.3610,151.3075,137.5535,103.4900,473293.0,3.680691e+12,2.697014e+09,3.683388e+12
4,2015Q1,73.000000,87.666667,88.333333,86.500000,94.500000,83.666667,103.666667,91.666667,95.166667,...,16388.1,135.2305,64.2700,153.2565,137.6245,111.5095,443528.0,3.286309e+12,1.091381e+09,3.287400e+12
5,2015Q2,74.833333,92.666667,92.500000,89.500000,96.833333,84.666667,103.833333,95.333333,94.666667,...,17144.1,131.1905,65.8325,149.4950,136.2795,107.1530,491144.0,2.010062e+12,1.118067e+09,2.011180e+12
6,2015Q3,64.166667,85.833333,87.333333,82.833333,93.000000,80.166667,104.000000,90.333333,91.000000,...,17627.4,130.0310,73.1780,144.8730,134.6695,107.9690,420534.0,3.184588e+12,1.080332e+09,3.185668e+12
7,2015Q4,73.333333,87.333333,87.000000,86.833333,95.166667,80.833333,98.666667,92.500000,95.833333,...,17287.4,125.2675,77.0180,138.8920,134.6370,102.5900,515284.0,4.151617e+12,2.721900e+09,4.154339e+12
8,2016Q1,65.166667,82.500000,84.166667,82.666667,88.166667,77.000000,103.833333,86.166667,91.666667,...,17222.6,126.1460,77.7615,138.8810,133.5430,103.5050,418645.0,3.820401e+12,1.094928e+09,3.821496e+12
9,2016Q2,62.833333,80.500000,89.333333,76.000000,87.166667,68.666667,97.166667,85.833333,88.833333,...,17901.5,123.4555,86.1450,135.2145,131.5960,100.2165,445501.0,3.743673e+12,1.120336e+09,3.744794e+12
10,2016Q3,55.000000,69.000000,81.166667,64.500000,76.666667,63.166667,96.166667,73.333333,87.833333,...,16936.2,115.9965,78.2515,126.9075,129.7570,95.3105,367208.0,2.277529e+12,1.086204e+09,2.278615e+12
11,2016Q4,56.333333,69.666667,76.500000,69.833333,77.666667,71.000000,95.500000,77.666667,88.833333,...,17089.2,115.6245,72.4855,129.5710,128.8490,96.0190,477257.0,3.738252e+12,2.740209e+09,3.740992e+12
12,2017Q1,59.333333,73.000000,74.500000,72.333333,77.833333,75.833333,94.333333,78.333333,87.333333,...,16784.1,109.4050,77.2820,119.6170,129.1070,91.2505,412467.0,3.372390e+12,1.069679e+09,3.373460e+12
13,2017Q2,57.833333,62.000000,63.333333,63.666667,69.333333,75.166667,93.666667,68.666667,87.833333,...,16340.2,110.7700,85.7670,116.5035,127.9770,91.2180,421588.0,3.386109e+12,1.043162e+09,3.387152e+12
14,2017Q3,53.500000,55.166667,56.000000,61.500000,65.500000,73.833333,96.500000,65.500000,83.166667,...,16267.9,101.0260,84.0730,105.4650,125.8965,86.1665,425888.0,1.544063e+12,1.130221e+09,1.545193e+12
15,2017Q4,56.166667,58.500000,61.833333,60.000000,68.833333,76.833333,92.833333,67.166667,83.000000,...,15105.1,99.4645,86.3795,101.7905,124.5955,84.1205,388913.0,1.616631e+12,3.122044e+09,1.619754e+12
16,2018Q1,58.833333,59.000000,62.500000,60.833333,68.666667,77.666667,100.333333,69.833333,87.500000,...,15331.1,94.8195,80.1290,98.2590,118.8945,83.4640,369958.0,1.865660e+12,1.020820e+09,1.866681e+12
17,2018Q2,60.333333,66.166667,69.500000,67.000000,72.500000,75.666667,99.500000,75.666667,87.500000,...,16055.8,100.2770,84.8550,105.7875,114.3905,89.5690,424738.0,2.449327e+12,1.019366e+09,2.450347e+12
18,2018Q3,54.666667,64.833333,71.500000,66.666667,75.000000,76.666667,95.833333,74.500000,84.333333,...,15690.5,101.0000,83.5255,105.8970,112.4235,92.1480,371236.0,1.229651e+12,1.046654e+09,1.230697e+12
19,2018Q4,60.333333,77.666667,81.000000,77.000000,83.833333,83.000000,98.666667,85.833333,88.000000,...,16859.1,103.9620,82.2075,109.6450,112.0440,94.8335,447023.0,2.100498e+12,2.739352e+09,2.103238e+12
20,2019Q1,69.333333,90.166667,96.333333,81.666667,90.500000,86.666667,101.666667,88.333333,90.166667,...,15836.3,103.0150,80.9085,110.8050,107.1235,98.7160,383546.0,2.541608e+12,1.073966e+09,2.542682e+12
21,2019Q2,75.333333,95.166667,96.833333,90.166667,99.666667,93.333333,100.166667,99.833333,90.833333,...,16392.2,106.1700,91.8195,111.7300,104.9455,101.1080,423831.0,3.242131e+12,1.076699e+09,3.243208e+12
22,2019Q3,75.500000,94.166667,92.333333,90.500000,97.833333,95.333333,100.333333,97.833333,92.833333,...,15752.5,109.6185,96.1130,113.3710,103.1110,107.6055,381103.0,1.965633e+12,1.089729e+09,1.966723e+12
23,2019Q4,78.333333,99.500000,100.833333,96.333333,103.500000,93.333333,103.000000,102.333333,92.833333,...,16453.5,106.7585,99.9630,106.6635,101.9745,105.5335,400460.0,3.138849e+12,3.960678e+09,3.142809e+12
24,2020Q1,67.833333,75.000000,76.333333,75.166667,77.666667,77.166667,103.166667,77.000000,88.666667,...,14998.7,103.4000,90.0500,105.3000,100.5500,104.1500,325178.0,2.430233e+12,1.069589e+09,2.431303e+12
25,2020Q2,38.666667,46.666667,47.500000,53.500000,51.833333,47.833333,117.833333,50.166667,69.333333,...,12910.3,92.1500,80.4500,84.5000,100.6000,91.2000,326528.0,2.025227e+12,1.159093e+09,2.026386e+12
26,2020Q3,56.833333,57.833333,59.666667,64.666667,66.000000,59.000000,107.333333,62.833333,78.833333,...,14445.5,101.0500,81.0000,104.2500,99.2500,101.5000,368574.0,2.268289e+12,1.083192e+09,2.269372e+12
27,2020Q4,78.500000,72.166667,70.000000,82.166667,81.166667,74.500000,104.833333,82.000000,88.500000,...,15424.1,103.3500,89.0500,107.0000,99.5500,103.1000,388036.0,2.581828e+12,4.287850e+09,2.586115e+12
28,2021Q1,76.500000,82.500000,82.666667,87.833333,89.666667,81.500000,96.500000,89.833333,92.833333,...,15767.7,100.5500,79.4500,103.7000,100.6000,102.3500,380094.0,2.857581e+12,1.117086e+09,2.858698e+12
29,2021Q2,83.666667,105.666667,99.500000,103.666667,104.500000,105.000000,100.166667,104.166667,92.166667,...,15586.0,97.3500,75.8000,96.8000,100.9500,96.3500,406704.0,2.387741e+12,1.103357e+09,2.388844e+12
30,2021Q3,82.000000,103.666667,109.500000,98.666667,100.000000,98.666667,101.166667,101.166667,92.333333,...,14768.8,98.4000,74.8000,100.0500,100.5500,99.0500,340854.0,2.082752e+12,1.185005e+09,2.083937e+12
31,2021Q4,79.666667,88.333333,94.833333,84.666667,91.166667,95.333333,101.833333,90.500000,92.500000,...,15254.0,104.6500,80.6000,105.0500,101.1000,103.4500,371136.0,2.986429e+12,4.446091e+09,2.990875e+12
32,2022Q1,81.000000,101.166667,105.833333,97.000000,99.000000,97.666667,101.666667,99.500000,95.833333,...,16478.3,107.8000,74.6500,109.0000,100.2000,108.3500,357338.0,2.047099e+12,1.283198e+09,2.048382e+12
33,2022Q2,75.500000,99.833333,98.666667,95.833333,103.500000,98.000000,103.666667,103.000000,93.833333,...,16097.9,111.4500,73.5000,109.9500,100.5000,110.6500,379565.0,3.448801e+12,1.272910e+09,3.450074e+12
34,2022Q3,81.333333,111.833333,115.333333,104.166667,110.166667,100.500000,101.000000,111.333333,96.500000,...,18333.3,119.0000,75.3500,120.8000,100.4000,118.9000,397620.0,3.180686e+12,1.265289e+09,3.181951e+12
35,2022Q4,87.000000,121.833333,121.666667,112.333333,117.333333,105.833333,95.500000,117.333333,98.166667,...,17232.2,119.2500,78.1000,117.3000,102.2000,115.8000,428953.0,6.082816e+12,2.855818e+09,6.085671e+12
36,2023Q1,92.166667,115.166667,113.666667,107.333333,112.000000,98.166667,97.500000,111.166667,100.166667,...,19402.9,121.3000,75.4000,119.7500,102.7500,116.5000,472196.0,5.019523e+12,1.375212e+09,5.020899e+12
37,2023Q2,97.000000,119.833333,120.833333,110.333333,111.000000,100.500000,95.500000,113.000000,100.333333,...,19923.6,124.7500,77.9500,121.4000,103.0000,116.2000,459796.0,7.874073e+12,1.415075e+09,7.875488e+12
38,2023Q3,97.833333,118.333333,121.500000,111.500000,111.166667,101.666667,94.666667,111.833333,103.500000,...,20607.6,125.7500,78.0000,120.5500,102.6000,117.8500,389831.0,4.678047e+12,1.449082e+09,4.679496e+12
39,2023Q4,93.500000,105.666667,107.000000,96.333333,99.500000,92.000000,101.333333,97.666667,101.500000,...,19729.6,125.7500,77.3500,119.3000,104.1000,115.9000,410591.0,6.633945e+12,3.242786e+09,6.637188e+12
40,2024Q1,85.500000,97.833333,101.500000,91.000000,94.166667,84.000000,102.666667,95.166667,96.500000,...,19419.5,124.2000,72.0000,121.7000,104.2500,113.0500,425536.0,6.498500e+12,1.498425e+09,6.499999e+12
41,2024Q2,95.500000,105.500000,105.833333,100.500000,99.500000,90.333333,97.833333,98.833333,95.333333,...,20801.8,128.8000,72.6000,128.0000,104.5000,116.3000,441108.0,8.515991e+12,1.548133e+09,8.517539e+12
42,2024Q3,92.833333,99.666667,102.666667,93.000000,96.166667,89.000000,106.166667,96.500000,95.000000,...,21740.3,131.5000,70.9000,129.9000,105.6500,118.2000,381671.0,6.245133e+12,1.725933e+09,6.246859e+12
43,2024Q4,92.000000,100.333333,101.166667,95.000000,96.000000,92.833333,104.500000,93.666667,97.166667,...,20950.9,130.6500,69.3500,130.3000,106.1000,118.2500,408518.0,7.219106e+12,2.390184e+09,7.221496e+12
44,2025Q1,86.666667,91.000000,98.166667,86.666667,92.166667,83.833333,100.833333,90.166667,96.000000,...,20621.7,141.1500,71.3500,137.1000,105.1000,127.9000,419890.0,7.551017e+12,1.412159e+09,7.552429e+12
45,2025Q2,89.833333,99.166667,103.166667,94.333333,95.666667,86.833333,100.500000,94.000000,97.166667,...,21412.0,144.3000,66.2500,142.3500,107.3500,130.5000,444279.0,8.037276e+12,-1.407790e+09,8.035868e+12

In [ ]:
df_merged.to_csv('운송장비.csv')

#데이터QoQ반환

In [ ]:
import pandas as pd

# df는 위의 데이터프레임
df_qoq = df_merged.copy()

# 분기 순서대로 정렬 (혹시 index가 문자열일 경우를 대비)
df_qoq = df_qoq.sort_values('index')

# 수치형 컬럼만 선택 (index 제외)
num_cols = df_qoq.select_dtypes(include=['number']).columns

# 전분기 대비 증감률 (%) 계산
df_qoq[num_cols] = df_qoq[num_cols].pct_change() * 100

# 결과 확인
print(df_qoq.head())

    index    업황실적BSI    매출실적BSI    수출실적BSI  내수판매실적BSI    생산실적BSI  신규수주실적BSI  \
0  2014Q1        NaN        NaN        NaN        NaN        NaN        NaN
1  2014Q2   2.385686  10.071942   9.289617   8.349146  12.909091   0.000000
2  2014Q3 -11.067961 -15.196078 -11.333333 -12.084063 -11.594203 -10.937500
3  2014Q4  -2.838428   8.477842   3.571429   7.171315   8.378871   9.551657
4  2015Q1  -1.573034  -6.571936  -3.811252  -3.531599  -4.705882 -10.676157

   제품재고실적BSI  가동률실적BSI  설비투자실적BSI  ...  운송장비 제조업      생산지수     내수출하지수  \
0        NaN       NaN        NaN  ...       NaN       NaN        NaN
1   0.981997  6.028369   0.874126  ...  1.150488 -2.007152 -11.604729
2  -0.972447 -9.531773  -0.519931  ... -4.135552 -3.477410  -8.825620
3   0.654664  8.133087  -0.348432  ... -4.020393 -0.934197  -5.073132
4   1.138211 -5.982906  -0.174825  ... -0.742549  1.693124  -3.150947

     수출출하지수    생산능력지수     가동률지수        자동차      EBITDA         인건비          합산
0       NaN       NaN       NaN        NaN         NaN         NaN         NaN
1 -1.264325  0.344783 -1.818438   2.818615   17.488452    7.125269   17.485007
2 -2.397395  1.310037 -4.814858 -12.367260  -54.974324   -0.678773  -54.957864
3  0.664633  0.434805  0.836979  11.952058  137.275541  159.914375  137.290674
4  1.288105  0.051616  7.749058  -6.288916  -10.714889  -59.533743  -10.750635

[5 rows x 25 columns]

In [ ]:
df_qoq
df_qoq = df_qoq.drop(index=[0, 1, 2,3])

In [ ]:
df_qoq.isnull().sum()

index         0
업황실적BSI       0
매출실적BSI       0
수출실적BSI       0
내수판매실적BSI     0
생산실적BSI       0
신규수주실적BSI     0
제품재고실적BSI     0
가동률실적BSI      0
설비투자실적BSI     0
채산성실적BSI      0
자금사정실적BSI     0
인력사정실적BSI     0
원자재구입가격BSI    0
ppi           0
운송장비 제조업      0
생산지수          0
내수출하지수        0
수출출하지수        0
생산능력지수        0
가동률지수         0
자동차           0
EBITDA        0
인건비           0
합산            0
dtype: int64

In [ ]:
df_qoq.to_csv('운송장비qoq.csv')

#데이터YoY변환

In [ ]:
import pandas as pd

# df_merged는 원본 데이터프레임
df_yoy = df_merged.copy()

# 분기 순서대로 정렬
df_yoy = df_yoy.sort_values('index')

# 수치형 컬럼만 선택 (index 제외)
num_cols = df_yoy.select_dtypes(include=['number']).columns

# 전년 동분기 대비 증감률 (%) 계산 (4분기 차이)
df_yoy[num_cols] = df_yoy[num_cols].pct_change(periods=4) * 100

# 결과 확인
print(df_yoy.head(10))

    index    업황실적BSI    매출실적BSI   수출실적BSI  내수판매실적BSI   생산실적BSI  신규수주실적BSI  \
0  2014Q1        NaN        NaN       NaN        NaN       NaN        NaN
1  2014Q2        NaN        NaN       NaN        NaN       NaN        NaN
2  2014Q3        NaN        NaN       NaN        NaN       NaN        NaN
3  2014Q4        NaN        NaN       NaN        NaN       NaN        NaN
4  2015Q1 -12.922465  -5.395683 -3.460838  -1.518027  3.090909 -12.847222
5  2015Q2 -12.815534  -9.150327 -7.500000  -5.954466 -6.441224 -11.805556
6  2015Q3 -15.938865  -0.770713 -1.503759  -0.996016  1.639344  -6.237817
7  2015Q4  -1.123596  -6.927176 -5.263158  -3.159851 -4.033613 -13.701068
8  2016Q1 -10.730594  -5.893536 -4.716981  -4.431599 -6.701940  -7.968127
9  2016Q2 -16.035635 -13.129496 -3.423423 -15.083799 -9.982788 -18.897638

   제품재고실적BSI  가동률실적BSI  설비투자실적BSI  ...  운송장비 제조업      생산지수     내수출하지수  \
0        NaN       NaN        NaN  ...       NaN       NaN        NaN
1        NaN       NaN        NaN  ...       NaN       NaN        NaN
2        NaN       NaN        NaN  ...       NaN       NaN        NaN
3        NaN       NaN        NaN  ...       NaN       NaN        NaN
4   1.800327 -2.482270  -0.174825  ... -7.622194 -4.711892 -25.905431
5   0.972447 -4.347826  -1.559792  ... -4.459887 -5.665173 -14.140294
6   2.127660  0.184843  -4.878049  ...  2.471181 -3.130378   4.678325
7  -3.739837 -5.128205   0.524476  ...  4.704222 -5.799036  16.059131
8   0.160772 -6.000000  -3.677758  ...  5.092110 -6.717789  20.991909
9  -6.420546 -9.965035  -6.161972  ...  4.417846 -5.896006  30.854821

     수출출하지수    생산능력지수     가동률지수       자동차      EBITDA        인건비          합산
0       NaN       NaN       NaN       NaN         NaN        NaN         NaN
1       NaN       NaN       NaN       NaN         NaN        NaN         NaN
2       NaN       NaN       NaN       NaN         NaN        NaN         NaN
3       NaN       NaN       NaN       NaN         NaN        NaN         NaN
4 -1.741333  2.154057  1.538889 -5.471844   12.069501  11.907022   12.069447
5 -2.925640  0.808140 -0.620928  1.806906  -41.656370   7.018053  -41.641614
6 -3.616229 -1.670950  5.201158 -0.527481  105.294312   4.112831  105.226675
7 -8.205476 -2.120266 -0.869649  8.872094   12.794512   0.922726   12.785819
8 -9.380026 -2.965678 -7.178312 -5.610243   16.252052   0.325000   16.246764
9 -9.552493 -3.436687 -6.473454 -9.293201   86.246616   0.202964   86.198782

[10 rows x 25 columns]

In [ ]:
df_yoy=df_yoy.dropna()

In [ ]:
df_yoy

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,...,운송장비 제조업,생산지수,내수출하지수,수출출하지수,생산능력지수,가동률지수,자동차,EBITDA,인건비,합산
4,2015Q1,-12.922465,-5.395683,-3.460838,-1.518027,3.090909,-12.847222,1.800327,-2.482270,-0.174825,...,-7.622194,-4.711892,-25.905431,-1.741333,2.154057,1.538889,-5.471844,12.069501,11.907022,12.069447
5,2015Q2,-12.815534,-9.150327,-7.500000,-5.954466,-6.441224,-11.805556,0.972447,-4.347826,-1.559792,...,-4.459887,-5.665173,-14.140294,-2.925640,0.808140,-0.620928,1.806906,-41.656370,7.018053,-41.641614
6,2015Q3,-15.938865,-0.770713,-1.503759,-0.996016,1.639344,-6.237817,2.127660,0.184843,-4.878049,...,2.471181,-3.130378,4.678325,-3.616229,-1.670950,5.201158,-0.527481,105.294312,4.112831,105.226675
7,2015Q4,-1.123596,-6.927176,-5.263158,-3.159851,-4.033613,-13.701068,-3.739837,-5.128205,0.524476,...,4.704222,-5.799036,16.059131,-8.205476,-2.120266,-0.869649,8.872094,12.794512,0.922726,12.785819
8,2016Q1,-10.730594,-5.893536,-4.716981,-4.431599,-6.701940,-7.968127,0.160772,-6.000000,-3.677758,...,5.092110,-6.717789,20.991909,-9.380026,-2.965678,-7.178312,-5.610243,16.252052,0.325000,16.246764
9,2016Q2,-16.035635,-13.129496,-3.423423,-15.083799,-9.982788,-18.897638,-6.420546,-9.965035,-6.161972,...,4.417846,-5.896006,30.854821,-9.552493,-3.436687,-6.473454,-9.293201,86.246616,0.202964,86.198782
10,2016Q3,-14.285714,-19.611650,-7.061069,-22.132797,-17.562724,-21.205821,-7.532051,-18.819188,-3.479853,...,-3.921168,-10.793195,6.933095,-12.400861,-3.647819,-11.724199,-12.680544,-28.482767,0.543554,-28.472924
11,2016Q4,-23.181818,-20.229008,-12.068966,-19.577735,-18.388792,-12.164948,-3.209459,-16.036036,-7.304348,...,-1.146500,-7.697926,-5.884988,-6.710970,-4.298967,-6.405108,-7.379814,-9.956728,0.672642,-9.949764
12,2017Q1,-8.951407,-11.515152,-11.485149,-12.500000,-11.720227,-1.515152,-9.149278,-9.090909,-4.727273,...,-2.546073,-13.271130,-0.616629,-13.870868,-3.321777,-11.839525,-1.475713,-11.726809,-2.305986,-11.724109
13,2017Q2,-7.957560,-22.981366,-29.104478,-16.228070,-20.458891,9.466019,-3.602058,-20.000000,-1.125704,...,-8.721616,-10.275362,-0.438795,-13.838013,-2.750084,-8.979060,-5.367665,-9.551161,-6.888459,-9.550365
14,2017Q3,-2.727273,-20.048309,-31.006160,-4.651163,-14.565217,16.886544,0.346620,-10.681818,-5.313093,...,-3.945986,-12.905993,7.439474,-16.896165,-2.975177,-9.593906,15.980044,-32.204466,4.052387,-32.187182
15,2017Q4,-0.295858,-16.028708,-19.172113,-14.081146,-11.373391,8.215962,-2.792321,-13.519313,-6.566604,...,-11.610257,-13.976277,19.167972,-21.440369,-3.301151,-12.391818,-18.510781,-56.754344,13.934540,-56.702566
16,2018Q1,-0.842697,-19.178082,-16.107383,-15.898618,-11.777302,2.417582,6.360424,-10.851064,0.190840,...,-8.657003,-13.331658,3.683911,-17.855322,-7.910106,-8.533104,-10.306037,-44.678403,-4.567610,-44.665684
17,2018Q2,4.322767,6.720430,9.736842,5.235602,4.567308,0.665188,6.227758,10.194175,-0.379507,...,-1.740493,-9.472781,-1.063346,-9.198007,-10.616361,-1.807757,0.747175,-27.665432,-2.281175,-27.657615
18,2018Q3,2.180685,17.522659,27.678571,8.401084,14.503817,3.837472,-0.690846,13.740458,1.402806,...,-3.549321,-0.025736,-0.651220,0.409615,-10.701648,6.941793,-12.832482,-20.362672,-7.393890,-20.353186
19,2018Q4,7.418398,32.763533,30.997305,28.333333,21.791768,8.026030,6.283662,27.791563,6.024096,...,11.611972,4.521714,-4.829850,7.716339,-10.073799,12.735302,14.941645,29.930550,-12.257731,29.849233
20,2019Q1,17.847025,52.824859,54.133333,34.246575,31.796117,11.587983,1.328904,26.491647,3.047619,...,3.295263,8.643264,0.972806,12.768296,-9.900374,18.273747,3.672849,36.231054,5.206205,36.214088
21,2019Q2,24.861878,43.828715,39.328537,34.577114,37.471264,23.348018,0.670017,31.938326,3.809524,...,2.095193,5.876721,8.207530,5.617393,-8.256805,12.882805,-0.213543,32.368215,5.624421,32.357090
22,2019Q3,38.109756,45.244216,29.137529,35.750000,30.444444,24.347826,4.695652,31.319911,10.079051,...,0.395144,8.533168,15.070248,7.057801,-8.283410,16.774645,2.657878,59.852959,4.115550,59.805556
23,2019Q4,29.834254,28.111588,24.485597,25.108225,23.459245,12.449799,4.391892,19.223301,5.492424,...,-2.405822,2.689925,21.598394,-2.719230,-8.987094,11.282933,-10.416243,49.433534,44.584491,49.427218
24,2020Q1,-2.163462,-16.820702,-20.761246,-7.959184,-14.180479,-10.961538,1.475410,-12.830189,-1.663586,...,-5.289114,0.373732,11.298566,-4.968187,-6.136375,5.504680,-15.217992,-4.382080,-0.407541,-4.380401
25,2020Q2,-48.672566,-50.963222,-50.946644,-40.665434,-47.993311,-48.750000,17.637271,-49.749583,-23.669725,...,-21.241200,-13.205237,-12.382446,-24.371252,-4.140721,-9.799422,-22.957971,-37.534086,7.652412,-37.519085
26,2020Q3,-24.724062,-38.584071,-35.379061,-28.545120,-32.538330,-38.111888,6.976744,-35.775128,-15.080790,...,-8.297096,-7.816655,-15.724200,-8.045267,-3.744508,-5.673966,-3.287563,15.397383,-0.599913,15.388519
27,2020Q4,0.212766,-27.470687,-30.578512,-14.705882,-21.578100,-20.178571,1.779935,-19.869707,-4.667864,...,-6.256420,-3.192720,-10.917039,0.315478,-2.377555,-2.305903,-3.102432,-17.746033,8.260499,-17.713259
28,2021Q1,12.776413,10.000000,8.296943,16.851441,15.450644,5.615551,-6.462036,16.666667,4.699248,...,5.127111,-2.756286,-11.771238,-1.519468,0.049727,-1.728277,16.887981,17.584638,4.440714,17.578856
29,2021Q2,116.379310,126.428571,109.473684,93.769470,101.607717,119.512195,-14.992928,107.641196,32.932692,...,20.725312,5.642973,-5.779988,14.556213,0.347913,5.646930,24.554096,17.899917,-4.808608,17.886927
30,2021Q3,44.281525,79.250720,83.519553,52.577320,51.515152,67.231638,-5.745342,61.007958,17.124736,...,2.238067,-2.622464,-7.654321,-4.028777,1.309824,-2.413793,-7.520878,-8.179610,9.399339,-8.171220
31,2021Q4,1.486200,22.401848,35.476190,3.042596,12.320329,27.964206,-2.861685,10.365854,4.519774,...,-1.102820,1.257862,-9.489051,-1.822430,1.557007,0.339476,-4.355266,15.671110,3.690437,15.651245
32,2022Q1,5.882353,22.626263,28.024194,10.436433,10.408922,19.836401,5.354059,10.760668,3.231598,...,4.506681,7.210343,-6.041536,5.110897,-0.397614,5.862237,-5.986940,-28.362522,14.870089,-28.345628
33,2022Q2,-9.760956,-5.520505,-0.837521,-7.556270,-0.956938,-6.666667,3.494176,-1.120000,1.808318,...,3.284358,14.483821,-3.034301,13.584711,-0.445765,14.841723,-6.672912,44.437835,15.367034,44.424407
34,2022Q3,-0.813008,7.877814,5.327245,5.574324,10.166667,1.858108,-0.164745,10.049423,4.512635,...,24.135339,20.934959,0.735294,20.739630,-0.149180,20.040384,16.654051,52.715553,6.774983,52.689430
35,2022Q4,9.205021,37.924528,28.295255,32.677165,28.702011,11.013986,-6.219313,29.650092,6.126126,...,12.968402,13.951266,-3.101737,11.661114,1.088032,11.938134,15.578386,103.681943,-35.767891,103.474643
36,2023Q1,13.786008,13.838550,7.401575,10.652921,13.131313,0.511945,-4.098361,11.725293,4.521739,...,17.748190,12.523191,1.004689,9.862385,2.544910,7.521920,32.142677,145.201819,7.170652,145.115350
37,2023Q2,28.476821,20.033389,22.466216,15.130435,7.246377,2.551020,-7.877814,9.708738,6.927176,...,23.765212,11.933603,6.054422,10.413824,2.487562,5.015816,21.137618,128.313359,11.168543,128.270138
38,2023Q3,20.286885,5.812221,5.346821,7.040000,0.907716,1.160862,-6.270627,0.449102,7.253886,...,12.405295,5.672269,3.516921,-0.206954,2.191235,-0.883095,-1.958905,47.076673,14.525796,47.063729
39,2023Q4,7.471264,-13.269494,-12.054795,-14.243323,-15.198864,-13.070866,6.108202,-16.761364,3.395586,...,14.492636,5.450734,-0.960307,1.705030,1.859100,0.086356,-4.280655,9.060432,13.550175,9.062539
40,2024Q1,-7.233273,-15.050651,-10.703812,-15.217391,-15.922619,-14.431239,5.299145,-14.392804,-3.660566,...,0.085554,2.390767,-4.509284,1.628392,1.459854,-2.961373,-9.881490,29.464490,8.959576,29.458874
41,2024Q2,-1.546392,-11.961057,-12.413793,-8.912387,-10.360360,-10.116086,2.443281,-12.536873,-4.983389,...,4.407838,3.246493,-6.863374,5.436573,1.456311,0.086059,-4.064411,8.152302,9.402853,8.152527
42,2024Q3,-5.110733,-15.774648,-15.500686,-16.591928,-13.493253,-12.459016,12.147887,-13.710879,-8.212560,...,5.496516,4.572565,-9.102564,7.756118,2.972710,0.296988,-2.093215,33.498722,19.105288,33.494265
43,2024Q4,-1.604278,-5.047319,-5.451713,-1.384083,-3.517588,0.905797,3.125000,-4.095563,-4.269294,...,6.190191,3.896620,-10.342599,9.220453,1.921230,2.027610,-0.504882,8.820707,-26.292270,8.803552
44,2025Q1,1.364522,-6.984668,-3.284072,-4.761905,-2.123894,-0.198413,-1.785714,-5.253940,-0.518135,...,6.190685,13.647343,-0.902778,12.654067,0.815348,13.135781,-1.326797,16.196294,-5.757100,16.191233
45,2025Q2,-5.933682,-6.003160,-2.519685,-6.135987,-3.852596,-3.874539,2.725724,-4.890388,1.923077,...,2.933400,12.034161,-8.746556,11.210937,2.727273,12.209802,0.718872,-5.621363,-190.934706,-5.655045

In [ ]:
df_yoy.to_csv("운송장비yoy.csv")

#상관계수 보기(qoq)

In [ ]:
qoq = pd.read_csv('운송장비qoq.csv')
qoq = qoq.drop(columns=["Unnamed: 0"])

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# GDP_QoQ 기준
target = '운송장비 제조업'

In [ ]:
# 수치형 컬럼만 선택
num_cols = qoq.select_dtypes(include=['number']).columns

# GDP 기준 상관계수 계산
corr = qoq[num_cols].corr()[target].sort_values(ascending=False)

print("📊 GDP 대비 단순 상관계수")
print(corr)

📊 GDP 대비 단순 상관계수
운송장비 제조업      1.000000
가동률실적BSI      0.618359
수출출하지수        0.617791
채산성실적BSI      0.583120
내수판매실적BSI     0.581421
생산실적BSI       0.579774
설비투자실적BSI     0.566483
업황실적BSI       0.564881
자금사정실적BSI     0.562443
생산지수          0.557835
매출실적BSI       0.534971
수출실적BSI       0.525605
가동률지수         0.497827
신규수주실적BSI     0.446430
자동차           0.368197
내수출하지수        0.234309
합산            0.078699
EBITDA        0.078631
생산능력지수        0.055524
인건비           0.027708
ppi          -0.061671
원자재구입가격BSI   -0.168317
제품재고실적BSI    -0.295202
인력사정실적BSI    -0.308234
Name: 운송장비 제조업, dtype: float64

In [ ]:
# df2 사본
df2 = qoq.copy()

# target 및 feature 지정
target_col = '운송장비 제조업'
feature_cols = [col for col in df2.columns if col not in ['index', target_col]]

# 결과 저장용 데이터프레임
corr_df = pd.DataFrame(columns=['Feature', 'Lag', 'Correlation'])

# lag 1~4 생성 및 상관계수 계산
for col in feature_cols:
    for lag in range(1, 5):  # lag 1~4
        lag_col_name = f"{col}_lag{lag}"
        df2[lag_col_name] = df2[col].shift(lag)  # 실제 데이터에 lag 컬럼 추가
        corr = df2[target_col].corr(df2[lag_col_name])  # 상관계수 계산
        corr_df = pd.concat(
            [corr_df, pd.DataFrame({'Feature': [col], 'Lag': [lag], 'Correlation': [corr]})],
            ignore_index=True
        )

# 상관계수 높은 순으로 정렬
corr_df.sort_values(by='Correlation', ascending=False, inplace=True)
corr_df.reset_index(drop=True, inplace=True)

corr_df

/tmp/ipython-input-92513580.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  corr_df = pd.concat(

      Feature Lag  Correlation
0         ppi   2     0.367493
1   제품재고실적BSI   3     0.278509
2      생산능력지수   4     0.205837
3      EBITDA   3     0.198176
4          합산   3     0.198092
..        ...  ..          ...
87   가동률실적BSI   3    -0.225568
88  자금사정실적BSI   3    -0.234805
89    업황실적BSI   3    -0.236985
90  내수판매실적BSI   3    -0.267055
91   채산성실적BSI   3    -0.292451

[92 rows x 3 columns]

In [ ]:
df2

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,...,EBITDA_lag3,EBITDA_lag4,인건비_lag1,인건비_lag2,인건비_lag3,인건비_lag4,합산_lag1,합산_lag2,합산_lag3,합산_lag4
0,2015Q1,-1.573034,-6.571936,-3.811252,-3.531599,-4.705882,-10.676157,1.138211,-5.982906,-0.174825,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015Q2,2.511416,5.703422,4.716981,3.468208,2.469136,1.195219,0.160772,4.000000,-0.525394,...,NaN,NaN,-59.533743,NaN,NaN,NaN,-10.750635,NaN,NaN,NaN
2,2015Q3,-14.253898,-7.374101,-5.585586,-7.448790,-3.958692,-5.314961,0.160514,-5.244755,-3.873239,...,NaN,NaN,2.445205,-59.533743,NaN,NaN,-38.821547,-10.750635,NaN,NaN
3,2015Q4,14.285714,1.747573,-0.381679,4.828974,2.329749,0.831601,-5.128205,2.398524,5.311355,...,-10.714889,NaN,-3.375049,2.445205,-59.533743,NaN,58.397933,-38.821547,-10.750635,NaN
4,2016Q1,-11.136364,-5.534351,-3.256705,-4.798464,-7.355517,-4.742268,5.236486,-6.846847,-4.347826,...,-38.835251,-10.714889,151.950379,-3.375049,2.445205,-59.533743,30.407137,58.397933,-38.821547,-10.750635
5,2016Q2,-3.580563,-2.424242,6.138614,-8.064516,-1.134216,-10.822511,-6.420546,-0.386847,-3.090909,...,58.432293,-38.835251,-59.773409,151.950379,-3.375049,2.445205,-8.011929,30.407137,58.397933,-38.821547
6,2016Q3,-12.466844,-14.285714,-9.141791,-15.131579,-12.045889,-8.009709,-1.029160,-14.563107,-1.125704,...,30.365905,58.432293,2.320589,-59.773409,151.950379,-3.375049,-2.007135,-8.011929,30.407137,58.397933
7,2016Q4,2.424242,0.966184,-5.749487,8.268734,1.304348,12.401055,-0.693241,5.909091,1.138520,...,-7.977993,30.365905,-3.046621,2.320589,-59.773409,151.950379,-39.152443,-2.007135,-8.011929,30.407137
8,2017Q1,5.325444,4.784689,-2.614379,3.579952,0.214592,6.807512,-1.221640,0.858369,-1.688555,...,-2.008375,-7.977993,152.273859,-3.046621,2.320589,-59.773409,64.178297,-39.152443,-2.007135,-8.011929
9,2017Q2,-2.528090,-15.068493,-14.988814,-11.981567,-10.920771,-0.879121,-0.706714,-12.340426,0.572519,...,-39.163248,-2.008375,-60.963603,152.273859,-3.046621,2.320589,-9.824458,64.178297,-39.152443,-2.007135
10,2017Q3,-7.492795,-11.021505,-11.578947,-3.403141,-5.528846,-1.773836,3.024911,-4.611650,-5.313093,...,64.136282,-39.163248,-2.478900,-60.963603,152.273859,-3.046621,0.405885,-9.824458,64.178297,-39.152443
11,2017Q4,4.984424,6.042296,10.416667,-2.439024,5.089059,4.063205,-3.799655,2.544529,-0.200401,...,-9.786972,64.136282,8.345651,-2.478900,-60.963603,152.273859,-54.380753,0.405885,-9.824458,64.178297
12,2018Q1,4.747774,0.854701,1.078167,1.388889,-0.242131,1.084599,8.078995,3.970223,5.421687,...,0.406800,-9.786972,176.233030,8.345651,-2.478900,-60.963603,4.825299,-54.380753,0.405885,-9.824458
13,2018Q2,2.549575,12.146893,11.200000,10.136986,5.582524,-2.575107,-0.830565,8.353222,0.000000,...,-54.400077,0.406800,-67.302833,176.233030,8.345651,-2.478900,15.244750,4.825299,-54.380753,0.405885
14,2018Q3,-9.392265,-2.015113,2.877698,-0.497512,3.448276,1.321586,-3.685092,-1.541850,-3.619048,...,4.699833,-54.400077,-0.142422,-67.302833,176.233030,8.345651,31.267570,15.244750,4.825299,-54.380753
15,2018Q4,10.365854,19.794344,13.286713,15.500000,11.777778,8.260870,2.956522,15.212528,4.347826,...,15.404166,4.699833,2.676933,-0.142422,-67.302833,176.233030,-49.774566,31.267570,15.244750,4.825299
16,2019Q1,14.917127,16.094421,18.930041,6.060606,7.952286,4.417671,3.040541,2.912621,2.462121,...,31.284757,15.404166,161.724768,2.676933,-0.142422,-67.302833,70.898044,-49.774566,31.267570,15.244750
17,2019Q2,8.653846,5.545287,0.519031,10.408163,10.128913,7.692308,-1.475410,13.018868,0.739372,...,-49.796395,31.284757,-60.794895,161.724768,2.676933,-0.142422,20.893733,70.898044,-49.774566,31.267570
18,2019Q3,0.221239,-1.050788,-4.647160,0.369686,-1.839465,2.142857,0.166389,-2.003339,2.201835,...,70.820734,-49.796395,0.254531,-60.794895,161.724768,2.676933,27.550636,20.893733,70.898044,-49.774566
19,2019Q4,3.752759,5.663717,9.205776,6.445672,5.792164,-2.097902,2.657807,4.599659,0.000000,...,21.000266,70.820734,1.210168,0.254531,-60.794895,161.724768,-39.358719,27.550636,20.893733,70.898044
20,2020Q1,-13.404255,-24.623116,-24.297521,-21.972318,-24.959742,-17.321429,0.161812,-24.755700,-4.488330,...,27.562170,21.000266,263.455242,1.210168,0.254531,-60.794895,59.799320,-39.358719,27.550636,20.893733
21,2020Q2,-42.997543,-37.777778,-37.772926,-28.824834,-33.261803,-38.012959,14.216478,-34.848485,-21.804511,...,-39.372192,27.562170,-72.994802,263.455242,1.210168,0.254531,-22.639193,59.799320,-39.358719,27.550636
22,2020Q3,46.982759,23.928571,25.614035,20.872274,27.331190,23.344948,-8.910891,25.249169,13.701923,...,59.686415,-39.372192,8.368065,-72.994802,263.455242,1.210168,-16.654321,-22.639193,59.799320,-39.358719
23,2020Q4,38.123167,24.783862,17.318436,27.061856,22.979798,26.271186,-2.329193,30.503979,12.262156,...,-22.575653,59.686415,-6.548313,8.368065,-72.994802,263.455242,11.991119,-16.654321,-22.639193,59.799320
24,2021Q1,-2.547771,14.318707,18.095238,6.896552,10.472279,9.395973,-7.949126,9.552846,4.896422,...,-16.665333,-22.575653,295.853233,-6.548313,8.368065,-72.994802,13.957311,11.991119,-16.654321,-22.639193
25,2021Q2,9.368192,28.080808,20.362903,18.026565,16.542751,28.834356,3.799655,15.955473,-0.718133,...,12.001730,-16.665333,-73.947634,295.853233,-6.548313,8.368065,10.540230,13.957311,11.991119,-16.654321
26,2021Q3,-1.992032,-1.892744,10.050251,-4.823151,-4.306220,-6.031746,0.998336,-2.880000,0.180832,...,13.822695,12.001730,-1.229065,-73.947634,295.853233,-6.548313,-16.435944,10.540230,13.957311,11.991119
27,2021Q4,-2.845528,-14.790997,-13.394216,-14.189189,-8.833333,-3.378378,0.658979,-10.543657,0.180505,...,10.680545,13.822695,7.399972,-1.229065,-73.947634,295.853233,-12.763797,-16.435944,10.540230,13.957311
28,2022Q1,1.673640,14.528302,11.599297,14.566929,8.592322,2.447552,-0.163666,9.944751,3.603604,...,-16.441889,10.680545,275.196001,7.399972,-1.229065,-73.947634,43.520418,-12.763797,-16.435944,10.540230
29,2022Q2,-6.790123,-1.317957,-6.771654,-1.202749,4.545455,0.341297,1.967213,3.517588,-2.086957,...,-12.773115,-16.441889,-71.138731,275.196001,7.399972,-1.229065,-31.512275,43.520418,-12.763797,-16.435944
30,2022Q3,7.726269,12.020033,16.891892,8.695652,6.441224,2.551020,-2.572347,8.090615,2.841918,...,43.388603,-12.773115,-0.801767,-71.138731,275.196001,7.399972,68.429210,-31.512275,43.520418,-12.763797
31,2022Q4,6.967213,8.941878,5.491329,7.840000,6.505295,5.306799,-5.445545,5.389222,1.727116,...,-31.453280,43.388603,-0.598725,-0.801767,-71.138731,275.196001,-7.771503,68.429210,-31.512275,43.520418
32,2023Q1,5.938697,-5.471956,-6.575342,-4.451039,-4.545455,-7.244094,2.094241,-5.255682,2.037351,...,68.472606,-31.453280,125.704840,-0.598725,-0.801767,-71.138731,91.255975,-7.771503,68.429210,-31.512275
33,2023Q2,5.244123,4.052098,6.304985,2.795031,-0.892857,2.376910,-2.051282,1.649175,0.166389,...,-7.774150,68.472606,-51.845252,125.704840,-0.598725,-0.801767,-17.496390,91.255975,-7.771503,68.429210
34,2023Q3,0.859107,-1.251739,0.551724,1.057402,0.150150,1.160862,-0.872600,-1.032448,3.156146,...,91.242271,-7.774150,2.898721,-51.845252,125.704840,-0.598725,56.854146,-17.496390,91.255975,-7.771503
35,2023Q4,-4.429302,-10.704225,-11.934156,-13.602392,-10.494753,-9.508197,7.042254,-12.667660,-1.932367,...,-17.480263,91.242271,2.403160,2.898721,-51.845252,125.704840,-40.581511,56.854146,-17.496390,91.255975
36,2024Q1,-8.556150,-7.413249,-5.140187,-5.536332,-5.360134,-8.695652,1.315789,-2.559727,-4.926108,...,56.868929,-17.480263,123.782108,2.403160,2.898721,-51.845252,41.835532,-40.581511,56.854146,-17.496390
37,2024Q2,11.695906,7.836457,4.269294,10.439560,5.663717,7.539683,-4.707792,3.852890,-1.208981,...,-40.589236,56.868929,-53.792049,123.782108,2.403160,2.898721,-2.066974,41.835532,-40.581511,56.854146
38,2024Q3,-2.792321,-5.529226,-2.992126,-7.462687,-3.350084,-1.476015,8.517888,-2.360877,-0.349650,...,41.810148,-40.589236,3.317340,-53.792049,123.782108,2.403160,31.039084,-2.066974,41.835532,-40.581511
39,2024Q4,-0.897666,0.668896,-1.461039,2.150538,-0.173310,4.307116,-1.569859,-2.936097,2.280702,...,-2.041690,41.810148,11.484825,3.317340,-53.792049,123.782108,-26.658879,31.039084,-2.066974,41.835532
40,2025Q1,-5.797101,-9.302326,-2.965404,-8.771930,-3.993056,-9.694794,-3.508772,-3.736655,-1.200686,...,31.045476,-2.041690,38.486473,11.484825,3.317340,-53.792049,15.602042,-26.658879,31.039084,-2.066974
41,2025Q2,3.653846,8.974359,5.093379,8.846154,3.797468,3.578529,-0.330579,4.251386,1.215278,...,-26.665814,31.045476,-40.918391,38.486473,11.484825,3.317340,4.582607,15.602042,-26.658879,31.039084

In [ ]:
# 숫자형 컬럼만 선택 (연도분기 제외)
numeric_df = df2.select_dtypes(include=["number"])

# 전체 상관계수
corr = numeric_df.corr()

target_corr = corr["운송장비 제조업"].drop("운송장비 제조업")
target_corr = target_corr.sort_values(ascending=False)
target_corr

가동률실적BSI          0.618359
수출출하지수            0.617791
채산성실적BSI          0.583120
내수판매실적BSI         0.581421
생산실적BSI           0.579774
                    ...
업황실적BSI_lag3     -0.236985
내수판매실적BSI_lag3   -0.267055
채산성실적BSI_lag3    -0.292451
제품재고실적BSI        -0.295202
인력사정실적BSI        -0.308234
Name: 운송장비 제조업, Length: 115, dtype: float64

In [ ]:
target_corr.to_csv('운송장비순서.csv')

In [ ]:
df2.dropna(inplace=True)

In [ ]:
df2

,index,업황실적BSI,매출실적BSI,수출실적BSI,내수판매실적BSI,생산실적BSI,신규수주실적BSI,제품재고실적BSI,가동률실적BSI,설비투자실적BSI,...,EBITDA_lag3,EBITDA_lag4,인건비_lag1,인건비_lag2,인건비_lag3,인건비_lag4,합산_lag1,합산_lag2,합산_lag3,합산_lag4
4,2016Q1,-11.136364,-5.534351,-3.256705,-4.798464,-7.355517,-4.742268,5.236486,-6.846847,-4.347826,...,-38.835251,-10.714889,151.950379,-3.375049,2.445205,-59.533743,30.407137,58.397933,-38.821547,-10.750635
5,2016Q2,-3.580563,-2.424242,6.138614,-8.064516,-1.134216,-10.822511,-6.420546,-0.386847,-3.090909,...,58.432293,-38.835251,-59.773409,151.950379,-3.375049,2.445205,-8.011929,30.407137,58.397933,-38.821547
6,2016Q3,-12.466844,-14.285714,-9.141791,-15.131579,-12.045889,-8.009709,-1.029160,-14.563107,-1.125704,...,30.365905,58.432293,2.320589,-59.773409,151.950379,-3.375049,-2.007135,-8.011929,30.407137,58.397933
7,2016Q4,2.424242,0.966184,-5.749487,8.268734,1.304348,12.401055,-0.693241,5.909091,1.138520,...,-7.977993,30.365905,-3.046621,2.320589,-59.773409,151.950379,-39.152443,-2.007135,-8.011929,30.407137
8,2017Q1,5.325444,4.784689,-2.614379,3.579952,0.214592,6.807512,-1.221640,0.858369,-1.688555,...,-2.008375,-7.977993,152.273859,-3.046621,2.320589,-59.773409,64.178297,-39.152443,-2.007135,-8.011929
9,2017Q2,-2.528090,-15.068493,-14.988814,-11.981567,-10.920771,-0.879121,-0.706714,-12.340426,0.572519,...,-39.163248,-2.008375,-60.963603,152.273859,-3.046621,2.320589,-9.824458,64.178297,-39.152443,-2.007135
10,2017Q3,-7.492795,-11.021505,-11.578947,-3.403141,-5.528846,-1.773836,3.024911,-4.611650,-5.313093,...,64.136282,-39.163248,-2.478900,-60.963603,152.273859,-3.046621,0.405885,-9.824458,64.178297,-39.152443
11,2017Q4,4.984424,6.042296,10.416667,-2.439024,5.089059,4.063205,-3.799655,2.544529,-0.200401,...,-9.786972,64.136282,8.345651,-2.478900,-60.963603,152.273859,-54.380753,0.405885,-9.824458,64.178297
12,2018Q1,4.747774,0.854701,1.078167,1.388889,-0.242131,1.084599,8.078995,3.970223,5.421687,...,0.406800,-9.786972,176.233030,8.345651,-2.478900,-60.963603,4.825299,-54.380753,0.405885,-9.824458
13,2018Q2,2.549575,12.146893,11.200000,10.136986,5.582524,-2.575107,-0.830565,8.353222,0.000000,...,-54.400077,0.406800,-67.302833,176.233030,8.345651,-2.478900,15.244750,4.825299,-54.380753,0.405885
14,2018Q3,-9.392265,-2.015113,2.877698,-0.497512,3.448276,1.321586,-3.685092,-1.541850,-3.619048,...,4.699833,-54.400077,-0.142422,-67.302833,176.233030,8.345651,31.267570,15.244750,4.825299,-54.380753
15,2018Q4,10.365854,19.794344,13.286713,15.500000,11.777778,8.260870,2.956522,15.212528,4.347826,...,15.404166,4.699833,2.676933,-0.142422,-67.302833,176.233030,-49.774566,31.267570,15.244750,4.825299
16,2019Q1,14.917127,16.094421,18.930041,6.060606,7.952286,4.417671,3.040541,2.912621,2.462121,...,31.284757,15.404166,161.724768,2.676933,-0.142422,-67.302833,70.898044,-49.774566,31.267570,15.244750
17,2019Q2,8.653846,5.545287,0.519031,10.408163,10.128913,7.692308,-1.475410,13.018868,0.739372,...,-49.796395,31.284757,-60.794895,161.724768,2.676933,-0.142422,20.893733,70.898044,-49.774566,31.267570
18,2019Q3,0.221239,-1.050788,-4.647160,0.369686,-1.839465,2.142857,0.166389,-2.003339,2.201835,...,70.820734,-49.796395,0.254531,-60.794895,161.724768,2.676933,27.550636,20.893733,70.898044,-49.774566
19,2019Q4,3.752759,5.663717,9.205776,6.445672,5.792164,-2.097902,2.657807,4.599659,0.000000,...,21.000266,70.820734,1.210168,0.254531,-60.794895,161.724768,-39.358719,27.550636,20.893733,70.898044
20,2020Q1,-13.404255,-24.623116,-24.297521,-21.972318,-24.959742,-17.321429,0.161812,-24.755700,-4.488330,...,27.562170,21.000266,263.455242,1.210168,0.254531,-60.794895,59.799320,-39.358719,27.550636,20.893733
21,2020Q2,-42.997543,-37.777778,-37.772926,-28.824834,-33.261803,-38.012959,14.216478,-34.848485,-21.804511,...,-39.372192,27.562170,-72.994802,263.455242,1.210168,0.254531,-22.639193,59.799320,-39.358719,27.550636
22,2020Q3,46.982759,23.928571,25.614035,20.872274,27.331190,23.344948,-8.910891,25.249169,13.701923,...,59.686415,-39.372192,8.368065,-72.994802,263.455242,1.210168,-16.654321,-22.639193,59.799320,-39.358719
23,2020Q4,38.123167,24.783862,17.318436,27.061856,22.979798,26.271186,-2.329193,30.503979,12.262156,...,-22.575653,59.686415,-6.548313,8.368065,-72.994802,263.455242,11.991119,-16.654321,-22.639193,59.799320
24,2021Q1,-2.547771,14.318707,18.095238,6.896552,10.472279,9.395973,-7.949126,9.552846,4.896422,...,-16.665333,-22.575653,295.853233,-6.548313,8.368065,-72.994802,13.957311,11.991119,-16.654321,-22.639193
25,2021Q2,9.368192,28.080808,20.362903,18.026565,16.542751,28.834356,3.799655,15.955473,-0.718133,...,12.001730,-16.665333,-73.947634,295.853233,-6.548313,8.368065,10.540230,13.957311,11.991119,-16.654321
26,2021Q3,-1.992032,-1.892744,10.050251,-4.823151,-4.306220,-6.031746,0.998336,-2.880000,0.180832,...,13.822695,12.001730,-1.229065,-73.947634,295.853233,-6.548313,-16.435944,10.540230,13.957311,11.991119
27,2021Q4,-2.845528,-14.790997,-13.394216,-14.189189,-8.833333,-3.378378,0.658979,-10.543657,0.180505,...,10.680545,13.822695,7.399972,-1.229065,-73.947634,295.853233,-12.763797,-16.435944,10.540230,13.957311
28,2022Q1,1.673640,14.528302,11.599297,14.566929,8.592322,2.447552,-0.163666,9.944751,3.603604,...,-16.441889,10.680545,275.196001,7.399972,-1.229065,-73.947634,43.520418,-12.763797,-16.435944,10.540230
29,2022Q2,-6.790123,-1.317957,-6.771654,-1.202749,4.545455,0.341297,1.967213,3.517588,-2.086957,...,-12.773115,-16.441889,-71.138731,275.196001,7.399972,-1.229065,-31.512275,43.520418,-12.763797,-16.435944
30,2022Q3,7.726269,12.020033,16.891892,8.695652,6.441224,2.551020,-2.572347,8.090615,2.841918,...,43.388603,-12.773115,-0.801767,-71.138731,275.196001,7.399972,68.429210,-31.512275,43.520418,-12.763797
31,2022Q4,6.967213,8.941878,5.491329,7.840000,6.505295,5.306799,-5.445545,5.389222,1.727116,...,-31.453280,43.388603,-0.598725,-0.801767,-71.138731,275.196001,-7.771503,68.429210,-31.512275,43.520418
32,2023Q1,5.938697,-5.471956,-6.575342,-4.451039,-4.545455,-7.244094,2.094241,-5.255682,2.037351,...,68.472606,-31.453280,125.704840,-0.598725,-0.801767,-71.138731,91.255975,-7.771503,68.429210,-31.512275
33,2023Q2,5.244123,4.052098,6.304985,2.795031,-0.892857,2.376910,-2.051282,1.649175,0.166389,...,-7.774150,68.472606,-51.845252,125.704840,-0.598725,-0.801767,-17.496390,91.255975,-7.771503,68.429210
34,2023Q3,0.859107,-1.251739,0.551724,1.057402,0.150150,1.160862,-0.872600,-1.032448,3.156146,...,91.242271,-7.774150,2.898721,-51.845252,125.704840,-0.598725,56.854146,-17.496390,91.255975,-7.771503
35,2023Q4,-4.429302,-10.704225,-11.934156,-13.602392,-10.494753,-9.508197,7.042254,-12.667660,-1.932367,...,-17.480263,91.242271,2.403160,2.898721,-51.845252,125.704840,-40.581511,56.854146,-17.496390,91.255975
36,2024Q1,-8.556150,-7.413249,-5.140187,-5.536332,-5.360134,-8.695652,1.315789,-2.559727,-4.926108,...,56.868929,-17.480263,123.782108,2.403160,2.898721,-51.845252,41.835532,-40.581511,56.854146,-17.496390
37,2024Q2,11.695906,7.836457,4.269294,10.439560,5.663717,7.539683,-4.707792,3.852890,-1.208981,...,-40.589236,56.868929,-53.792049,123.782108,2.403160,2.898721,-2.066974,41.835532,-40.581511,56.854146
38,2024Q3,-2.792321,-5.529226,-2.992126,-7.462687,-3.350084,-1.476015,8.517888,-2.360877,-0.349650,...,41.810148,-40.589236,3.317340,-53.792049,123.782108,2.403160,31.039084,-2.066974,41.835532,-40.581511
39,2024Q4,-0.897666,0.668896,-1.461039,2.150538,-0.173310,4.307116,-1.569859,-2.936097,2.280702,...,-2.041690,41.810148,11.484825,3.317340,-53.792049,123.782108,-26.658879,31.039084,-2.066974,41.835532
40,2025Q1,-5.797101,-9.302326,-2.965404,-8.771930,-3.993056,-9.694794,-3.508772,-3.736655,-1.200686,...,31.045476,-2.041690,38.486473,11.484825,3.317340,-53.792049,15.602042,-26.658879,31.039084,-2.066974
41,2025Q2,3.653846,8.974359,5.093379,8.846154,3.797468,3.578529,-0.330579,4.251386,1.215278,...,-26.665814,31.045476,-40.918391,38.486473,11.484825,3.317340,4.582607,15.602042,-26.658879,31.039084

In [ ]:
df2 = df2.reset_index()
df2 = df2.drop(columns=["level_0"])

In [ ]:
df2.to_csv('운송장비lag.csv', encoding='utf-8-sig')

#ARIMA

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('운송장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = '운송장비 제조업'   # GDP 예측 대상 칼럼
exog_vars = ['가동률실적BSI','수출출하지수','채산성실적BSI','내수판매실적BSI','생산실적BSI','설비투자실적BSI','업황실적BSI']
y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (3.0, 1.0, 0.0)
📉 평균 Train MAE: 3.5676
📈 평균 Test MAE: 3.8985

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('운송장비lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = '운송장비 제조업'   # GDP 예측 대상 칼럼
exog_vars = ['가동률실적BSI','수출출하지수','채산성실적BSI','내수판매실적BSI','생산실적BSI']
y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (3.0, 1.0, 1.0)
📉 평균 Train MAE: 2.6308
📈 평균 Test MAE: 3.987

#랜덤포레스트

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('운송장비lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2016Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '운송장비 제조업'
exog_vars = ['가동률실적BSI','수출출하지수','채산성실적BSI','내수판매실적BSI','생산실적BSI','설비투자실적BSI','업황실적BSI']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.5289
📈 평균 Test MAE: 4.6323

#AR

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('운송장비qoq.csv')

# GDP 단일 시계열만 사용 (AR(1))
y = df['운송장비 제조업'].dropna()
y.index = pd.PeriodIndex(df.loc[y.index, 'index'], freq='Q')

# -----------------------------
# 2️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

train_mae_list = []
test_mae_list = []

# -----------------------------
# 3️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    train_data = y.loc[train_start:train_end]
    test_data = y.loc[test_end:test_end]

    if len(train_data) < train_window:
        continue

    try:
        # AR(1) 학습
        model = AutoReg(train_data, lags=1, old_names=False)
        fit = model.fit()

        # --- Train 예측 ---
        # fittedvalues는 길이가 n-1이므로 첫 번째 값 제외하고 MAE 계산
        train_mae = mean_absolute_error(train_data[1:], fit.fittedvalues)
        train_mae_list.append(train_mae)

        # --- Test 예측 (1분기 앞 예측) ---
        pred = fit.predict(start=len(train_data), end=len(train_data))
        test_mae = mean_absolute_error(test_data, pred)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 4️⃣ 결과 출력
# -----------------------------
print("✅ AR(1) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ AR(1) 롤링 예측 결과
📉 평균 Train MAE: 4.9410
📈 평균 Test MAE: 6.1921

#XGB

In [ ]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('운송장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '운송장비 제조업'
exog_vars = ['가동률실적BSI','수출출하지수','채산성실적BSI','내수판매실적BSI','생산실적BSI','설비투자실적BSI','업황실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 하이퍼파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'n_estimators': [200, 400, 600],
    'learning_rate': [0.03, 0.05, 0.1],
    'max_depth': [3, 5, 7, 9],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.3]
}

# 첫 번째 윈도우로 탐색
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

# RandomizedSearchCV 실행
xgb = XGBRegressor(random_state=42, objective='reg:squarederror')
rand_search = RandomizedSearchCV(
    xgb,
    param_distributions=param_grid,
    n_iter=15,          # 전체 중 15조합 탐색
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 고정된 최적 파라미터로 학습
        model = XGBRegressor(**best_params, random_state=42, objective='reg:squarederror')
        model.fit(X_train, y_train)

        # 예측
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # MAE 계산
        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 XGBoost 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'subsample': 0.8, 'n_estimators': 600, 'min_child_weight': 1, 'max_depth': 3, 'learning_rate': 0.05, 'gamma': 0, 'colsample_bytree': 0.8}

📊 XGBoost 롤링 예측 결과
📉 평균 Train MAE: 0.0006
📈 평균 Test MAE: 5.3718

#MLP

In [ ]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('운송장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '운송장비 제조업'
exog_vars = ['가동률실적BSI','수출출하지수','채산성실적BSI','내수판매실적BSI','생산실적BSI','설비투자실적BSI','업황실적BSI'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# 스케일링 (NN에서는 매우 중요)
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(), index=y.index)

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 하이퍼파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'hidden_layer_sizes': [(32,), (64,), (32,16), (64,32), (128,64)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'lbfgs'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate_init': [0.001, 0.01]
}

# 첫 번째 윈도우로 하이퍼파라미터 탐색
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X_scaled.loc[start_period:first_train_end]
first_y_train = y_scaled.loc[start_period:first_train_end]

mlp = MLPRegressor(random_state=42, max_iter=1000)
rand_search = RandomizedSearchCV(
    mlp,
    param_distributions=param_grid,
    n_iter=10,
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y_scaled.loc[train_start:train_end]
    y_test = y_scaled.loc[test_end:test_end]
    X_train = X_scaled.loc[train_start:train_end]
    X_test = X_scaled.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = MLPRegressor(**best_params, random_state=42, max_iter=1000)
        model.fit(X_train, y_train)

        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # 스케일링 복원
        train_pred_inv = scaler_y.inverse_transform(train_pred.reshape(-1, 1)).flatten()
        test_pred_inv = scaler_y.inverse_transform(test_pred.reshape(-1, 1)).flatten()
        y_train_inv = scaler_y.inverse_transform(y_train.values.reshape(-1, 1)).flatten()
        y_test_inv = scaler_y.inverse_transform(y_test.values.reshape(-1, 1)).flatten()

        # MAE 계산
        train_mae = mean_absolute_error(y_train_inv, train_pred_inv)
        test_mae = mean_absolute_error(y_test_inv, test_pred_inv)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 Neural Network (MLP) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'solver': 'adam', 'learning_rate_init': 0.001, 'hidden_layer_sizes': (32,), 'alpha': 0.01, 'activation': 'relu'}

📊 Neural Network (MLP) 롤링 예측 결과
📉 평균 Train MAE: 0.8899
📈 평균 Test MAE: 5.4083

#LSTM

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('운송장비lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = '운송장비 제조업'
exog_vars = ['가동률실적BSI','수출출하지수','채산성실적BSI','내수판매실적BSI','생산실적BSI','설비투자실적BSI','업황실적BSI']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 스케일링
# -----------------------------
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(), index=y.index)

# -----------------------------
# 4️⃣ LSTM 입력 형태 변환 함수
# -----------------------------
def create_lstm_input(X, y, lookback=4):
    """
    lookback: 과거 몇 분기 데이터를 사용할지 (ex. 4 = 1년)
    """
    Xs, ys, idxs = [], [], []
    for i in range(lookback, len(X)):
        Xs.append(X.iloc[i-lookback:i].values)
        ys.append(y.iloc[i])
        idxs.append(y.index[i])
    return np.array(Xs), np.array(ys), idxs

lookback = 4
X_seq, y_seq, idxs = create_lstm_input(X_scaled, y_scaled, lookback)
y_seq = pd.Series(y_seq, index=idxs)

# -----------------------------
# 5️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 6️⃣ LSTM 모델 정의 함수
# -----------------------------
def build_lstm(input_shape):
    model = Sequential()
    model.add(LSTM(64, activation='tanh', input_shape=input_shape, return_sequences=False))
    model.add(Dropout(0.2))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mae')
    return model

# -----------------------------
# 7️⃣ 롤링 예측
# -----------------------------
train_mae_list, test_mae_list = [], []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    # 윈도우 범위 맞추기
    train_mask = (np.array(idxs) >= train_start) & (np.array(idxs) <= train_end)
    test_mask = (np.array(idxs) == test_end)

    X_train, y_train = X_seq[train_mask], y_seq[train_mask]
    X_test, y_test = X_seq[test_mask], y_seq[test_mask]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = build_lstm((X_train.shape[1], X_train.shape[2]))
        early_stop = EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)
        model.fit(X_train, y_train, epochs=200, batch_size=8, verbose=0, callbacks=[early_stop])

        # 예측
        train_pred = model.predict(X_train, verbose=0)
        test_pred = model.predict(X_test, verbose=0)

        # 스케일링 복원
        train_pred_inv = scaler_y.inverse_transform(train_pred)
        test_pred_inv = scaler_y.inverse_transform(test_pred)
        y_train_inv = scaler_y.inverse_transform(y_train.values.reshape(-1, 1))
        y_test_inv = scaler_y.inverse_transform(y_test.values.reshape(-1, 1))

        # MAE 계산
        train_mae = mean_absolute_error(y_train_inv, train_pred_inv)
        test_mae = mean_absolute_error(y_test_inv, test_pred_inv)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 8️⃣ 결과 요약
# -----------------------------
print("\n📊 LSTM 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f32f4143740> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f32f4143740> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

📊 LSTM 롤링 예측 결과
📉 평균 Train MAE: 3.2500
📈 평균 Test MAE: 6.5750