In [1]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 41 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 1s (19.3 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 125080 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

# 데이터 불러오기

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rc('font', family='NanumBarunGothic')

!pip install tspoon
import tspoon as tsp

Collecting tspoon
  Downloading tspoon-0.2.10-py3-none-any.whl.metadata (4.2 kB)
Downloading tspoon-0.2.10-py3-none-any.whl (9.2 kB)
Installing collected packages: tspoon
Successfully installed tspoon-0.2.10

In [3]:
!pip install xmltodict
import pandas as pd

import requests
import xml.etree.ElementTree as ET
import xml.dom.minidom
import xmltodict

import json
from urllib.request import urlopen

def getECOS(topic,period,beg,end,item1='?',item2='?',item3='?',item4='?', df=None):
    key = ''
    url = 'https://ecos.bok.or.kr/api/StatisticSearch/'+'OIT9OYFOZDZWLHSBQJWU'+'/xml/kr/'+str(1)+'/'+str(50000)+'/'+topic+'/'+period+'/'+beg+'/'+end \
            +'/'+item1+'/'+item2+'/'+item3+'/'+item4
    # print(url)
    ## call OpenAPI URL
    response = requests.get(url)

    ## get API return value upon the http request
    if response.status_code == 200:
        try:
            contents = response.text
            ecosRoot = ET.fromstring(contents)

            # error check
            if ecosRoot[0].text[:4] in ("INFO","ERRO"):
                print(ecosRoot[0].text + " : " + ecosRoot[1].text)

            else:
                #print(contents)
                #dom = xml.dom.minidom.parse(xml_fname)
                dom = xml.dom.minidom.parseString(contents)
                pretty_xml_as_string = dom.toprettyxml(indent=" ")
                # print(pretty_xml_as_string)
                dic = xmltodict.parse(pretty_xml_as_string)

                n = int(dic['StatisticSearch']['list_total_count']['#text'])
                df_ecos = pd.DataFrame(index = [dic['StatisticSearch']['row'][i]['TIME'] for i in range(n)])
                df_ecos[dic['StatisticSearch']['row'][0]['ITEM_NAME1']] = [float(dic['StatisticSearch']['row'][i]['DATA_VALUE']) for i in range(n)]

                if type(df)==type(pd.DataFrame()):
                    df_ecos = df.merge(df_ecos, left_index=True, right_index=True, how='left')

                return df_ecos

        except Exception as e:
            print(str(e))


def getKOSIS(table,period,beg,end,item, orgId='101', obj1='',obj2='',obj3='',obj4='',obj5='',obj6='',obj7='',obj8='', title=None, title_no='0', debug=False):
     # Korean Statistics
    key = 'MzhiMmQwZTYyMWZiNGM1ZGFkZDJmZTI2OTE1OGU2NzQ='
    url = 'https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey='+key \
            +'&orgId='+orgId\
            +'&tblId='+table \
            +'&prdSe='+period \
            +'&startPrdDe='+beg \
            +'&endPrdDe='+end \
            +'&itmId='+item \
            +'&objL1='+obj1 \
            +'&objL2='+obj2 \
            +'&objL3='+obj3 \
            +'&objL4='+obj4 \
            +'&objL5='+obj5 \
            +'&objL6='+obj6 \
            +'&objL7='+obj7 \
            +'&objL8='+obj8 \
            +'&format=json&jsonVD=Y&outputFields=ITM_NM+PRD_DE+DT'
    res = requests.get(url)
    py_json = res.json()

    data = []
    for v in py_json:
        value = []
        value.append(v['PRD_DE'])

        # ✅ DT 값이 '-' 또는 ''일 때 NaN으로 처리
        try:
            value.append(float(v['DT']))
        except (ValueError, KeyError):
            value.append(np.nan)

        data.append(value)

    df = pd.DataFrame(data, columns=['PRD_DE', 'DT'])

    if debug:
        print(df.head())

    return df


    #get json data from url
    with urlopen(url) as url_:
        json_file = url_.read()

    py_json = json.loads(json_file.decode('utf-8'))


    #data transformation
    data = []

    for i, v in enumerate(py_json):
        value = []
        value.append(v['PRD_DE'])
        value.append(float(v['DT']))

        data.append(value)

    if title is not None:
        title = str(title)
    elif title_no=='0':
        title = v['ITM_NM_ENG']
    else:
        title = v['C'+title_no+'_NM_ENG']

    df_kosis = pd.DataFrame({v['PRD_SE']:[x[0] for x in data], title:[x[1] for x in data]}).set_index(v['PRD_SE'])

    if debug:
        return v

    return df_kosis

Collecting xmltodict
  Downloading xmltodict-1.0.2-py3-none-any.whl.metadata (15 kB)
Downloading xmltodict-1.0.2-py3-none-any.whl (13 kB)
Installing collected packages: xmltodict
Successfully installed xmltodict-1.0.2

In [4]:
import pandas as pd
import numpy as np
import os
import seaborn as sns

In [5]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

In [6]:
# change directory to where you have your data file!!
%cd gdrive/MyDrive/GDP/데이터

/content/gdrive/MyDrive/GDP/데이터

## GDP

"('200Y104', 'Q', '1980Q1', '2025Q1','110401')
+ ('200Y104', 'Q', '1980Q1', '2025Q1','110402')"
('200Y104', 'Q', '1980Q1', '2025Q1','110403')

In [8]:
gdp1 = getECOS('200Y104', 'Q', '2014Q1', '2025Q2','110401').reset_index()
gdp2 = getECOS('200Y104', 'Q', '2014Q1', '2025Q2','110402').reset_index()
gdp3 = getECOS('200Y104', 'Q', '2014Q1', '2025Q2','110403').reset_index()

In [11]:
from functools import reduce
# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [gdp1,gdp2,gdp3]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
gdp = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
gdp

     index     전기업  가스, 증기 및 공기조절 공급업  수도, 하수 및 폐기물 처리, 원료 재생업
0   2014Q1  4576.9             1476.4                   3167.7
1   2014Q2  4656.3             1483.6                   3179.3
2   2014Q3  4713.4             1486.3                   3212.1
3   2014Q4  5050.0             1456.1                   3204.8
4   2015Q1  5138.3             1390.5                   3321.0
5   2015Q2  5173.4             1436.3                   3369.4
6   2015Q3  5339.8             1397.4                   3439.0
7   2015Q4  5524.6             1273.4                   3284.0
8   2016Q1  5252.0             1392.8                   3432.7
9   2016Q2  5068.1             1345.3                   3558.8
10  2016Q3  5175.9             1434.2                   3430.1
11  2016Q4  5278.4             1436.0                   3321.9
12  2017Q1  5420.7             1581.8                   3363.0
13  2017Q2  5614.9             1518.6                   3263.8
14  2017Q3  5727.5             1598.2                   3263.0
15  2017Q4  5689.5             1661.7                   3089.6
16  2018Q1  5076.0             1651.8                   3332.3
17  2018Q2  5328.2             1596.7                   3336.7
18  2018Q3  5607.2             1526.1                   3317.3
19  2018Q4  5821.9             1505.9                   3298.8
20  2019Q1  5835.2             1542.1                   3280.6
21  2019Q2  6466.8             1590.9                   3347.2
22  2019Q3  5316.2             1500.0                   3414.7
23  2019Q4  5664.9             1538.6                   3509.4
24  2020Q1  6515.9             1497.2                   3469.2
25  2020Q2  6712.4             1409.8                   3348.2
26  2020Q3  6394.4             1428.2                   3390.3
27  2020Q4  6334.6             1594.2                   3510.9
28  2021Q1  6617.1             1656.3                   3400.3
29  2021Q2  6426.5             1700.6                   3448.5
30  2021Q3  6513.1             1617.6                   3470.6
31  2021Q4  6519.3             1550.4                   3482.8
32  2022Q1  7020.8             1537.5                   3367.7
33  2022Q2  7224.8             1567.7                   3467.7
34  2022Q3  7309.1             1536.8                   3317.4
35  2022Q4  6987.7             1604.4                   3551.0
36  2023Q1  7795.0             1425.7                   3424.9
37  2023Q2  7354.8             1453.1                   3459.3
38  2023Q3  6799.7             1536.9                   3324.2
39  2023Q4  7632.1             1624.1                   3467.8
40  2024Q1  7547.9             1520.9                   3512.5
41  2024Q2  7528.2             1584.8                   3465.6
42  2024Q3  8122.9             1649.9                   3544.5
43  2024Q4  8190.6             1422.5                   3099.7
44  2025Q1  8128.9             1632.6                   3429.3
45  2025Q2  7497.4             1580.3                   3420.5

In [12]:
gdp['gdp'] = gdp['전기업']+gdp['가스, 증기 및 공기조절 공급업']+gdp['수도, 하수 및 폐기물 처리, 원료 재생업']
gdp = gdp.drop(columns=["전기업","가스, 증기 및 공기조절 공급업","수도, 하수 및 폐기물 처리, 원료 재생업"])

In [13]:
gdp

     index      gdp
0   2014Q1   9221.0
1   2014Q2   9319.2
2   2014Q3   9411.8
3   2014Q4   9710.9
4   2015Q1   9849.8
5   2015Q2   9979.1
6   2015Q3  10176.2
7   2015Q4  10082.0
8   2016Q1  10077.5
9   2016Q2   9972.2
10  2016Q3  10040.2
11  2016Q4  10036.3
12  2017Q1  10365.5
13  2017Q2  10397.3
14  2017Q3  10588.7
15  2017Q4  10440.8
16  2018Q1  10060.1
17  2018Q2  10261.6
18  2018Q3  10450.6
19  2018Q4  10626.6
20  2019Q1  10657.9
21  2019Q2  11404.9
22  2019Q3  10230.9
23  2019Q4  10712.9
24  2020Q1  11482.3
25  2020Q2  11470.4
26  2020Q3  11212.9
27  2020Q4  11439.7
28  2021Q1  11673.7
29  2021Q2  11575.6
30  2021Q3  11601.3
31  2021Q4  11552.5
32  2022Q1  11926.0
33  2022Q2  12260.2
34  2022Q3  12163.3
35  2022Q4  12143.1
36  2023Q1  12645.6
37  2023Q2  12267.2
38  2023Q3  11660.8
39  2023Q4  12724.0
40  2024Q1  12581.3
41  2024Q2  12578.6
42  2024Q3  13317.3
43  2024Q4  12712.8
44  2025Q1  13190.8
45  2025Q2  12498.2

##PPI(단순평균)

('404Y014','Q','1965Q1','2025Q2','401AA')
('404Y014','Q','1965Q1', '2025Q2','402AA')

In [14]:
ppi1 = getECOS('404Y014','Q','2014Q1','2025Q2','401AA').reset_index()
ppi2 = getECOS('404Y014','Q','2014Q1','2025Q2','402AA').reset_index()

In [16]:
# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [ppi1,ppi2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
ppi = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
ppi

ppi['ppi']=(ppi['전력,가스및증기']+ppi['수도,폐기물처리및재활용서비스'])/2
ppi = ppi.drop(columns=["전력,가스및증기","수도,폐기물처리및재활용서비스"])
ppi

     index      ppi
0   2014Q1   97.340
1   2014Q2   97.745
2   2014Q3   97.725
3   2014Q4   97.825
4   2015Q1   95.625
5   2015Q2   92.665
6   2015Q3   91.925
7   2015Q4   92.945
8   2016Q1   92.080
9   2016Q2   90.820
10  2016Q3   89.835
11  2016Q4   91.555
12  2017Q1   91.970
13  2017Q2   92.365
14  2017Q3   93.015
15  2017Q4   94.745
16  2018Q1   94.830
17  2018Q2   95.055
18  2018Q3   95.245
19  2018Q4   95.790
20  2019Q1   96.960
21  2019Q2   97.575
22  2019Q3   99.010
23  2019Q4   99.830
24  2020Q1  101.460
25  2020Q2  101.335
26  2020Q3   98.700
27  2020Q4   98.500
28  2021Q1   99.155
29  2021Q2  100.260
30  2021Q3  100.850
31  2021Q4  104.685
32  2022Q1  109.225
33  2022Q2  112.260
34  2022Q3  117.490
35  2022Q4  126.320
36  2023Q1  129.560
37  2023Q2  127.350
38  2023Q3  128.105
39  2023Q4  129.630
40  2024Q1  131.295
41  2024Q2  130.820
42  2024Q3  131.590
43  2024Q4  135.020
44  2025Q1  136.425
45  2025Q2  136.305

##BSI(단순평균)

D3500, S5000

In [17]:
업황실적BSI1 = getECOS('512Y007','M','201401','202506','AA','D3500').reset_index()
업황실적BSI2 = getECOS('512Y007','M','201401','202506','AA','S5000').reset_index()

In [18]:
from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [업황실적BSI1,업황실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
업황실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
업황실적BSI

      index  업황실적BSI 1)_x  업황실적BSI 1)_y
0    201401         105.0          60.0
1    201402          91.0          53.0
2    201403          95.0          61.0
3    201404          87.0          64.0
4    201405          82.0          69.0
..      ...           ...           ...
133  202502          91.0          51.0
134  202503          95.0          52.0
135  202504          83.0          52.0
136  202505          85.0          58.0
137  202506          84.0          46.0

[138 rows x 3 columns]

In [19]:
업황실적BSI['업황실적BSI']=(업황실적BSI['업황실적BSI 1)_x']+업황실적BSI['업황실적BSI 1)_y'])/2
업황실적BSI = 업황실적BSI.drop(columns=["업황실적BSI 1)_x","업황실적BSI 1)_y"])
업황실적BSI

      index  업황실적BSI
0    201401     82.5
1    201402     72.0
2    201403     78.0
3    201404     75.5
4    201405     75.5
..      ...      ...
133  202502     71.0
134  202503     73.5
135  202504     67.5
136  202505     71.5
137  202506     65.0

[138 rows x 2 columns]

In [20]:
매출실적BSI1 = getECOS('512Y007','M','201401','202506','AB','D3500').reset_index()
매출실적BSI2 = getECOS('512Y007','M','201401','202506','AB','S5000').reset_index()

from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [매출실적BSI1,매출실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
매출실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
매출실적BSI

매출실적BSI['매출실적BSI']=(매출실적BSI['매출실적BSI 2)_x']+매출실적BSI['매출실적BSI 2)_y'])/2
매출실적BSI = 매출실적BSI.drop(columns=["매출실적BSI 2)_x","매출실적BSI 2)_y"])
매출실적BSI

      index  매출실적BSI
0    201401     75.5
1    201402     79.5
2    201403     80.5
3    201404     79.5
4    201405     75.5
..      ...      ...
133  202502     72.0
134  202503     78.0
135  202504     73.0
136  202505     76.0
137  202506     69.0

[138 rows x 2 columns]

In [21]:
채산성실적BSI1 = getECOS('512Y007','M','201401','202506','AE','D3500').reset_index()
채산성실적BSI2 = getECOS('512Y007','M','201401','202506','AE','S5000').reset_index()
from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [채산성실적BSI1,채산성실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
채산성실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
채산성실적BSI

채산성실적BSI['채산성실적BSI']=(채산성실적BSI['채산성실적BSI 6)_x']+채산성실적BSI['채산성실적BSI 6)_y'])/2
채산성실적BSI = 채산성실적BSI.drop(columns=["채산성실적BSI 6)_x","채산성실적BSI 6)_y"])
채산성실적BSI

      index  채산성실적BSI
0    201401      87.5
1    201402      76.0
2    201403      78.5
3    201404      86.0
4    201405      83.0
..      ...       ...
133  202502      75.0
134  202503      78.5
135  202504      78.0
136  202505      78.5
137  202506      77.0

[138 rows x 2 columns]

In [22]:
자금사정실적BSI1 = getECOS('512Y007','M','201401','202506','AO','D3500').reset_index()
자금사정실적BSI2 = getECOS('512Y007','M','201401','202506','AO','S5000').reset_index()


# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [자금사정실적BSI1,자금사정실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
자금사정실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
자금사정실적BSI


자금사정실적BSI['자금사정실적BSI']=(자금사정실적BSI['자금사정실적BSI 6)_x']+자금사정실적BSI['자금사정실적BSI 6)_y'])/2
자금사정실적BSI = 자금사정실적BSI.drop(columns=["자금사정실적BSI 6)_x","자금사정실적BSI 6)_y"])
자금사정실적BSI

      index  자금사정실적BSI
0    201401       86.5
1    201402       81.0
2    201403       77.5
3    201404       83.5
4    201405       86.0
..      ...        ...
133  202502       78.0
134  202503       78.5
135  202504       76.0
136  202505       77.0
137  202506       76.0

[138 rows x 2 columns]

In [24]:
인력사정실적BSI1 = getECOS('512Y007','M','201401','202506','AJ','D3500').reset_index()
인력사정실적BSI2 = getECOS('512Y007','M','201401','202506','AJ','S5000').reset_index()

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [인력사정실적BSI1,인력사정실적BSI2]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
인력사정실적BSI = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
인력사정실적BSI

인력사정실적BSI['인력사정실적BSI']=(인력사정실적BSI['인력사정실적BSI 3)_x']+인력사정실적BSI['인력사정실적BSI 3)_y'])/2
인력사정실적BSI = 인력사정실적BSI.drop(columns=["인력사정실적BSI 3)_x","인력사정실적BSI 3)_y"])
인력사정실적BSI

      index  인력사정실적BSI
0    201401       86.0
1    201402       85.0
2    201403       87.0
3    201404       88.5
4    201405       87.0
..      ...        ...
133  202502       74.0
134  202503       80.0
135  202504       82.5
136  202505       78.5
137  202506       79.0

[138 rows x 2 columns]

In [25]:
from functools import reduce

# 불러온 BSIDataFrame들을 리스트로 모으기
dfs = [업황실적BSI, 매출실적BSI, 채산성실적BSI, 자금사정실적BSI, 인력사정실적BSI]
dfs = [df.drop(columns=[col for col in df.columns if "Unnamed" in col]) for df in dfs]

# '시점' 기준으로 병합
df_merged = reduce(lambda left, right: pd.merge(left, right, on="index", how="outer"), dfs)
df_merged

      index  업황실적BSI  매출실적BSI  채산성실적BSI  자금사정실적BSI  인력사정실적BSI
0    201401     82.5     75.5      87.5       86.5       86.0
1    201402     72.0     79.5      76.0       81.0       85.0
2    201403     78.0     80.5      78.5       77.5       87.0
3    201404     75.5     79.5      86.0       83.5       88.5
4    201405     75.5     75.5      83.0       86.0       87.0
..      ...      ...      ...       ...        ...        ...
133  202502     71.0     72.0      75.0       78.0       74.0
134  202503     73.5     78.0      78.5       78.5       80.0
135  202504     67.5     73.0      78.0       76.0       82.5
136  202505     71.5     76.0      78.5       77.0       78.5
137  202506     65.0     69.0      77.0       76.0       79.0

[138 rows x 6 columns]

In [26]:
df_merged.isnull().sum()

index        0
업황실적BSI      0
매출실적BSI      0
채산성실적BSI     0
자금사정실적BSI    0
인력사정실적BSI    0
dtype: int64

In [27]:
import pandas as pd

# index가 숫자라면 문자열로 변환
df_merged['index'] = df_merged['index'].astype(str)

# 연도와 월 분리
df_merged['연도'] = df_merged['index'].str[:4].astype(int)
df_merged['월'] = df_merged['index'].str[4:6].astype(int)

# 월 → 분기 변환 함수
def month_to_quarter(month):
    if month in [1, 2, 3]:
        return 'Q1'
    elif month in [4, 5, 6]:
        return 'Q2'
    elif month in [7, 8, 9]:
        return 'Q3'
    else:
        return 'Q4'

# 분기 계산
df_merged['분기'] = df_merged['월'].apply(month_to_quarter)

# 분기 인덱스 생성 (예: 2015Q1)
df_merged['index'] = df_merged['연도'].astype(str) + df_merged['분기']

# 분기별 평균 집계
df_quarter = df_merged.groupby('index').mean(numeric_only=True).reset_index()

# 결과 확인
print(df_quarter.head())

    index    업황실적BSI    매출실적BSI   채산성실적BSI  자금사정실적BSI  인력사정실적BSI      연도     월
0  2014Q1  77.500000  78.500000  80.666667  81.666667  86.000000  2014.0   2.0
1  2014Q2  73.500000  74.833333  82.833333  84.333333  88.666667  2014.0   5.0
2  2014Q3  69.833333  72.666667  77.500000  78.500000  89.666667  2014.0   8.0
3  2014Q4  70.333333  75.333333  81.500000  83.000000  91.166667  2014.0  11.0
4  2015Q1  65.000000  72.666667  77.166667  78.333333  90.666667  2015.0   2.0

In [28]:
df_quarter = df_quarter.drop(columns=['연도', '월'], errors='ignore')

In [29]:
dfs = [ppi, gdp]
df_final = df_quarter.copy()
key_col = 'index'
for df in dfs:
    df_final = df_final.merge(df, on=key_col, how='left')

df_final

,index,업황실적BSI,매출실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,ppi,gdp
0,2014Q1,77.500000,78.500000,80.666667,81.666667,86.000000,97.340,9221.0
1,2014Q2,73.500000,74.833333,82.833333,84.333333,88.666667,97.745,9319.2
2,2014Q3,69.833333,72.666667,77.500000,78.500000,89.666667,97.725,9411.8
3,2014Q4,70.333333,75.333333,81.500000,83.000000,91.166667,97.825,9710.9
4,2015Q1,65.000000,72.666667,77.166667,78.333333,90.666667,95.625,9849.8
5,2015Q2,73.000000,71.333333,82.833333,85.166667,85.833333,92.665,9979.1
6,2015Q3,62.166667,58.500000,75.666667,80.000000,85.666667,91.925,10176.2
7,2015Q4,61.833333,57.000000,75.833333,80.833333,87.500000,92.945,10082.0
8,2016Q1,62.166667,61.166667,76.666667,79.333333,87.333333,92.080,10077.5
9,2016Q2,66.833333,65.500000,79.000000,83.333333,84.500000,90.820,9972.2
10,2016Q3,69.166667,71.333333,80.666667,84.666667,86.833333,89.835,10040.2
11,2016Q4,73.666667,80.333333,89.166667,88.000000,90.500000,91.555,10036.3
12,2017Q1,82.000000,87.166667,91.000000,91.666667,87.000000,91.970,10365.5
13,2017Q2,86.333333,93.166667,86.166667,87.000000,87.833333,92.365,10397.3
14,2017Q3,85.000000,93.500000,92.833333,88.000000,89.833333,93.015,10588.7
15,2017Q4,88.333333,95.500000,90.833333,89.833333,89.666667,94.745,10440.8
16,2018Q1,88.000000,99.333333,91.000000,87.000000,92.000000,94.830,10060.1
17,2018Q2,86.166667,96.833333,91.000000,88.833333,88.500000,95.055,10261.6
18,2018Q3,83.166667,94.000000,88.666667,88.166667,84.666667,95.245,10450.6
19,2018Q4,81.666667,88.500000,86.833333,87.000000,85.833333,95.790,10626.6
20,2019Q1,78.666667,83.166667,86.500000,86.000000,89.166667,96.960,10657.9
21,2019Q2,81.333333,83.500000,85.000000,83.833333,86.000000,97.575,11404.9
22,2019Q3,78.833333,83.666667,83.166667,84.333333,88.500000,99.010,10230.9
23,2019Q4,81.500000,81.666667,86.333333,84.833333,86.833333,99.830,10712.9
24,2020Q1,69.166667,68.833333,77.333333,79.500000,86.833333,101.460,11482.3
25,2020Q2,59.833333,59.500000,72.833333,73.333333,84.666667,101.335,11470.4
26,2020Q3,65.833333,59.000000,76.000000,77.500000,80.666667,98.700,11212.9
27,2020Q4,72.833333,66.000000,81.666667,81.333333,83.666667,98.500,11439.7
28,2021Q1,80.666667,79.500000,87.000000,82.666667,81.833333,99.155,11673.7
29,2021Q2,88.833333,91.166667,91.500000,87.166667,82.500000,100.260,11575.6
30,2021Q3,94.000000,103.500000,93.000000,90.166667,86.333333,100.850,11601.3
31,2021Q4,85.500000,95.500000,90.000000,81.833333,79.333333,104.685,11552.5
32,2022Q1,82.666667,94.833333,85.166667,85.500000,76.833333,109.225,11926.0
33,2022Q2,82.000000,91.166667,79.666667,81.833333,80.166667,112.260,12260.2
34,2022Q3,74.500000,87.166667,81.666667,75.000000,76.000000,117.490,12163.3
35,2022Q4,77.166667,93.500000,81.666667,80.333333,75.666667,126.320,12143.1
36,2023Q1,75.000000,80.333333,75.833333,79.166667,76.500000,129.560,12645.6
37,2023Q2,73.500000,72.166667,78.666667,77.333333,80.333333,127.350,12267.2
38,2023Q3,76.833333,73.833333,81.666667,81.333333,85.500000,128.105,11660.8
39,2023Q4,72.000000,69.166667,79.000000,81.000000,80.166667,129.630,12724.0
40,2024Q1,73.000000,70.166667,80.833333,78.833333,76.166667,131.295,12581.3
41,2024Q2,77.666667,79.666667,86.333333,84.500000,78.166667,130.820,12578.6
42,2024Q3,78.500000,79.333333,85.000000,83.833333,81.166667,131.590,13317.3
43,2024Q4,71.833333,73.166667,81.666667,82.500000,80.833333,135.020,12712.8
44,2025Q1,70.166667,72.000000,75.000000,78.166667,76.500000,136.425,13190.8
45,2025Q2,68.000000,72.666667,77.833333,76.333333,80.000000,136.305,12498.2

In [30]:
df_final.to_csv("전기가스수도1차.csv")

## 생산지수

('DT_1F02001','Q','197501','202502','T20','101','00','D35')
('DT_1KC2020','Q','200001','202502','T3','101','E')

In [39]:
생산지수 = getKOSIS('DT_1KC2020','Q','201401','202502','T3','101','E')
def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

생산지수['index']=생산지수['PRD_DE'].apply(to_quarter)
생산지수 = 생산지수.drop(columns=["PRD_DE"])
생산지수 = 생산지수.rename(columns={'DT': '생산지수'})
생산지수

     생산지수   index
0    87.7  2014Q1
1    85.3  2014Q2
2    86.9  2014Q3
3    87.8  2014Q4
4    88.6  2015Q1
5    90.9  2015Q2
6    94.3  2015Q3
7    90.1  2015Q4
8    92.3  2016Q1
9    95.1  2016Q2
10   93.3  2016Q3
11   93.6  2016Q4
12   96.2  2017Q1
13   92.1  2017Q2
14   95.0  2017Q3
15   94.8  2017Q4
16   95.9  2018Q1
17   98.0  2018Q2
18   97.7  2018Q3
19   97.2  2018Q4
20   94.7  2019Q1
21   94.2  2019Q2
22   98.1  2019Q3
23   99.3  2019Q4
24  101.3  2020Q1
25   97.8  2020Q2
26   97.6  2020Q3
27  103.2  2020Q4
28  101.3  2021Q1
29  103.1  2021Q2
30  102.4  2021Q3
31  101.8  2021Q4
32   99.0  2022Q1
33   97.3  2022Q2
34   98.1  2022Q3
35   95.9  2022Q4
36   98.8  2023Q1
37   96.9  2023Q2
38   97.1  2023Q3
39   94.8  2023Q4
40   96.2  2024Q1
41   95.0  2024Q2
42   95.0  2024Q3
43   94.5  2024Q4
44   91.1  2025Q1
45   92.1  2025Q2

https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MGNkMzY3MTdhNjZlMTNiZDMxYjU4NDA4NTdjZWU0YmQ=&itmId=T20+&objL1=D+&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=Q&startPrdDe=201401&endPrdDe=202502&outputFields=OBJ_NM+NM+ITM_NM+PRD_DE+&orgId=101&tblId=DT_1F02016

## 내수출하지수

In [40]:
내수출하지수 = getKOSIS('DT_1F02016','Q','201401','202502','T20','101','D')

In [41]:
def to_quarter(x):
    year = str(x)[:4]   # 앞 4자리 → 연도
    q = str(x)[-2:]     # 뒤 2자리 → 분기
    return f"{year}Q{q[-1]}"  # 예: 200904 → 2009Q4

내수출하지수['index']=내수출하지수['PRD_DE'].apply(to_quarter)
내수출하지수 = 내수출하지수.drop(columns=["PRD_DE"])
내수출하지수 = 내수출하지수.rename(columns={'DT': '내수출하지수'})
내수출하지수

     내수출하지수   index
0    91.701  2014Q1
1    94.490  2014Q2
2    93.042  2014Q3
3    95.707  2014Q4
4    94.011  2015Q1
5    92.986  2015Q2
6    92.834  2015Q3
7    90.764  2015Q4
8    95.550  2016Q1
9    92.520  2016Q2
10   94.783  2016Q3
11   93.236  2016Q4
12   97.685  2017Q1
13  100.033  2017Q2
14  102.251  2017Q3
15  104.131  2017Q4
16  104.794  2018Q1
17  105.313  2018Q2
18  107.641  2018Q3
19  105.995  2018Q4
20  103.961  2019Q1
21  105.336  2019Q2
22  102.430  2019Q3
23   99.936  2019Q4
24   97.600  2020Q1
25  100.400  2020Q2
26   99.900  2020Q3
27  102.400  2020Q4
28  103.100  2021Q1
29  105.200  2021Q2
30  106.600  2021Q3
31  105.700  2021Q4
32  110.000  2022Q1
33  108.100  2022Q2
34  107.400  2022Q3
35  104.900  2022Q4
36  104.400  2023Q1
37  102.700  2023Q2
38  102.800  2023Q3
39  103.900  2023Q4
40  104.800  2024Q1
41  105.300  2024Q2
42  109.800  2024Q3
43  100.300  2024Q4
44  108.200  2025Q1
45  106.800  2025Q2

## 기업데이터

In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv('임지오기업.csv')

전기업 + 가스, 증기 및 공기조절 공급업 수도, 하수 및 폐기물 처리, 원료 재생업

In [44]:
운송장비기업1 = df[df['매핑한 산업'] == "전기업 + 가스, 증기 및 공기조절 공급업"]
운송장비기업2 = df[df['매핑한 산업'] == "하수 및 폐기물 처리, 원료 재생업"]

In [45]:
columns = ['EBITDA', '인건비']
grouped1 = 운송장비기업1.groupby('조사일')[columns].sum()
grouped1

                  EBITDA           인건비
조사일
2000-01-01  0.000000e+00  1.001799e+08
2000-04-01  0.000000e+00  1.270041e+08
2000-07-01  0.000000e+00  9.326003e+07
2000-10-01  9.611912e+12  1.335659e+09
2001-01-01  0.000000e+00  9.946722e+07
...                  ...           ...
2024-04-01  1.793114e+12  2.443646e+08
2024-07-01  1.090854e+12  2.565800e+08
2024-10-01  5.366528e+12  2.415679e+08
2025-01-01  4.604242e+12  2.041978e+08
2025-04-01  2.828906e+12 -1.913964e+08

[102 rows x 2 columns]

In [46]:
grouped1 = grouped1.reset_index()

In [47]:
grouped1['조사일']=pd.to_datetime(grouped1['조사일'])

# 분기(Quarter) 단위로 변환
grouped1["index"] = grouped1["조사일"].dt.to_period("Q")
grouped1 = grouped1.drop(columns=["조사일"])
print(grouped1)

grouped1

           EBITDA           인건비   index
0    0.000000e+00  1.001799e+08  2000Q1
1    0.000000e+00  1.270041e+08  2000Q2
2    0.000000e+00  9.326003e+07  2000Q3
3    9.611912e+12  1.335659e+09  2000Q4
4    0.000000e+00  9.946722e+07  2001Q1
..            ...           ...     ...
97   1.793114e+12  2.443646e+08  2024Q2
98   1.090854e+12  2.565800e+08  2024Q3
99   5.366528e+12  2.415679e+08  2024Q4
100  4.604242e+12  2.041978e+08  2025Q1
101  2.828906e+12 -1.913964e+08  2025Q2

[102 rows x 3 columns]

           EBITDA           인건비   index
0    0.000000e+00  1.001799e+08  2000Q1
1    0.000000e+00  1.270041e+08  2000Q2
2    0.000000e+00  9.326003e+07  2000Q3
3    9.611912e+12  1.335659e+09  2000Q4
4    0.000000e+00  9.946722e+07  2001Q1
..            ...           ...     ...
97   1.793114e+12  2.443646e+08  2024Q2
98   1.090854e+12  2.565800e+08  2024Q3
99   5.366528e+12  2.415679e+08  2024Q4
100  4.604242e+12  2.041978e+08  2025Q1
101  2.828906e+12 -1.913964e+08  2025Q2

[102 rows x 3 columns]

In [51]:
mask = (grouped1["index"] >= pd.Period("2014Q1")) & (grouped1["index"] <= pd.Period("2025Q2"))
기업= grouped1.loc[mask]
기업
기업['합산'] = 기업['EBITDA']+기업['인건비']
기업

/tmp/ipython-input-3670662141.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기업['합산'] = 기업['EBITDA']+기업['인건비']

           EBITDA          인건비   index            합산
56   1.574491e+12  190183934.0  2014Q1  1.574682e+12
57   8.579764e+11  186647701.0  2014Q2  8.581630e+11
58   2.455023e+12  194933769.0  2014Q3  2.455218e+12
59   1.842156e+12  159067852.0  2014Q4  1.842315e+12
60   1.940467e+12  201482251.0  2015Q1  1.940669e+12
61   3.114885e+12  200631918.0  2015Q2  3.115086e+12
62   3.111111e+12  194980600.0  2015Q3  3.111306e+12
63   1.698320e+12  245019534.0  2015Q4  1.698565e+12
64   2.543067e+12  211014421.0  2016Q1  2.543278e+12
65   2.935296e+12  196393733.0  2016Q2  2.935493e+12
66   3.717050e+12  239001096.0  2016Q3  3.717289e+12
67   1.466102e+12  285468812.0  2016Q4  1.466387e+12
68   1.415622e+12  210574223.0  2017Q1  1.415833e+12
69   1.490701e+12  217812412.0  2017Q2  1.490919e+12
70   2.909997e+12  256284198.0  2017Q3  2.910253e+12
71   1.784161e+12  272942823.0  2017Q4  1.784434e+12
72   9.647345e+11  237985667.0  2018Q1  9.649725e+11
73   5.546587e+11  222409216.0  2018Q2  5.548812e+11
74   1.687232e+12  247013685.0  2018Q3  1.687479e+12
75   8.887286e+11  254037233.0  2018Q4  8.889827e+11
76  -1.358156e+11  239403120.0  2019Q1 -1.355762e+11
77   1.694234e+12  235268508.0  2019Q2  1.694470e+12
78   1.727302e+12  245419572.0  2019Q3  1.727547e+12
79   5.876310e+11  351575108.0  2019Q4  5.879826e+11
80   1.948368e+12  251181480.0  2020Q1  1.948619e+12
81   1.733330e+12  238578817.0  2020Q2  1.733569e+12
82   2.728452e+12  248434616.0  2020Q3  2.728700e+12
83   3.010684e+12  300737944.0  2020Q4  3.010985e+12
84   1.372078e+12  259281018.0  2021Q1  1.372337e+12
85   3.409066e+11  239941974.0  2021Q2  3.411465e+11
86   2.037810e+08  268666292.0  2021Q3  4.724473e+08
87  -2.425974e+12  285524486.0  2021Q4 -2.425689e+12
88  -6.852098e+12  247426340.0  2022Q1 -6.851851e+12
89  -4.406913e+12  245864544.0  2022Q2 -4.406667e+12
90  -7.507268e+12  269253751.0  2022Q3 -7.506999e+12
91  -7.712317e+12  273855213.0  2022Q4 -7.712044e+12
92  -4.339705e+12  261905439.0  2023Q1 -4.339443e+12
93   6.233543e+11  194227435.0  2023Q2  6.235485e+11
94   8.919776e+11  252359598.0  2023Q3  8.922299e+11
95   3.906316e+12  301698198.0  2023Q4  3.906617e+12
96   3.910664e+12  259467494.0  2024Q1  3.910923e+12
97   1.793114e+12  244364619.0  2024Q2  1.793359e+12
98   1.090854e+12  256580006.0  2024Q3  1.091111e+12
99   5.366528e+12  241567935.0  2024Q4  5.366769e+12
100  4.604242e+12  204197775.0  2025Q1  4.604446e+12
101  2.828906e+12 -191396355.0  2025Q2  2.828715e+12

## 전체 데이터 합산

In [52]:
from functools import reduce
import pandas as pd

# 모든 데이터프레임의 index 컬럼을 문자열로 변환
for df in [df_final,생산지수, 내수출하지수, 기업]:
    df['index'] = df['index'].astype(str)

# 리스트에 넣고 합치기
dfs = [df_final,생산지수, 내수출하지수, 기업]
df_merged = reduce(lambda left, right: pd.merge(left, right, on='index', how='outer'), dfs)

/tmp/ipython-input-4156791558.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['index'] = df['index'].astype(str)

In [53]:
df_merged
df_merged = df_merged[['index'] + [col for col in df_merged.columns if col != 'index']]

In [54]:
df_merged

,index,업황실적BSI,매출실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,ppi,gdp,생산지수,내수출하지수,EBITDA,인건비,합산
0,2014Q1,77.500000,78.500000,80.666667,81.666667,86.000000,97.340,9221.0,87.7,91.701,1.574491e+12,190183934.0,1.574682e+12
1,2014Q2,73.500000,74.833333,82.833333,84.333333,88.666667,97.745,9319.2,85.3,94.490,8.579764e+11,186647701.0,8.581630e+11
2,2014Q3,69.833333,72.666667,77.500000,78.500000,89.666667,97.725,9411.8,86.9,93.042,2.455023e+12,194933769.0,2.455218e+12
3,2014Q4,70.333333,75.333333,81.500000,83.000000,91.166667,97.825,9710.9,87.8,95.707,1.842156e+12,159067852.0,1.842315e+12
4,2015Q1,65.000000,72.666667,77.166667,78.333333,90.666667,95.625,9849.8,88.6,94.011,1.940467e+12,201482251.0,1.940669e+12
5,2015Q2,73.000000,71.333333,82.833333,85.166667,85.833333,92.665,9979.1,90.9,92.986,3.114885e+12,200631918.0,3.115086e+12
6,2015Q3,62.166667,58.500000,75.666667,80.000000,85.666667,91.925,10176.2,94.3,92.834,3.111111e+12,194980600.0,3.111306e+12
7,2015Q4,61.833333,57.000000,75.833333,80.833333,87.500000,92.945,10082.0,90.1,90.764,1.698320e+12,245019534.0,1.698565e+12
8,2016Q1,62.166667,61.166667,76.666667,79.333333,87.333333,92.080,10077.5,92.3,95.550,2.543067e+12,211014421.0,2.543278e+12
9,2016Q2,66.833333,65.500000,79.000000,83.333333,84.500000,90.820,9972.2,95.1,92.520,2.935296e+12,196393733.0,2.935493e+12
10,2016Q3,69.166667,71.333333,80.666667,84.666667,86.833333,89.835,10040.2,93.3,94.783,3.717050e+12,239001096.0,3.717289e+12
11,2016Q4,73.666667,80.333333,89.166667,88.000000,90.500000,91.555,10036.3,93.6,93.236,1.466102e+12,285468812.0,1.466387e+12
12,2017Q1,82.000000,87.166667,91.000000,91.666667,87.000000,91.970,10365.5,96.2,97.685,1.415622e+12,210574223.0,1.415833e+12
13,2017Q2,86.333333,93.166667,86.166667,87.000000,87.833333,92.365,10397.3,92.1,100.033,1.490701e+12,217812412.0,1.490919e+12
14,2017Q3,85.000000,93.500000,92.833333,88.000000,89.833333,93.015,10588.7,95.0,102.251,2.909997e+12,256284198.0,2.910253e+12
15,2017Q4,88.333333,95.500000,90.833333,89.833333,89.666667,94.745,10440.8,94.8,104.131,1.784161e+12,272942823.0,1.784434e+12
16,2018Q1,88.000000,99.333333,91.000000,87.000000,92.000000,94.830,10060.1,95.9,104.794,9.647345e+11,237985667.0,9.649725e+11
17,2018Q2,86.166667,96.833333,91.000000,88.833333,88.500000,95.055,10261.6,98.0,105.313,5.546587e+11,222409216.0,5.548812e+11
18,2018Q3,83.166667,94.000000,88.666667,88.166667,84.666667,95.245,10450.6,97.7,107.641,1.687232e+12,247013685.0,1.687479e+12
19,2018Q4,81.666667,88.500000,86.833333,87.000000,85.833333,95.790,10626.6,97.2,105.995,8.887286e+11,254037233.0,8.889827e+11
20,2019Q1,78.666667,83.166667,86.500000,86.000000,89.166667,96.960,10657.9,94.7,103.961,-1.358156e+11,239403120.0,-1.355762e+11
21,2019Q2,81.333333,83.500000,85.000000,83.833333,86.000000,97.575,11404.9,94.2,105.336,1.694234e+12,235268508.0,1.694470e+12
22,2019Q3,78.833333,83.666667,83.166667,84.333333,88.500000,99.010,10230.9,98.1,102.430,1.727302e+12,245419572.0,1.727547e+12
23,2019Q4,81.500000,81.666667,86.333333,84.833333,86.833333,99.830,10712.9,99.3,99.936,5.876310e+11,351575108.0,5.879826e+11
24,2020Q1,69.166667,68.833333,77.333333,79.500000,86.833333,101.460,11482.3,101.3,97.600,1.948368e+12,251181480.0,1.948619e+12
25,2020Q2,59.833333,59.500000,72.833333,73.333333,84.666667,101.335,11470.4,97.8,100.400,1.733330e+12,238578817.0,1.733569e+12
26,2020Q3,65.833333,59.000000,76.000000,77.500000,80.666667,98.700,11212.9,97.6,99.900,2.728452e+12,248434616.0,2.728700e+12
27,2020Q4,72.833333,66.000000,81.666667,81.333333,83.666667,98.500,11439.7,103.2,102.400,3.010684e+12,300737944.0,3.010985e+12
28,2021Q1,80.666667,79.500000,87.000000,82.666667,81.833333,99.155,11673.7,101.3,103.100,1.372078e+12,259281018.0,1.372337e+12
29,2021Q2,88.833333,91.166667,91.500000,87.166667,82.500000,100.260,11575.6,103.1,105.200,3.409066e+11,239941974.0,3.411465e+11
30,2021Q3,94.000000,103.500000,93.000000,90.166667,86.333333,100.850,11601.3,102.4,106.600,2.037810e+08,268666292.0,4.724473e+08
31,2021Q4,85.500000,95.500000,90.000000,81.833333,79.333333,104.685,11552.5,101.8,105.700,-2.425974e+12,285524486.0,-2.425689e+12
32,2022Q1,82.666667,94.833333,85.166667,85.500000,76.833333,109.225,11926.0,99.0,110.000,-6.852098e+12,247426340.0,-6.851851e+12
33,2022Q2,82.000000,91.166667,79.666667,81.833333,80.166667,112.260,12260.2,97.3,108.100,-4.406913e+12,245864544.0,-4.406667e+12
34,2022Q3,74.500000,87.166667,81.666667,75.000000,76.000000,117.490,12163.3,98.1,107.400,-7.507268e+12,269253751.0,-7.506999e+12
35,2022Q4,77.166667,93.500000,81.666667,80.333333,75.666667,126.320,12143.1,95.9,104.900,-7.712317e+12,273855213.0,-7.712044e+12
36,2023Q1,75.000000,80.333333,75.833333,79.166667,76.500000,129.560,12645.6,98.8,104.400,-4.339705e+12,261905439.0,-4.339443e+12
37,2023Q2,73.500000,72.166667,78.666667,77.333333,80.333333,127.350,12267.2,96.9,102.700,6.233543e+11,194227435.0,6.235485e+11
38,2023Q3,76.833333,73.833333,81.666667,81.333333,85.500000,128.105,11660.8,97.1,102.800,8.919776e+11,252359598.0,8.922299e+11
39,2023Q4,72.000000,69.166667,79.000000,81.000000,80.166667,129.630,12724.0,94.8,103.900,3.906316e+12,301698198.0,3.906617e+12
40,2024Q1,73.000000,70.166667,80.833333,78.833333,76.166667,131.295,12581.3,96.2,104.800,3.910664e+12,259467494.0,3.910923e+12
41,2024Q2,77.666667,79.666667,86.333333,84.500000,78.166667,130.820,12578.6,95.0,105.300,1.793114e+12,244364619.0,1.793359e+12
42,2024Q3,78.500000,79.333333,85.000000,83.833333,81.166667,131.590,13317.3,95.0,109.800,1.090854e+12,256580006.0,1.091111e+12
43,2024Q4,71.833333,73.166667,81.666667,82.500000,80.833333,135.020,12712.8,94.5,100.300,5.366528e+12,241567935.0,5.366769e+12
44,2025Q1,70.166667,72.000000,75.000000,78.166667,76.500000,136.425,13190.8,91.1,108.200,4.604242e+12,204197775.0,4.604446e+12
45,2025Q2,68.000000,72.666667,77.833333,76.333333,80.000000,136.305,12498.2,92.1,106.800,2.828906e+12,-191396355.0,2.828715e+12

In [55]:
df_merged.to_csv('전기가스수도.csv')

# 데이터 QoQ 반환

In [56]:
import pandas as pd

# df는 위의 데이터프레임
df_qoq = df_merged.copy()

# 분기 순서대로 정렬 (혹시 index가 문자열일 경우를 대비)
df_qoq = df_qoq.sort_values('index')

# 수치형 컬럼만 선택 (index 제외)
num_cols = df_qoq.select_dtypes(include=['number']).columns

# 전분기 대비 증감률 (%) 계산
df_qoq[num_cols] = df_qoq[num_cols].pct_change() * 100

# 결과 확인
print(df_qoq.head())

    index   업황실적BSI   매출실적BSI  채산성실적BSI  자금사정실적BSI  인력사정실적BSI       ppi  \
0  2014Q1       NaN       NaN       NaN        NaN        NaN       NaN
1  2014Q2 -5.161290 -4.670913  2.685950   3.265306   3.100775  0.416067
2  2014Q3 -4.988662 -2.895323 -6.438632  -6.916996   1.127820 -0.020461
3  2014Q4  0.715990  3.669725  5.161290   5.732484   1.672862  0.102328
4  2015Q1 -7.582938 -3.539823 -5.316973  -5.622490  -0.548446 -2.248914

        gdp      생산지수    내수출하지수      EBITDA        인건비          합산
0       NaN       NaN       NaN         NaN        NaN         NaN
1  1.064960 -2.736602  3.041406  -45.507711  -1.859375  -45.502439
2  0.993648  1.875733 -1.532437  186.141135   4.439416  186.101616
3  3.177926  1.035673  2.864298  -24.963822 -18.399027  -24.963301
4  1.430351  0.911162 -1.772075    5.336775  26.664344    5.338617

In [57]:
df_qoq
df_qoq = df_qoq.drop(index=[0, 1, 2,3])

In [58]:
df_qoq.isnull().sum()

index        0
업황실적BSI      0
매출실적BSI      0
채산성실적BSI     0
자금사정실적BSI    0
인력사정실적BSI    0
ppi          0
gdp          0
생산지수         0
내수출하지수       0
EBITDA       0
인건비          0
합산           0
dtype: int64

In [59]:
df_qoq.to_csv('전기가스수도qoq.csv')

## 데이터YoY변환

In [60]:
import pandas as pd

# df_merged는 원본 데이터프레임
df_yoy = df_merged.copy()

# 분기 순서대로 정렬
df_yoy = df_yoy.sort_values('index')

# 수치형 컬럼만 선택 (index 제외)
num_cols = df_yoy.select_dtypes(include=['number']).columns

# 전년 동분기 대비 증감률 (%) 계산 (4분기 차이)
df_yoy[num_cols] = df_yoy[num_cols].pct_change(periods=4) * 100

# 결과 확인
print(df_yoy.head(10))

    index    업황실적BSI    매출실적BSI  채산성실적BSI  자금사정실적BSI  인력사정실적BSI       ppi  \
0  2014Q1        NaN        NaN       NaN        NaN        NaN       NaN
1  2014Q2        NaN        NaN       NaN        NaN        NaN       NaN
2  2014Q3        NaN        NaN       NaN        NaN        NaN       NaN
3  2014Q4        NaN        NaN       NaN        NaN        NaN       NaN
4  2015Q1 -16.129032  -7.430998 -4.338843  -4.081633   5.426357 -1.761866
5  2015Q2  -0.680272  -4.677060  0.000000   0.988142  -3.195489 -5.197197
6  2015Q3 -10.978520 -19.495413 -2.365591   1.910828  -4.460967 -5.935022
7  2015Q4 -12.085308 -24.336283 -6.952965  -2.610442  -4.021938 -4.988500
8  2016Q1  -4.358974 -15.825688 -0.647948   1.276596  -3.676471 -3.707190
9  2016Q2  -8.447489  -8.177570 -4.627767  -2.152642  -1.553398 -1.991043

        gdp      생산지수    내수출하지수      EBITDA        인건비          합산
0       NaN       NaN       NaN         NaN        NaN         NaN
1       NaN       NaN       NaN         NaN        NaN         NaN
2       NaN       NaN       NaN         NaN        NaN         NaN
3       NaN       NaN       NaN         NaN        NaN         NaN
4  6.819217  1.026226  2.519056   23.244082   5.940732   23.241992
5  7.081080  6.565064 -1.591703  263.050248   7.492306  262.994665
6  8.121720  8.515535 -0.223555   26.724278   0.024024   26.722158
7  3.821479  2.619590 -5.164721   -7.808017  54.034603   -7.802678
8  2.311722  4.176072  1.637042   31.054369   4.731022   31.051636
9 -0.069145  4.620462 -0.501151   -5.765507  -2.112418   -5.765272

In [61]:
df_yoy=df_yoy.dropna()

In [62]:
df_yoy

,index,업황실적BSI,매출실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,ppi,gdp,생산지수,내수출하지수,EBITDA,인건비,합산
4,2015Q1,-16.129032,-7.430998,-4.338843,-4.081633,5.426357,-1.761866,6.819217,1.026226,2.519056,2.324408e+01,5.940732,2.324199e+01
5,2015Q2,-0.680272,-4.677060,0.000000,0.988142,-3.195489,-5.197197,7.081080,6.565064,-1.591703,2.630502e+02,7.492306,2.629947e+02
6,2015Q3,-10.978520,-19.495413,-2.365591,1.910828,-4.460967,-5.935022,8.121720,8.515535,-0.223555,2.672428e+01,0.024024,2.672216e+01
7,2015Q4,-12.085308,-24.336283,-6.952965,-2.610442,-4.021938,-4.988500,3.821479,2.619590,-5.164721,-7.808017e+00,54.034603,-7.802678e+00
8,2016Q1,-4.358974,-15.825688,-0.647948,1.276596,-3.676471,-3.707190,2.311722,4.176072,1.637042,3.105437e+01,4.731022,3.105164e+01
9,2016Q2,-8.447489,-8.177570,-4.627767,-2.152642,-1.553398,-1.991043,-0.069145,4.620462,-0.501151,-5.765507e+00,-2.112418,-5.765272e+00
10,2016Q3,11.260054,21.937322,6.607930,5.833333,1.361868,-2.273593,-1.336452,-1.060445,2.099446,1.947663e+01,22.576859,1.947682e+01
11,2016Q4,19.137466,40.935673,17.582418,8.865979,3.428571,-1.495508,-0.453283,3.884573,2.723547,-1.367340e+01,16.508593,-1.366904e+01
12,2017Q1,31.903485,42.506812,18.695652,15.546218,-0.381679,-0.119461,2.857852,4.225352,2.234432,-4.433406e+01,-0.208610,-4.433040e+01
13,2017Q2,29.177057,42.239186,9.071730,4.400000,3.944773,1.701167,4.262851,-3.154574,8.120406,-4.921464e+01,10.905989,-4.921062e+01
14,2017Q3,22.891566,31.074766,15.082645,3.937008,3.454894,3.539823,5.463039,1.822079,7.879050,-2.171219e+01,7.231390,-2.171033e+01
15,2017Q4,19.909502,18.879668,1.869159,2.083333,-0.920810,3.484244,4.030370,1.282051,11.685400,2.169420e+01,-4.387866,2.168913e+01
16,2018Q1,7.317073,13.957935,0.000000,-5.090909,5.747126,3.109710,-2.946312,-0.311850,7.277474,-3.185085e+01,13.017474,-3.184418e+01
17,2018Q2,-0.193050,3.935599,5.609284,2.107280,0.759013,2.912359,-1.305147,6.406080,5.278258,-6.279208e+01,2.110442,-6.278260e+01
18,2018Q3,-2.156863,0.534759,-4.488330,0.189394,-5.751391,2.397463,-1.304221,2.842105,5.271342,-4.201947e+01,-3.617278,-4.201609e+01
19,2018Q4,-7.547170,-7.329843,-4.403670,-3.153989,-4.275093,1.102961,1.779557,2.531646,1.790053,-5.018787e+01,-6.926575,-5.018125e+01
20,2019Q1,-10.606061,-16.275168,-4.945055,-1.149425,-3.079710,2.246125,5.942287,-1.251303,-0.794893,-1.140780e+02,0.595604,-1.140498e+02
21,2019Q2,-5.609284,-13.769363,-6.593407,-5.628518,-2.824859,2.651097,11.141537,-3.877551,0.021840,2.054553e+02,5.781816,2.053752e+02
22,2019Q3,-5.210421,-10.992908,-6.203008,-4.347826,4.527559,3.952963,-2.102272,0.409417,-4.841092,2.374904e+00,-0.645354,2.374462e+00
23,2019Q4,-0.204082,-7.721281,-0.575816,-2.490421,1.165049,4.217559,0.812113,2.160494,-5.716307,-3.387959e+01,38.395110,-3.385894e+01
24,2020Q1,-12.076271,-17.234469,-10.597303,-7.558140,-2.616822,4.641089,7.735107,6.969377,-6.118641,-1.534568e+03,4.919886,-1.537287e+03
25,2020Q2,-26.434426,-28.742515,-14.313725,-12.524851,-1.550388,3.853446,0.574315,3.821656,-4.685957,2.307567e+00,1.407034,2.307442e+00
26,2020Q3,-16.490486,-29.482072,-8.617234,-8.102767,-8.851224,-0.313100,9.598374,-0.509684,-2.469979,5.796034e+01,1.228526,5.795228e+01
27,2020Q4,-10.633947,-19.183673,-5.405405,-4.125737,-3.646833,-1.332265,6.784344,3.927492,2.465578,4.123426e+02,-14.459830,4.120874e+02
28,2021Q1,16.626506,15.496368,12.500000,3.983229,-5.758157,-2.271831,1.666913,0.000000,5.635246,-2.957811e+01,3.224576,-2.957388e+01
29,2021Q2,48.467967,53.221289,25.629291,18.863636,-2.559055,-1.060838,0.917143,5.419223,4.780876,-8.033227e+01,0.571365,-8.032114e+01
30,2021Q3,42.784810,75.423729,22.368421,16.344086,7.024793,2.178318,3.463868,4.918033,6.706707,-9.999253e+01,8.143662,-9.998269e+01
31,2021Q4,17.391304,44.696970,10.204082,0.614754,-5.179283,6.279188,0.986040,-1.356589,3.222656,-1.805788e+02,-5.058709,-1.805613e+02
32,2022Q1,2.479339,19.287212,-2.107280,3.427419,-6.109980,10.155817,2.161268,-2.270484,6.692532,-5.993958e+02,-4.572135,-5.992834e+02
33,2022Q2,-7.692308,0.000000,-12.932605,-6.118547,-2.828283,11.968881,5.914164,-5.625606,2.756654,-1.392704e+03,2.468334,-1.391723e+03
34,2022Q3,-20.744681,-15.780998,-12.186380,-16.820702,-11.969112,16.499752,4.844285,-4.199219,0.750469,-3.684088e+06,0.218658,-1.589060e+06
35,2022Q4,-9.746589,-2.094241,-9.259259,-1.832994,-4.621849,20.666762,5.112313,-5.795678,-0.756859,2.179060e+02,-4.086961,2.179321e+02
36,2023Q1,-9.274194,-15.289982,-10.958904,-7.407407,-0.433839,18.617533,6.033876,-0.202020,-5.090909,-3.666604e+01,5.851883,-3.666757e+01
37,2023Q2,-10.365854,-20.840951,-1.255230,-5.498982,0.207900,13.442010,0.057095,-0.411100,-4.995375,-1.141449e+02,-21.002259,-1.141501e+02
38,2023Q3,3.131991,-15.296367,0.000000,8.444444,12.500000,9.034811,-4.131280,-1.019368,-4.283054,-1.118815e+02,-6.274436,-1.118853e+02
39,2023Q4,-6.695464,-26.024955,-3.265306,0.829876,5.947137,2.620329,4.783787,-1.147028,-0.953289,-1.506503e+02,10.167046,-1.506561e+02
40,2024Q1,-2.666667,-12.655602,6.593407,-0.421053,-0.435730,1.339148,-0.508477,-2.631579,0.383142,-1.901136e+02,-0.930849,-1.901250e+02
41,2024Q2,5.668934,10.392610,9.745763,9.267241,-2.697095,2.724774,2.538477,-1.960784,2.531646,1.876557e+02,25.813647,1.876053e+02
42,2024Q3,2.169197,7.449210,4.081633,3.073770,-5.068226,2.720425,14.205715,-2.162719,6.809339,2.229618e+01,1.672379,2.229035e+01
43,2024Q4,-0.231481,5.783133,3.375527,1.851852,0.831601,4.157988,-0.088023,-0.316456,-3.464870,3.738080e+01,-19.930601,3.737637e+01
44,2025Q1,-3.881279,2.612827,-7.216495,-0.845666,0.437637,3.907232,4.844491,-5.301455,3.244275,1.773555e+01,-21.301211,1.773296e+01
45,2025Q2,-12.446352,-8.786611,-9.845560,-9.664694,2.345416,4.192784,-0.639181,-3.052632,1.424501,5.776494e+01,-178.324086,5.773277e+01

In [64]:
df_yoy.to_csv("전기가스수도yoy.csv")

# 상관계수 보기(qoq)

In [65]:
qoq = pd.read_csv('전기가스수도qoq.csv')
qoq = qoq.drop(columns=["Unnamed: 0"])

In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# GDP_QoQ 기준
target = 'gdp'

In [67]:
# 수치형 컬럼만 선택
num_cols = qoq.select_dtypes(include=['number']).columns

# GDP 기준 상관계수 계산
corr = qoq[num_cols].corr()[target].sort_values(ascending=False)

print("📊 GDP 대비 단순 상관계수")
print(corr)

📊 GDP 대비 단순 상관계수
gdp          1.000000
내수출하지수       0.356599
인건비          0.225684
ppi          0.050955
EBITDA       0.047757
합산           0.047483
업황실적BSI     -0.073586
생산지수        -0.102609
자금사정실적BSI   -0.113082
매출실적BSI     -0.163991
채산성실적BSI    -0.280148
인력사정실적BSI   -0.332734
Name: gdp, dtype: float64

In [69]:
# df2 사본
df2 = qoq.copy()

# target 및 feature 지정
target_col = 'gdp'
feature_cols = [col for col in df2.columns if col not in ['index', target_col]]

# 결과 저장용 데이터프레임
corr_df = pd.DataFrame(columns=['Feature', 'Lag', 'Correlation'])

# lag 1~4 생성 및 상관계수 계산
for col in feature_cols:
    for lag in range(1, 5):  # lag 1~4
        lag_col_name = f"{col}_lag{lag}"
        df2[lag_col_name] = df2[col].shift(lag)  # 실제 데이터에 lag 컬럼 추가
        corr = df2[target_col].corr(df2[lag_col_name])  # 상관계수 계산
        corr_df = pd.concat(
            [corr_df, pd.DataFrame({'Feature': [col], 'Lag': [lag], 'Correlation': [corr]})],
            ignore_index=True
        )

# 상관계수 높은 순으로 정렬
corr_df.sort_values(by='Correlation', ascending=False, inplace=True)
corr_df.reset_index(drop=True, inplace=True)

corr_df

/tmp/ipython-input-1052179002.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  corr_df = pd.concat(

      Feature Lag  Correlation
0   자금사정실적BSI   1     0.338696
1         인건비   1     0.326937
2    채산성실적BSI   1     0.270519
3         ppi   4     0.186929
4   인력사정실적BSI   4     0.185562
5      내수출하지수   2     0.183573
6   인력사정실적BSI   1     0.169198
7     매출실적BSI   1     0.161258
8   자금사정실적BSI   4     0.153795
9         ppi   1     0.125001
10    업황실적BSI   1     0.105691
11       생산지수   1     0.083396
12    업황실적BSI   4     0.073156
13       생산지수   2     0.070937
14    매출실적BSI   4     0.070310
15     EBITDA   3     0.061199
16         합산   3     0.060882
17  자금사정실적BSI   3     0.052383
18     EBITDA   4     0.035529
19         합산   4     0.035395
20   채산성실적BSI   2     0.031742
21       생산지수   3     0.031668
22     내수출하지수   3     0.023497
23   채산성실적BSI   4     0.017243
24  인력사정실적BSI   3     0.011999
25    업황실적BSI   2     0.003347
26    매출실적BSI   2     0.002204
27        인건비   3    -0.025198
28    업황실적BSI   3    -0.045078
29        인건비   2    -0.047952
30    매출실적BSI   3    -0.055325
31        ppi   3    -0.070984
32       생산지수   4    -0.084366
33     내수출하지수   4    -0.089743
34   채산성실적BSI   3    -0.093308
35        인건비   4    -0.095954
36     EBITDA   2    -0.096438
37         합산   2    -0.096880
38         합산   1    -0.112971
39     EBITDA   1    -0.113750
40  인력사정실적BSI   2    -0.123959
41        ppi   2    -0.192887
42  자금사정실적BSI   2    -0.218519
43     내수출하지수   1    -0.400328

In [70]:
df2

,index,업황실적BSI,매출실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,ppi,gdp,생산지수,내수출하지수,...,EBITDA_lag3,EBITDA_lag4,인건비_lag1,인건비_lag2,인건비_lag3,인건비_lag4,합산_lag1,합산_lag2,합산_lag3,합산_lag4
0,2015Q1,-7.582938,-3.539823,-5.316973,-5.622490,-0.548446,-2.248914,1.430351,0.911162,-1.772075,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015Q2,12.307692,-1.834862,7.343413,8.723404,-5.330882,-3.095425,1.312717,2.595937,-1.090298,...,NaN,NaN,26.664344,NaN,NaN,NaN,5.338617,NaN,NaN,NaN
2,2015Q3,-14.840183,-17.990654,-8.651911,-6.066536,-0.194175,-0.798576,1.975128,3.740374,-0.163465,...,NaN,NaN,-0.422039,26.664344,NaN,NaN,60.516100,5.338617,NaN,NaN
3,2015Q4,-0.536193,-2.564103,0.220264,1.041667,2.140078,1.109600,-0.925689,-4.453871,-2.229787,...,5.336775e+00,NaN,-2.816759,-0.422039,26.664344,NaN,-0.121358,60.516100,5.338617,NaN
4,2016Q1,0.539084,7.309942,1.098901,-1.855670,-0.190476,-0.930658,-0.044634,2.441731,5.273016,...,6.052243e+01,5.336775e+00,25.663545,-2.816759,-0.422039,26.664344,-45.406684,-0.121358,60.516100,5.338617
5,2016Q2,7.506702,7.084469,3.043478,5.042017,-3.244275,-1.368375,-1.044902,3.033586,-3.171115,...,-1.211848e-01,6.052243e+01,-13.878531,25.663545,-2.816759,-0.422039,49.731008,-45.406684,-0.121358,60.516100
6,2016Q3,3.491272,8.905852,2.109705,1.600000,2.761341,-1.084563,0.681896,-1.892744,2.445958,...,-4.541114e+01,-1.211848e-01,-6.928762,-13.878531,25.663545,-2.816759,15.421612,49.731008,-45.406684,-0.121358
7,2016Q4,6.506024,12.616822,10.537190,3.937008,4.222649,1.914621,-0.038844,0.321543,-1.632149,...,4.974019e+01,-4.541114e+01,21.694869,-6.928762,-13.878531,25.663545,26.632539,15.421612,49.731008,-45.406684
8,2017Q1,11.312217,8.506224,2.056075,4.166667,-3.867403,0.453279,3.280093,2.777778,4.771762,...,1.542347e+01,4.974019e+01,19.442470,21.694869,-6.928762,-13.878531,-60.552239,26.632539,15.421612,49.731008
9,2017Q2,5.284553,6.883365,-5.311355,-5.090909,0.957854,0.429488,0.306787,-4.261954,2.403644,...,2.663287e+01,1.542347e+01,-26.235647,19.442470,21.694869,-6.928762,-3.447555,-60.552239,26.632539,15.421612
10,2017Q3,-1.544402,0.357782,7.736944,1.149425,2.277040,0.703730,1.840863,3.148751,2.217268,...,-6.055738e+01,2.663287e+01,3.437358,-26.235647,19.442470,21.694869,5.303294,-3.447555,-60.552239,26.632539
11,2017Q4,3.921569,2.139037,-2.154399,2.083333,-0.185529,1.859915,-1.396772,-0.210526,1.838613,...,-3.443118e+00,-6.055738e+01,17.662807,3.437358,-26.235647,19.442470,95.198668,5.303294,-3.447555,-60.552239
12,2018Q1,-0.377358,4.013962,0.183486,-3.153989,2.602230,0.089714,-3.646272,1.160338,0.636698,...,5.303571e+00,-3.443118e+00,6.500059,17.662807,3.437358,-26.235647,-38.684582,95.198668,5.303294,-3.447555
13,2018Q2,-2.083333,-2.516779,0.000000,2.107280,-3.804348,0.237267,2.002962,2.189781,0.495257,...,9.521000e+01,5.303571e+00,-12.807501,6.500059,17.662807,3.437358,-45.922768,-38.684582,95.198668,5.303294
14,2018Q3,-3.481625,-2.925990,-2.564103,-0.750469,-4.331450,0.199884,1.841818,-0.306122,2.210553,...,-3.868856e+01,9.521000e+01,-6.545121,-12.807501,6.500059,17.662807,-42.497722,-45.922768,-38.684582,95.198668
15,2018Q4,-1.803607,-5.851064,-2.067669,-1.323251,1.377953,0.572209,1.684114,-0.511771,-1.529157,...,-4.592783e+01,-3.868856e+01,11.062702,-6.545121,-12.807501,6.500059,204.115338,-42.497722,-45.922768,-38.684582
16,2019Q1,-3.673469,-6.026365,-0.383877,-1.149425,3.883495,1.221422,0.294544,-2.572016,-1.918958,...,-4.250659e+01,-4.592783e+01,2.843384,11.062702,-6.545121,-12.807501,-47.318880,204.115338,-42.497722,-45.922768
17,2019Q2,3.389831,0.400802,-1.734104,-2.519380,-3.551402,0.634282,7.008885,-0.527983,1.322611,...,2.041927e+02,-4.250659e+01,-5.760617,2.843384,11.062702,-6.545121,-115.250716,-47.318880,204.115338,-42.497722
18,2019Q3,-3.073770,0.199601,-2.156863,0.596421,2.906977,1.470664,-10.293821,4.140127,-2.758791,...,-4.732622e+01,2.041927e+02,-1.727050,-5.760617,2.843384,11.062702,-1349.828040,-115.250716,-47.318880,204.115338
19,2019Q4,3.382664,-2.390438,3.807615,0.592885,-1.883239,0.828199,4.711218,1.223242,-2.434834,...,-1.152820e+02,-4.732622e+01,4.314672,-1.727050,-5.760617,2.843384,1.952092,-1349.828040,-115.250716,-47.318880
20,2020Q1,-15.132924,-15.714286,-10.424710,-6.286837,0.000000,1.632776,7.181996,2.014099,-2.337496,...,-1.347452e+03,-1.152820e+02,43.254715,4.314672,-1.727050,-5.760617,-65.964311,1.952092,-1349.828040,-115.250716
21,2020Q2,-13.493976,-13.559322,-5.818966,-7.756813,-2.495202,-0.123201,-0.103638,-3.455084,2.868852,...,1.951764e+00,-1.347452e+03,-28.555386,43.254715,4.314672,-1.727050,231.407637,-65.964311,1.952092,-1349.828040
22,2020Q3,10.027855,-0.840336,4.347826,5.681818,-4.724409,-2.600286,-2.244909,-0.204499,-0.498008,...,-6.597983e+01,1.951764e+00,-5.017354,-28.555386,43.254715,4.314672,-11.036055,231.407637,-65.964311,1.952092
23,2020Q4,10.632911,11.864407,7.456140,4.946237,3.719008,-0.202634,2.022670,5.737705,2.502503,...,2.315632e+02,-6.597983e+01,4.131045,-5.017354,-28.555386,43.254715,57.403659,-11.036055,231.407637,-65.964311
24,2021Q1,10.755149,20.454545,6.530612,1.639344,-2.191235,0.664975,2.045508,-1.841085,0.683594,...,-1.103683e+01,2.315632e+02,21.053156,4.131045,-5.017354,-28.555386,10.345020,57.403659,-11.036055,231.407637
25,2021Q2,10.123967,14.675052,5.172414,5.443548,0.814664,1.114417,-0.840351,1.776900,2.036857,...,5.741099e+01,-1.103683e+01,-13.785067,21.053156,4.131045,-5.017354,-54.422326,10.345020,57.403659,-11.036055
26,2021Q3,5.816135,13.528336,1.639344,3.441683,4.646465,0.588470,0.222019,-0.678952,1.330798,...,1.034405e+01,5.741099e+01,-7.458720,-13.785067,21.053156,4.131045,-75.141197,-54.422326,10.345020,57.403659
27,2021Q4,-9.042553,-7.729469,-3.225806,-9.242144,-8.108108,3.802677,-0.420643,-0.585938,-0.844278,...,-5.442639e+01,1.034405e+01,11.971360,-7.458720,-13.785067,21.053156,-99.861512,-75.141197,-54.422326,10.345020
28,2022Q1,-3.313840,-0.698080,-5.370370,4.480652,-3.151261,4.336820,3.233066,-2.750491,4.068117,...,-7.515399e+01,-5.442639e+01,6.274771,11.971360,-7.458720,-13.785067,-513530.547616,-99.861512,-75.141197,-54.422326
29,2022Q2,-0.806452,-3.866432,-6.457926,-4.288499,4.338395,2.778668,2.802281,-1.717172,-1.727273,...,-9.994022e+01,-7.515399e+01,-13.343215,6.274771,11.971360,-7.458720,182.470315,-513530.547616,-99.861512,-75.141197
30,2022Q3,-9.146341,-4.387569,2.510460,-8.350305,-5.197505,4.658828,-0.790362,0.822199,-0.647549,...,-1.190581e+06,-9.994022e+01,-0.631217,-13.343215,6.274771,11.971360,-35.686473,182.470315,-513530.547616,-99.861512
31,2022Q4,3.579418,7.265774,0.000000,7.111111,-0.438596,7.515533,-0.166073,-2.242610,-2.327747,...,1.824473e+02,-1.190581e+06,9.513046,-0.631217,-13.343215,6.274771,70.355493,-35.686473,182.470315,-513530.547616
32,2023Q1,-2.807775,-14.081996,-7.142857,-1.452282,1.101322,2.564915,4.138153,3.023983,-0.476644,...,-3.568521e+01,1.824473e+02,1.708969,9.513046,-0.631217,-13.343215,2.731381,70.355493,-35.686473,182.470315
33,2023Q2,-2.000000,-10.165975,3.736264,-2.315789,5.010893,-1.705773,-2.992345,-1.923077,-1.628352,...,7.035210e+01,-3.568521e+01,-4.363537,1.708969,9.513046,-0.631217,-43.731603,2.731381,70.355493,-35.686473
34,2023Q3,4.535147,2.309469,3.813559,5.172414,6.431535,0.592854,-4.943263,0.206398,0.097371,...,2.731344e+00,7.035210e+01,-25.840626,-4.363537,1.708969,9.513046,-114.369321,-43.731603,2.731381,70.355493
35,2023Q4,-6.290672,-6.320542,-3.265306,-0.409836,-6.237817,1.190430,9.117728,-2.368692,1.070039,...,-4.373021e+01,2.731344e+00,29.929944,-25.840626,-4.363537,1.708969,43.089090,-114.369321,-43.731603,2.731381
36,2024Q1,1.388889,1.445783,2.320675,-2.674897,-4.989605,1.284425,-1.121503,1.476793,0.866218,...,-1.143640e+02,-4.373021e+01,19.550911,29.929944,-25.840626,-4.363537,337.848733,43.089090,-114.369321,-43.731603
37,2024Q2,6.392694,13.539192,6.804124,7.188161,2.625821,-0.361781,-0.021460,-1.247401,0.477099,...,4.309319e+01,-1.143640e+02,-13.997665,19.550911,29.929944,-25.840626,0.110226,337.848733,43.089090,-114.369321
38,2024Q3,1.072961,-0.418410,-1.544402,-0.788955,3.837953,0.588595,5.872673,0.000000,4.273504,...,3.379388e+02,4.309319e+01,-5.820719,-13.997665,19.550911,29.929944,-54.144876,0.110226,337.848733,43.089090
39,2024Q4,-8.492569,-7.773109,-3.921569,-1.590457,-0.410678,2.606581,-4.539208,-0.526316,-8.652095,...,1.113155e-01,3.379388e+02,4.998836,-5.820719,-13.997665,19.550911,-39.158240,-54.144876,0.110226,337.848733
40,2025Q1,-2.320186,-1.594533,-8.163265,-5.252525,-5.360825,1.040587,3.759990,-3.597884,7.876371,...,-5.414808e+01,1.113155e-01,-5.850834,4.998836,-5.820719,-13.997665,391.862785,-39.158240,-54.144876,0.110226
41,2025Q2,-3.087886,0.925926,3.777778,-2.345416,4.575163,-0.087960,-5.250629,1.097695,-1.293900,...,-3.916426e+01,-5.414808e+01,-15.469835,-5.850834,4.998836,-5.820719,-14.204511,391.862785,-39.158240,-54.144876

In [71]:
# 숫자형 컬럼만 선택 (연도분기 제외)
numeric_df = df2.select_dtypes(include=["number"])

# 전체 상관계수
corr = numeric_df.corr()

target_corr = corr["gdp"].drop("gdp")
target_corr = target_corr.sort_values(ascending=False)
target_corr

내수출하지수            0.356599
자금사정실적BSI_lag1    0.338696
인건비_lag1          0.326937
채산성실적BSI_lag1     0.270519
인건비               0.225684
ppi_lag4          0.186929
인력사정실적BSI_lag4    0.185562
내수출하지수_lag2       0.183573
인력사정실적BSI_lag1    0.169198
매출실적BSI_lag1      0.161258
자금사정실적BSI_lag4    0.153795
ppi_lag1          0.125001
업황실적BSI_lag1      0.105691
생산지수_lag1         0.083396
업황실적BSI_lag4      0.073156
생산지수_lag2         0.070937
매출실적BSI_lag4      0.070310
EBITDA_lag3       0.061199
합산_lag3           0.060882
자금사정실적BSI_lag3    0.052383
ppi               0.050955
EBITDA            0.047757
합산                0.047483
EBITDA_lag4       0.035529
합산_lag4           0.035395
채산성실적BSI_lag2     0.031742
생산지수_lag3         0.031668
내수출하지수_lag3       0.023497
채산성실적BSI_lag4     0.017243
인력사정실적BSI_lag3    0.011999
업황실적BSI_lag2      0.003347
매출실적BSI_lag2      0.002204
인건비_lag3         -0.025198
업황실적BSI_lag3     -0.045078
인건비_lag2         -0.047952
매출실적BSI_lag3     -0.055325
ppi_lag3         -0.070984
업황실적BSI          -0.073586
생산지수_lag4        -0.084366
내수출하지수_lag4      -0.089743
채산성실적BSI_lag3    -0.093308
인건비_lag4         -0.095954
EBITDA_lag2      -0.096438
합산_lag2          -0.096880
생산지수             -0.102609
합산_lag1          -0.112971
자금사정실적BSI        -0.113082
EBITDA_lag1      -0.113750
인력사정실적BSI_lag2   -0.123959
매출실적BSI          -0.163991
ppi_lag2         -0.192887
자금사정실적BSI_lag2   -0.218519
채산성실적BSI         -0.280148
인력사정실적BSI        -0.332734
내수출하지수_lag1      -0.400328
Name: gdp, dtype: float64

In [72]:
target_corr.to_csv('전기가스수도순서.csv')

In [73]:
df2.dropna(inplace=True)

In [74]:
df2

,index,업황실적BSI,매출실적BSI,채산성실적BSI,자금사정실적BSI,인력사정실적BSI,ppi,gdp,생산지수,내수출하지수,...,EBITDA_lag3,EBITDA_lag4,인건비_lag1,인건비_lag2,인건비_lag3,인건비_lag4,합산_lag1,합산_lag2,합산_lag3,합산_lag4
4,2016Q1,0.539084,7.309942,1.098901,-1.855670,-0.190476,-0.930658,-0.044634,2.441731,5.273016,...,6.052243e+01,5.336775e+00,25.663545,-2.816759,-0.422039,26.664344,-45.406684,-0.121358,60.516100,5.338617
5,2016Q2,7.506702,7.084469,3.043478,5.042017,-3.244275,-1.368375,-1.044902,3.033586,-3.171115,...,-1.211848e-01,6.052243e+01,-13.878531,25.663545,-2.816759,-0.422039,49.731008,-45.406684,-0.121358,60.516100
6,2016Q3,3.491272,8.905852,2.109705,1.600000,2.761341,-1.084563,0.681896,-1.892744,2.445958,...,-4.541114e+01,-1.211848e-01,-6.928762,-13.878531,25.663545,-2.816759,15.421612,49.731008,-45.406684,-0.121358
7,2016Q4,6.506024,12.616822,10.537190,3.937008,4.222649,1.914621,-0.038844,0.321543,-1.632149,...,4.974019e+01,-4.541114e+01,21.694869,-6.928762,-13.878531,25.663545,26.632539,15.421612,49.731008,-45.406684
8,2017Q1,11.312217,8.506224,2.056075,4.166667,-3.867403,0.453279,3.280093,2.777778,4.771762,...,1.542347e+01,4.974019e+01,19.442470,21.694869,-6.928762,-13.878531,-60.552239,26.632539,15.421612,49.731008
9,2017Q2,5.284553,6.883365,-5.311355,-5.090909,0.957854,0.429488,0.306787,-4.261954,2.403644,...,2.663287e+01,1.542347e+01,-26.235647,19.442470,21.694869,-6.928762,-3.447555,-60.552239,26.632539,15.421612
10,2017Q3,-1.544402,0.357782,7.736944,1.149425,2.277040,0.703730,1.840863,3.148751,2.217268,...,-6.055738e+01,2.663287e+01,3.437358,-26.235647,19.442470,21.694869,5.303294,-3.447555,-60.552239,26.632539
11,2017Q4,3.921569,2.139037,-2.154399,2.083333,-0.185529,1.859915,-1.396772,-0.210526,1.838613,...,-3.443118e+00,-6.055738e+01,17.662807,3.437358,-26.235647,19.442470,95.198668,5.303294,-3.447555,-60.552239
12,2018Q1,-0.377358,4.013962,0.183486,-3.153989,2.602230,0.089714,-3.646272,1.160338,0.636698,...,5.303571e+00,-3.443118e+00,6.500059,17.662807,3.437358,-26.235647,-38.684582,95.198668,5.303294,-3.447555
13,2018Q2,-2.083333,-2.516779,0.000000,2.107280,-3.804348,0.237267,2.002962,2.189781,0.495257,...,9.521000e+01,5.303571e+00,-12.807501,6.500059,17.662807,3.437358,-45.922768,-38.684582,95.198668,5.303294
14,2018Q3,-3.481625,-2.925990,-2.564103,-0.750469,-4.331450,0.199884,1.841818,-0.306122,2.210553,...,-3.868856e+01,9.521000e+01,-6.545121,-12.807501,6.500059,17.662807,-42.497722,-45.922768,-38.684582,95.198668
15,2018Q4,-1.803607,-5.851064,-2.067669,-1.323251,1.377953,0.572209,1.684114,-0.511771,-1.529157,...,-4.592783e+01,-3.868856e+01,11.062702,-6.545121,-12.807501,6.500059,204.115338,-42.497722,-45.922768,-38.684582
16,2019Q1,-3.673469,-6.026365,-0.383877,-1.149425,3.883495,1.221422,0.294544,-2.572016,-1.918958,...,-4.250659e+01,-4.592783e+01,2.843384,11.062702,-6.545121,-12.807501,-47.318880,204.115338,-42.497722,-45.922768
17,2019Q2,3.389831,0.400802,-1.734104,-2.519380,-3.551402,0.634282,7.008885,-0.527983,1.322611,...,2.041927e+02,-4.250659e+01,-5.760617,2.843384,11.062702,-6.545121,-115.250716,-47.318880,204.115338,-42.497722
18,2019Q3,-3.073770,0.199601,-2.156863,0.596421,2.906977,1.470664,-10.293821,4.140127,-2.758791,...,-4.732622e+01,2.041927e+02,-1.727050,-5.760617,2.843384,11.062702,-1349.828040,-115.250716,-47.318880,204.115338
19,2019Q4,3.382664,-2.390438,3.807615,0.592885,-1.883239,0.828199,4.711218,1.223242,-2.434834,...,-1.152820e+02,-4.732622e+01,4.314672,-1.727050,-5.760617,2.843384,1.952092,-1349.828040,-115.250716,-47.318880
20,2020Q1,-15.132924,-15.714286,-10.424710,-6.286837,0.000000,1.632776,7.181996,2.014099,-2.337496,...,-1.347452e+03,-1.152820e+02,43.254715,4.314672,-1.727050,-5.760617,-65.964311,1.952092,-1349.828040,-115.250716
21,2020Q2,-13.493976,-13.559322,-5.818966,-7.756813,-2.495202,-0.123201,-0.103638,-3.455084,2.868852,...,1.951764e+00,-1.347452e+03,-28.555386,43.254715,4.314672,-1.727050,231.407637,-65.964311,1.952092,-1349.828040
22,2020Q3,10.027855,-0.840336,4.347826,5.681818,-4.724409,-2.600286,-2.244909,-0.204499,-0.498008,...,-6.597983e+01,1.951764e+00,-5.017354,-28.555386,43.254715,4.314672,-11.036055,231.407637,-65.964311,1.952092
23,2020Q4,10.632911,11.864407,7.456140,4.946237,3.719008,-0.202634,2.022670,5.737705,2.502503,...,2.315632e+02,-6.597983e+01,4.131045,-5.017354,-28.555386,43.254715,57.403659,-11.036055,231.407637,-65.964311
24,2021Q1,10.755149,20.454545,6.530612,1.639344,-2.191235,0.664975,2.045508,-1.841085,0.683594,...,-1.103683e+01,2.315632e+02,21.053156,4.131045,-5.017354,-28.555386,10.345020,57.403659,-11.036055,231.407637
25,2021Q2,10.123967,14.675052,5.172414,5.443548,0.814664,1.114417,-0.840351,1.776900,2.036857,...,5.741099e+01,-1.103683e+01,-13.785067,21.053156,4.131045,-5.017354,-54.422326,10.345020,57.403659,-11.036055
26,2021Q3,5.816135,13.528336,1.639344,3.441683,4.646465,0.588470,0.222019,-0.678952,1.330798,...,1.034405e+01,5.741099e+01,-7.458720,-13.785067,21.053156,4.131045,-75.141197,-54.422326,10.345020,57.403659
27,2021Q4,-9.042553,-7.729469,-3.225806,-9.242144,-8.108108,3.802677,-0.420643,-0.585938,-0.844278,...,-5.442639e+01,1.034405e+01,11.971360,-7.458720,-13.785067,21.053156,-99.861512,-75.141197,-54.422326,10.345020
28,2022Q1,-3.313840,-0.698080,-5.370370,4.480652,-3.151261,4.336820,3.233066,-2.750491,4.068117,...,-7.515399e+01,-5.442639e+01,6.274771,11.971360,-7.458720,-13.785067,-513530.547616,-99.861512,-75.141197,-54.422326
29,2022Q2,-0.806452,-3.866432,-6.457926,-4.288499,4.338395,2.778668,2.802281,-1.717172,-1.727273,...,-9.994022e+01,-7.515399e+01,-13.343215,6.274771,11.971360,-7.458720,182.470315,-513530.547616,-99.861512,-75.141197
30,2022Q3,-9.146341,-4.387569,2.510460,-8.350305,-5.197505,4.658828,-0.790362,0.822199,-0.647549,...,-1.190581e+06,-9.994022e+01,-0.631217,-13.343215,6.274771,11.971360,-35.686473,182.470315,-513530.547616,-99.861512
31,2022Q4,3.579418,7.265774,0.000000,7.111111,-0.438596,7.515533,-0.166073,-2.242610,-2.327747,...,1.824473e+02,-1.190581e+06,9.513046,-0.631217,-13.343215,6.274771,70.355493,-35.686473,182.470315,-513530.547616
32,2023Q1,-2.807775,-14.081996,-7.142857,-1.452282,1.101322,2.564915,4.138153,3.023983,-0.476644,...,-3.568521e+01,1.824473e+02,1.708969,9.513046,-0.631217,-13.343215,2.731381,70.355493,-35.686473,182.470315
33,2023Q2,-2.000000,-10.165975,3.736264,-2.315789,5.010893,-1.705773,-2.992345,-1.923077,-1.628352,...,7.035210e+01,-3.568521e+01,-4.363537,1.708969,9.513046,-0.631217,-43.731603,2.731381,70.355493,-35.686473
34,2023Q3,4.535147,2.309469,3.813559,5.172414,6.431535,0.592854,-4.943263,0.206398,0.097371,...,2.731344e+00,7.035210e+01,-25.840626,-4.363537,1.708969,9.513046,-114.369321,-43.731603,2.731381,70.355493
35,2023Q4,-6.290672,-6.320542,-3.265306,-0.409836,-6.237817,1.190430,9.117728,-2.368692,1.070039,...,-4.373021e+01,2.731344e+00,29.929944,-25.840626,-4.363537,1.708969,43.089090,-114.369321,-43.731603,2.731381
36,2024Q1,1.388889,1.445783,2.320675,-2.674897,-4.989605,1.284425,-1.121503,1.476793,0.866218,...,-1.143640e+02,-4.373021e+01,19.550911,29.929944,-25.840626,-4.363537,337.848733,43.089090,-114.369321,-43.731603
37,2024Q2,6.392694,13.539192,6.804124,7.188161,2.625821,-0.361781,-0.021460,-1.247401,0.477099,...,4.309319e+01,-1.143640e+02,-13.997665,19.550911,29.929944,-25.840626,0.110226,337.848733,43.089090,-114.369321
38,2024Q3,1.072961,-0.418410,-1.544402,-0.788955,3.837953,0.588595,5.872673,0.000000,4.273504,...,3.379388e+02,4.309319e+01,-5.820719,-13.997665,19.550911,29.929944,-54.144876,0.110226,337.848733,43.089090
39,2024Q4,-8.492569,-7.773109,-3.921569,-1.590457,-0.410678,2.606581,-4.539208,-0.526316,-8.652095,...,1.113155e-01,3.379388e+02,4.998836,-5.820719,-13.997665,19.550911,-39.158240,-54.144876,0.110226,337.848733
40,2025Q1,-2.320186,-1.594533,-8.163265,-5.252525,-5.360825,1.040587,3.759990,-3.597884,7.876371,...,-5.414808e+01,1.113155e-01,-5.850834,4.998836,-5.820719,-13.997665,391.862785,-39.158240,-54.144876,0.110226
41,2025Q2,-3.087886,0.925926,3.777778,-2.345416,4.575163,-0.087960,-5.250629,1.097695,-1.293900,...,-3.916426e+01,-5.414808e+01,-15.469835,-5.850834,4.998836,-5.820719,-14.204511,391.862785,-39.158240,-54.144876

In [75]:
df2 = df2.reset_index()
df2 = df2.drop(columns=["level_0"])

In [76]:
df2.to_csv('전기가스수도lag.csv', encoding='utf-8-sig')

# ARIMA

In [77]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('전기가스수도lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1','인력사정실적BSI','내수출하지수_lag1']
y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (0.0, 1.0, 1.0)
📉 평균 Train MAE: 2.7013
📈 평균 Test MAE: 2.7196

In [78]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('전기가스수도lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1','인력사정실적BSI']
y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (1.0, 1.0, 0.0)
📉 평균 Train MAE: 3.0967
📈 평균 Test MAE: 2.5402

In [79]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('전기가스수도lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1','내수출하지수_lag1']
y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (0.0, 1.0, 1.0)
📉 평균 Train MAE: 2.8008
📈 평균 Test MAE: 2.3451

In [80]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('전기가스수도lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1']
y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (1.0, 1.0, 0.0)
📉 평균 Train MAE: 3.1068
📈 평균 Test MAE: 2.0425

In [82]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('전기가스수도lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','내수출하지수_lag1']
y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (1.0, 1.0, 1.0)
📉 평균 Train MAE: 2.7677
📈 평균 Test MAE: 2.2884

In [83]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('전기가스수도lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['내수출하지수','자금사정실적BSI_lag1']
y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (0.0, 1.0, 1.0)
📉 평균 Train MAE: 3.0388
📈 평균 Test MAE: 2.3105

In [84]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('전기가스수도lag.csv')

# 분기형 인덱스로 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X) 설정
# -----------------------------
target = 'gdp'   # GDP 예측 대상 칼럼
exog_vars = ['내수출하지수']
y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X의 인덱스 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 예측 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

# 예측 구간: 2017Q1 이후부터 2025Q2까지
start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 파라미터 범위 설정
# -----------------------------
p_values = range(0, 4)
d_values = range(1, 4)
q_values = range(0, 4)

# -----------------------------
# 5️⃣ 결과 저장
# -----------------------------
results = []

# -----------------------------
# 6️⃣ (p,d,q) 조합별 탐색
# -----------------------------
for p in p_values:
    for d in d_values:
        for q in q_values:

            train_mae_list = []
            test_mae_list = []

            for test_start in pd.period_range(start_period, end_period, freq='Q'):
                train_end = test_start - 1
                test_end = test_start
                train_start = train_end - (train_window - 1)

                train_data = y.loc[train_start:train_end]
                test_data = y.loc[test_end:test_end]
                X_train = X.loc[train_start:train_end]
                X_test = X.loc[test_end:test_end]

                if len(train_data) < train_window or len(X_test) == 0:
                    continue

                try:
                    model = SARIMAX(train_data, exog=X_train, order=(p, d, q),
                                    enforce_stationarity=False, enforce_invertibility=False)
                    fit = model.fit(disp=False)

                    # 예측
                    pred = fit.forecast(steps=1, exog=X_test)

                    # Train MAE (fittedvalues vs train_data)
                    train_mae = mean_absolute_error(train_data, fit.fittedvalues)
                    train_mae_list.append(train_mae)

                    # Test MAE (out-of-sample)
                    test_mae = mean_absolute_error(test_data, pred)
                    test_mae_list.append(test_mae)

                except Exception:
                    continue

            if train_mae_list and test_mae_list:
                results.append({
                    'p': p, 'd': d, 'q': q,
                    'train_MAE': np.mean(train_mae_list),
                    'test_MAE': np.mean(test_mae_list)
                })

# -----------------------------
# 7️⃣ 결과 정리 및 최적 모델 출력
# -----------------------------
results_df = pd.DataFrame(results)
best = results_df.loc[results_df['test_MAE'].idxmin()]

print("✅ 최적 ARIMAX(p,d,q):", tuple(best[['p', 'd', 'q']]))
print("📉 평균 Train MAE:", round(best['train_MAE'], 4))
print("📈 평균 Test MAE:", round(best['test_MAE'], 4))

✅ 최적 ARIMAX(p,d,q): (2.0, 1.0, 1.0)
📉 평균 Train MAE: 2.6208
📈 평균 Test MAE: 2.3875

# 랜덤포레스트

In [85]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2016Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1','인력사정실적BSI','내수출하지수_lag1']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.0618
📈 평균 Test MAE: 2.9075

In [86]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2016Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1','인력사정실적BSI']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.0539
📈 평균 Test MAE: 3.0462

In [87]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2016Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1','내수출하지수_lag1']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.0637
📈 평균 Test MAE: 2.9283

In [88]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2016Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.098
📈 평균 Test MAE: 3.3571

In [89]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도lag.csv')

# 인덱스 처리 (index 컬럼 없을 경우 자동 생성)
if 'index' not in df.columns:
    df.index = pd.period_range(start='2016Q1', periods=len(df), freq='Q')
else:
    df['index'] = pd.PeriodIndex(df['index'], freq='Q')
    df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','내수출하지수_lag1']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y, X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 결과 저장
# -----------------------------
train_mae_list = []
test_mae_list = []

# -----------------------------
# 5️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 랜덤포레스트 모델 학습
        rf = RandomForestRegressor(
            n_estimators=500,     # 트리 개수
            max_depth=None,      # 깊이 제한 없음
            random_state=42
        )
        rf.fit(X_train, y_train)

        # 학습 구간 예측 (Train MAE)
        train_pred = rf.predict(X_train)
        train_mae = mean_absolute_error(y_train, train_pred)
        train_mae_list.append(train_mae)

        # 테스트 구간 예측 (Test MAE)
        test_pred = rf.predict(X_test)
        test_mae = mean_absolute_error(y_test, test_pred)
        test_mae_list.append(test_mae)

    except Exception:
        continue

# -----------------------------
# 6️⃣ 결과 요약 출력
# -----------------------------
print("✅ 랜덤포레스트 롤링 예측 결과")
print("📉 평균 Train MAE:", round(np.mean(train_mae_list), 4))
print("📈 평균 Test MAE:", round(np.mean(test_mae_list), 4))

✅ 랜덤포레스트 롤링 예측 결과
📉 평균 Train MAE: 1.0929
📈 평균 Test MAE: 2.8803

#AR

In [90]:
import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도qoq.csv')

# GDP 단일 시계열만 사용 (AR(1))
y = df['gdp'].dropna()
y.index = pd.PeriodIndex(df.loc[y.index, 'index'], freq='Q')

# -----------------------------
# 2️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

train_mae_list = []
test_mae_list = []

# -----------------------------
# 3️⃣ 롤링 예측 실행
# -----------------------------
for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    train_data = y.loc[train_start:train_end]
    test_data = y.loc[test_end:test_end]

    if len(train_data) < train_window:
        continue

    try:
        # AR(1) 학습
        model = AutoReg(train_data, lags=1, old_names=False)
        fit = model.fit()

        # --- Train 예측 ---
        # fittedvalues는 길이가 n-1이므로 첫 번째 값 제외하고 MAE 계산
        train_mae = mean_absolute_error(train_data[1:], fit.fittedvalues)
        train_mae_list.append(train_mae)

        # --- Test 예측 (1분기 앞 예측) ---
        pred = fit.predict(start=len(train_data), end=len(train_data))
        test_mae = mean_absolute_error(test_data, pred)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 4️⃣ 결과 출력
# -----------------------------
print("✅ AR(1) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ AR(1) 롤링 예측 결과
📉 평균 Train MAE: 2.4989
📈 평균 Test MAE: 2.9953

#XGB

In [92]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1','인력사정실적BSI','내수출하지수_lag1']


y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 하이퍼파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'n_estimators': [200, 400, 600],
    'learning_rate': [0.03, 0.05, 0.1],
    'max_depth': [3, 5, 7, 9],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.3]
}

# 첫 번째 윈도우로 탐색
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

# RandomizedSearchCV 실행
xgb = XGBRegressor(random_state=42, objective='reg:squarederror')
rand_search = RandomizedSearchCV(
    xgb,
    param_distributions=param_grid,
    n_iter=15,          # 전체 중 15조합 탐색
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 고정된 최적 파라미터로 학습
        model = XGBRegressor(**best_params, random_state=42, objective='reg:squarederror')
        model.fit(X_train, y_train)

        # 예측
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # MAE 계산
        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 XGBoost 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'subsample': 1.0, 'n_estimators': 400, 'min_child_weight': 1, 'max_depth': 5, 'learning_rate': 0.1, 'gamma': 0.1, 'colsample_bytree': 1.0}

📊 XGBoost 롤링 예측 결과
📉 평균 Train MAE: 0.1511
📈 평균 Test MAE: 2.7623

In [93]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','내수출하지수_lag1']


y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 하이퍼파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'n_estimators': [200, 400, 600],
    'learning_rate': [0.03, 0.05, 0.1],
    'max_depth': [3, 5, 7, 9],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.3]
}

# 첫 번째 윈도우로 탐색
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X.loc[start_period:first_train_end]
first_y_train = y.loc[start_period:first_train_end]

# RandomizedSearchCV 실행
xgb = XGBRegressor(random_state=42, objective='reg:squarederror')
rand_search = RandomizedSearchCV(
    xgb,
    param_distributions=param_grid,
    n_iter=15,          # 전체 중 15조합 탐색
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y.loc[train_start:train_end]
    y_test = y.loc[test_end:test_end]
    X_train = X.loc[train_start:train_end]
    X_test = X.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        # 고정된 최적 파라미터로 학습
        model = XGBRegressor(**best_params, random_state=42, objective='reg:squarederror')
        model.fit(X_train, y_train)

        # 예측
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # MAE 계산
        train_mae = mean_absolute_error(y_train, train_pred)
        test_mae = mean_absolute_error(y_test, test_pred)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 XGBoost 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'subsample': 0.8, 'n_estimators': 600, 'min_child_weight': 1, 'max_depth': 5, 'learning_rate': 0.1, 'gamma': 0.3, 'colsample_bytree': 0.8}

📊 XGBoost 롤링 예측 결과
📉 평균 Train MAE: 0.2524
📈 평균 Test MAE: 3.2791

#LSTM

In [94]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1','인력사정실적BSI','내수출하지수_lag1']

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# -----------------------------
# 3️⃣ 스케일링
# -----------------------------
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(), index=y.index)

# -----------------------------
# 4️⃣ LSTM 입력 형태 변환 함수
# -----------------------------
def create_lstm_input(X, y, lookback=4):
    """
    lookback: 과거 몇 분기 데이터를 사용할지 (ex. 4 = 1년)
    """
    Xs, ys, idxs = [], [], []
    for i in range(lookback, len(X)):
        Xs.append(X.iloc[i-lookback:i].values)
        ys.append(y.iloc[i])
        idxs.append(y.index[i])
    return np.array(Xs), np.array(ys), idxs

lookback = 4
X_seq, y_seq, idxs = create_lstm_input(X_scaled, y_scaled, lookback)
y_seq = pd.Series(y_seq, index=idxs)

# -----------------------------
# 5️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 6️⃣ LSTM 모델 정의 함수
# -----------------------------
def build_lstm(input_shape):
    model = Sequential()
    model.add(LSTM(64, activation='tanh', input_shape=input_shape, return_sequences=False))
    model.add(Dropout(0.2))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mae')
    return model

# -----------------------------
# 7️⃣ 롤링 예측
# -----------------------------
train_mae_list, test_mae_list = [], []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    # 윈도우 범위 맞추기
    train_mask = (np.array(idxs) >= train_start) & (np.array(idxs) <= train_end)
    test_mask = (np.array(idxs) == test_end)

    X_train, y_train = X_seq[train_mask], y_seq[train_mask]
    X_test, y_test = X_seq[test_mask], y_seq[test_mask]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = build_lstm((X_train.shape[1], X_train.shape[2]))
        early_stop = EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)
        model.fit(X_train, y_train, epochs=200, batch_size=8, verbose=0, callbacks=[early_stop])

        # 예측
        train_pred = model.predict(X_train, verbose=0)
        test_pred = model.predict(X_test, verbose=0)

        # 스케일링 복원
        train_pred_inv = scaler_y.inverse_transform(train_pred)
        test_pred_inv = scaler_y.inverse_transform(test_pred)
        y_train_inv = scaler_y.inverse_transform(y_train.values.reshape(-1, 1))
        y_test_inv = scaler_y.inverse_transform(y_test.values.reshape(-1, 1))

        # MAE 계산
        train_mae = mean_absolute_error(y_train_inv, train_pred_inv)
        test_mae = mean_absolute_error(y_test_inv, test_pred_inv)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 8️⃣ 결과 요약
# -----------------------------
print("\n📊 LSTM 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7c3b6c989f80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7c3b6c989f80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

📊 LSTM 롤링 예측 결과
📉 평균 Train MAE: 1.0563
📈 평균 Test MAE: 3.8394

#MLP

In [95]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

# -----------------------------
# 1️⃣ 데이터 불러오기
# -----------------------------
df = pd.read_csv('전기가스수도lag.csv')

# 인덱스 설정
df['index'] = pd.PeriodIndex(df['index'], freq='Q')
df = df.set_index('index')

# -----------------------------
# 2️⃣ 예측 대상(y)과 외생 변수(X)
# -----------------------------
target = 'gdp'
exog_vars = ['내수출하지수','자금사정실적BSI_lag1','인건비_lag1','인력사정실적BSI','내수출하지수_lag1'
]

y = df[target].dropna()
X = df[exog_vars].dropna()

# y와 X 동기화
df_model = pd.concat([y, X], axis=1).dropna()
y = df_model[target]
X = df_model[exog_vars]

# 스케일링 (NN에서는 매우 중요)
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = pd.DataFrame(scaler_X.fit_transform(X), index=X.index, columns=X.columns)
y_scaled = pd.Series(scaler_y.fit_transform(y.values.reshape(-1, 1)).flatten(), index=y.index)

# -----------------------------
# 3️⃣ 롤링 윈도우 설정
# -----------------------------
periods_per_year = 4
train_years = 5
train_window = train_years * periods_per_year

start_period = pd.Period('2016Q1', freq='Q')
end_period = pd.Period('2025Q2', freq='Q')

# -----------------------------
# 4️⃣ 하이퍼파라미터 후보 & RandomizedSearchCV
# -----------------------------
param_grid = {
    'hidden_layer_sizes': [(32,), (64,), (32,16), (64,32), (128,64)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'lbfgs'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate_init': [0.001, 0.01]
}

# 첫 번째 윈도우로 하이퍼파라미터 탐색
first_train_end = start_period + (train_years * periods_per_year - 1)
first_X_train = X_scaled.loc[start_period:first_train_end]
first_y_train = y_scaled.loc[start_period:first_train_end]

mlp = MLPRegressor(random_state=42, max_iter=1000)
rand_search = RandomizedSearchCV(
    mlp,
    param_distributions=param_grid,
    n_iter=10,
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)
rand_search.fit(first_X_train, first_y_train)
best_params = rand_search.best_params_
print("✅ 최적 하이퍼파라미터:", best_params)

# -----------------------------
# 5️⃣ 롤링 예측 (최적 파라미터 고정)
# -----------------------------
train_mae_list = []
test_mae_list = []

for test_start in pd.period_range(start_period, end_period, freq='Q'):
    train_end = test_start - 1
    test_end = test_start
    train_start = train_end - (train_window - 1)

    y_train = y_scaled.loc[train_start:train_end]
    y_test = y_scaled.loc[test_end:test_end]
    X_train = X_scaled.loc[train_start:train_end]
    X_test = X_scaled.loc[test_end:test_end]

    if len(y_train) < train_window or len(X_test) == 0:
        continue

    try:
        model = MLPRegressor(**best_params, random_state=42, max_iter=1000)
        model.fit(X_train, y_train)

        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)

        # 스케일링 복원
        train_pred_inv = scaler_y.inverse_transform(train_pred.reshape(-1, 1)).flatten()
        test_pred_inv = scaler_y.inverse_transform(test_pred.reshape(-1, 1)).flatten()
        y_train_inv = scaler_y.inverse_transform(y_train.values.reshape(-1, 1)).flatten()
        y_test_inv = scaler_y.inverse_transform(y_test.values.reshape(-1, 1)).flatten()

        # MAE 계산
        train_mae = mean_absolute_error(y_train_inv, train_pred_inv)
        test_mae = mean_absolute_error(y_test_inv, test_pred_inv)

        train_mae_list.append(train_mae)
        test_mae_list.append(test_mae)

    except Exception as e:
        print("❌ Error:", e)
        continue

# -----------------------------
# 6️⃣ 결과 요약
# -----------------------------
print("\n📊 Neural Network (MLP) 롤링 예측 결과")
print(f"📉 평균 Train MAE: {np.mean(train_mae_list):.4f}")
print(f"📈 평균 Test MAE: {np.mean(test_mae_list):.4f}")

✅ 최적 하이퍼파라미터: {'solver': 'adam', 'learning_rate_init': 0.01, 'hidden_layer_sizes': (32, 16), 'alpha': 0.0001, 'activation': 'relu'}

📊 Neural Network (MLP) 롤링 예측 결과
📉 평균 Train MAE: 0.0581
📈 평균 Test MAE: 4.1971